### ISSUE TITLE
QtApp: Tint slider wrong at full left

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#10]
The tint slider has a strange behaviour when at full left.

**Comment by masc4ii** [comment]
The cocoa code is:
```
-(void)tintSliderMethod
{
    double tintSliderValue = [self doubleValue] - 0.5;
    /* Control should be more fine when its closer to zero... */
    double tintValue = tintSliderValue;
    if (tintValue < 0) tintValue = -tintValue;
    tintValue = pow(tintValue, 1.7) * 20.0;
    if (tintSliderValue < 0) tintValue = -tintValue;
    processingSetWhiteBalanceTint(App->processingSettings, tintValue);
    [App->tintValueLabel setStringValue: [NSString stringWithFormat:@"%6.3f", ([self doubleValue] - 0.5) * 2 ]];
}
```

**Comment by masc4ii** [comment]
@ilia3101 : Is it worth to do all this calculation? Because when typing the value the slider has to be set with another function, so this is never 100% exact (same problem as saturation). My range was from -20..20, your range is from -6.2..6.2 (is this enough? Or would be -10..10 better?). So we had this strange behaviour in my app.
Would it also be okay, to do it linear -6.2..6.2 (or -10..10), or is this not fine enough when near to 0?

**Comment by ilia3101** [comment]
Hmm, maybe it is not truly worth it, but calculation takes too little time to be a real problem.
But thanks for pointing out that my range is 6.2, it seems correct way to get the full range would be
```-(void)tintSliderMethod
{
    double tintSliderValue = ([self doubleValue] - 0.5) * 2.0;
    /* Control should be more fine when its closer to zero... */
    double tintValue = tintSliderValue;
    if (tintValue < 0) tintValue = -tintValue;
    tintValue = pow(tintValue, 1.7) * 20.0;
    if (tintSliderValue < 0) tintValue = -tintValue;
    processingSetWhiteBalanceTint(App->processingSettings, tintValue);
    [App->tintValueLabel setStringValue: [NSString stringWithFormat:@"%6.3f", ([self doubleValue] - 0.5) * 2 ]];
}```

**Comment by masc4ii** [comment]
Okay, thx. -10..10 is interesting. That is the reason of the false colours at -20. 

The calculation time is no problem. The problem I have is more the accuracy of the function and 1/function when typing the value as number - that is never correct. This problem does not exist if it is linear. But yes... please check if the non-linearity is worth it! :-)

**Comment by ilia3101** [comment]
Well, I think the non-linearity should not be shown to the user, the non-linearity could only be applied when passing the value to setProcessinghkfkjaghsdfiTint(), that way user and saving in the masxml is linear, but the nonlinearity is still there.

**Comment by masc4ii** [comment]
Hm, I don't know if the handling of the double cocoa slider is different there. The precision of the slider in Qt is fixed, limited and int. 
So if the user types the value via keyboard, I calc 1/"your function above" and set the slider. The slider (often) can't go to the exact calculated value and will jump to the next possible value, this sets with "your function above" the value again. The value changed now slightly to the value the user entered. This is how the user "sees" the non-linearity, and I have no idea how to make that better. That is only why I asked. If the user only drags the slider the behaviour will be okay non-linear.

**Comment by masc4ii** [comment]
Limited slider range to -10..10 with [commit](https://github.com/ilia3101/MLV-App/commit/12964c97d0cd348dc6701503073ac7dd74a23657)

**Comment by ilia3101** [comment]
That is good!
I compared non-linear and linear behaviour, but I still got the impression that non-linear feels more right, as the changes are less drastic when the slider is closer to the middle, and to me that seems correct (user should not notice it).
See if my way will work 😉 (Non-linearity only applied when passing value to processing object)

**Comment by ilia3101** [comment]
Actually had a better idea: maybe give it linear input, but all the non-linear effects will be done internally.
After all, why should GUI be doing processing module's work? 😆

**Comment by masc4ii** [comment]
Okay...that was what I understood the post above already :-)

**Comment by ilia3101** [comment]
Oh good, that wasn't exactly what I meant a few comments ago, but you read my mind from the future.
So yeah, basically don't worry about this, I will implement it all inside the processing object.

**Comment by masc4ii** [comment]
What you commited seems to do what you wanted to change. It is nonlinear now and finer around 0. So I think all is done for this bug finally?
