### ISSUE TITLE
OSX: Deploy app package with openMP

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#101]
I mostly got openMP on OSX working. 

**El Capitan:** 
-`brew install llvm`
-add llvm compiler to Qt compilers and create a new kit
-comment in the llvm lines in .pro file
-compile
-deploy
This works, but compatibility  is OSX 10.11+ only.

**Mavericks:**
-brew don't allow installing llvm, so we have to find another way...
-load llvm binaries from [here](http://releases.llvm.org/download.html)
-I installed it to /usr/local/opt/llvm, the same path where brew installes it (via link)
-add llvm compiler to Qt compilers and create a new kit
![bildschirmfoto 2018-08-03 um 19 53 13](https://user-images.githubusercontent.com/30245296/43657765-0a74a602-9757-11e8-86f0-63dd09c6490c.png)
![bildschirmfoto 2018-08-03 um 19 53 35](https://user-images.githubusercontent.com/30245296/43657775-10482f90-9757-11e8-97f2-03d7d4441813.png)
-comment in the llvm lines in .pro file
```
macx{
    QMAKE_CC = /usr/local/opt/llvm/bin/clang
    QMAKE_CXX = /usr/local/opt/llvm/bin/clang++
    QMAKE_LINK = /usr/local/opt/llvm/bin/clang++
    QMAKE_CFLAGS += -fopenmp
    QMAKE_CXXFLAGS += -fopenmp
    INCLUDEPATH += -I/usr/local/opt/llvm/include
    LIBS += -L/usr/local/opt/llvm/lib -lgomp
    QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.8
}
```
-compile (works, QtCreator is able to run it; starting app from finder does not work)
-deploy fails with this output:
```
ERROR: Cannot resolve rpath "libomp.dylib"
ERROR:  using QSet("/Applications/Qt5.7.0/5.7/clang_64/lib")
ERROR: Cannot resolve rpath "libc++.1.dylib"
ERROR:  using QSet("/Applications/Qt5.7.0/5.7/clang_64/lib")
```

Don't laugh, but I don't understand the output. Do you have any idea what I could do? Linking these two libraries to /usr/local/lib/ before deploying does not help...

**Comment by masc4ii** [comment]
Oh... short after writing the item I found a way... 
Just copy libomp.dylib and libc++.1.dylib to MLVApp/Contents/Frameworks/ and it works. 

But normally this should work automatically. Any ideas what could be wrong here?

**Comment by masc4ii** [comment]
I found a way to get deployment working! **MLVApp using openMP on MacOS 10.8.5+ is safe!!!**
Linking the missing libraries to the Qt lib folder resolved it.
```
cd /Applications/Qt5.7.0/5.7/clang_64/lib/
ln -s /usr/local/opt/llvm/lib/libc++abi.1.dylib libc++aci.1.dylib
ln -s /usr/local/opt/llvm/lib/libc++.1.dylib libc++.1.dylib
ln -s /usr/local/opt/llvm/lib/libomp.dylib libomp.dylib
```
I am not sure if this is a good way, because just changing the Qt version brings the same problem again... has someone a better idea?

**Comment by bouncyball-git** [comment]
It's so sad you have to jump through all those hoops for making this work under mac...

**Comment by dannephoto** [comment]
Got it working on mac both adding the command inside the pro fle or specified outside:
In Mlv App compiler oneliner:
`$(ls -d -t /usr/local/Cellar/qt/5* | head -1 | tr -d ':')/bin/qmake ~/MLV-App-master/platform/qt/MLVApp.pro QMAKE_CC=/usr/local/opt/llvm/bin/clang QMAKE_CXX=/usr/local/opt/llvm/bin/clang++ QMAKE_LINK=/usr/local/opt/llvm/bin/clang++ QMAKE_CFLAGS+=-fopenmp QMAKE_CXXFLAGS+=-fopenmp INCLUDEPATH+=-I/usr/local/opt/llvm/include LIBS+=-L/usr/local/opt/llvm/lib LIBS+=-lgomp QMAKE_MACOSX_DEPLOYMENT_TARGET=10.8 -spec macx-clang CONFIG+=x86_64 CONFIG+=release QMAKE_MAC_SDK=macosx10.9 && /usr/bin/make -j4 && $(ls -d -t /usr/local/Cellar/qt/5* | head -1 | tr -d ':')/bin/macdeployqt ~/MLV-App-master/platform/Mlv_app_master/MLV\ App.app`

I use latest llvm:
`brew install llvm@6`

All processes are automated in latest Mlv App compiler.
