### ISSUE TITLE
AppImage is missing libnsl.so.1

### ISSUE THREAD

**Issue by marekjedrzejewski** [ilia3101/MLV-App#102]
As in title. If you try to run it and don't have libnsl installed, it won't run. Happens on fedora, maybe other distros have that by default.

**Comment by masc4ii** [comment]
Found it. It is a part of GNU compiler. Very strange that it is not automatically installed by linuxdeployqt.

**Comment by masc4ii** [comment]
Known issue at linuxdeployqt: https://github.com/probonopd/linuxdeployqt/issues/158

> On Ubuntu indeed everything works, I have a working environment there already. However, RPM and AppImage created on Ubuntu don't work on CentOS (c/c++ runtime is too old there), hence my question.
I've just found out a way around it, in case anybody else is hit by this issue: I build on CentOS without -appimage, which means linuxdeployqt does not try to deploy libnsl. The package after this still runs fine (in my case at least) on CentOS, Fedora, Ubuntu and Debian.

**Comment by ilia3101** [comment]
Yep, had this issue on fedora some time ago thanks for bringing the package name up
