### ISSUE TITLE
mlv files missing after accidentally running script

### ISSUE THREAD

**Issue by Ars697** [ilia3101/MLV-App#103]
Hi, I was successfully running this app for months. Today I installed the lated version and loved the LUT and new filters. During exporting some of my mlv files I checked 'post export - HDR_MOV.command'. It requested installing some packages using terminal which I did. I noticed that some folders were created in the original folder where my mlv files resided. In these new folders tiff files were generated. When all finished all my mlv files vanished. Do you have an idea where they might be. Is there a way to recover them. Regards, Artur.

**Comment by Ars697** [comment]
[HDRMOV_LOG.txt](https://github.com/ilia3101/MLV-App/files/2268554/HDRMOV_LOG.txt)
I just wanted to add that in that folder where my mlv files used to be a log file has been created.

**Comment by bouncyball-git** [comment]
Danne usually moves the original MLVs to other folder (that's how his Switch is working) so I think, this script written by him does the same and they are nearby, in some newly created folder.

**Comment by dannephoto** [comment]
Thanks for getting back. I can't check into this atm but I see some dependencies missing. Maybe related to this.
Will check into this when I can. You can use photorec I think to recover files.

**Comment by Ars697** [comment]
Thank you so much for helpful attitude. I really do appreciate it. I will try to describe the process more accurately. After importing all the mlv files into the app I just wanted to try this HDR just to see what it does. When I did, it said that the process couldn't be completed because some components were missing. Terminal opened straight away and prompted to import some missing packages which I did. I had the folder open and could see that something was going. Like I mentioned 2 new folders were created and they started to fill in with tiff files which were created out of 2 previously processed .mov files which were also in that same folder as the mlv files. In fact after the process was finished no only the mlv files went missing but also the 2 previously processed and exported .mov files as well. It was so shocking to me to actually see how all the files were wiped out while I watched. The whole process seemed to be running in the background even after I closed the app itself. So after the files were gone the log file appeared and I couldn't do anything. The bin didn't contain anything. never seen anything like this before. Now I suspect that the system was doing it not the app and probably initiated somehow by the app and the components/scripts.

**Comment by dannephoto** [comment]
Ale kurwa :)
Hopefully you can recover those files with photorec. I used the program to recover 20gb of mlv files this summer.
Thanks to your report I will rework removal routines. Probably gonna keep alm files after processing since something could get wrong but I am not sure how. 
Very sorry for this. Will post again when fixed.

**Comment by Ars697** [comment]
I used PhotoRec which is brilliant. Indeed I recovered lots of mlv files but none of them are the files I lost. So there is hope they still must be somewhere. But for the life of me, I can not find them.

**Comment by Ars697** [comment]
I went through a finder window and used 'All My Files' scroll and couldn't find them. Is it possible that the files were hidden from view.

**Comment by masc4ii** [comment]
Do you know the tool EasyFind? Way better than Finder Search.

**Comment by dannephoto** [comment]
Maybe they are renamed somehow? Could you check by size, date?

**Comment by Ars697** [comment]
I used the tool EasyFind which really impressive. I looked for all .MLV videos. No luck. Seem to be gone permanently with no trace.

**Comment by Ars697** [comment]
Which is even more shocking that no trace of the files was found on the computer. Using photorec I was able to find all deleted mlv files on the CF card that was used during capture. Unfortunately, the newer files replaced the ones I lost.

**Comment by dannephoto** [comment]
@Ars697 
Very sorry to hear that you seem to have permanently lost your files. I have now removed the rm -r in the scripts so it can´t remove folders anymore. Note that if using the workflow again the only way to close it is from the small bash menu that opens up in the right corner. Press C and it will cancel and kill processing...
Latest commit:
https://github.com/ilia3101/MLV-App/commit/4b87ca2ad81b07106683c19a77a3cfc30194be2b

**Comment by masc4ii** [comment]
Has someone tested? Can we close?

**Comment by dannephoto** [comment]
Did a short test but nothing extensive. Will have a go tomorrow. Would be great to test some bigger files too.

**Comment by dannephoto** [comment]
@masc4ii 
I tested the script again agains a bunch of mlv files. Folders are kept and most HDR mov files ar created. However due to a bug with Hugin/enfuse which sometimes fails to complete a file or two it will break ffmpeg output. This can however also be fixed with a safeguard checking for completed files or else restart processing of that particular troubling file. I can put this into the script when I find some time. You can check for safeguarding in this post:
https://www.magiclantern.fm/forum/index.php?topic=21454.msg196815#msg196815

Anyway. Regarding the issues in this thread I consider this issue solved.

**Comment by masc4ii** [comment]
Good... so we let it opened for you as reminder? Or do we close and you create another enhancement issue?

**Comment by dannephoto** [comment]
Nah, keep it opened, I'm on it...

**Comment by masc4ii** [comment]
Great! Thx!
