### ISSUE TITLE
here is a quick ubuntu 18.04 debian package

### ISSUE THREAD

**Issue by revast** [ilia3101/MLV-App#105]
Congrats to  1.0 release !

http://openartisthq.org/debian/bionic64/mlvapp_1.0.0-1~openArtist1_amd64.deb

**Comment by ilia3101** [comment]
@revast Wow never knew about openartist before, very nice! And very nice of MLV App to be on it :smiley:.

Would you be ok with me reuploading the deb package on the download/release page of MLV App? Or should I just link? maybe so you can have a nice download count on there...

BTW how do you make a deb?

**Comment by revast** [comment]
oh thanks.

to make a deb, you can do that manually quite easy (which I prefer to do). Once you get the Hang of the Structure, its easy to do it. You can just unpack the deb I made and take a look. If a new version comes out, just alter the name, also in control file, the size, and copy the binary to the usr/bin folder, that's pretty much it (if you do not have to tinker around with documentation or such). What would be nice for this package would be that the big 512x512 icon has its smaller counterparts, loading such big icons slows any start menu...

The other way is the debian's one. That is, to get the sources build be the source package information, basically it's a DEBIAN folder inside the sources, which then contains all the bould dependencies info, the patches (which a debian package maintainter makes ; remember debian packages are built for MANY architectures, they tend to need some extra patches) 
That way (which is way more complicated) is the route to get a package into official debian repository. There, the package must comply specific rules (documentation, license... it is checked by a program called lintian) and must have an active maintainer, or it will get removed asap. 
But this is also the way you have to go to make a PPA at ubuntu's launchpad, as it's only accepting source-uploads, which then get build on ubuntu's build server infrastructure.. There are (many) helper programs which help in generating the debian sources package information, but, let's face it, its a quite complex process, which I try to avoid, because I have to handle way too much packages to concentrate on that. 

  Actually (besides the size when I include an app in the default install) only the one thing that the appimage does not work with the theme of the system it is run of prevents me of using it. I even filed a bug at linuxdeployqt and was looking into the issue, but to no avail till now, I use qt5ct, so that my Distro's qt packages match the GTK theme (which is a dark theme). So using just the appimage looks like a bright alien on my eyes, especially at night. Maybe it is possible to integrate a dark theme and a means to switch it into the app? I have seen people do so. Better would be to investigate what actions have to be done to include qt5ct into the appimage (and what i've seen that would also mean to add (parts of ) gtk to feed the dependencies of the gtk.so of qt5ct..)

**Comment by ilia3101** [comment]
Thanks for all of the information I might try and do this next time :)
Wait so appimage's dark theme is not working for you?

**Comment by alexmyczko** [comment]
i also have deb packages of it, in later version http://phd-sid.ethz.ch/debian/mlv-app/ and it's waiting to get into debian (official), and ubuntu will get the copy for free: http://ftp-master.debian.org/new.html

**Comment by masc4ii** [comment]
Thank you so much! That sounds absolutely great! I'll post the debian link to the main page!
