### ISSUE TITLE
IGV: artifacts in highlights

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#106]
When IGV is chosen, overexposed highlights get sometimes very bad artifacts (flickers).
![bildschirmfoto 2018-09-02 um 16 38 27](https://user-images.githubusercontent.com/30245296/44957133-a1738a80-aece-11e8-98c2-af921d2063ee.png)

**Comment by masc4ii** [comment]
https://www.ebay-kleinanzeigen.de/s-anzeige/ikea-tisch-lack-buche-90er-breite/936309899-88-29
This fixes the issue for my 5D2 clips - whyever. When changing the limit from 40000 to a higher value, the issue is back; lowering the value cuts image data. Maybe someone understands what happens and can replace the 40000 with a correct value.

**Comment by masc4ii** [comment]
https://github.com/ilia3101/MLV-App/commit/27dc244e3cb9ff7b863943c56d79b31040156376
This fixes the issue for my 5D2 clips - whyever. When changing the limit from 40000 to a higher value, the issue is back; lowering the value cuts image data. Maybe someone understands what happens and can replace the 40000 with a correct value.

**Comment by masc4ii** [comment]
@ilia3101 : If you find some time and if you like to help me... IGV demosaic sometimes brings better results than AMaZE (e.g. for scenes with moiree on lines and lots of detail). But hard contrast lines get cyan or red sometimes. I took your whitebalance code from AMaZE, it became better. I changed it a bit and calculated with correct black level (you just made average -= 4000 or something) and it became again a bit better. But now I have no idea to get it still better... do you have any ideas how to improve? For me it looks like it is not shifted to a correct range...
![bildschirmfoto 2018-10-13 um 20 32 48](https://user-images.githubusercontent.com/30245296/46908710-2e2a5300-cf27-11e8-8544-74ec4138f3f2.png)

**Comment by bouncyball-git** [comment]
>  I changed it a bit and calculated with correct black level (you just made average -= 4000 or something)

Will it help to amaze too? Did you try?

**Comment by masc4ii** [comment]
Yes I did, and the code is still there (commented out). But with the 4000 the result was better there (whyever, maybe I missunderstood what it shall do).

**Comment by masc4ii** [comment]
Solved in https://github.com/ilia3101/MLV-App/commit/5b058c017a04fdfd203543fa2357f92c60565088
