### ISSUE TITLE
MAPP and loading time improvement when audio is present

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#109]
I've been thinking lately about loading time improvement of the MLV with audio. 

Now audio loading unloading is done by AudioPlayback object. What if loading will occur during MLV scan itself? Adding one field (pointer to audio buffer) in MlvObject struct will simplify a lot of code. Loading/unloading of audio will be performed at the same time when MLV object is created/deleted.

If it will be designed like this there will be very easy way to add audio data to MAPP file and then load it from MAPP in a one straight sequential read. Will be quicker than even indexed access to MLV for getting audio chunks and assemble the buffer.

@masc4ii: It would require some reworks but is definitely doable without a big PITA. What do you think?

**Comment by masc4ii** [comment]
I use MLV with audio only... so why not 😄 
If you know what to do, you could try it! Let me know, if I can do something as well.
I now started to write a kind of manual, what trys to explain all the stuff. See Wiki area here on github.

**Comment by bouncyball-git** [comment]
Cool! be back soon.

**Comment by masc4ii** [comment]
STOP! Found one issue: audio end is to early now! Look the audio wave graph - in the very right something is missing (especially for very short clips)
![bildschirmfoto 2018-09-23 um 16 56 52](https://user-images.githubusercontent.com/30245296/45929450-41628800-bf52-11e8-9548-1e3a059684ff.png)

**Comment by bouncyball-git** [comment]
Hm... Is it like this for every clip?

**Comment by masc4ii** [comment]
At least for all short clips. Until now audio was long enough, so I expect it is a bug. Uploaded the file for you.

**Comment by masc4ii** [comment]
Something seems to be really off! Look my synctest clip (you have it, right?!). In the end a little bit is missing - but: Normally the sync offset is 1 frame - now it is 2 or 3 frames.
![bildschirmfoto 2018-09-23 um 20 57 49](https://user-images.githubusercontent.com/30245296/45931842-f0fc2200-bf73-11e8-808e-70e3d3a83af7.png)

**Comment by bouncyball-git** [comment]
Yes  have that file and already put two versions of mlv app like you do! ;)

There is something with audio graph. it is condensed in newer version nonlinearly, e.g. like: 

`new_val = old_val * some_descending_coeff`

Exported audio data as WAV is absolutely identical for v1.0 and latest commit. Also visually exported clips have same sync.

Can you help and take a look what I'm missing in graph generation?

**Comment by masc4ii** [comment]
Thanks for the hints. I was searching already for a while, but found nothing so far. But with these hints I might be more successful!

**Comment by bouncyball-git** [comment]
I found the reason.

I deleted those lines:

`//Correct audio length to video length
        uint64_t theoreticSize = getMlvAudioChannels( m_pMlvObject ) * getMlvSampleRate( m_pMlvObject ) * sizeof( uint16_t ) * getMlvFrames( m_pMlvObject ) / getMlvFramerate( m_pMlvObject );
if( theoreticSize < audio_size ) audio_size = theoreticSize;`

Because I thought they are not needed any more (audio already aligned in every manner) but I was wrong.
Addint those lines back corrected issue.

However I can not understand why????

**Comment by bouncyball-git** [comment]
commited

**Comment by masc4ii** [comment]
Right. But if you compare theoreticSize and audio_size before setting it equal, they are different. You know why?

**Comment by bouncyball-git** [comment]
Hate reading own code after a while ;)

Commited, please review.

**Comment by masc4ii** [comment]
Something is wrong with "readMlvAudioData()" ... can't find this function and can't compile.

**Comment by bouncyball-git** [comment]
Did you clean all and then compiled? I changed a lot of stuff... it compiles under linux and runs.
 w/o issues.

**Comment by bouncyball-git** [comment]
Fixed it :smile:

**Comment by bouncyball-git** [comment]
MLV export fixed as well.

**Comment by masc4ii** [comment]
👍 Works now. Audio graphic seems to be right. What I don't understand: if I export ProRes, export CDNG (take Wav only) or export Wav only. Then I drop all clips to FCPX timeline... 
![bildschirmfoto 2018-09-24 um 20 32 25](https://user-images.githubusercontent.com/30245296/45971631-ca082380-c039-11e8-93a1-16db618553a5.png)

**Comment by bouncyball-git** [comment]
What about Resolve?

**Comment by bouncyball-git** [comment]
Good catch. Well I'll take a look tomorrow. If you're gonna find out something new please post here. Seya.

**Comment by masc4ii** [comment]
In Resolve all is fine...
![bildschirmfoto 2018-09-24 um 20 50 00](https://user-images.githubusercontent.com/30245296/45972411-e907b500-c03b-11e8-9f90-1c08d9191b6e.png)

**Comment by masc4ii** [comment]
What was wrong with mlv export?

**Comment by bouncyball-git** [comment]
After all those changes it was broken too.

Did you try mlc app v1.0 to test the same you showed on picture with FCPX strange async?

**Comment by masc4ii** [comment]
Okay :) Good work!
Yes, same behaviour with v1.0 (what I find strange... but seems to be a FCPX issue).

**Comment by bouncyball-git** [comment]
As far as I've tested cut in/out works for both playback and export. Take a look at it please to be 100% sure.

**Comment by bouncyball-git** [comment]
Cool! Thank you!

**Comment by bouncyball-git** [comment]
[Commited](https://github.com/ilia3101/MLV-App/commit/0bb47b954e5eecd3175d506053281ba5e2744b3c) MAPP v2 support.

Actually I'm really pleased with the result. Please try and share your findings.

**Comment by masc4ii** [comment]
With my small set of testclip it works well.

**Comment by bouncyball-git** [comment]
You have to try with more than 2 chunk MLVs, it's where it shines 😄

**Comment by masc4ii** [comment]
Cool. I'll do this evening!

**Comment by masc4ii** [comment]
9.5GB MLV, 32 vs 2 sec loading time! But: MAPPs are very very large now! If MAPP v1 was 7kB, MAPP v2 is 1.2MB! Is that right?

**Comment by bouncyball-git** [comment]
Yes that is right. MAPP v2 includes whole syncesd and aligned audio. For speed's sake you have to sacrifice something :smile:

**Comment by bouncyball-git** [comment]
It can be as big as 800mb for 1 hour clip. You just do not have separate WAV file lying around.

**Comment by bouncyball-git** [comment]
Is that a huge problem?

**Comment by ilia3101** [comment]
I like that it contains audio!

**Comment by bouncyball-git** [comment]
@masc4ii 

I can optionally make v2 with audio or without it. Do you need it?

**Comment by masc4ii** [comment]
@bouncyball-git : no, no big deal. 
a) if I like it fast, I switch it on. b) if I like it small, I switch it off. All is fine 😄

**Comment by bouncyball-git** [comment]
Yes sure :)
