### ISSUE TITLE
QtApp: Adding metadata to png export files

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#11]
Add the "cHRM Chunk" to libpng files. From this documentation: http://www.libpng.org/pub/png/book/chapter10.html
Might begin filling it with values once actual gamut/space options are added(and hopefully ffmpeg won't ignore that info).

**Comment by ilia3101** [comment]
Good idea to be adding these things to the issue tracker 👍

**Comment by masc4ii** [comment]
I have seen the "enhancement" label and thought this might be good as wishlist...

**Comment by masc4ii** [comment]
The chunk can be set using
`png_set_cHRM( ... );`

But I can't find how to connect that to the png created in my line
`png_image_write_to_file( &image, m_fileName.toLatin1().data(), 0, buffer, 0, NULL );`

And then we need to know all the colour parameters:
White point x | 4 bytes (0-2,147,483,647)
White point y | 4 bytes (0-2,147,483,647)
Red x | 4 bytes (0-2,147,483,647)
Red y | 4 bytes (0-2,147,483,647)
Green x | 4 bytes (0-2,147,483,647)
Green y | 4 bytes (0-2,147,483,647)
Blue x | 4 bytes (0-2,147,483,647)
Blue y | 4 bytes (0-2,147,483,647)

**Comment by ilia3101** [comment]
For now, if you already decide to add this, just fill it with sRGB values.

**Comment by masc4ii** [comment]
In [this commit](https://github.com/ilia3101/MLV-App/commit/59460830501cba451a40ad7f28511555eb3c87d9) I set the png image flag to 16bit sRGB.
@ilia3101 : can you test if that changes anything? (It is only one line, maybe you can check also with your cocoa app)

**Comment by masc4ii** [comment]
I checked all possible flags and also no flag (as it was before) and I can't find any difference in the files :(
But Photoshop and other image browser tell it is a 16bit sRGB PNG. (always)

**Comment by ilia3101** [comment]
Sorry for missing this :(
So if you just input random data to the cHRM chunk it is not picked up anywhere?
Well, for now it should be fine anyway as by default it is interpreted as sRGB, which is what I've been assuming the whole time.
Hopefully this works in the future though.

**Comment by masc4ii** [comment]
I'll close this issue, because we no longer use intermediate PNGs for clip export.
