### ISSUE TITLE
Gradient mouse click behaves wrong when previously color picker was active

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#113]
When color picker is active and you try to apply gradient frame by mouse white balance changes after mouse click in image according to the place it was clicked to ;)

I have one proposition if it's not very hard to do. Color picker should be active unless mouse cursor hovers over the image window. If It's off the image windows picker should be turned off.

Is it possible?

**Comment by masc4ii** [comment]
Thanks for posting.

I like your idea, because that would be great to use this way. But I must study Qt for that.

An easy solution is to disable WBPicker when eabling gradient painter.

**Comment by masc4ii** [comment]
Okay... that seems to be possible. BUT: if gradient lines are shown on the picture, hovering over them means also to leave hovering on picture and WBPicker would be disabled. Not good, or what do you think?!

And already now: when draging using pipette on the hovered gradient lines, move the lines and click WB... :-P  (oh man)

**Comment by masc4ii** [comment]
Haha... found another solution, and this works like a charme. Now I only can still drag the gradient lines by using the picker.

**Comment by masc4ii** [comment]
Gradient element is now locked, if wb picker is enabled. Please test... all should be fine now! And I love your idea of disabling wb picker when leaving the viewer.

**Comment by bouncyball-git** [comment]
Picker goes off when out of the image!!! great. It Also goes off when gradient drawer button is pressed! great. It does not go off when gradient enable box is checked ;) can be this corrected easily?

**Comment by masc4ii** [comment]
😄 But is this a problem? If yes, it should go off when using any other element in GUI. And now it gets complicated again... 😄 ... or wait... maybe one idea could work... 😄

**Comment by bouncyball-git** [comment]
Try this scenario. Activate picker then do not go into image area and press to enable gradient then go to image are ;)

**Comment by masc4ii** [comment]
Try latest commit.

**Comment by bouncyball-git** [comment]
Great!
