### ISSUE TITLE
DPI/Scaling Issues on Windows

### ISSUE THREAD

**Issue by ajmrly** [ilia3101/MLV-App#114]
I use a huge 4K monitor for video editing and so use display scaling on Windows. The app seems to honour scaling for font sizes, but not element widths. See below. The simple solution would be to make the toolbar element widths based on the type size (like rem for web design) or manually scalable by the user.

At 150% display scaling (buttons cut off)
![2018-10-13 17_54_37-2018-10-13 17_42_09-](https://user-images.githubusercontent.com/15355321/46902428-2bbcfe80-cf11-11e8-8f37-4e17518f8d1f.jpg)

At 100% display scaling (what is this? An app for ants?)
![2018-10-13 17_55_08-2018-10-13 17_48_28-](https://user-images.githubusercontent.com/15355321/46902452-632bab00-cf11-11e8-92e6-306966cb685b.jpg)

Thanks for the great app!

**Comment by masc4ii** [comment]
The problem isn't MLVApp. The problem is Windows. There is nothing we can do to avoid it. You could use any other OS or Windows at 100% and you won't have the scaling problem.

**Comment by ilia3101** [comment]
Maybe not just windows' fault, but specifically Qt on windows? As most windows apps that I've seen scale fine

**Comment by masc4ii** [comment]
I don't know... I have seen so many programs not running correctly on Windows scaling > 100%, that I can't understand any user is using it. I don't think all these programs run with Qt.

**Comment by ilia3101** [comment]
https://stackoverflow.com/questions/24367355/automatic-rescaling-of-an-application-on-high-dpi-windows-platform
What do you think of this? Anything useful? Or is it too old to be relevant

**Comment by masc4ii** [comment]
The craziest thing is, that there seems to be no rule, how Windows changes that. Normal text is bigger, Groupbox text is still small, graphic text as in the timecode label is again big (whyever). While graphics are mostly small, but slider handles are big, button icons are big, menu item icons are again small, and stylesheet around the slider handels is half half (radius is still small, but overall size is big). WTF?!?!?!?!

**Comment by bouncyball-git** [comment]
Booo Microsooft!!!

**Comment by masc4ii** [comment]
This will make Windows Skaling Users happy(er). https://github.com/ilia3101/MLV-App/commit/5bbb004ac5c71af7713238c339cedab5c5836df3

Still not perfect, but maybe better usable. I just forbit rescaling of graphics...
![win150percent](https://user-images.githubusercontent.com/30245296/46939713-55883980-d067-11e8-9984-68f223ccc028.png)
