### ISSUE TITLE
Small change to default values

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#115]
could we make this:
![screenshot from 2018-10-13 12-56-52](https://user-images.githubusercontent.com/23642861/46905149-93f6ea80-cee7-11e8-90b3-801ee69c1ab6.png)
be this:
![screenshot from 2018-10-13 12-57-04](https://user-images.githubusercontent.com/23642861/46905164-bab52100-cee7-11e8-91da-3cec8f132bab.png)
by default?

The current numbers seem a bit non aesthetic. I have thought this for such a long time :cat2:

Unless it affects the image noticeably ? Then maybe 20 for the strength and 80 for range... idk

**Comment by ilia3101** [comment]
I made this change to cocoa app in its final days.

**Comment by masc4ii** [comment]
@ilia3101 : is 20 and 75 okay? Like that the darks are looking nearly the same. Using 25 or 80 (more aesthetic, sure) the darks are getting darker... or 20 and 70?

**Comment by masc4ii** [comment]
Yes... better with 20 and 70... what do you think?

**Comment by ilia3101** [comment]
20 and 70 is good

**Comment by masc4ii** [comment]
All okay now? Can we close here?
