### ISSUE TITLE
Add new focus pixel maps

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#116]
There are new focus pixel maps availlable... could we add it @bouncyball-git ?
https://www.magiclantern.fm/forum/index.php?topic=16054.msg207178;topicseen#msg207178

**Comment by bouncyball-git** [comment]
Yeah I know. Cool!

**Comment by bouncyball-git** [comment]
We can add the available [80000326_1808x3508.fpm](https://bitbucket.org/daniel_fort/ml-focus-pixels/src/default/focus_pixel_map_files/80000326_1808x3508.fpm) for now (it works in mlv app). But we should wait until fdort updates his script.

**Comment by masc4ii** [comment]
Okay. Done for now.

**Comment by Jip-Hop** [comment]
Would it be a good idea to add an 'auto update' feature in there for the focus pixel maps?

I installed the latest MLV app release (v1.11), but it didn't include the focus pixel maps for the "5k anamorphic flv" preset. Manually downloading all maps by daniel_fort from hist [Bitbucket](https://bitbucket.org/daniel_fort/ml-focus-pixels/) repo, and placing them in the `/Applications/MLV App.app/Contents/MacOS` made the focus pixels go away.

Perhaps MLV app could not include any maps by default, but check an external repo for the latest focus pixel maps. If new maps are released, it could ask the user to download and update the focus pixel maps. That way there doesn't need to be another MLV app release when new maps are made, and users won't have to manually download maps or check if there are new maps in the repo.

**Comment by masc4ii** [comment]
This would exactly be my dream since a long time. But I have no solution yet, how to realize with this repository here, or bitbucket. GitHub changes its links for each commit.

**Comment by Jip-Hop** [comment]
You already have auto update working for MLV App itself. Can't a similar approach work for the map files, if they were in a GitHub repo?

Or there could be a manifest file in the repo, with a last updated date in it. MLV App would then check for example this URL: https://raw.githubusercontent.com/ilia3101/ml-focus-pixels/master/manifest.json and download the whole repo as ZIP if there's an update according to the manifest. URL to zip could be: https://github.com/ilia3101/ml-focus-pixels/archive/master.zip.

I suppose a similar strategy could work for a Bitbucket repo.

**Comment by masc4ii** [comment]
The update function is just a check, which parses the release page. It does not know about a download link. And it can't download, unzip, or install. I would need a kind of ftp (or similar) where I can check if single files (maps) are existing, download them (one by one) and copy it to the right place. No idea if this can be realized with GitHub...

**Comment by Jip-Hop** [comment]
Could be done with the [GitHub API](https://developer.github.com/v3/):

`curl --silent "https://api.github.com/repos/ilia3101/MLV-App/contents/platform/qt"`

Or just open [the link](https://api.github.com/repos/ilia3101/MLV-App/contents/platform/qt) in the browser.
It will list all the files in the `qt` folder in this repo as an example.

It includes hashes for the files, so they can be easily compared and only different files can be downloaded and updated individually. No need for FTP.

**Comment by masc4ii** [comment]
Thank you very much for the input!!! With that I can imagine something. Maybe we get this feature! :)

**Comment by Jip-Hop** [comment]
Great to hear!

**Comment by masc4ii** [comment]
I think I got it realized. Please try! 😄

**Comment by Jip-Hop** [comment]
Would love to. Do you have a MacOS build I can try?

**Comment by masc4ii** [comment]
https://www.dropbox.com/s/k7g0iam34i82j71/MLV%20App.zip?dl=0
I did not test it on a Mac without Qt. Hope it runs.

**Comment by Jip-Hop** [comment]
Trying to install Qt now (maybe I already succeeded?), so I could compile. But this is faster! Thanks :)

**Comment by Jip-Hop** [comment]
Did you by any chance zip the wrong version of MLV App? For me it says, date created: 31/03/2020. It runs for me, but doesn't seem to pull any extra maps after opening or manually checking for updates. It has these maps included:

```
80000346_1872x1060.fpm
80000218_2040x793.bpm
80000218_2040x1268.bpm
80000218_2944x1212.bpm
80000218_4256x610.bpm
80000326_2592x1107.fpm
80000331_1808x727.fpm
80000331_1808x759.bpm
80000331_1808x1951.fpm
80000331_1808x2031.bpm
80000331_1872x1059.fpm
80000331_1872x1190.fpm
80000331_5040x2149.bpm
```

**Comment by masc4ii** [comment]
Strange.
https://www.dropbox.com/s/0m1i8f0m167a7a5/MLV%20App.zip?dl=0
Please try again.

**Comment by Jip-Hop** [comment]
This one came without focus pixel maps.
How do I trigger the download of the maps?

<img width="1440" alt="Screenshot 2020-07-11 at 00 12 18" src="https://user-images.githubusercontent.com/2871973/87207062-48b37b00-c30b-11ea-89fc-8b86529f0f5a.png">

<img width="1440" alt="Screenshot 2020-07-11 at 00 12 31" src="https://user-images.githubusercontent.com/2871973/87207051-40f3d680-c30b-11ea-8ff4-30a305071f6e.png">

**Comment by masc4ii** [comment]
Just open a clip which needs a fpm.

**Comment by masc4ii** [comment]
Now MLVApp also asks to install all maps for one camera in one step. Status is shown and hidden automatically when ready.

**Comment by Jip-Hop** [comment]
> I think this was your wish. 

Yeah it's great! Just said it to confirm this time I had the right version to test. Awesome work, implementing this feature already!

Sounds good that it downloads all maps for one cam too :)

I've got another suggestion though. Are you sure the PixelMaps directory hidden 2 levels deep in the MLV App repo is the best place to keep the maps? Personally I'd make a dedicated repository for it and invite others, like Danne, as collaborators so they can directly commit (upload) new maps to the repo. Then MLV App will check this repo with the same api you use now. Benefit would be a central place for all the maps, perhaps with instructions on how to make them. You don't have to give others control over the MLV App repository for them to upload new maps. MLV App is not the only program to use the maps, so it would make sense to me to make a dedicated repo for them and not keep them as part of MLV App.

Could it be that a map file is updated (changed) on GitHub and needs to be redownloaded? Is there already a check for this?

**Comment by masc4ii** [comment]
Okay. We moved to root. If a map changed, you must delete it first for now. The app doesn't overwrite the map as it is now.

**Comment by Jip-Hop** [comment]
If you want to overwrite maps when they've changed, you can make use of the `sha` entry for each file in the json data returned by the api.

For example, to compute the `sha` value of file `80000346_5080x738.fpm`, you'd run this command: `git hash-object 80000346_5080x738.fpm` which outputs: `3d9d999196f0bd658aec09ec22b0ccbd23dc049c`. It's the same value as in the json data, so the file doesn't need to be overwritten.

Of course `git hash-object` can only be used if git is installed, so to compute these hashes in MLV App you'd need to use a crypto library that computes sha1 hashes. But in the case of git the hashes need to be computed in a specific way, as explained in [this answer](https://stackoverflow.com/a/5290484/1318145):
> You see a difference because git hash-object doesn't just take a hash of the bytes in the file - it prepends the string "blob " followed by the file size and a NUL to the file's contents before hashing.

This perl example returns the same value as `git hash-object`.
```perl
( perl -e '$size = (-s shift); print "blob $size\x00"' 80000346_5080x738.fpm \ && cat 80000346_5080x738.fpm ) | openssl sha1
```

The answers to [this question](https://stackoverflow.com/q/552659/1318145) provide some more example implementations, which return the same hash as `git hash-object`.

**Comment by Jip-Hop** [comment]
I just compiled MLV App from source, and it asked me if I wanted to install all the maps for my camera. This is great! 😃 

<img width="540" alt="Screenshot 2020-07-11 at 16 06 58" src="https://user-images.githubusercontent.com/2871973/87225901-9a521900-c390-11ea-874d-33975d4bd5a4.png">

**Comment by masc4ii** [comment]
The standard MLVApp user won't have git and git is no part of MLVApp. But there is a way in Qt to get the SHA: https://stackoverflow.com/questions/16383392/how-to-get-the-sha-1-md5-checksum-of-a-file-with-qt
This could be compared to the hash in the json file. 
Disadvantage: even if a map is available, MLVApp has to go online...
Maybe this check should not be performed every time a clip is selected.

**Comment by masc4ii** [comment]
Hm... unfortunately this does not work. That means the functions work, but I get always a different hash with the correct size.

**Comment by Jip-Hop** [comment]
Aah nice, it's not difficult to generate hashes with Qt then.

Did you try the method I posted? Or did you only compute the hash of the file contents?

What I was trying to explain is that just computing the sha1 hash of the file won't work. You have to compute it in the same way git does.

From [here](https://stackoverflow.com/a/552725/1318145):
> This is how Git calculates the SHA1 for a file (or, in Git terms, a "blob"):
>
>`sha1("blob " + filesize + "\0" + data)`
>So you can easily compute it yourself without having Git installed. Note that "\0" is the NULL-byte, not a two-character string.


```C++
    QFile f(fileName);
    if (f.open(QFile::ReadOnly)) {
        QCryptographicHash hash(hashAlgo);
        if (hash.addData(stuffToHash)) {
            return hash.result();
        }
    }
```

Where `hashAlgo` is the sha1 QCryptographicHash::Algorithm enum value and `stuffToHash` is: the string "blob " + file size as a number + NULL-byte + the actual file data as read by f.open().

Contacting GitHub each time a clip is selected is too much indeed. It would be enough to just retrieve the JSON file once at startup, compare all local maps and only update the ones where the hash doesn't match. Keep the JSON file for as long as MLV App is open. Then each time a clip is added, if the map hasn't yet been downloaded, but according to the already downloaded JSON file there is a map available, then the popup will ask if the user wants to download the map.

**Comment by Jip-Hop** [comment]
Ah I see that you compute the hash from the file contents only:
https://github.com/ilia3101/MLV-App/blob/83491d2850c883c0e95ac30bb5794f75f90d0315/platform/qt/FocusPixelMapManager.cpp#L115 

I don't know exactly how to concatenate the components we need in C++, but probably using `QCryptographicHash::addData()`.

Maybe something like:
```C++
QCryptographicHash hash(QCryptographicHash::Sha1);
hash.addData(string "blob "); // start with the string "blob "
hash.addData(f.readAll().length); // add size in bytes of the content
hash.addData(\0); // null byte
hash.addData(f.readAll()); // actual file content
shaFile = hash.result().toHex();
```

Obviously has errors but might help as an example.

**Comment by masc4ii** [comment]
Thank you for your help. But it is neccessary at all to build this hash? Why not comparing the size? The only part of the hash brought in by the file is its size...

**Comment by Jip-Hop** [comment]
Then two files with same size but different content will be seen as identical, and the file won't be updated. The hash is computed from both the content and the file size, so it won't have this issue.

**Comment by masc4ii** [comment]
But where is the content used? Ahhh... now... last "addData" line... forget what I wrote. Sry. 😄

**Comment by Jip-Hop** [comment]
Haha it would have been much easier if git just used the file contents for the hash :p then you'd already be done! But you're almost there now :)

**Comment by masc4ii** [comment]
Still no success (with the length). This addData only accepts char* with length or QByteArray. Whatever I try, I get the wrong hash or a crash.

**Comment by Jip-Hop** [comment]
Sorry don't know how to fix that. Maybe first format a string consisting of all the parts?

**Comment by masc4ii** [comment]
I tried, but I get another hash, not the correct one.

**Comment by Jip-Hop** [comment]
Can you show what you've tried? Commit or paste some of the code here. I don't normally write C++ and never used Qt. But I could try to look at it tomorrow. Would be helpful to see what you already tried.

**Comment by masc4ii** [comment]
```
            QCryptographicHash hash(QCryptographicHash::Sha1);
            hash.addData( QString( "blob " ).toUtf8() ); // start with the string "blob "
            hash.addData( QString( "%1" ).arg( f.size() ).toUtf8() ); // add size in bytes of the content
            hash.addData( QString( "\0" ).toUtf8() ); // null byte
            hash.addData( f.readAll() ); // actual file content
            shaFile = hash.result().toHex();
```

**Comment by Jip-Hop** [comment]
Could the try the answer to the question I posted on StackOverflow?

https://stackoverflow.com/a/62862398/1318145

**Comment by masc4ii** [comment]
Great! Thank you! That works!

**Comment by masc4ii** [comment]
Okay. Now it updates outdated maps once a day.

**Comment by Jip-Hop** [comment]
Lovely!

Do you think MLV App should ask the user for permission to contact GitHub to check for map updates?

Maybe a message at first launch asking:

> Allow MLV App to contact GitHub to automatically check for application updates, and keep the focus pixel maps up to date (internet connection required)?

I think it would make sense to have these 2 update features (app update and map updates) share the same "Auto Check for Updates" checkbox.

Also I'd check (again) for focus pixel maps when the user manually presses the "Check for Updates" menu item.

**Comment by masc4ii** [comment]
>Do you think MLV App should ask the user for permission to contact GitHub to check for map updates?

No, I don't think so.

>I think it would make sense to have these 2 update features (app update and map updates) share the same "Auto Check for Updates" checkbox.

This is what I did.

>Also I'd check (again) for focus pixel maps when the user manually presses the "Check for Updates" menu item.

Here I am not really sure - I'll check that.

**Comment by Jip-Hop** [comment]
Looks complete to me now. 😃 Awesome you were able to add it so quickly. Looking forward to see it in the next release.

I had two more performance improvements suggestions. Don't know if they're worth it, so I'll just leave them here:

- After opening the file here: https://github.com/ilia3101/MLV-App/blob/04da9784d954f1426b5bdf3f35131228817fb791/platform/qt/FocusPixelMapManager.cpp#L114
Compare the size of the local file with `size` in the JSON file. If they don't match, they're different and the file needs to be updated (no need to hash the file). If they match, they could be identical so we need to perform the hash check. It's a performance improvement because we check a cheap condition first, and only perform the expensive one (file hash) if necessary. However, if all maps are up to date (probably most of the time?), then all files need to be hashed and it's actually adding the size check on top...
- I noticed quite a few maps are identical in contents, only the filenames are different. You can see which ones have the same contents in the JSON file, because they share the same hash. For files with the same hash, don't download identical contents again, instead download it once and for all next files with the same contents copy the frist file and rename. Probably easiest to sort the maps in the JSON file by their hashes, and then check in a loop if the current map has the same hash as the previous one. If that's the case, don't start another download but copy and rename.
