### ISSUE TITLE
Cocoa App does not have key features

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#12]
Sessions.... Histogram..... AUdio.... Tabs.... etc

**Comment by ilia3101** [comment]
Issue update
Sessions may be done soon: https://github.com/ilia3101/MLV-App/commit/e828da24593a037bcaea85296297a92d0453c91e
Multiple clips can be opened already.

**Comment by bouncyball-git** [comment]
I really have to revive my hackintosh :) never ever saw the cocoa version on my screen.
