### ISSUE TITLE
Dual iso section improvement in edit pane.

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#122]
Hey guys talking about design. I have a small idea regarding fu..ing/bloody dual iso section ;)

Finally I want to account the DISO block presence. So I think there can be these changes in the edit pane:

1. When DISO block is not detected all widgets of dual iso part will be grayed out, except the small check box with title "Force dual iso" or "Old dual iso" or similar which fits in the interface better, you decide, you got the idea (this is for older dual iso MLVs without DISO block or ones which are somewhat stubborn to be detected). Or maybe put small push on push off bitton with lamp or exclamation pictogram on it...
2. When DISO block is detected all widgets of dual iso block will be active except "Force" check box which will be grayed out.

What do you think about it?

**Comment by masc4ii** [comment]
So we just have one button "Force" more than now? What if Force is checked? Are the greyed out buttons enabled again?

**Comment by bouncyball-git** [comment]
Never mind it was off topic there and deserves separate issue thread anyway.

Yes they should be active after "Force" is checked.

**Comment by bouncyball-git** [comment]
@masc4ii 

Commited backend code [link](https://github.com/ilia3101/MLV-App/commit/1c3704e4fe7415a35dcf626f2e2430053d362b0c)

There are 2 funcs for you:

```
enum { DISO_INVALID, DISO_FORCED, DISO_VALID }; // Return values
int llrpGetDualIsoValidity(mlvObject_t * video);
```

and


```
void llrpSetDualIsoValidity(mlvObject_t * video, int diso_force);
```

diso_force can be true/false

**Comment by masc4ii** [comment]
First function is for autodetection and autosetting of the button? 
Valid = all buttons enabled, force disabled
Invalid = all buttons disabled and force enabled
forced = all buttons enabled because force was enabled
?

**Comment by bouncyball-git** [comment]
Yes llrpGetDualIsoValidity returns enum status which was set either during MLV loading or when you call llrpSetDualIsoValidity with forced set to "true"

And yes all is correct for buttons!

**Comment by masc4ii** [comment]
I think about, would that also fit:
Valid = all buttons enabled, on button = "On"
Invalid = all buttons disabled and on button = "Force" (not checked)
forced = all buttons enabled because on button = "Force" is checked
? So we wouldn't need another button.

**Comment by bouncyball-git** [comment]
Yeah... I've been thinking about is too.

But it somewhat complicates things and yes preview also should be forced. Have other ideas?

**Comment by masc4ii** [comment]
Haven't really done anything until now... but:
-Loading a darkframe crashes the app.
-Opening a session directly after app launch crashes the app. 
Don't know why... :(

**Comment by masc4ii** [comment]
Okay... please test. Your button is there... tricky little thing...

**Comment by bouncyball-git** [comment]
Oh you spent a lot of time. I thought it would be just simple check box beside the title (on the right).

Thank you! It works great! Just the button a bit larger (taller) then other three.

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-11-01 um 17 54 18](https://user-images.githubusercontent.com/30245296/47866505-39beba80-ddff-11e8-8bc1-0deba27f13d4.png)
You mean this way?

**Comment by bouncyball-git** [comment]
Yes! it is very nice.

**Comment by bouncyball-git** [comment]
I guess it can be closed
