### ISSUE TITLE
v1.2 DUAL ISO problems are back..

### ISSUE THREAD

**Issue by gac123** [ilia3101/MLV-App#123]
so saturday i recorded the first show of my friends in dual iso seeing the v1.1 version fixed the dual iso problem, i was quite comfortable doing this

upon opeing mlv app i was pleasantly greeted with the "there's a new version" popup, so i decided to get the new and improved..

~8 hours later the 1 hour show was converted and there are problems every x frames... from a small blue line appearing at the top to (overexposed) highlights not being "un-dual-iso-ed"

see https://imgur.com/a/eXHQPtS

so i re-export with v1.1 (and 8 hours later), no such problems, but (doh!) i forget to export with clog, so olé i'm exporting again for another 8 hours :) (how is the multi threaded thing moving along? :) )

**Comment by masc4ii** [comment]
Could you upload a clip for testing such issues please?

For the multithreading topic: we got more problems with that than it accelerated anything so this is stopped. Dualiso algorithms have to be written new from scratch for that.

**Comment by gac123** [comment]
is there a way to cut a split mlv file? (total size is about 86GB)

maybe the issue is the same with my previous test clip (found here: https://mega.nz/#F!V1IiEKqC!K-YCjrQ7LOKwdXX5fv17xQ)

**Comment by gac123** [comment]
just tested it with my previous test clip, export is fine with v1.2

**Comment by masc4ii** [comment]
You could cut it with MLVApp. Use CutIn&CutOut and export as MLV.

**Comment by gac123** [comment]
done! i've compared my previous v1.2 export with the cut version on v1.2 and the results are not consistent

the errors are not seen in the preview, only in the export with prores 4444, duals iso on, and tonemapped alexa log c

**Comment by gac123** [comment]
sorry, seems v1.1 **does** have the same issues (but not on the same frames as v1.2, seeing the cut export on v1.2 VS v1.2 also doesn't have the same exact problems consistently I was probably being naive)..

**Comment by bouncyball-git** [comment]
OK, will check again :smile:

**Comment by gac123** [comment]
yea, i just drag and dropped the v1.1 export into the timeline on a frame where the error was from the v1.2 export and it was perfect so i ASS-U-ME-D v1.1 didn't have any problems, based on the previous testing we did ':-)

**Comment by bouncyball-git** [comment]
I guess those inconsistencies may be only because of open mp. Gotta check this by turning off, one by one, every loop pragmas.

**Comment by gac123** [comment]
did some more testing... seems the errors in frame are gone when exporting dng uncompressed!

though there a new problem cropped up.. first I tried exporting dng lossless but I get the error "Could not save: ...dng How do you like to proceed?"

exporting dng uncompressed went without a hitch

**Comment by bouncyball-git** [comment]
Hm... it is really strange b/c I can't see any direct connection between lossless export and dual iso inconsistencies.

Losless DNG has a quirch on some footage and i can not do anything about it (lj92 lib encoder issue). So your best bet always uncompressed.

However the issues you described have no connection to compression at all...

**Comment by gac123** [comment]
maybe it's handed off differently to the encoders VS cDNG ?

**Comment by bouncyball-git** [comment]
Nope. I wrote this so I'm sure it handed of the same way. Difference is: for lossless raw feed is going to compressor and for uncompressed just to bitpacker. Inconsistencies' happening way before those procedures.

**Comment by gac123** [comment]
oh no.. so after reexporting the whole thing again but this time in uncompressed cdng i've noticed here and there some highlights with "un-dual-iso-ed" artifacts so idd the problem is happening way before the hand off, it's just not so severe via cdng uncompressed

**Comment by bouncyball-git** [comment]
OK. I checked v1.1 vs v1.2 and now know what was my mistake. It does not mean this correct all of the issues v1.1 also had (e.g. some stripes in highlights), but there is some regression for some clips and it will be corrected.

**Comment by bouncyball-git** [comment]
@gac123: You can try the latest ver.

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-11-01 um 21 32 16](https://user-images.githubusercontent.com/30245296/47878084-b9f41880-de1d-11e8-87db-39dc3008a174.png)
@bouncyball-git : you still know this? It is back... :( (2nd last master commit used)

**Comment by gac123** [comment]
@bouncyball-git sorry, github is very confusing, where do I find the latest? on the releases page it still only shows v1.2

**Comment by masc4ii** [comment]
You tried to build with MSVC2017. This does not work. You need MinGW version.

**Comment by bouncyball-git** [comment]
> @bouncyball-git : you still know this? It is back... :( (2nd last master commit used)

Give me that MLV please.

**Comment by masc4ii** [comment]
> Give me that MLV please.

Okay, I'll upload this afternoon.

**Comment by gac123** [comment]
such a noob at this.. closed qt creator, i've downloaded and installed mingw (all basic components), deleted the pro.user file, restarted qt creator with mingw as default, reopend the mlvapp project, test run, build release/debug/profile, all end in errors, no idea what to do next, maybe the steps required to build this or any app from a clean machine requires maybe a few more than just 
-install Qt5 (minimum 5.6)
-unpack ffmpegWin.zip in platform/qt/FFmpeg (and copy it later into build directory)
-open platform/qt/MLVApp.pro in QtCreator
-go to tab project, add command line argument -j4 (for quad core)
-Build and Start

seemed so simple, i've trying different stuff and researching online for hours now.. ugh

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-11-02 um 10 30 43](https://user-images.githubusercontent.com/30245296/47906886-74216980-de8a-11e8-910c-fe2afc5648c6.png)
If you use Online installer, it should look like this (version don't cares if >5.6, but MinGW is important).

**Comment by gac123** [comment]
wish it were so easy... i first removed everything, reinstalled qt with only the option you show, open project, projects tab, build & run>desktop qt5.10.0 MinGW 32bit>Build(don't touch anything)>Run(only add the Command line arguments -j4)
then i go from the top menu Build>Build Project "MLVApp" -> stops at 54 errors

ugh²?

![image](https://user-images.githubusercontent.com/7746819/47908726-1ee75700-de8e-11e8-94d8-64ae19492f86.png)

**Comment by masc4ii** [comment]
These are warnings, no errors. Press green play button and have fun.

**Comment by gac123** [comment]
Oh, Build and Run! :) works and already test exporting a piece of the footage

I **do** already notice that blue line at the top in the preview window

**Comment by bouncyball-git** [comment]
This is interesting. Looks like dng header corrupted.

**Comment by gac123** [comment]
here is the file


[M28-0123_1_2018-10-28_0001_C0000_002409.zip](https://github.com/ilia3101/MLV-App/files/2543406/M28-0123_1_2018-10-28_0001_C0000_002409.zip)
(no dng allowed.. github)

**Comment by masc4ii** [comment]
Here is the MLV with the wrong highlights after dual iso processing:
https://www.dropbox.com/s/g3w0g93qilhqiyt/dualIso12Lossless.MLV?dl=0

**Comment by masc4ii** [comment]
If I remember right, in the past this was caused by some wrong limiting, if clip was recorded with less than 14bit... do you remember too?

**Comment by masc4ii** [comment]
@bouncyball-git : found it: https://www.magiclantern.fm/forum/index.php?topic=20025.msg203364#msg203364

**Comment by bouncyball-git** [comment]
The code you refer to is changed almost entirely. OK will check this file.

**Comment by bouncyball-git** [comment]
For me, without any change, if white level set to 5600, car light becomes _normal_, flare above remains violet and when highlight reconstruction is switched on green color kicks in. Can you try this?

**Comment by bouncyball-git** [comment]
This is the latest scale algo (it can not be go above 16200):

```
    int32_t scaled_white_level = 16200;
    double scale_ratio = (double)(scaled_white_level - raw_info->black_level) / (double)(raw_info->white_level - raw_info->black_level);
    raw_info->white_level = scaled_white_level;

#pragma omp parallel for
    for(uint32_t i = 0; i < pixel_count; ++i)
    {
        image_data[i] = (uint16_t)((double)((image_data[i] - raw_info->black_level) * scale_ratio + raw_info->black_level) + 0.5);
    }
```

And it even has minimal rounding error.

**Comment by masc4ii** [comment]
>...and when highlight reconstruction is switched on green color kicks in. Can you try this?

Yes, that is a known problem with my highlight reconstruction algo. It is threaded, but it shouldn't be. So for areas without highlight problem a false color is selected. I could make it slower, than in would work better.

**Comment by masc4ii** [comment]
Works wonderful for this clip!

**Comment by masc4ii** [comment]
I am not sure if it has something to do with this change, but last time I tested this clip it looked cleaner, now there is a lot of noise:
![dualiso_m18-1960_5d3_frame_1](https://user-images.githubusercontent.com/30245296/47988116-a1b42000-e0e1-11e8-8d26-527b4c626e99.png)

**Comment by bouncyball-git** [comment]
S..t :). That's why I commented this code out... gonna take a look again...

**Comment by bouncyball-git** [comment]
Well I not sure in anything any more ;) but please try it again.

**Comment by bouncyball-git** [comment]
@gac123

PLease try [latest](http://bouncyball.myweb.ge/mlvapp/?dir=&download=MLVApp.exe) win64 version.

**Comment by gac123** [comment]
sorry.. black frame still exist
[M28-0123_002378.zip](https://github.com/ilia3101/MLV-App/files/2548845/M28-0123_002378.zip)
though the preview is ok
![image](https://user-images.githubusercontent.com/7746819/48004689-fd969d00-e111-11e8-8e60-19a2ef01052d.png)

not consistent, if i scrub back and forth a few frames it might appear black as the output
this happens multiple times accross the video.. i'll export the test i did as mlv without raw corrections (fast mlv) on the mega drive M28-0123-2378-4205.MLV https://mega.nz/#F!V1IiEKqC!K-YCjrQ7LOKwdXX5fv17xQ (it's uploading 1,5gb ETA~15min)

and more inconsistencies.. the cut "untouched" clip has problems on different frames, etc..

**Comment by masc4ii** [comment]
> and when highlight reconstruction is switched on green color kicks in. 

Could you try now? Now one highest green is searched for the frame, not per thread. Should be better now...

**Comment by gac123** [comment]
like so? even more ff'ed up :)

![image](https://user-images.githubusercontent.com/7746819/48006129-6df2ed80-e115-11e8-8a11-0992b67e824c.png)

**Comment by gac123** [comment]
ok, so i'm uploading the original mlv that came out of the camera on the same mega drive under the folder M28-0123, it might take an hour

**Comment by masc4ii** [comment]
Hm... for some dual iso clips highlight reconstruction won't work for sure. With the current reconstruction strategy we can do there absolutely nothing to get it 100% working. Sry to say that. Dual ISO forbids to get it 100%.

**Comment by gac123** [comment]
oh, i understand things can't be perfect, but this is almost the entire thing.. almost 1,5h footage lol :)

**Comment by bouncyball-git** [comment]
I never get any color bar on the top. I think it can be windows only (+omp?) thing...

**Comment by gac123** [comment]
ive also had it in the export

**Comment by bouncyball-git** [comment]
BTW you had main iso set to 3200 and recovery iso to 800 (Dual iso 3200/800). I'm not sure if it's a correct  approach.

**Comment by bouncyball-git** [comment]
:) we'll see what else can be done.

**Comment by bouncyball-git** [comment]
Downloaded 1.5gb file. Reproduced very dark frames.

**Comment by gac123** [comment]
oh and the original 10,4gb straight out of camera mlv is done uploading..

yes, 3200/800, normally i shoot 1600 raw, which is the middle ground in what is unrecoverable shadows or hightlights, so for dual iso to be usefull i expanded it a bit

**Comment by masc4ii** [comment]
@gac123 : please test highlight reconstuction again. I tried finding a better method for getting the currect input value for our algorithm... maybe it works better for you too. Or... could you please upload just this frame you've shown above as MLV?

**Comment by gac123** [comment]
@masc4ii the frame is included in the 1.5gb file, it's the first frame :) in the original mlv (which is also uploaded.. it's frame 2378)

but here it is with the latest (non omp) version

![image](https://user-images.githubusercontent.com/7746819/48048378-97565c80-e19b-11e8-8dbb-6c1d92a72c45.png)

@bouncyball-git i scrubbed through the footage with the non omp version and idd, the line at the top is no more.. i'm going to export to uncompressed dng again to check

**Comment by gac123** [comment]
without "camera matrix" setting

![image](https://user-images.githubusercontent.com/7746819/48048512-0e8bf080-e19c-11e8-816f-9570e8147de0.png)

**Comment by gac123** [comment]
@bouncyball-git next show (this saturday) i'll try it the other way around 800/3200

**Comment by bouncyball-git** [comment]
> @bouncyball-git i scrubbed through the footage with the non omp version and idd, the line at the top is no more.. i'm going to export to uncompressed dng again to check

Very nice. Use [this latest build](http://bouncyball.myweb.ge/mlvapp/?dir=&download=MLVApp.exe) with @masc4ii's changes then.

**Comment by masc4ii** [comment]
> the frame is included in the 1.5gb file, it's the first frame :) in the original mlv (which is also uploaded.. it's frame 2378)

Okay... then it should be better now for you. I did not see any artifacts there any more with latest commit. Searching now some more clips, where latest commit still fails, to adapt my parameters...

**Comment by ilia3101** [comment]
Can lowering white level not just fix highlight reconstruction? It always works on normal ISO, is it somehow different on dual?

**Comment by bouncyball-git** [comment]
Yes it can :(

**Comment by gac123** [comment]
@bouncyball-git (your) non-omp version looking good!
now testing @masc4ii's latest build

**Comment by gac123** [comment]
i don't see the highlight reconstruction doing much, but at least no issues (will do a full test to confirm)

![image](https://user-images.githubusercontent.com/7746819/48052610-bdcec480-e1a8-11e8-91e8-c363b9cec702.png)

without reconstruction
![image](https://user-images.githubusercontent.com/7746819/48052621-cc1ce080-e1a8-11e8-8f82-73fe5338451f.png)

what does camera matrix do? (except seemingly boosting saturation)
![image](https://user-images.githubusercontent.com/7746819/48052652-dfc84700-e1a8-11e8-987b-dfeb590237fb.png)

+reconstruction
![image](https://user-images.githubusercontent.com/7746819/48052665-eb1b7280-e1a8-11e8-8bee-f5512458a127.png)

**Comment by masc4ii** [comment]
>Can lowering white level not just fix highlight reconstruction? It always works on normal ISO, is it somehow different on dual?

Nope. The information of highest_green gets lost on dual iso stitching, and is different in each frame. In the end it seems like there is a gaussian curve around a peak (which may be there, may be not, sometimes it is small, sometimes it is high). That is why I had to implement an algorithm, which trys to find this, if there is one. 
So I start from full 16bit (65535) and search all local maxima, until I get a maxima which is bigger than a limit. If the maxima become bigger than a smaller maxima I found green signal and there is no peak (->no clipped green).

>what does camera matrix do?

See it as a kind of calibrated color for the camera.

**Comment by bouncyball-git** [comment]
> what does camera matrix do? (except seemingly boosting saturation)

It is the future of MLV App ;)

**Comment by bouncyball-git** [comment]
Without OMP diso processing got 3 times slower :(. But I really do not have time to learn stuff like this now [LINK](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjH0sn6wb_eAhVBlosKHQ_EA3EQFjAAegQIBBAC&url=https%3A%2F%2Fmoodle.rrze.uni-erlangen.de%2Fmod%2Fresource%2Fview.php%3Fid%3D1921&usg=AOvVaw1N1xi_VOZ8-jl4V-Rc4h69)

**Comment by gac123** [comment]
hmm, i've tried 4 different settings (besides dual iso) nothing, then plus highlight recon, then plus cam matrix, then plus alexa log c
all 4 dng's uncompressed exports seem (are) exactly the same

the preview shows the difference of ticking/unticking those boxes but does not follow the export
[highlight recon settings not working in export¿.zip](https://github.com/ilia3101/MLV-App/files/2552613/highlight.recon.settings.not.working.in.export.zip)

also, there is still some problems, this time i notice the highlights on the metal rig of the drums, seemingly full red, green or other pixels
![image](https://user-images.githubusercontent.com/7746819/48057415-499a1e00-e1b4-11e8-9ee7-66a462a8e96e.png)

**Comment by gac123** [comment]
@bouncyball-git yes i've notice the whole thing is much slower, preview, export

**Comment by masc4ii** [comment]
> also, there is still some problems, this time i notice the highlights on the metal rig of the drums, seemingly full red, green or other pixels

Switch of bad pixel fix. Such highlights often are interpreted as bad pixels.

**Comment by gac123** [comment]
@masc4ii switching off making it worse :(

![image](https://user-images.githubusercontent.com/7746819/48057733-0f7d4c00-e1b5-11e8-84d1-68cefc015912.png)

**Comment by bouncyball-git** [comment]
Honestly, I would not use Dual Iso for such a kind of shot. Whole dynamic range have to be spent on stage . You really do not need to see people's backs right?

**Comment by gac123** [comment]
> Honestly, I would not use Dual Iso for such a kind of shot. Whole dynamic range have to be spent on stage . You really do not need to see people's backs right?

well, at a certain point in the show there is a moshpit, wall of death and sitting, so yes, seeing the crowd is actually a big part of those videos, i make these for the band, they can either use some footage for promotional stuff or as a kind of gage to see how the crowd reacts to the setlist

**Comment by gac123** [comment]
@masc4ii actually, the fix bad pixel option does take away quite a bit of highlights, even highlights on the faces, so not sure how this function works i would a bad pixel to be a red, green or blue pixel stuck at full brightness and alone

**Comment by masc4ii** [comment]
What this exactly does - I don't know as well. It is copied 1:1 from older/other ML projects, to not re-invent the wheel for each feature. But I know that it has problems on small areas with big contrast difference. So for example on water.

AMaZE + BadPixel
![bildschirmfoto 2018-11-06 um 11 46 42](https://user-images.githubusercontent.com/30245296/48059547-c2e83f80-e1b9-11e8-8df8-6ac0aec392d5.png)

AMaZE without BadPixel
![bildschirmfoto 2018-11-06 um 11 46 59](https://user-images.githubusercontent.com/30245296/48059565-d1cef200-e1b9-11e8-9f04-bf418403f499.png)

IGV without BadPixel
![bildschirmfoto 2018-11-06 um 11 47 12](https://user-images.githubusercontent.com/30245296/48059582-da272d00-e1b9-11e8-8a38-190d2b36256a.png)

**Comment by bouncyball-git** [comment]
Yup, right. Dad pixel searching code gets fooled by those very contrasty magenta-ish pixels and after interpolating around it often produces even more artifacts.

**Comment by bouncyball-git** [comment]
Hm... how good looks IGV in this case?!

**Comment by masc4ii** [comment]
IGV+BadPixels creates dark dots.
![bildschirmfoto 2018-11-06 um 12 06 13](https://user-images.githubusercontent.com/30245296/48060497-6d616200-e1bc-11e8-8926-730131627bce.png)

**Comment by masc4ii** [comment]
Yes... there are 2 possibilities:
a) use OpenMP from the beginning and develop with it -> works
b) don't use it forever -> works
------------
c) try to upgrade with OpenMP -> ...

**Comment by bouncyball-git** [comment]
@masc4ii 

Can you give me that 5D2 clip shown above for testing?

**Comment by masc4ii** [comment]
> Can you give me that 5D2 clip shown above for testing?

You mean my famous boot clip? But it is no dual iso... 
https://www.dropbox.com/s/igf6ao5cjs1u1m5/short_M23-1205.MLV?dl=0

**Comment by bouncyball-git** [comment]
@masc4ii: Yeah! Exactly your famous boat clip :) Thanks! I need to check water artifacts time to time.

@gac123: yes this can be done but I do not like the Idea because I'm getting random horizontal stripes in highlights and that's the OMP race case for sure.

**Comment by bouncyball-git** [comment]
@masc4ii: I think it is amplified 5D2 aliasing on the water. On 5D3 this kind of s..t appears not so often.

**Comment by bouncyball-git** [comment]
@gac123: [latest build with omp](http://bouncyball.myweb.ge/mlvapp/?dir=&download=MLVApp.exe)

**Comment by bouncyball-git** [comment]
> so far... no line in sight!!

And what about horizontal lines in highlights or black frames?

**Comment by gac123** [comment]
oh, and no black frames! :)

**Comment by gac123** [comment]
but still, all raw corrections besides bad pixel fix and diso on/off don't do anything at all in the exports..

**Comment by gac123** [comment]
ugh, it is pretty inconsistent, shot another video, this time 100/1600

![image](https://user-images.githubusercontent.com/7746819/48197742-f1e7e800-e356-11e8-9288-ac5b91be8874.png)

next frame:
![image](https://user-images.githubusercontent.com/7746819/48197766-0330f480-e357-11e8-92cd-a4d5f3dae5af.png)

ugh, i don't know what i'm doing wrong.... is anybody having success with dual iso footage?

**Comment by bouncyball-git** [comment]
And what about non opm build on this same footage?

**Comment by gac123** [comment]
previous build without omp
with bad pixel ON (purple highlights)
![image](https://user-images.githubusercontent.com/7746819/48208761-d3441a00-e373-11e8-93b0-8e988650404f.png)


OFF
![image](https://user-images.githubusercontent.com/7746819/48208812-ee168e80-e373-11e8-81fe-8a580e321d65.png)

EITHER way (with or without omp) raw color corrections is broken (why is nobody acknowledging this?)

**Comment by gac123** [comment]
yes, it's a different frame from my previous, but i kept the erroneous video, lined up with the new test ones and stopped at the frame with the visible purple horizontal stripes

**Comment by bouncyball-git** [comment]
Those horizontal stripes exactly ones I've been talking about in prev messages. Just use the non omp version. And try to not use dual iso in shots like above. It is useless here. You need so narrow DR in this shot that dual iso is a real overkill. To eliminate noise in shadows there are other sane technics supported by ML. Forum is your friend.
