### ISSUE TITLE
Export Selected Clips: remember last folder

### ISSUE THREAD

**Issue by gac123** [ilia3101/MLV-App#124]
It always defaults to where the source originates from.

Maybe have an option what the default behavior would be? Or just remember the path when the last time something was exported to?

We're working with sized files so I'm always exporting directly from the cf card to a subfolder of a subfolder of a folder on a different drive, always clicking through folders to get to the export folder again is a pain :)

**Comment by masc4ii** [comment]
Thanks for the reminder. Wanted to have remember the last export path since a long time. Done, see one of the latest commits.

**Comment by gac123** [comment]
awesome man!

especially with testing exports it gets annoying fast :)
