### ISSUE TITLE
Add methods/functions to manipulate llrawproc

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#13]
Atm there is only the init function in llrawproc, and the llrawproc struct in mlvObject. 
To realize changes from GUI to llrawproc the struct must be changed, what can easily result in problems (when doing it wrong). 
Better would be having methods or functions (which also filter unwanted input). 

When a parameter gets changed, the debayering must run again. (atm realized also by manipulation of mlvObject)

**Comment by bouncyball-git** [comment]
Correct. I'll think about it.

**Comment by ilia3101** [comment]
I wanna bring this up again, what do you think bouncyball?
This would make it much easier to implement in GUI, and would look cleaner in code.

**Comment by ilia3101** [comment]
We need this, these interface functions must also do `mark_mlv_uncached()` so that changes take place on cached frames - we definitely don't want to be callung that private function from GUI code.

**Comment by bouncyball-git** [comment]
Yeah, right. Hehe I'm so lazy when things are working and just polishing is needed ;). Give me the time.

**Comment by ilia3101** [comment]
That's alright ;) Fine if it takes a while, at least it works the way it is right now.

**Comment by masc4ii** [comment]
I think, this is fine now. Close.
