### ISSUE TITLE
Fix matrix issues

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#131]
The blue highlights with highlight reconstruction. Also bright red colours go yellow (when u film at bonfire night).

**Comment by ilia3101** [comment]
I tried a couple methods for fixing it nothing worked. Tried  converting to HSV, then applying reinhard to saturation, it seemed broken, maybe worth revisiting. Another method was finding intersection with RGB cube instead of MIN MAX for clipping the channels separately, also maybe worth revisiting.

Maybe we should release with matrix off by default?

**Comment by masc4ii** [comment]
We could do so... no problem.

**Comment by bouncyball-git** [comment]
I don't think this bluish issue gonna influence on users, despite if they want they could get back to the old processing. I would not turn off latest processing in the next release. The feedback from users can even help.

**Comment by masc4ii** [comment]
I played around with your test commits about fixing matrix issues. You tried to go a way with HSV conversion. Very interesting idea. 
When I limited the RGB range even more (e.g. 1..65534) the strange cyan effect became bigger than it was without. So... might be the problem that we limit and convert after the matrix multiplication to uint16 before applying gamma? Would it be better applying gamma without precalc matrix on the "result[...]" variable on double type, limiting to uint16 after? You know what I mean?

**Comment by bouncyball-git** [comment]
I'm really off from this research so I could be stupidly wrong. I wonder why we limit ourself by 16bit interger for RGB? Could we use uint32_t for internal processing instead? there will not be any worries to go out of this range and performance impact will be negligible.

**Comment by masc4ii** [comment]
Would be possible but makes no sense. We use uint16 matrices, which are precalculated. If we want to avoid that, we should goto float I think... but this would mostly mean starting at 0 with processing.

**Comment by bouncyball-git** [comment]
Yeah, precalculated matrices are good for speed, can't they be uint32?

**Comment by ilia3101** [comment]
Yeah uint16 is used because look up tables only need 0-65535 range. It would need to go up much higher with uint32, and only way to be 100% safe is to make it the full 0-4billion range. Also uint32 does not go negative and does not help with these ultra saturated colours.

> So... might be the problem that we limit and convert after the matrix multiplication to uint16 before applying gamma? Would it be better applying gamma without precalc matrix on the "result[...]" variable on double type, limiting to uint16 after? You know what I mean?

It could help a tiny but if we do tonemapping at that stage, but it won't help with the ultra saturated colours that much, as they have values going negative because they are out of rec709/srgb gamut.

I want to replace the matrix with something other than rec709, rec2020 seems like a good replacement for wider gamut internal processing - it will fix these ultra saturated colours mostly, but they will still need to be dealt with at the end of processing when converting to the output colour space.

**Comment by bouncyball-git** [comment]
You mean they go negative because of working color space now is rec709/sRGB? Hm...

I've read somewhere that linear color space is lot more simpler to handle with processing. That is why ACES' been chosen.

**Comment by bouncyball-git** [comment]
Anyway we do not have IDT for our cameras to convert it correctly to ACES.

**Comment by ilia3101** [comment]
> Does doing CAM SPACE(cam matrices)->XYZ->ACES makes any sense?

Makes perfect sense. I considered ACES, not 100% sure how it works with the white point being different from D65 like it is in most normal colour spaces... I have concerns like what if white stops being white when adding saturation etc, but ACES is definitely worth trying. I would prefer it as it's bigger.

> I've read somewhere that linear color space is lot more simpler to handle with processing. That is why ACES' been chosen (one of the main reasons).

When I said colour space space I meant gamut (just the triangle on the xy diagram), no gamma. We can use the rec2020 wide gamut but still linear. MLV App is linear in places where it needs to be (like exposure), and non linear for contrast and saturation as that looked better.

**Comment by ilia3101** [comment]
> You mean they go negative because of working color space now is rec709/sRGB? Hm...

What happens when colours are out of gamut.

**Comment by bouncyball-git** [comment]
> When  I said colour space space I meant gamut (just the triangle on the xy  diagram), no gamma. We can use the rec2020 wide gamut but still linear.  

Ah... yes of course, my bad.

> MLV App is linear in places where it needs to be (like exposure), and  non linear for contrast and saturation as that looked better.

Wow, I did not know it.

**Comment by bouncyball-git** [comment]
> What happens when colours are out of any gamut you are converting to (rec709 as example).

Yes that's why perceptual and relative colorimetric intents are for.
[Link](https://www.cambridgeincolour.com/tutorials/color-space-conversion.htm)

**Comment by ilia3101** [comment]
> Yes that's why perceptual and relative colorimetric intents are for.
> [Link](https://www.cambridgeincolour.com/tutorials/color-space-conversion.htm)

I've always found that 'perceptual' and 'colorimetric' intent stuff a bit offputting as I don't understand how it's actually done.

I'm also not certain how it should be used, but here's my current interpretation: the perceptual transformation should only be used once, at the end of processing when converting to a smaller colour gamut, so that the final image will have smooth colours, and any colour space transforms before that should be absolute to keep accuracy.

Is that correct?

I have not found a single piece of documentation that describes an algorithm to do a perceptual colour transformation, so it's really unclear to me how it works.

What I was doing with HSV saturation tonemapping though was a bit like a DIY perceptual conversion.

**Comment by bouncyball-git** [comment]
> the perceptual transformation should only be used once, at the end of processing when converting to a smaller colour gamut, so that the final image will have smooth colours, and any colour space transforms before that should be absolute to keep accuracy.
Is that correct?

Absolutly agree.
Once a while ago I've been digging into ArgyllCMS and dispcalGui. ArgyllCMS supports all those color intents fully.

**Comment by ilia3101** [comment]
> Once a while ago I've been digging into ArgyllCMS and dispcalGui. ArgyllCMS supports all those color intents fully.

mmm ArgyllCMS and dispcalGui

Have you been calibrating your display and dealing with colour management on Linux? How has it gone?

**Comment by bouncyball-git** [comment]
dispcalgui now called DisplayCal it works in linux/mac/windows and the best free calibraion software available. I've got this colorimether [link](https://www.amazon.com/gp/product/B0055MBQOW/ref=oh_aui_search_detailpage?ie=UTF8&psc=1). It is nice one, not the spectrometer though :) spectros cost 2-3 times more.

**Comment by masc4ii** [comment]
Will be fixed in #158 .
