### ISSUE TITLE
Resize ffmpeg allow filter choice

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#132]
I don't know what the current one is but I'd like to be able to choose sinc cubic linear etc. I find when I upscale a small amount with editing software it reduces the detail a lot, so I'd like to do it with sinc filter out of MLV app.

I didn't check that the default filter in mlv app and haven't compared yet but I think it should be an option as sometimes different upscale methods are useful.

**Comment by masc4ii** [comment]
Do you have some information how to do that? (example commands) Now our command is this:
`... -vf scale=w=1920:h=1080 ...` for 1920x1080

**Comment by ilia3101** [comment]
I was going to try and do this earlier, but qt code is still something I don't understand. But the way to set scaling method it seems is this:
```
-sws_flags scaling_filter
```
where scaling filter names are listed here: https://ffmpeg.org/ffmpeg-scaler.html

**Comment by masc4ii** [comment]
Thanks, I'll have a look at this. 
I think what you don't understand is not Qt, it is my puzzle game attaching all snippets of the ffmpeg command together...
From Qt side, there is only `QString( "..." )`, `QString( "...%1..." ).arg( variable )` and `string.append( "..." )`. I think you understand this :)

**Comment by masc4ii** [comment]
Please test latest commit. sws_flags=sinc is no the only standard. To make it switchable: what options else from the list do you like to be supported?

**Comment by ilia3101** [comment]
thank you!!!

**Comment by ilia3101** [comment]
@masc4ii 2880x1080 clips look beautiful upscaled to 3840x1440 with sinc! A big improvement over previous scaling.

I think lanczos should be an option too, I think its good for scaling.

**Comment by bouncyball-git** [comment]
Yes lanczos is really good.

**Comment by masc4ii** [comment]
Can we close, or do we need something more?
