### ISSUE TITLE
Small issue of Copy/Paste Receipt from/to different bit depth uncompressed clips

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#133]
@masc4ii 

I've noticed this behavior to day: [link](http://bouncyball.myweb.ge/mlvapp/?dir=&download=copy_paste_receipt-2018-11-16_13.02.11.mp4)

It's not a problem at all if you uncheck black and white levels in the receipt mask, but may be you can come up with more elegant solution to avoid this blak/white screen and consequential explanation to the user what happened :)

**Comment by masc4ii** [comment]
Yes, I know this. But in the end, this is as it should be. This is the main reason why I added the checkboxes in the copy mask.
What would you do? Calculate corresponding levels in relation to bit depth? But this works only, if you use the same camera in the session... else you also have to uncheck it in the mask.

**Comment by bouncyball-git** [comment]
No I would save bit depth in receipt then before paste compare it to current clips bit depth do not change black and white values despite they are were checked in copy mas dialog.

**Comment by masc4ii** [comment]
Ah okay... hm... no bad idea.

**Comment by bouncyball-git** [comment]
Cool works as expected!

**Comment by masc4ii** [comment]
I saved the state in the mask dialog to not spam the receipt... here would be the problem that we have to handle all steps which have to do with receipts and export... no fun :)

**Comment by bouncyball-git** [comment]
A... I'm not quite sure I understand what you said in prev message...

**Comment by masc4ii** [comment]
The bitdepth from the source is saved in Mask dialog now. I don't want to spam the receipt. Because if we would do so, export, receipt import/export, etc. has to handle that - and I don't like to change it there... ;)

**Comment by bouncyball-git** [comment]
Ah ok understood. 

Yes it is just temporary variable for runtime period and should be only changed when copy receipt is called. Export/Import of that bit depth is pointless. No matter where it'll be saved until current receipt status is valid.

**Comment by masc4ii** [comment]
https://github.com/ilia3101/MLV-App/commit/fb23d0a40283c0a1eeaf8cdca3ccc33686db4114
Again changed.

**Comment by bouncyball-git** [comment]
Yeah... that's good :). Let the user think a bit.

**Comment by masc4ii** [comment]
Good idea. Haha. Close?

**Comment by bouncyball-git** [comment]
Yup
