### ISSUE TITLE
1.2x AR stretching

### ISSUE THREAD

**Issue by kononega** [ilia3101/MLV-App#135]
Option for 1.2x AR stretching of native 1600x900 mlv to 1920x1080.

Edit: I haven't coded since MySpace was the thing but is:

#define STRETCH_H_120 1.2
#define STRETCH_V_120 1.2

...all that needs to be added to platform/qt/StretchFactors.h in order for 1.2x to work? I see:

double getHorizontalStretchFactor();
    double getVerticalStretchFactor();

...in MainWindow.h but think I'm missing something in the middle that I'm overlooking because the menu has an "x" behind the stretch factor.

What's the difference between stretch factor and resize (on export)?

Many kudos for this app!!!

**Comment by ilia3101** [comment]
Why not just resize on export?

The stretch factor presets are mostly for anamorphic lenses and slow motion where the image is stretched either vertically or horizontally. And your question is not aspect ratio related, as 1600x900 has the same aspect ratio as 1920x1080.

Resize and stretch factor are both done during export at the same time.

**Comment by bouncyball-git** [comment]
Stretching factors in mlvapp used for displaying frame with correct aspect ration when image for some reason has skewed pixel ratio (Note: not resolution ratio!). 

Examles: if anamorphic lens has used (horizontal stretch needed), or if 50/60 high frame rate MLV recorded, or crop_rec settings used with not NxN (1x3, 2x3, 3x1) bining/skipping (vertical stretch needed)

So it is for just displaying not resizing the final image. Resizing is done during export and specified in export dialog.

**Comment by ilia3101** [comment]
Ah so I was wrong, aspect is only for preview

**Comment by bouncyball-git** [comment]
@ilia3101: anyway what you've said in your message is truth and IS correct.

I just wanted to explain to @kononega why wrong 1.2x stretch factor not needed.

BTW: both 1600x900 and 1920x1080 (as @ilia3101 stated) are 16x9 ratio and do not need any stretching, just upscaling.

**Comment by masc4ii** [comment]
Stretching != Resizing. 
Stretching is for changing aspect ratio.
Resizing is for changing resolution.
All is implemented in MLVApp since many versions.

**Comment by kononega** [comment]
Thanks, your follow up answered my ultimate question - they're both done on export.
