### ISSUE TITLE
Add HSL elements

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#137]
In Lightroom there are these HSL sliders. I tried to create something, what is able to do the same, but what is easier to use. Here the example for Hue vs. Luma, I also got it drawn for Hue vs. Saturation:
![bildschirmfoto 2018-12-03 um 20 01 16](https://user-images.githubusercontent.com/30245296/49395319-6d5e6e80-f736-11e8-8f8a-9c23c85e912b.png)

I tried to implement also the processing functions (as prototype). But here I got problems. I found RGB2HSL and HSL2RGB here (and changed it to 16bit RGB):
https://www.programmingalgorithms.com/algorithm/hsl-to-rgb?lang=C%2B%2B
https://www.programmingalgorithms.com/algorithm/rgb-to-hsl
The conversion works so far - that means, converting and converting back brings the same picture like without conversion. But if I try to select some pixels by Hue value and change their Luma or Saturation strange things happen. 

Testcode for lowering the luma by 20% between red and yellow:
```
for (uint16_t * pix = img; pix < img_end; pix += 3)
    {
        float hsv[3];
        rgb_to_hsl( pix, hsv );

        if( hsv[0] > 0 && hsv[0] < 60 )
        {
            hsv[2] *= 0.8;
        }

        hsl_to_rgb( hsv, pix );
    }
```

![m23-1205_frame_1](https://user-images.githubusercontent.com/30245296/49397136-0ee7bf00-f73b-11e8-8461-682b9fecc67a.png)

Or lower luma from cyan to violett by 20%:
```
for (uint16_t * pix = img; pix < img_end; pix += 3)
    {
        float hsv[3];
        rgb_to_hsl( pix, hsv );

        if( hsv[0] > 180 && hsv[0] < 285 )
        {
            hsv[2] *= 0.8;
        }

        hsl_to_rgb( hsv, pix );
    }
```

![m23-1205_frame_1](https://user-images.githubusercontent.com/30245296/49397708-a863a080-f73c-11e8-8f62-7e3b6670fff2.png)

In both pics, see the mountains... 
I'll need some help here! :-) 
Someone likes to help?

**Edit:**
Doing some smoother functions (a triangle, before it was just a square) and it looks better. But is it good to multiply something onto the luma? See all the artifacts everywhere in the sky and on the buildings:

```
for (uint16_t * pix = img; pix < img_end; pix += 3)
    {
        float hsv[3];
        rgb_to_hsl( pix, hsv );

        if( hsv[0] > 180 && hsv[0] < 240 )
        {
            hsv[2] *= 0.8 + ( 0.2 * (fabs(210-hsv[0])/30.0) );
        }

        hsl_to_rgb( hsv, pix );
    }
```

![m24-1153_frame_1](https://user-images.githubusercontent.com/30245296/49399329-4d807800-f741-11e8-8c1e-3e13aaf16575.png)

**Comment by bouncyball-git** [comment]
Oh, ugly artifacts indeed.

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-12-05 um 22 46 40](https://user-images.githubusercontent.com/30245296/49546078-b56cc500-f8df-11e8-9dc3-b4b8362cf4de.png)

Cosine interpolation... in da house!

**Comment by bouncyball-git** [comment]
Does it work? Wanna try :P

**Comment by masc4ii** [comment]
It is just GUI only for now. I'm gonna keep tinkering tonight.

**Comment by bouncyball-git** [comment]
BTW that cosine interpolation can be useful for gradation curves?

**Comment by masc4ii** [comment]
Not really. Gradation curve needs cubic interpolation (mathematical derivation != 0 in each point) and for HSL curves mathematical derivation needs to be 0 in each point, and lines in between have to be independant. That's the reason for 2 different interpolation methods.

**Comment by bouncyball-git** [comment]
Thanks for info :)

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-12-06 um 21 53 40](https://user-images.githubusercontent.com/30245296/49611580-40ae8f00-f9a2-11e8-81b7-268c704efe44.png)

Now you can test. It is not ready yet. See commit for some more comments...

**Comment by bouncyball-git** [comment]
Artifacts are very ugly, all over he image ugly dots dots dots :o:

**Comment by masc4ii** [comment]
I only get dots on moiree artifacts. No idea how to filter them. In past I had exactly the same with the vibrance slider but got it fixed (there was a wrong condition in "current saturation" (before applying) calculation). Here there is different code... have to look into that. Maybe these rgb2hsl and hsl2rgb functions are not correct.

**Comment by bouncyball-git** [comment]
Well, I have to correct myself. It gets more ugly with noisier images.
![sidecar_frame_1](https://user-images.githubusercontent.com/17232233/49645024-d6462f00-fa33-11e8-9734-d96939b74e66.png)
![sidecar_frame_2](https://user-images.githubusercontent.com/17232233/49645026-d80ff280-fa33-11e8-9695-982fd4f63095.png)
Other than that with good image it does the job.

**Comment by masc4ii** [comment]
Japp, right. In the end it is very similar as the old vibrance problem. In the first version where this was included, it looked the same.

**Comment by bouncyball-git** [comment]
We could try to make thing like this:

When staying over created point on a Hue vs Luma curve rotate mouse wheel or click and hold right mouse button and then drag the mouse pointer. This will change 3rd dimension which can be Saturation. This means we could have 3d curve Hue vs Lightness vs Saturation. Interpolate this points for example with 3D Hermite Interpolation:

```
/*
   Tension: 1 is high, 0 normal, -1 is low
   Bias: 0 is even,
         positive is towards first segment,
         negative towards the other
*/
double HermiteInterpolate(
   double y0,double y1,
   double y2,double y3,
   double mu,
   double tension,
   double bias)
{
   double m0,m1,mu2,mu3;
   double a0,a1,a2,a3;

	mu2 = mu * mu;
	mu3 = mu2 * mu;
   m0  = (y1-y0)*(1+bias)*(1-tension)/2;
   m0 += (y2-y1)*(1-bias)*(1-tension)/2;
   m1  = (y2-y1)*(1+bias)*(1-tension)/2;
   m1 += (y3-y2)*(1-bias)*(1-tension)/2;
   a0 =  2*mu3 - 3*mu2 + 1;
   a1 =    mu3 - 2*mu2 + mu;
   a2 =    mu3 -   mu2;
   a3 = -2*mu3 + 3*mu2;

   return(a0*y1+a1*m0+a2*m1+a3*y2);
}
```

**Comment by masc4ii** [comment]
I planned to edit hue and saturation with further diagrams. HueVsSaturation is done now. And HueVsLuma works better now too (at least for my testclips). Try out.

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-12-07 um 17 00 13](https://user-images.githubusercontent.com/30245296/49658135-98e89e00-fa41-11e8-8ee2-ce6fbd546c00.png)

**Comment by masc4ii** [comment]
Adobe seems to have the same problems and uses a blur on the edited areas (see the sky):
![bildschirmfoto 2018-12-07 um 17 15 56](https://user-images.githubusercontent.com/30245296/49659163-e0702980-fa43-11e8-8f93-1784e2a0ed0a.png)

**Comment by bouncyball-git** [comment]
H vs S Works great!
![m04-1040_frame_320](https://user-images.githubusercontent.com/17232233/49660557-4ff41200-fa60-11e8-90c5-690d39bad89e.png)

**Comment by bouncyball-git** [comment]
Did you also blur H vs L processed areas? I looks lot more better.

**Comment by masc4ii** [comment]
No, I tried some different math... I now multiply instead of add/subtract, so it works in relation what was before -> artifacts are not amplified.

**Comment by bouncyball-git** [comment]
Do not get the meaning of "in relation what was before", but it really helps a lot :)

**Comment by masc4ii** [comment]
Hue vs. Hue working... yeay.
![bildschirmfoto 2018-12-07 um 19 57 05](https://user-images.githubusercontent.com/30245296/49667149-7b73fe00-fa5a-11e8-9a2b-102c68f2df21.png)
Now doing this into receipt...

**Comment by masc4ii** [comment]
Btw: should we create a new tab "HSL" for these 3 curves, or is it okay in Processing tab?

**Comment by masc4ii** [comment]
Now we have full receipt support for HSL curves.

**Comment by bouncyball-git** [comment]
I think it deserves separate section. It is more on color correction side.

**Comment by bouncyball-git** [comment]
Overall... GREAT job MAN! 😁

**Comment by masc4ii** [comment]
So I'll add a new Groupbox for it. In Processing tab there are too many elements now, I think too.

**Comment by masc4ii** [comment]
> When mouse leaves area accidentally the point deleted and annoying behavior happens.
> 
> I just wanna ask you to disable deleting point when mouse leaves the working area in all 3 editors. Just do nothing and leave the dragged point at the edge of the area where mouse crossed the border. I think it will be more comfortable.

Done.

**Comment by bouncyball-git** [comment]
Cool! Thanks! I'm out of reach of any PC now... will check it tomorrow at work.

**Comment by bouncyball-git** [comment]
It just fu..n works! Thanks!
