### ISSUE TITLE
CPU Multy Core scaling

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#138]
Hey guys right now I'm installing new servers for oracle databases in our 2 data centers, so before run them into production I decided to give a try for MLV App on the most powerful one - 4xCPU Xeon system with 80 physical cores and 160 threads, 768GB RAM :grin: 

Here is the [video](http://bouncyball.myweb.ge/mlvapp/?dir=&download=160thread_test-2018-12-07_19.33.57.mp4) I've recorded so far.

I was surprisingly disappointed with the result (playback/exporting cpu scaling). Exporting do add some more work on to CPUs but not much to be satisfied. About 10% average load :-1: 

Of course dual iso w/o OpenMP was the disaster too. One poor core is 100% loaded and other 159 do almost nothing hahaha.

So what do you think guys what can we do about it?

**Comment by masc4ii** [comment]
Haha... strange... 160 threads and same speed as my old Core2Duo from 2010... 
Could you test an older version, where we have AMaZE cached debayer running? Should be faster. Processing is running 100% multithreaded. So I won't understand if it is slower than on our cheep and old systems.

**Comment by bouncyball-git** [comment]
Yeah!!! Despite the resolution of this video is 2880x1226 the result is depressing ;)

As you see denoiser and sharpen add some stress to CPUs.

**Comment by bouncyball-git** [comment]
Could I blame appimage for that? Should I compile mlvapp from scratch in redhat (oracle linux actually)?

**Comment by masc4ii** [comment]
No idea, if appimage makes a difference there...

**Comment by bouncyball-git** [comment]
I have to qDebug print:

int cores = QThread::idealThreadCount();
