### ISSUE TITLE
Close mlv app: "Save session?", Accidentally click new session: Instantly deleted

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#139]
Slightly annoying. Also happens constantly on linux because it is right next to file menu.

Unless this has been changed since 1.3?

Also why not release 1.4 soon?

**Comment by masc4ii** [comment]
Oh, right, here comes no messagebox. But that's not hard to implement. Thx.

1.4 can be released then... if you all like ;)

**Comment by masc4ii** [comment]
Please try out latest commit.

**Comment by ilia3101** [comment]
Thank you @masc4ii
