### ISSUE TITLE
Unable to Render Dual Iso Video

### ISSUE THREAD

**Issue by youshouldtry11** [ilia3101/MLV-App#141]
v1.2
Can't make dual iso videos despite turning on dual iso to every possible option.
It still flashes from the two alternating iso...
Thanks

SETUP:
CANON EOS M

**Comment by masc4ii** [comment]
Please try latest version (v1.4) and report back.

**Comment by youshouldtry11** [comment]
on v1.4:
I can only choose the option first before toggling the on/off/preview functions,
after pressing force it still flashes,
after pressing on the footage becomes a very distorted black and green almost matrix like glitchy thing.

P.S. I tried to export it but it it flashes and has crazy green and purple

**Comment by masc4ii** [comment]
Please upload the clip. We have to analyze it.

**Comment by youshouldtry11** [comment]
> I bet you are using HDR not dual iso mode.
you are 100% correct! problem solved
