### ISSUE TITLE
Seems we have fixed every issue in the world except the 20 still left?!?!

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#142]
As there hasn't been a new one since 7 Dec 🤪

**Comment by masc4ii** [comment]
Found another implementation. The interfaces of this one are not very different to ours... just a little.
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/demosaic_algos.cc
See function lmmse_interpolate_omp. It also has omp, so we could simplify our thread code - or we comment our omp and use our code... we would be free. It just has to be done. 😄
