### ISSUE TITLE
Release Discussion v1.5

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#143]
Hi guys,
I started writing down the new features since 1.4 in release section. Are we ready for another version, or are the new things not enough?! Do you still have plans? 
I was hoping to solve the LMMSE dots problem, but I only became crazy with it (same for you Ilia?!)... so:
- let it with dots?
or
- revert to version with cyan edges?

**Comment by ilia3101** [comment]
I think we should revert to cyan edges for LMSSE, the dots are not very usable for real footage. Though I hope no one uses LMSSE too much until this is fixed.

> same for you Ilia?!

Yep, went in to it thinking "Oh I'm sure I'll find a small change to make in about 5 minutes"...  spent like an hour being amazed about how nothing changes.

**Comment by masc4ii** [comment]
Thanks. I think the same. Reverted.

**Comment by bouncyball-git** [comment]
Cool for 1.5 :)

**Comment by masc4ii** [comment]
Commit is there, OSX version is uploaded. @bouncyball-git : do you find some time for the windows versions? Tomorrow I'll add Linux.

**Comment by masc4ii** [comment]
Thanks! And... BAM! 😄
