### ISSUE TITLE
Importing receipt only applies to one clip, not all selected

### ISSUE THREAD

**Issue by polymetric1** [ilia3101/MLV-App#147]
If I import a receipt, it doesn't apply to all the clips I have selected, only the one that's currently in the viewport. It's not a huge inconvenience, just a minor one, since I can still copy the receipt and paste it. Pasting does apply to all selected clips. I'd like to see this behavior in importing receipts as well, so I can just quickly load up a bunch of clips, apply a preset receipt, and be done.

**Comment by masc4ii** [comment]
Now receipt is imported to all selected clips and into clipboard. Additionally you can select which parameters of the receipt shall be imported.

**Comment by masc4ii** [comment]
Feel free to reopen, if you are not satisfied. Close for now.

**Comment by polymetric1** [comment]
Sounds good.
