### ISSUE TITLE
Unclear as to what color space (gamut) is being output

### ISSUE THREAD

**Issue by polymetric1** [ilia3101/MLV-App#148]
So I understand you can select a gamma curve in the processing menu. This does not have any effect on the color gamut.

What _does_ appear to have an effect on gamut is the "Use Camera Matrix" checkbox, which when unchecked, outputs a wider gamut than when checked. However, I can't tell what either of these gamuts are, because the program doesn't say.

I'm wondering if anyone could provide more information on this, as well as suggesting this be made more clear in the interface. Thanks!

**Comment by ilia3101** [comment]
I'll explain, MLV App is still not doing this stuff right. This is what the ACES processing branch will solve when I actually finish it. I also plan to separate output colour space and processing profile in to two separate options - this is actually very difficult to dowith the 16 bit integer processing while avoiding clipping but I have some ideas.

But the current state is:

All profiles use the same gamut, which is sRGB by default. The log profiles are nothing more than a curve right now.

And if camera matrix is disabled, the gamut is literally what comes off the sensor (RAW channels).

**Comment by polymetric1** [comment]
Alright, thanks for the response!

**Comment by masc4ii** [comment]
>    * All profiles use the same gamut, which is sRGB by default. The log profiles are nothing more than a curve right now.

Okay... but all software I tested made the same. Is there another possiblity?!

**Comment by ilia3101** [comment]
That software is wrong then, all log colour spaces I know have a specific gamut/ matrix, though it can be challenging to find that info online. Once that is done, technically the arri log profile will create an identical look to an alexa, but who knows 😂

I also remember andy600 once saying how a lot of software does this wrong.
