### ISSUE TITLE
QtApp: cut-in & cut-out

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#15]
Functionality for cut-in and cut-out could be added.

**Comment by bouncyball-git** [comment]
'Could' is the wrong word - 'Should' is the correct one :D

**Comment by masc4ii** [comment]
I worked on this old enhancement issue now. What is working now:
- set cut in & out via button in dependency to the position slider
- set cut in & out as number
- cut out can't be before cut in
- delete buttons for cut in & out
- receipt support
- file open & save support
- save variables to export queue
- playback stops at cut out
- loop jumps to cut in
- "goto first frame" 1st click: position = cut in; 2nd click = 1st frame

![pic](https://image.ibb.co/eSy4f6/Bildschirmfoto_2017_11_24_um_22_03_04.png)

What has to be done:
-> Cut export. For the video frames this should be no problem. But for audio this is a bit more difficult, at least for me..., cut out is no problem, but I don't know the syntax for a cut in. I get only crashes. Could someone please assist here?

**Comment by bouncyball-git** [comment]
Theoretically cutting the beginning is as simple as cutting the end. Where exactly are you stuck?

**Comment by masc4ii** [comment]
My problem was to cut the beginning in audio_mlv.c line 132. The end works simply with the 2nd parameter. For the first I wanted to increment the starting address, but I got only crashes.

**Comment by masc4ii** [comment]
This function also needs 2 parameters then - in and out frame.

**Comment by masc4ii** [comment]
Video export is cut now too. :-)

**Comment by bouncyball-git** [comment]
Clip loops from cut in to cut out when looping enabled. Is that intended behavior?

**Comment by masc4ii** [comment]
Yes it is. And it was not that easy as it looks ;-)

**Comment by masc4ii** [comment]
Okay. I got it. Feature complete for cutIn cutOut.
@ilia3101 : I made a new audio write wave function for compatibility reasons to your code. If you like you could easily adapt to the parameters of the new function: cut_in = 1, cut_out = getMlvFrames(video). Then we could delete the old one (and name the new again as the old function).
@all: please test, I expect some bugs. The change was more work as expected...

**Comment by masc4ii** [comment]
@ilia3101 : now I think you mustn't change it anymore. I made a function which generates the audio header, so the write wave functions are way smaller. So we can have both version in the code...

**Comment by seescho** [comment]
Works fine here for cutting video (have no audio, so I cannot tell anything about audio).
Thanks for implementing.

**Comment by bouncyball-git** [comment]
Great job! :)

**Comment by masc4ii** [comment]
Thank you. So we can close, when it works for you?

**Comment by bouncyball-git** [comment]
I corrected buffer pointer + in_offset issue. Now everything is right and synced.

**Comment by masc4ii** [comment]
Cool, thank you. So this was not working on Linux? Haven't had a problem on Mac... but now it is save... :-)

**Comment by bouncyball-git** [comment]
I can't believe this was not a problem on mac really ;). It should be a problem anywhere! 

fwrite been starting saving the data from buffer 'pointer + **cut_in * 2bytes**'!

If it is the case I'm happy that I'm not developing on a Mac! :P, I don't even understand what mechanism corrects this on the mac!

**Comment by bouncyball-git** [comment]
btw you wrote this some while ago:

> My problem was to cut the beginning in audio_mlv.c line 132. The end works simply with the 2nd parameter. **For the first I wanted to increment the starting address, but I got only crashes**.

How did you solve this problem? I can't find the related commit.

**Comment by masc4ii** [comment]
I solved it as you can see. Before the syntax was completely wrong :-D

**Comment by bouncyball-git** [comment]
ok, never mind :)

I'm just so curious how compiler? or anything corrects incorrect memory access for mac. As you remember this is not the first time I'm correcting things like this to work on Linux. Freeing NULL pointer buffers and so on... it is just very strange and unacceptable to me :).
