### ISSUE TITLE
Ready for v1.6?

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#153]
Same question as usual: are you fine for v1.6? Do you still have something planned, do you have found bugs, etc.? 
I'll add latest additions into app's help and then I am ready from my side. A release draft is created, if you like to read...

**Comment by dannephoto** [comment]
Yes, go for it. 
Not specifically bug tested but seems running nicely so far. Got a gig tonight and will use mlv app for post correction. Will let you know how it goes.

**Comment by bouncyball-git** [comment]
Yup!!! :) Hey guys I'm sorry about being so busy these days.

**Comment by ilia3101** [comment]
Ready! Nothing to add yet

**Comment by dannephoto** [comment]
Looking good. Running nicely here. Mapp files used for the first time. Really good to have. 
Occasionally it crashes but hey. So do photoshop from time to time. IfI can norrow something down I let you know.

**Comment by masc4ii** [comment]
Please let me now how you get it to crashes! Thanks.

**Comment by bouncyball-git** [comment]
@dannephoto: Yes please! :) How to reproduce.

**Comment by dannephoto** [comment]
Random. Last I was exporting a bunch of takes but before last file was exported the whole gui vanished. No error message.
Will see if I can repeat the issue somehow.

**Comment by masc4ii** [comment]
If MLVApp crashes on OSX, OSX brings a Diagnosis Dialog. There is a detailed description inside, which function crashed, and from what function it was called, etc. . If it happens again, please copy this text for us! ;)

**Comment by dannephoto** [comment]
Cool. Where is the dialog placed?

**Comment by masc4ii** [comment]
In the middle of your screen, right after the crash.
![Bildschirmfoto 2019-03-14 um 12 39 19](https://user-images.githubusercontent.com/30245296/54354176-488f6680-4656-11e9-9026-6f4a3d855e74.png)
Details:
![Bildschirmfoto 2019-03-14 um 12 39 34](https://user-images.githubusercontent.com/30245296/54354187-4c22ed80-4656-11e9-8ad3-a415aaa845fd.png)
Scroll down:
![Bildschirmfoto 2019-03-14 um 12 40 18](https://user-images.githubusercontent.com/30245296/54354218-5a710980-4656-11e9-9b00-3281175bbeb5.png)

**Comment by masc4ii** [comment]
Some days after I started this discussion, I found some nice code for biliteral filtering (in some way a denoiser). I included it to the project and it works better than all we had before in terms of noise reduction, but has some problems on the right edge. I have no idea how to fix that. 
I found some code which should have corrected this problem, but it is written for VisualC++. I tried to translate back to universal standard C++, but I get only crashes. Someone else like to try? Or do we just release for now?
https://github.com/Fig1024/OP_RBF
_(See RBFilterPlain.cpp/h)_

**Comment by masc4ii** [comment]
Code corrected and fine tuned. See latest commit. 
If someone knows how SSE2 works, we could accelerate the code a lot. A code base is there, but all for 4x8bit.

**Comment by dannephoto** [comment]
Cool! Busy here, hopefully find time soon..

**Comment by masc4ii** [comment]
v1.6 commited. @bouncyball-git : could you build windows version please? OSX & Linux is on the way... 😎

**Comment by bouncyball-git** [comment]
Sure, sorry for so late answer... (s..t)

**Comment by bouncyball-git** [comment]
Done 😁

**Comment by masc4ii** [comment]
Thank you so much!
