### ISSUE TITLE
Could we make the super amazing new denoising operate on colour channels only?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#155]
Good job @masc4ii on the denoiser! I haven't used it yet, but some of the samples look very good. Could an option be added to make it affect only the Cb and Cr channels? (if chroma separation is enabled) It would provide high quality colour denoising... right now using my chroma blur looks soooo bad that I never use it.

**Comment by ilia3101** [comment]
Never mind it can already do this!!!!!!!!!!!! Duck

**Comment by masc4ii** [comment]
Bouncyball had the idea to have 2 range sliders: one for luma and one for chroma. For next version maybe?!
