### ISSUE TITLE
Create a proper Discussion platform 

### ISSUE THREAD

**Issue by XLAR-8** [ilia3101/MLV-App#159]
Create a proper Discussion platform to share ideas and have discussion over already implemented things .

**Comment by masc4ii** [comment]
>Discussion platform

--> Thread in ML forum
--> Issue page

>discussion over already implemented things

--> Manual & Wiki (->how to)
--> Startpage (-> feature list)
--> Thread in ML forum (->for questions)
--> Issue page (->if help needed)

**Comment by bouncyball-git** [comment]
Think it was a bot :)

**Comment by XLAR-8** [comment]
ok thanks, will check there. :)

**Comment by masc4ii** [comment]
Wiki, Issus Page and Features list is on this site.
ML forum: https://www.magiclantern.fm/forum/index.php?topic=20025
