### ISSUE TITLE
For better historical preservation

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#160]
Could we add a string to MASXML saying which version of MLV App saved it? So that when I look at my old MLV and MASXML files in 100 years time, and compatibility has been broken, I can look at the file's text and know which old MLV App version I should download to open it.

Just something like "Saved with MLV App 1.7" or `mlvapp="1.7"` in mlvfiles tag. Whatever you think is best @masc4ii

**Comment by masc4ii** [comment]
We haven't exactly this, but something very close. Each file starts with:

```
<?xml version="1.0" encoding="UTF-8"?>
<mlv_files version="2">
```

Version="2" is for compatibilty. But I can add mlvapp version if you like.

**Comment by masc4ii** [comment]
Done: https://github.com/ilia3101/MLV-App/commit/602127ec5b46e3878c257880169afe579a62f319

**Comment by masc4ii** [comment]
Files start like this now:
```
<?xml version="1.0" encoding="UTF-8"?>
<mlv_files version="2" mlvapp="1.6">
...
```

**Comment by ilia3101** [comment]
Thanks, I know masxml version is there, but in 100 years I probably wouldn't remember what it means 🙃
