### ISSUE TITLE
Frame number does not match exported image number

### ISSUE THREAD

**Issue by bverkron** [ilia3101/MLV-App#161]
The frame number show in the MLV interface does not match the file suffix number when exporting DNG files.  The frame numbers are 1 based but the filename suffixes are 0 based.  This makes it tricky to match things up exactly when pulling the image files into an LNE.

Now that I know about the mismatch I can work around it but it would be nice if the file name suffix represented the frame number instead of being a zero based sequence. Maybe an added option in the export settings?

**Comment by masc4ii** [comment]
It depends on feature... :
Timecode: 0 based - this is a standard
Framenumber: 1 based - some people won't understand if I write 50/99 if a clip has 100 frames
DNG filename: 0 based - should be the standard

**Comment by bverkron** [comment]
Definitely could be confusing. That's why I was thinking some kind of drop down or other config option in the settings with some added instructions in the manual. Maybe a checkbox for "match file number to frame number" or something?

One example of where frame number is important to me is when I have exported a proxy of the whole clip for rough editing and then want to go back to the exported DNGs and grab or edit just the necessary frames.

If I have the entire clip already exported as DNGs then the file number is only off by 1 so it isn't so bad but if I have a subset of the original clip in DNG form then the numbers are off by a different mount which makes it more challenging to grab the correct frames without skimming the DNGs to find the right frames.

Arguably I could re-export the DNGs after setting cut in / out points that match the frames I'm looking for but that increases workflow time, etc.  Definitely could adjust my workflow to compensate for these scenarios too but it would be nice to have this feature, I think.  Not a hug priority though :)

**Comment by masc4ii** [comment]
Sorry, don't understand your workflow at all and don't understand the problem. How can work this at all what you're doing?! The proxy which you export is the entire clip... so why don't you export the same as DNG -> the entire clip?! How can any NLE relink if you don't do it this way? And the framenumber isn't burned into the proxy at all.

**Comment by bverkron** [comment]
No worries. It's not a huge propriety and I can and have adjusted my workflow to compensate.  Closing.
