### ISSUE TITLE
Export Receipts (Feature Request)

### ISSUE THREAD

**Issue by bverkron** [ilia3101/MLV-App#162]
Maybe I'm missing existing functionality that does this but it would be great to have "recipes" / presets for export settings. I export in 2-3 different ways and if I miss a particular checkbox or setting when adjusting the export settings it breaks my workflow later down the line and I have to go back and re-export and push the new file through a bunch of workflow steps again. Would help avoid human error :)

**Comment by masc4ii** [comment]
This is not existing yet. Could be done...

**Comment by bverkron** [comment]
Would be very handy for me and others that use multiple types of exports in a single project workflow.

For example I initially export proxies for rough editing, then later go back and export either ProRes or CinemaDNG for mastering. The settings for each are different and specific and one missed setting in in the master file exports can break the workflow in late stages when relinking the proxies to the masters in the NLE (i.e. if frame rate doesn't match exactly, etc).  Would be a very nice addition. 

Thanks so much for the app thus far. It's fantastic and your time is greatly appreciated!! I can't imagine doing as clean of a workflow with "dump" tools, etc. :)

**Comment by masc4ii** [comment]
Implemented: https://github.com/ilia3101/MLV-App/commit/7e035696f22ffa2f315078518362d694aae73c1c

![Bildschirmfoto 2019-05-20 um 15 18 57](https://user-images.githubusercontent.com/30245296/58024672-0893a680-7b13-11e9-98c4-53e5d57b5ef0.png)

**Comment by masc4ii** [comment]
Feel free to reopen, if bugs were found.

**Comment by bverkron** [comment]
Looks fantastic, thanks! I will try it on my next project.
