### ISSUE TITLE
Framerate Override setting not retained

### ISSUE THREAD

**Issue by bverkron** [ilia3101/MLV-App#163]
If MLV App is closed and re-opened the Framerate override checkbox gets unchecked.  The frame rate number seems to be retained as well as all the other settings I have tried.

Edit: Seems this setting gets wiped other times too. Maybe after running an export. Haven't nailed it down yet but it happened without quitting the app.

**Comment by masc4ii** [comment]
Framerate override checkbox is not saved when quitting the app and is initially set to OFF on startup.

**Comment by masc4ii** [comment]
Behavoir changed, fps override checkbox is written now into registry too.

**Comment by bverkron** [comment]
Wow that's great. Thank you!
