### ISSUE TITLE
Framerate not consistent in exports

### ISSUE THREAD

**Issue by bverkron** [ilia3101/MLV-App#164]
Maybe not a bug but the nature of things.

When I export to ProRes Proxy (have not tried other formats) clips end up with slightly different frame rates even though they were all shot at the same frame rate (29.97) with the same settings.

<img width="792" alt="Screen Shot 2019-04-11 at 12 51 35 PM" src="https://user-images.githubusercontent.com/19174503/55988483-d613a580-5c58-11e9-8f6d-684f390561f0.png">

Arguably this is what the Framerate override setting is for (and now that the setting is remembered via #163 it will be less of an issue) but I'm curious why they end up with different, nonstandard frame rates in the first place and also if using the force option could cause jittery frames.

In the screenshot above all clips were exported with the same settings in MLV App and footage had the same settings but since Framerate override was not remaining checked between my MLV App sessions and I didn't notice initially it cause many of the clips to have different frame rates which now cause re-linking problems when I try to either fix the proxy or relink to the master version.

**Comment by masc4ii** [comment]
Framerate is not created by MLVApp. It is written to MLV file in camera. So no MLVApp issue at all.
