### ISSUE TITLE
Maybe we should just do black level subtraction at debayer already

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#165]
I only made it after debayering  because I had this dream that it would be cached without black level subtraction and you could change the black level without recalculating whole cache again. But without caching now I don't care. And even if it returns no big deal anyway, who ever changes black level.

I think this would improve debayering quite a lot (maybe close the gap someone showed with MLRawViewer).

**Comment by masc4ii** [comment]
We could try. I tried to do so in past, that is why blacklevel parameter goes directly into debayer algorithms (but isn't used atm). Maybe both has to be done before: WB and blacklevel...

**Comment by masc4ii** [comment]
Hm... did another quick test, but I get greenish edges. But maybe I am doing it wrong.

**Comment by ilia3101** [comment]
I think debayers assume black is at 0 so probably something wrong

**Comment by bouncyball-git** [comment]
S..t! I've tried to dig into and mlraviewer sources several times, but never succeeded to understand fully 😁 why amaze works better there.

**Comment by masc4ii** [comment]
Blacklevel subtraction before debayer can be tried out here: https://github.com/ilia3101/MLV-App/commit/88e803d1033640953edd284de4bccdae88645c63

**Comment by masc4ii** [comment]
Reverted blacklevel subtraction because of very bad image errors in bright areas here: https://github.com/ilia3101/MLV-App/commit/8ec2d91faf57f8907af870147ad66a0676a5d4de

**Comment by masc4ii** [comment]
Let's descuss in #146 , because it is more or less the same topic. Unfortunately blacklevel subtraction did not work in my tests (see above).
