### ISSUE TITLE
Bad pixel manual picker and map saver/loader

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#167]
@masc4ii 

Well I have some ideas and also waiting yours :)

In raw correction:
![Screenshot from 2019-05-13 20-59-32](https://user-images.githubusercontent.com/17232233/57640456-a7744c00-75c3-11e9-8234-96c6b4fc1b06.png)
The picker/saver can be placed below or above of loader/switcher to not make new expandable section.

After loading the map, "On" should be activated and both search methods greyed out.
If file name deleted switch to Off or maybe to On and auto searching mode?
What do you think?

**Comment by masc4ii** [comment]
I think we need more buttons/elements. A map consists of n pixel coordinates?!
-> Off, On, Force, Manual (enables new elements)
-> Open map, filename
--------
-> Save map
-> Picker
-> Table which shows pixel coordinates (select pixels) (double click for editing coordinates)
-> Delete pixel (e.g. if picker failed)

Puh... 👀

**Comment by bouncyball-git** [comment]
Yeah lot of work but I think it worth it.

Guess pixel table not necessary, we should visualize picked pixels on the image with some color dot of "+" sign or whatever. Then those pixels should be selectable/removable by mouse. I think it would be ideal to visualize/edit any loaded map even focus pixels to see what it looks like. Full blown pixel map editor :), none of proggies has it right now.

**Comment by masc4ii** [comment]
Visualization of pixels is not straight forward. Will need more time. Problem: transformation for 1x3, 3x1, 3x5,... I would like to have some "+" overlay on the picture, but it will become e.g. a "--+--". Then we should somehow activate/deactivate this overlay layer. It should also change mouse pointer icon (for deleting points).
Have you started implementing loading a .bpm (? bad pixel map?) for starting this? Next we would need some transfer functions to GUI. The topic is still very interesting! :)

**Comment by bouncyball-git** [comment]
> Problem: transformation for 1x3, 3x1, 3x5,... I would like to have some "+" overlay on the picture, but it will become e.g. a "--+--".

Hehe, right, I never thought about it :grin: 

> Then we should somehow activate/deactivate this overlay layer. It should also change mouse pointer icon (for deleting / moving points).

Yes, so true.

> Have you started implementing loading a .bpm (? bad pixel map?) for starting this? Next we would need some transfer functions to GUI. The topic is still very interesting! :)

Simple .bpm loading was implemented from the beginning. If app finds it it will be loaded. Need some time to recall the code and improve it further.

**Comment by masc4ii** [comment]
>Simple .bpm loading was implemented from the beginning. If app finds it it will be loaded. Need some time to recall the code and improve it further.

Cool, what name should it have to be found? I could try exporting a png and find the cursor coordinates and try if that works! Inside the bpm looks identical to the fpm?

**Comment by bouncyball-git** [comment]
Ahh, I believe it has to have the same name as fpm. e.g. camid_raw_resolution but ending with .bpm extension. I'll take a look on monday...

**Comment by masc4ii** [comment]
Hm... for my EOS M I could try this, but my 5D2 has more bad pixels I don't like ;) But for this I don't know how the file must be named.

**Comment by bouncyball-git** [comment]
Type:
mlvdump -v your.mlv > some_file.txt

then find IDNT block (example):
Block: IDNT
  Offset: 0x000001ac
  Number: 6
    Size: 84
    Time: 0.004000 ms
     Camera Name:   'Canon EOS 5D Mark II'
     Camera Serial: '2591E264' (630317668)
     **_Camera Model:  0x80000218_**
Camera ID is here ^^^

then find block RAWI (example):
Block: RAWI
  Offset: 0x00000034
  Number: 1
    Size: 180
    Time: 178.341000 ms
    Res:  1856x1044
    raw_info:
      api_version      0x00000001
      **_height           1268
      width            2040_**
RAW buffer resolution is here ^^^
      pitch            3570
      frame_size       0x004512A8
      bits_per_pixel   14
      black_level      1791
      white_level      16200
      active_area.y1   18
      active_area.x1   160
      active_area.y2   1268
      active_area.x2   2040
      exposure_bias    0, 0
      cfa_pattern      0x02010100
      calibration_ill  1

**Comment by masc4ii** [comment]
THANKS! How great is this? That really works! I can just remove my few bad pixels and all detail in the clips is not touched!

**Comment by bouncyball-git** [comment]
Cool! :). I'm glad it works as intended. I want to help you out and write backend of the the dot editor... maybe next week?

My father broke 6 ribs and he is 89 years old. My mother had her eye surgery 2 days ago (second eye has to be done after a month) and my brother has some illness (legs) and cant walk right now, nit to mention my own family (2kids) :) so  I've got a lot of stuff to do... :)

**Comment by masc4ii** [comment]
OMG. Sounds not good. No problem if you don't have time right now, because I don't have much time either atm. This and next week will be very warm here, so we will be outside a lot... and on the other side, there are still 450GB of holiday MLVs waiting. So take your time!

**Comment by masc4ii** [comment]
@bouncyball-git : I am currently writing some code to create and edit the .bpm files automatically in background. Goal is to click with a picker to add and remove the pixels from the file. 
My problem is now: if the file exists, it will always use it, and the buttons "Force, Norm, Aggr, ..." do nothing. Are you able to help? I think the .bpm file should only be used, if activated (e.g. with another button or however, for now with a C function).

**Comment by masc4ii** [comment]
Added all to repos.
How it works (for now):
- Activate "Off". Now you see the bad pixels.
- Activate "Map". (In background it is still off, so nothing happens)
- Activate "Edit". Click on a bad pixel (zoom in before to get it). Nothing else happens.
- Activate "On". This one bad pixel disappears.
- Activate "Map". (In background it is on now, so each click on a pixel will bring a change)

- Clicking a pixel twice, removes the pixel from map.

What we need to make it better: force select between auto search and map. Then, point 2-4 will be better (like point 5).

**Comment by bouncyball-git** [comment]
Great! Now I have some messed up feeling, have to toy with it more to get to right opinion.

**Comment by bouncyball-git** [comment]
I liked your simple approach to work with .bpm file directly and not messing with bad pixels buffer!

I think I have an idea. Will be back soon...

**Comment by masc4ii** [comment]
>I liked your simple approach to work with .bpm file directly and not messing with bad pixels buffer!

It already worked great! Why reinventing... 😄 I was using the bpm maps feature for soo long now with my 5D2 clips and was very satisfied. Just adding new pixels was a bit hard.

>I think I have an idea. Will be back soon...

Great to hear!

**Comment by bouncyball-git** [comment]
[commited](https://github.com/ilia3101/MLV-App/commit/69816174161646806bcfb6ae1ad327e2d2c45f56) the patch.

Bad pixels UI behavior:
1. Off - nothing happens
2. On - if pixel map found: load and use; else: go search for 1st frame only
3. Force - no matter pixel map is there or not go search for every frame
4. Map - if map is there load it and interpolate, stay in map/picker mode. If map is not loaded start from scratch and stay in map/picker mode interpolating after every click.

Note: I think in map there must be indication of every pixel, e.g. every pixel have to be marked by small white (maybe other color) cross (plus sign). If .bpm exists load all pixels from it and mark them on scree.

**Comment by bouncyball-git** [comment]
I think delete pixels hard too ;)

**Comment by masc4ii** [comment]
Cool, will try out. 
Is it also possible to only search for 1st frame when "On"? Else "On" and "Map" is identical, if a bpm is there, while the auto search is not accessible.

I thought creating a function which shows the pixels from the map on the frame. To be done. You're right: otherwise it is hard to delete the pixels...

**Comment by bouncyball-git** [comment]
> Is it also possible to only search for 1st frame when "On"? Else "On" and "Map" is identical, if a bpm is there, while the auto search is not accessible. While on the other side, I also like your idea.

Well, yes it is theoretically possible, but I thought that when "Map" is active all pixels will be shown to edit (add/delete) and when done we just switch to "On" to see the clean image again.

> "Norm" and "Aggr" do nothing, while a bpm is found, or?!

Yes they are only search methods and are meaningless when map is loded from file.


> I thought creating another function which shows the pixels from the map on the frame. To be done. You're right: otherwise it is hard to delete the pixels...

Yes exactly ;). Will be cool!

**Comment by masc4ii** [comment]
Okay... so leave it as is for now. I'll just implement the pixel layer. I hope I'll find a way which also works with all that stretching.

**Comment by bouncyball-git** [comment]
Look I though more and maybe it will be better as you've said.

have 4 buttons as Off, Auto, Force, Map

1. Off - as it is.
2. Auto - will search 1st frame always even if map file is present.
3. Force - as it is
4. Map will activate map mode e.g. try to load .bpm map and start from scratch if no map is found.

Pixel marks will be shown only when picker is active. What do you think? This will comprehend all features and also gonna be very intuitive, huh?

**Comment by DeafEyeJedi** [comment]
Agreed. I like this layout very much. Seems like a solid foundation that makes most sense as far as options goes.

**Comment by masc4ii** [comment]
Hm, this was more or less my idea, how it should be. But your idea (before) wasn't worse. 
>Pixel marks will be shown only when picker is active!

The normal usecase should be fine like this. But what, if two bad pixels are very close and the marks hide the bad pixel (had this with my 5D2)? That's why I think we need a dedicated button for the markers. From ML forum PM talk: a reset button would also be nice, right... seems we need another button row in Bad Pixel Fix area.

**Comment by dannephoto** [comment]
Good stuff! Saving my eosm with a cluster of dead pixels always present.

Adding this from my message post:
I guess map is always enabled if added in Mlv app? Why not grey out "on" and "force" and simply keep map or off enabled if map files are active? 
Also wonder if we should be able to erase the map file if we want too. Reset or something?

**Comment by bouncyball-git** [comment]
Yes I'm now more biased to your prev idea. I think mine was not very intuitive.

> The normal usecase should be fine like this. But what, if two bad pixels are very close and the marks hide the bad pixel (had this with my 5D2)? 

No problem, we can always zoom in. Which is the best mode to pick the pixels anyway.
No need for dedicated button.

>From ML forum PM talk: a reset button would also be nice, right... seems we need another button row in Bad Pixel Fix area.

This would require dedicated button. I have a proposition like make small icon above map button with recycle image or whatever which will be activated only when Map mode is active.

**Comment by dannephoto** [comment]
> @masc4ii
> 
> Yes I'm now more biased to your prev idea. I think mine was not very intuitive.
> 
> > The normal usecase should be fine like this. But what, if two bad pixels are very close and the marks hide the bad pixel (had this with my 5D2)?
> 
> No problem, we can always zoom in. Which is the best mode to pick the pixels anyway.
> No need for dedicated button.
> 
> > From ML forum PM talk: a reset button would also be nice, right... seems we need another button row in Bad Pixel Fix area.
> 
> This would require dedicated button. I have a proposition like make small icon above map button (on the very right side) with recycle image or whatever which will be activated only when Map mode is active.

Aha, so you can still enable cold pixel fix on top of the created bpm file? If so it should actually stay as it is. I thought only bpm(map) files was active once it was created. Maybe better keeping it in those case we also have more general pixel issues as well.

Even better with a recycle arrow than a reset button.

**Comment by masc4ii** [comment]
If the search methods are not needed in Map mode, I could hide it and place only the "Map buttons". 
I would like to have a cross for each bad pixel in the map like this:
![Bildschirmfoto 2019-12-12 um 11 48 02](https://user-images.githubusercontent.com/30245296/70706321-f909c400-1cd5-11ea-9fe7-f011dc575667.png)
But the problem is the stretching and scrolling. The 4 lines should always have same length, even in 3x1 or 1x3. This layer must move with the image when dragging. It is the problem why I did not implement this in past... I have no good idea how to solve this "simple" problem.

**Comment by bouncyball-git** [comment]
> If the search method buttons are not needed in Map mode, I could hide them and place only the "Map buttons" (recycle and edit).

Not necessary, graying them out is enough. Let's make it look like this:
![Screenshot from 2019-12-12 18-09-36](https://user-images.githubusercontent.com/17232233/70719357-4a807600-1d0b-11ea-95e2-7b3d60be7404.png)
Besides I like pencil button being in "Search Method" row. Like manual search.
IMHO just small icon above the map which will be activated together with pencil when "Map" pressed is good enough.

I like the cross mark!

> But the problem is the stretching and scrolling. The 4 lines should always have same length, even in 3x1 or 1x3. This layer must move with the image when dragging. It is the problem why I did not implement this in past... I have no good idea how to solve this "simple" problem.

Yes this is the real problem, especially stretching. Will think about it too...

**Comment by bouncyball-git** [comment]
> The 4 lines should always have same length, even in 3x1 or 1x3.

BTW who said that this is mandatory? Let the cross lines stretch/compress as well ;). The only thing is important: the correct pixel to be selected. After vertical stretching the pixel will become 3 vertical pixels anyway. Am I wrong?

**Comment by masc4ii** [comment]
This is how one bad pixel looks like in 1x3:
![Bildschirmfoto 2019-12-12 um 16 17 14](https://user-images.githubusercontent.com/30245296/70724503-05544800-1cfb-11ea-919f-f39878ffedc3.png)

And this is how two bad pixels look like in 1x3 (vertically)
![Bildschirmfoto 2019-12-12 um 16 17 42](https://user-images.githubusercontent.com/30245296/70724536-1604be00-1cfb-11ea-9d39-3bb2df3ed530.png)

**Comment by bouncyball-git** [comment]
This is original, out of the camera, stretched pics right?
Can you give me MLV?

**Comment by masc4ii** [comment]
Yes, this is a 1x3 stretched clip from Danne's EOSM.
https://bitbucket.org/Dannephoto/magic-lantern/downloads/M19-1215.MLV
But I was wrong: both pictures show two very close bad pixels. A cross marker for one pixel would hide the second pixel.

**Comment by bouncyball-git** [comment]
Thanks for Danne's famous cat :)

Yup, it seams both are 2 vertically placed bad pixels (or stretched artifact produced after vertical bining done by camera) and 2 mouse clicks eliminate this artifact entirely.

IMHO after deeply zooming in mark crosses placed virtually one above another gonna separate and be fully visible. I think it is no problem at all.

I can not pick the exact pixel if not zoomed in quite a bit.

**Comment by DeafEyeJedi** [comment]
This is all fantastic progress. So glad I kept one of the three EOSM’s I have which has several bad pixels showing up every single MLV. I love the cross mark!

**Comment by dannephoto** [comment]
> Thanks for Danne's famous cat :)
> 
> Yup, it seams both are 2 vertically placed bad pixels, or stretched artifact produced after vertical bining done by camera with one or more bad pixels existing in those bined rows, and 2 mouse clicks eliminate this artifact entirely.
> 
> IMHO after deeply zooming in crossmarks placed virtually one above another gonna separate and be fully visible. I think it is no problem at all.
> 
> Anyway, I can not pick the exact pixel if not zoomed in quite a bit.

Zooming in is ok, and yeah. One of my eosm,s came with severe pixelation trouble. So this picker will be heavenly ;)

**Comment by masc4ii** [comment]
Delete button is available now. 
Without zooming in, it is impossible to click the correct pixel - sure. But note, that the cross will zoom with the image - so the pixels from the cross will be over the e.g. 2nd bad pixel. So you don't see what you click.

**Comment by masc4ii** [comment]
The cross is available now too. But be carefully... any stretching applied with crosses will break your eyes!
https://github.com/ilia3101/MLV-App/commit/8f31ac282a019cf05034cab930d4029e331f4fba

**Comment by bouncyball-git** [comment]
Ouch!!! :grin: The ugliest thing I've ever seen hahaha.

Thank you for taking time and implementing it.

Of course I meant that crosses are not affected by zoom (maybe a bit by vertical stretch) and always stay small and pretty. I understand this is lot harder to implement. The layer should be generated dynamically during zoom...

**Comment by bouncyball-git** [comment]
BTW I like how you zoom the "Linear Gradient" layer. Lines thickness is not affected by zoom at all.

**Comment by bouncyball-git** [comment]
[commited](https://github.com/ilia3101/MLV-App/commit/497f1342127382391bb398d1fd5209dc574f9d31)

    Off - do nothing (show all bad pixels)
    Auto - search bad pixels for 1st frame only and use for whole clip
    Force - search and fix bad pixels for every frame
    Map - activate map mode e.g. try to load .bpm map and start from scratch if no map is found

**Comment by bouncyball-git** [comment]
There is one bug: when picker button is active and then you clicked on off/auto/force picker stays active.

Also deactivation of the picker after leaving working image are is a bit annoying. Maybe let is be pressed and deactivate is manually?

**Comment by masc4ii** [comment]
Yes, ugly, but that's it. 
The gradient element is a polygon vector element with one line. One line can be a class which can be added as new layer to the viewer. One cross could minimum be one of such polygons as well. So 50 crosses means we have 50 new layers (each has one class (maybe in a vector) and each need independant calculation for correct position and size). No idea where to start with that... the gradient element already nearly broke my neck when I did it... but this... puh. That's the reason why I did not work on this issue for so long 😄 
Maybe someone knows better how to handle such graphic elements...

Thanks for the commit. Will try this evening. Also thanks for pointing out this bug - you're correct, I forgot to implement this rules. 
The deactivation on leaving working area was not easy to implement and is my favorite behavior for the pickers... I miss it so much in Lightroom! Haha. The gradient control deactivates when line was drawn.

**Comment by masc4ii** [comment]
I fixed the bug. Now each clip outside the viewer quits pixel edit mode - same behavior as for WB picker. 
But I found another bug on your side: "Aggr" mode seems not to work. There is no difference between "Norm" and "Aggr". When compairing to older versions I would say the old "Norm" is what we have now in both modes.

**Comment by masc4ii** [comment]
![Bildschirmfoto 2019-12-13 um 20 49 23](https://user-images.githubusercontent.com/30245296/70827723-192aa780-1dea-11ea-80d0-a5ff3b65fc34.png)
Changed button bahavior a bit... and the ugly crosshair can be hidden now.

**Comment by dannephoto** [comment]
Nice! Pencil back and hidden until pushing map button, really cool. I couldn´t get the cross next to the pencil to work. I only got a hand shown but I am only using the pencil as Search method but since it´s there it should work I suppose.
Good work!

**Comment by masc4ii** [comment]
You need the cross + the pencil beeing pressed to get into edit mode with crosses.
![78998455_10220383697598086_4930947997149167616_n](https://user-images.githubusercontent.com/30245296/70829341-baffc380-1ded-11ea-9191-11ce1a07f164.jpg)

**Comment by bouncyball-git** [comment]
Coo progress thanx! Will check Norm/Aggr and be back...

**Comment by bouncyball-git** [comment]
@masc4ii 

Nice catch! Fixed the bug.

Played a bit with new interface. I'm lost:
1. Really do not like the scenario when showing crossmarks depends on two buttons simultaneously. Please pull out the pencil button from this equation.
2. I can not understand what clear button does. It does nothing IMHO.
3. Less important but anyway. 3 new buttons are a bit shorter vertically than Norm/Aggr, so whole GUI below shifts a bit in Linux.

**Comment by masc4ii** [comment]
Cool, thanks! Will try out!
1. Clicking just the pencil: edit the pixels by clicking. Clicking pencil+crosshair: edit pixels by clicking and see added pixels by crosshair.
2. Clear button deletes the map. You should find it in the trash.
3. Oh... really? Is the font so large in Linux?! Here on OSX there is still space left. Will see what I can do...

**Comment by bouncyball-git** [comment]
1. I'll explain what kills me :). If crossmarks are visible and in edit mode, when I leave the image area pencil deactivates and all crossmarks disapear. This is really, REALLY annoying ;). This makes plus mark button obsolete.
2. Unfortunately In Linux it does not work. .bpm file always there. Hence no reset. I clicked reset button 1000 times ;)

**Comment by bouncyball-git** [comment]
Oh and one more thing the deletion of the .bpm file is a bit dangerous. Imagine you spent a lot of time and got rid of 333 bad pixels manually. Ad you think all is saved and are happy. Yes it is saved for now, but after one accidental click on reset button the file disapears (or all pixel info deleted no matter). Do you think this is good for nerves? :grin:. Not always one will remember to make backup copy of the file.

**Comment by masc4ii** [comment]
1. Don't understand the problem.
2. Delete doesn't work? Oha. Does clip delete from session work for you? It works with exactly the same function! 
Deletion isn't really dangerous. We move to trash and don't delete. But I can bring a messagebox if you like, which clearifies what will happen.

**Comment by bouncyball-git** [comment]
1. I want to drag the image around with visible crossmarks! What's impossible right now.
2. "Remove clip from session/Delete from disk" works fine :(
3. Yes I think messagebox is a good idea

Look at [this](http://bouncyball.myweb.ge/mlvapp/?dir=&download=pixel_picker-2019-12-14_21.29.39.mp4) video

**Comment by bouncyball-git** [comment]
Do you close file before deletion?

**Comment by masc4ii** [comment]
1. Ah, now I understand. So you want to edit if edit is enabled, and you always want to see crosses when crosses are enabled... good. That is doable.
2. Strange... will have another look.
3. Will be done...

**Comment by bouncyball-git** [comment]
1. Yay!!! Waiting ...
2. Found very strange behavior. If .bpm once deleted it is in trash. 2nd time it can not be deleted to trash... I guess macos handles second deletion of the same file from the same place and the same name more intelligently.
3. Cool!

**Comment by bouncyball-git** [comment]
HAHA found out second strangest thing from file manager the same file can be move to trash infinite times but not with command MoveToTrash( QFileInfo( fileName ).absoluteFilePath() )

SHIT!

**Comment by masc4ii** [comment]
Okay... done all this. Except the move to trash problem. I expect the problem in the linux code part in this function. On OSX this works without problem. But I can't debug the linux code here. The function should get the full path+filename. On OSX this works. Maybe you can go into this function and have a look (if you like).

**Comment by masc4ii** [comment]
You can use qDebug() << variable1 << variable2 << "some string"; for debugging with console window in QtCreator... (I think you already know). Maybe filename or path is wrong?

**Comment by bouncyball-git** [comment]
Nope, unfortunately filename and path are ok. In the trash second time deleted same file gets renamed to (aslso infi file):

```
<oldfilename>.2.<extension>
<oldfilename>.2.<extension>.trashinfo
```

And so on 2 becomes 3... n

The Linux section of "int MoveToTrash( QString fileName )" function unfortunately does not check the file existance in trash and does not react to this accordingly.

**Comment by masc4ii** [comment]
Aha, okay. No idea. I found the code somewhere in the internet and used it for MLV and MAPP removal. There it works. Funny strange. Checking for existance can be made with "QFileInfo( fileName ).exists()", if that helps somehow. No idea what to change and how to solve this. Did you have the file already in your trash? Or how came this problem up?

**Comment by bouncyball-git** [comment]
Yes if file already in the trash second file with same same name have ca not be trashed w/o renaming. Gonna try to change this function when have time.

**Comment by masc4ii** [comment]
If you have any idea about that, this would be great! Thanks.

**Comment by bouncyball-git** [comment]
I'll try...

Hey thnanks for changing crossmark button behavior. Now it feels right :)

But [this](http://bouncyball.myweb.ge/mlvapp/?dir=&download=movements.mp4) small issue still exists.

**Comment by bouncyball-git** [comment]
Almost forgot... When switching to off/auto/force crossmarks button also have to be deactivated

**Comment by masc4ii** [comment]
Ah... nice found. Fixed. Now crosses are shown only in Map mode and if RAW Corrections are enabled.
The video: you mean button height? Button height is defined by content. On Linux font seems to be higher then the 12pix icon. That is difficult without font in at least one of the buttons.

**Comment by masc4ii** [comment]
Could you try? I set a minimum to the button height... the OSX standard height. Maybe this is larger the Linux minimum.

**Comment by bouncyball-git** [comment]
Now it is a bit better but still noticeable.

**Comment by bouncyball-git** [comment]
I'm happy now :grin: 

[commit](https://github.com/ilia3101/MLV-App/commit/64681f1820d1a28d327a5377d56132684e4a51ee)

**Comment by bouncyball-git** [comment]
Can we change the minimum height again?

**Comment by masc4ii** [comment]
Great! Thanks! 
I think we need at least on button in this row with text inside, else this won't work for at least on OS.

**Comment by bouncyball-git** [comment]
Linux: "Correcting button height part2" made things even worse :)

**Comment by bouncyball-git** [comment]
One proposition: maybe put in one button one symbol like "l" but give it background color to make it invisible?

**Comment by masc4ii** [comment]
Haha... same here. Only on Windows it works this way. Text+icon shifts icon to the left. So we only can exchange an icon vs. text.

**Comment by bouncyball-git** [comment]
Aha, perhaps redo reset to "Delete"? Or "Start Over"?

**Comment by masc4ii** [comment]
Exchanged icon of one button with "Del".

**Comment by bouncyball-git** [comment]
Fantastic! Static solid transition :)

**Comment by masc4ii** [comment]
The pixel mud is the past... vector crosses are the future... yay. https://github.com/ilia3101/MLV-App/commit/f20881ac831e04afa50e3d462cd28ee9e02eb02c

The code change looks not huge... but I am very happy to have it solved now. And this is how it looks:
![Bildschirmfoto 2019-12-19 um 20 31 33](https://user-images.githubusercontent.com/30245296/71204067-897c7180-229f-11ea-9717-33c4a97e564d.png)
I hope you like it. For n crosses we have n vector graphic layers now.

**Comment by dannephoto** [comment]
![Screenshot 2019-12-19 at 21 15 08 png_800px](https://user-images.githubusercontent.com/22038358/71206587-33123180-22a5-11ea-9eb5-f180bc76fa7a.jpg
It is perfect!

**Comment by bouncyball-git** [comment]
Oh you did it anyway? Despite of n vector layers? Hahaha thank you!

**Comment by bouncyball-git** [comment]
BTW why all crossmarks blink when adding new pixel?

**Comment by masc4ii** [comment]
All pixel layers will be generated from new when adding a new pixel or deleting an old one (and before all layers are deleted). I guess this is why it blinks... but have not debugged this yet. That was the simplest way to realize this.

**Comment by masc4ii** [comment]
Retest please... changed a bit.

**Comment by bouncyball-git** [comment]
Hm... It is not blinking any more !!!

Hahaha I almost blamed QT 9.14 and GCC 9.2.1 for this ;)
