### ISSUE TITLE
Using MAPP file blocks focus pixel removal

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#169]
@bouncyball-git : I found a problem, when a MAPP file is available. When trying to activate focus pixel removal, that does not work (at least for all focus pixels). Here is a file, where the focus pixels can be removed, when no MAPP is there. Is the MAPP file created, all pixels stay there (this means, when loading the MLV if the MAPP was created. A very first time it works.).
https://www.dropbox.com/s/xqgxb36o2iwnx0a/M31-1455short.MLV?dl=0

In another file around 50% of the pixels were removed with MAPP file, 100% without MAPP file.

Any idea?

Steps to reproduce:
- download my MLV
- open MLVApp
- check "Create MAPP Files"
- open my MLV
--> focus dots removal works
- new session
- open my MLV
--> focus dots removal doesn't work
- delete MAPP
- new session
- open my MLV
--> focus dots removal works
...

**Comment by masc4ii** [comment]
There is a slight difference in debug output, between working and not working (see above).
If it works:
```
Using focus pixel map: '80000331_1872x1190.fpm'
111384 pixels loaded
Using fpi method: 'MLVFS'
raw_image_buff[1000] = **4098**, Proc_Black = 8188, Proc_White = 64346, Raw_Black = 2047, Raw_White = 16200 <= THE END OF LLRAWPROC
```

If it does not work:
```
Using focus pixel map: '80000331_1872x1190.fpm'
111384 pixels loaded
Using fpi method: 'MLVFS'
raw_image_buff[1000] = **4052**, Proc_Black = 8188, Proc_White = 64346, Raw_Black = 2047, Raw_White = 16200 <= THE END OF LLRAWPROC
```

No idea if that helps.

**Comment by masc4ii** [comment]
Found why it is not working:
when loading with MAPP file:
video->VIDF.panPosX = 0
video->VIDF.panPosY = 0
It seems this information gets lost.

**Comment by masc4ii** [comment]
Found a fix: https://github.com/ilia3101/MLV-App/commit/f6ce5fa874076b96c838d6e341197b089670d593

But I don't know if it is correct, what I did. @bouncyball-git : was there a reason for not including VIDF structure into MAPP files, or was it just forgotten?

**Comment by bouncyball-git** [comment]
Hey! Hello guys!

The reason is that every VIDF header has its own panPos(X/Y) and it should be derived on reading the current frame (header + data)

I'll check out why header is not not read and values not updated when MAPP is active,,,

**Comment by masc4ii** [comment]
Hey @bouncyball-git ! Yes, I made some debug outputs and have seen, that if no MAPP is there, there are panPos availlable, while with MAPP those values are = 0. With my (I now see) wrong patch this was solved. What you write sounds better... maybe you get it corrected in the right way! 😄

**Comment by bouncyball-git** [comment]
Yes I'll take a look soon :)

**Comment by masc4ii** [comment]
Could this be the problem:

```
int openMlvClip(mlvObject_t * video, char * mlvPath, int open_mode, char * error_message)
{
    ...
    /* In preview mode we don't need to waste time on audio loading from mapp v2*/
    if(open_mode != MLV_OPEN_PREVIEW)
    {
        if(!load_mapp(video)) goto short_cut;
    }
...
            else if ( memcmp(block_header.blockType, "VIDF", 4) == 0 )
            {
                fread_err &= fread(&video->VIDF, sizeof(mlv_vidf_hdr_t), 1, video->file[i]);

                DEBUG( printf("video frame %i | chunk %i | size %lu | offset %lu | time %lu\n",
                               video->VIDF.frameNumber, i, video->VIDF.blockSize - sizeof(mlv_vidf_hdr_t) - video->VIDF.frameSpace,
                               block_start + video->VIDF.frameSpace, video->VIDF.timestamp); )
...
short_cut:
...
```

**Comment by bouncyball-git** [comment]
Yup that's it, goto label skips vidf reading when mapp is active. That's why I said vidf header is not updated. But I was wrong ;). There is a ancient flaw in raw video frame data reading header is not updated at all :). This was not a problem when we not needed to account panpos/croppos but if this matters (now we see that it is!) then I have to patch the reading routine. What's I'm doing right now... stay tuned :)

**Comment by bouncyball-git** [comment]
Now mlvobject -> VIDF header gets upadated for current frame. Your patch reverted. Please try b82761e3044531d855fce5d9ac59048cf816924b

**Comment by masc4ii** [comment]
Yay... first test looks good. Thank you. Will test more this week-end, while processing last holiday clips 😄

**Comment by bouncyball-git** [comment]
Cool!!! BTW Nice catch with that MAPP stuff, thank you :grin:

**Comment by bouncyball-git** [comment]
I've been in Vienna and Prague last week and you know what? I had no my 5D3 with me ;) because my friend has it and he is in Paris 2 weeks already.

Where have you spent your last holidays?

**Comment by masc4ii** [comment]
Yes... I thought I am too stupid to find the right focus pixel maps. Shortend the file, watched if it works... focus pixels away... hääää?! Tested again, pixels there again... häää? 😄 

I was at La Palma (Canary Islands), mostly used my 5D2, and the M for some special clips (45fps or if I needed IS with my kit lens). Have now 460GB of MLV files here... it won't become borring.

**Comment by bouncyball-git** [comment]
Cool! You always choose the right place to rest :)

**Comment by masc4ii** [comment]
LOL. I do my very best :)
Unfortunately I couldn't record the best adventure as MLV... milky way without moon. Photo's: ISO6400, f/2.8, 20sec. 
![pic](https://scontent-frt3-2.xx.fbcdn.net/v/t1.0-9/61922488_10218668561000743_4446877261307576320_n.jpg?_nc_cat=101&_nc_ht=scontent-frt3-2.xx&oh=39967b48d371162e408bf6ac213e98bb&oe=5D9B1842)

**Comment by bouncyball-git** [comment]
This is fantastic man! Is that 20 sec time lapse? What is resolution?

**Comment by masc4ii** [comment]
This is just a cr2 photo (10 stitched - darkframe) with 20sec exposure. Final resolution is 11000x3600px.

I now found another bug. If I load this file:
https://www.dropbox.com/s/q66hkq8o58t2zbv/M22-1233short.MLV?dl=0
the app crashes.

![Bildschirmfoto 2019-06-14 um 17 58 32](https://user-images.githubusercontent.com/30245296/59522087-1e0bae80-8ece-11e9-86ef-d2083660cdf5.png)
![Bildschirmfoto 2019-06-14 um 17 58 57](https://user-images.githubusercontent.com/30245296/59522093-21069f00-8ece-11e9-9b98-0d74c7640fc0.png)

**Comment by masc4ii** [comment]
Sorry... found it... bad MAPP file. Deleted MAPP, reopened, works.

**Comment by bouncyball-git** [comment]
Ahh It's OK. I guess this because of loading MAPP file saved by patched (your quick fix) mapp writer. It had an extra info equal to sizeof(vidf_header_t). Surely this broke the day :grin: 

The stiched panorama is Awesome! I wonder what the original looks like :)

**Comment by masc4ii** [comment]
Yes, sure this was the reason. But I thought reading a wrong MAPP is like reading no MAPP, and without crash. But nobody else will do what I did, so no real problem.

The original panorama looks a bit noisy... ISO6400 is not best for 5D2, but I had no choice. My 16-35 is not better ;) This island is sooo dark at night.
