### ISSUE TITLE
Tuning sharpener with masking

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#174]
In LR/PS, there are sharpeners which work with masking. I like that, because only detail is sharpened, while noise isn't (mostly). I started thinking about how to realize this in MLVApp. When applying a sobel filter we get something very close to the LR mask. If we now could somehow use the pixel value from the sobel filter to blend the sharpener to the original picture, we would be nearly there. 

I found a sobel filter [here](https://github.com/petermlm/SobelFilter/tree/master/src). Just change all "byte" to "uint16_t" and we have it @ 16bit. We can apply it like that:
```
        int img_a = imageX * imageY;
        uint16_t *gray,
             *sobel_h_res,
             *sobel_v_res,
             *contour_img;
        sobelFilter( outputImage, &gray, &sobel_h_res, &sobel_v_res, &contour_img, imageX, imageY );

#pragma omp parallel for   
        for( int i = 0; i < img_a; i++ )
        {
            int j = i*3;
            outputImage[j+0] = contour_img[i];
            outputImage[j+1] = contour_img[i];
            outputImage[j+2] = contour_img[i];
        }
```
This looks like that (I would like to use this as mask for the sharpener):
![Bildschirmfoto 2019-08-06 um 21 09 32](https://user-images.githubusercontent.com/30245296/62570254-c404e500-b88f-11e9-9fb1-2e97ced9ade5.png)

Now my problem:
@ilia3101 : I don't understand completely your realization of your sharpener, and I am not sure if we get the sobel filter divided on this thread solution. Could you give some help and idea please? 😄

**Comment by ilia3101** [comment]
That mask looks great! just like the one I remember seeing in adobe camera raw.

The sharpening is just multiplying the middle pixel, and subtracting the ones around it a little bit. To put this mask to use I imagine you just need to blend the result with the original according to what the mask says? Or is my code confusing. I will have a look, don't remember how exactly it works.

**Comment by masc4ii** [comment]
Thanks @ilia3101 ! I think I got it now.

This is the good old standard sharpener:
![M23-1205_frame_1a](https://user-images.githubusercontent.com/30245296/62734590-a66b8300-ba29-11e9-9b88-228dcf9afb4d.png)

This is the mask:
![M23-1205_frame_1c](https://user-images.githubusercontent.com/30245296/62734606-b1beae80-ba29-11e9-9b43-c93a55fcb46e.png)

And this is the masked sharpener:
![M23-1205_frame_1b](https://user-images.githubusercontent.com/30245296/62734621-baaf8000-ba29-11e9-9749-b66b1b07ed3b.png)

**Comment by ilia3101** [comment]
Looks like it's doing the job of keeping sharpening only on the edges :+1:

**Comment by masc4ii** [comment]
Now you can try out: https://github.com/ilia3101/MLV-App/commit/0fbaa7e0c33151a5f21337752709017da3c01445
GUI elements and mask function tweaking to be done.

**Comment by masc4ii** [comment]
Now you can try out without hacking the code... GUI slider and function faking done.
https://github.com/ilia3101/MLV-App/commit/4b44125d783e597b3c41710f9899800d24d1915f

**Comment by ilia3101** [comment]
Works well so far, haven't tested it on particularly noisy footage yet though
