### ISSUE TITLE
MLV Generation

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#175]
I realised it is not too hard to make MLVs with different parameters like resolution or bitdepth (if you have one open already), so I want to find a way of creating new MLVs from other raw formats.

I think it would be nice to make a tool to convert other camera raw formats to MLV.

@bouncyball-git I have a couple of questions I think you know the answers to:

What are the most important / required blocks to make an MLV?

Does the MLV format have a block that can contain camera matrix?

**Comment by bouncyball-git** [comment]
Hey! sorry for late answer (some personal life problems, my father (90yo) is in hospital).

To make MLVs from scratch you can refer to my code in [raw2dng.c](https://bitbucket.org/hudson/magic-lantern/src/unified/modules/lv_rec/raw2dng.c). I've added the RAW to MLV converter there couple of years ago. It saves valid MLVs with correct time stamp, some required basic blocks etc...

The matrixes are part of _struct_ **raw_info** (raw.h), which itself is a part of _struct_ **mlv_rawi_hdr_t** (mlv.c)

**Comment by ilia3101** [comment]
> Hey! sorry for late answer (some personal life problems, my father (90yo) is in hospital).

> To make MLVs from scratch you can refer to my code in raw2dng.c. I've added the RAW to MLV converter there couple of years ago. It saves valid MLVs with correct time stamp, some required basic blocks etc...

So sorry to hear that. No worries at all. Thank you very much, I will take a look at raw2dng.c

> The matrixes are part of struct raw_info (raw.h), which itself is a part of struct mlv_rawi_hdr_t (mlv.h).

Ah! For some reason raw_info is not in mlv_structures.h, was a little confuse.

**Comment by ilia3101** [comment]
Had a weird issue recently, some discussion in MLV App forum thread. I generate an increased resolution MLV this way: write the same metadata as an original using `saveMlvHeaders`, having before that change xRes and yRes in rawi_hdr_t, then write the new frames manually. When exporting DNGs through MLV App from this enlarged MLV, the created DNG frames will be interpreted as having the wrong resolution by some software.

I think I know where the isssue may be now: is there also something in the raw_info struct that needs to be also changed to set resolution?

It's a bit of an intimidating structure.

**Comment by masc4ii** [comment]
Is done now using raw2mlv and libmlv.
