### ISSUE TITLE
Could the AVIR scaling be applied for FFMPEG export too?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#177]
Also i cant find any samples anywhere showing how this algorithm compares to anything else.

**Comment by masc4ii** [comment]
Yes, this would be possible, but I would have to change the resizing for that pipe in general.  Therefor fast and bad quality algorithms (e.g. bilinear) would disappear (ffmpeg + AVIR in one pipe would be complexity-overkill).

You can easily compare AVIR to (I think) bicubic (=Qt smooth algorithm) in the MLVApp viewer, by toggling between "Playback -> Better resizer for viewer". If you have a 1x3 clip, the difference is visibile already.

You can also use "Single Frame Export" vs. "ffmpeg PNG export". Here you can compare to all ffmpeg algorithms.

**Comment by ilia3101** [comment]
I just compared AVIR with bicubic and lanczos. It's very impressively good.

You could have a pipe set up for upscaled resolution, and once processing outputs an image, run the AVIR algorithm to upscale the image while putting it in to the pipe at the same time. Could that be possibel? Doesn't mean we have to replace original algorithm options, or is this too difficult.

**Comment by masc4ii** [comment]
For ffmpeg rescaling, we need to adapt the ffmpeg command (string made of parameters). For AVIR I have to setup some memory, find parameters and call a library function. Both alone is okay, but mixing that, makes it much more complicated. It is possible to do...

**Comment by masc4ii** [comment]
Have a look in mainwindow.cpp and compare the rescaling code:
- ffmpeg: startExportPipe
- AVFoundation (with AVIR): startExportAVFoundation

**Comment by ilia3101** [comment]
I will have a look. I guess it does add more complexity, a whole new type of exporting. I was just thinking that the exclusivity to AVFoundation is a bit weird, as the algorithm has nothing to do with Apple.

**Comment by masc4ii** [comment]
That is right. I just was searching something "good and easy-to-use" to be able to scale AVFoundation exported footage. And AVIR did the job ;)

**Comment by ilia3101** [comment]
> That is right. I just was searching something "good and easy-to-use" to be able to scale AVFoundation exported footage. I always liked the Apple colors more than the ffmpeg colors. And AVIR did the job ;)

The colours thing still confuses me, I'm gonna have to investigate. What is the difference like to you?

**Comment by masc4ii** [comment]
E.g. the shadows always seems to be a little brighter in ffmpeg than in MLVApp viewer, while with AVFoundation it looks correct to me. Saturated colors (green, yellow, orange, red) look more as I adjusted it in MLVApp when exporting with AVFoundation.

**Comment by ilia3101** [comment]
Are you viewing in apple quicktime player? I get this issue on all kinds of clips (not just MLV App exports), in VLC the issue goes away, also final cut doesn't seem to have the issue. I don't exactly remember if I've compared MLV App ffmpeg and AVFoundation directl. Gonna do that now.

Do you think what you experience could be this?

**Comment by masc4ii** [comment]
Partially I went crazy in FCPX, when I imported footage and thought "I must have been blind when grading in MLVApp! This is overexposed!". But yes, in Quicktime it was even worse.

**Comment by ilia3101** [comment]
Ok I just did a comparison, Quicktime showed ffmpeg as being very different, then I tried to compare in VLC, but VLC thinks it's smart not to allow multiple windows, so I could not compare easily.

In the end I managed to compare with IINA video player (https://iina.io/), it seems to not distort colour how quicktime does. I found that Anatanoli actually looks different in terms of colour. Argh!

But Kostya and AVFoundation look the same! No brightness difference, no hue shifts.

Interestingly, AVFoundation was sharper then both FFMpeg versions, however I was using 422, maybe it has a smarter way of downsampling to 422 than ffmpeg does. I am guessing prores 4444 detail should look the same in ffmpeg and apple.

I hate nothing more than colour management in the video world :(

**Comment by masc4ii** [comment]
What you also need, is the right clip for such a comparison. Sometimes I am very satisfied, sometimes I think WTF. It depends on the recorded colors...

**Comment by ilia3101** [comment]
I compared ProRes 4444 in kostya and ffpeg using Blender, which I trust to not do anything to the colour. And my conclusion is that ffmpeg export is slightly softer. It is like a mild denoise. I can't see any difference in colour, but after subtracting the images in blender node editor, it seems that ffmpeg is a tiny bit brighter overall, I think it's due to the smoothing/softness effect. Visually, colour looks the same, though it may be worth checking more clips.

Exported frame grabs from Blender:

|Kostya|AVFoundation|
| -- | -- |
|![vid_KOstya](https://user-images.githubusercontent.com/23642861/64606753-e1f9c400-d3be-11e9-80f4-17eb1c09ee1a.png)|![vid_AVFoundation](https://user-images.githubusercontent.com/23642861/64606765-eaea9580-d3be-11e9-83ca-5c38536473ff.png)|

Now screenshotted from quicktime:

|Kostya|AVFoundation|
| -- | -- |
|![fdsfsd](https://user-images.githubusercontent.com/23642861/64607014-867c0600-d3bf-11e9-9ef1-ed5ca14df274.png)|![asdf](https://user-images.githubusercontent.com/23642861/64607021-8aa82380-d3bf-11e9-8515-b9e21eff2238.png)|

I no longer trust ProRes as a format or. Going to compare it with high quality h.264, I suspect h264 may be better.

**Comment by masc4ii** [comment]
Did also some tests again. It seems I often used Anatanoli in past. And this makes brighter footage. Kostya and AVFoundation is indeed very close, but not identical. Some tones are a very little bit different.
Conclusion: don't use Anatanoli.

**Comment by ilia3101** [comment]
https://www.drastic.tv/index.php?option=com_content&view=article&id=202:prores-colour-shifts-in-post-production&catid=59&Itemid=94

This must be the issue, prores does actually have metadata on colour primaries, and either it's being set wrong or being read wrong somehwere.

Anyway, this isn't something we'll be able to test or fix easily. FFmpeg does not seem to very much about colour, yet implement some colour features to make everything unclear. Would prefer if it just had no colour conversions built in.

**Comment by masc4ii** [comment]
This might be the problem. Yes. Especially for Anatoli. If I remember right, Anatoli ignores those values, while Kostya doesn't.
`...-color_primaries bt709 -color_trc bt709 -colorspace bt709...`

**Comment by ilia3101** [comment]
Intetesting. Seems quicktime has more colour metadata than i ever thought.

**Comment by masc4ii** [comment]
Back to topic... do we need it for ffmpeg as well? Do we need all the old rescale algorithm options for ffmpeg?

**Comment by ilia3101** [comment]
If you can implement this for ffmpeg, I think it is completely fine to remove the old upscale options. No reason to use anything other than this.

**Comment by masc4ii** [comment]
Okay, can do this. 
The only reason for e.g. bilinear ffmpeg rescaling would be rendering speed... From quality side, I fully agree.

**Comment by ilia3101** [comment]
> The only reason for e.g. bilinear ffmpeg rescaling would be rendering speed... From quality side, I fully agree.

True, but if someone needs speed it's probably better for them simply not to upscale.

**Comment by masc4ii** [comment]
I especially thought on guys rendering quick proxies as first step. But in the end... AVIR is not so much slower. I'll rewrite this part of ffmpeg pipe soon.

**Comment by ilia3101** [comment]
Thank you very much!

**Comment by ilia3101** [comment]
https://github.com/ilia3101/MLV-App/commit/2c5b2921ff69803172bd00261c2b764c97a1bdae
