### ISSUE TITLE
MLVApp eats up all of my RAM + crashing

### ISSUE THREAD

**Issue by 8lacKy175** [ilia3101/MLV-App#182]
First of all, this is a really great tool for MLV files and it works like a charm for the most part. A big thanks to the contributors~
I am using the newest version of MLVApp, running on a 64bit Win10 system with 16 GBs of DDR3 RAM, a FX-8350 and a 1060.

So, here's my problem: When I export a video - the mlvs and export location are both located on my ssd system drive - MLVApp starts occupying more and more RAM as time goes on. Once it reaches ~13 GB and my RAM is on 98% workload, it just crashes / closes itself without any additional message or pop-up. This basically means that I can't export multiple files in a row without restarting the program after a while (it doesn't clear its cache after it's done) and any video that's longer than 45 seconds is outright impossible to export. Especially this 2nd issue is a big problem for me and I have no idea what to do here. ._.

This isn't normal behaviour, is it? Anything I didn't setup correctly or is this actually a new issue that hasn't occured yet? I will answer any question if further information is needed. Thank you in advance~

**Comment by masc4ii** [comment]
Thanks for the report. I think you use the latest official release? 
-> This is a known issue and was already fixed (hopefully). 
https://github.com/ilia3101/MLV-App/commit/9e17284b0a183f5b6badcc8261c3675463c08905
It should only happen, if you use the sharpen mask slider. If you need it, you could compile latest version, or wait for next official release.

**Comment by 8lacKy175** [comment]
Aaand that actually did the trick, wow. Thank you very much!

I also had to exclude both the MLVApp and ffmpeg processes from my antivirus software because it seemingly interfered with something. This actually fixed the issue for my 1st test export, but my 2nd one was still causing the same problem, because it had the mentioned Masking applied to it. Now it works perfectly, so thanks again.

Really looking forward to the future of this project! ;)
