### ISSUE TITLE
Resize bug latest commits.

### ISSUE THREAD

**Issue by cmhamiche** [ilia3101/MLV-App#185]
It's related to the latest commits: on an "anamorphic" shot, if the the resize box isn't ticked in the export settings, I get a shorter video which is a 3x3 mosaic of the shot.
![1](https://user-images.githubusercontent.com/32405217/66840367-3cf77b80-ef68-11e9-9b01-6e5076ba406e.jpg)
![2](https://user-images.githubusercontent.com/32405217/66840374-3ec13f00-ef68-11e9-8b74-020ec5a8be68.jpg)

Compiled the 15th of october on Windows 10.
This message was posted on the magic lantern forum but it's "awaiting approval by a moderator".

**Comment by masc4ii** [comment]
Thanks for testing and posting... I think I know where to search!

**Comment by cmhamiche** [comment]
AVIR stuff I guess...

**Comment by masc4ii** [comment]
It will have to do with upscaling/downscaling command, not with AVIR directly. Anamorphic footage is a special case here, and I expect a small mistake there.

**Comment by masc4ii** [comment]
I think I found and fixed it. Please try again!
https://github.com/ilia3101/MLV-App/commit/b4ba83ad8be92ab1075feb9c6f900410bb0ec93a

**Comment by cmhamiche** [comment]
I tried with and without the box ticked and it is fixed indeed.

**Comment by masc4ii** [comment]
Thanks for reporting and testing! 
So I'll close the issue. If there is more to do, feel free to reopen, or creating a new issue.
