### ISSUE TITLE
Original ML recording version missing in exported MLV VERS block

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#186]
quote a1ex:

While trying to identify the root cause of [these artifacts](https://www.magiclantern.fm/forum/index.php?topic=24553.0), I've noticed I'm unable to identify ML version used for the original recording. The sample clip shared there appears to be exported from MLV App, and this is the only VERS block I could find:

```
Block: VERS
  Offset: 0x0000023c
  Number: 8
    Size: 40
    Time: 18446744073709552.000000 ms
  String: 'MLV App version 1.9'
```

Normally, mlv_rec/mlv_lite are saving extended version info (multiple VERS blocks) about ML core version, alongside with info about modules loaded, including the version of each module.

Based on this, I'd say the preferred way to handle VERS blocks while transcoding is to add the app-specific block on top of existing ones.

**Comment by bouncyball-git** [comment]
Ah OK. Exported MLV has mlvapp version instead. I will add original ML version too...

**Comment by bouncyball-git** [comment]
Done, please test and report :) (MAPP mode also supported)

**Comment by masc4ii** [comment]
I posted it in the forum. Maybe a1ex can test - he found this... :)
Or can you tell me how I can test it?

**Comment by bouncyball-git** [comment]
:grin: 

mlv_dump -v file.mlv > info_before.txt: 
mlv_dump -v file.mlv > info_after.txt

With builds before last commit and after...

**Comment by masc4ii** [comment]
Hm... is there a difference? Or did I make something wrong?
Old:
```
Block: VERS
  Offset: 0x00000258
  Number: 8
    Size: 40
    Time: 18446744073709552.000000 ms
  String: 'MLV App version 1.8'
```

New:
```
Block: VERS
  Offset: 0x00000278
  Number: 9
    Size: 53
    Time: 18446744073709552.000000 ms
  String: 'Exported by MLV App version 1.10'
```

**Comment by masc4ii** [comment]
Ah... okay... all my MLVs don't have any VERS when coming from cam. Exporting the file twice brings (old) one VERS and (new) two VERS.

**Comment by bouncyball-git** [comment]
Yeah... To test this, MLVs must have the original VERS blocks from camera. Doesn't EOS M footage recorded by latest builds have them?

BTW you fount the issue, every other export from mlvapp will add one more VERS (exported from...). Not good - gonna correct it :)

**Comment by bouncyball-git** [comment]
Or... maybe I'm gonna leave it as is and just add the date:time of the export to trace the amount of exports and version of mlvapp. What do you think?

**Comment by masc4ii** [comment]
> Yeah... To test this, MLVs must have the original VERS blocks from camera. Doesn't EOS M footage recorded by latest builds have them?

Nope, EOSM doesn't record it and my 5D2 doesn't as well. 

I don't think it is bad to have the full file history.
