### ISSUE TITLE
I think there should be a BIG warning on smooth aliasing option, I see a lot of people are making their videos all smooth and smeary by accidentally keeping it enabled. It also causes slow exports.

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#187]

**Comment by masc4ii** [comment]
![Bildschirmfoto 2019-10-25 um 16 51 21](https://user-images.githubusercontent.com/30245296/67581123-c9afef80-f747-11e9-9ba5-b45622894730.png)
There is already this tool tip. But most people can't read. Maybe we should bring it as MessageBox::warning when selecting anything else than OFF?

**Comment by masc4ii** [comment]
Or would it be enough if all non-Off options get a yellow warning icon?

**Comment by masc4ii** [comment]
![Bildschirmfoto 2019-10-25 um 16 56 56](https://user-images.githubusercontent.com/30245296/67581556-7db17a80-f748-11e9-9aa0-c0b3681a6d51.png)

![Bildschirmfoto 2019-10-25 um 16 56 39](https://user-images.githubusercontent.com/30245296/67581564-81450180-f748-11e9-988c-74788d70841f.png)

**Comment by ilia3101** [comment]
I think the yellow sign is a good idea. I also think the tool tip should say not to use it on shots with a lot of movement.

**Comment by masc4ii** [comment]
Done.

**Comment by ilia3101** [comment]
Thank you!
