### ISSUE TITLE
MLV averaged frame export crash.

### ISSUE THREAD

**Issue by cmhamiche** [ilia3101/MLV-App#189]
MLV App might crash when exporting to MLV Averaged Frame on Windows 64.

**Comment by masc4ii** [comment]
Could you upload the file which makes MLVApp crashing? No problem here...

**Comment by masc4ii** [comment]
Alternatively: you installed Qt? Run it with debugger and tell me in which line it crashes.

**Comment by masc4ii** [comment]
And: important is: all frames MUST have the same resolution (just a note if they don't have, when creating a MLV before with different pictures).

**Comment by cmhamiche** [comment]
I've not installed the debugger, let me figure this out in the meantime I'll upload the mlv.
If i recall, it's prone to crashing in certain conditions, try those step:
Transcode a bunch of CR2s
Save (the mlv appears in session)
Select MLV Averaged Frame in Export settings
Export selected clips
Pick a location (rename it; because it's the same name as the previous mlv).
Frames has the same resolution (even tho it would be great to mention this somewhere in the forum).
I can't manage to make it crash right now.

**Comment by masc4ii** [comment]
This is what I did. But can't get it crashed.

**Comment by masc4ii** [comment]
I get it crashed, as written above: using raw frames of different cameras in one MLV.

**Comment by cmhamiche** [comment]
I can't make it crash right now but i'm using the exact same CR2s that when it crashed, those three photos were taken in burst. I'll come back to you once I reproduced it and upload the incriminating mlv. I'm trying to get gdp on msys2 right now.

**Comment by masc4ii** [comment]
If you use standard Qt, gdb should be installed already.

**Comment by cmhamiche** [comment]
It's not it's msys2's precompiled static qt for mingw64

**Comment by cmhamiche** [comment]
I'll also try with the previous non static build. Maybe that's the culprit.

**Comment by cmhamiche** [comment]
I've added gdb on the kit but it still throws "Unable to create a debugging engine." I'll figure this out later but you know what? It happens with the build that didn't included the last commit so I guess it's due to that typo. I'll update the forum post. Sorry for the inconvenience. You can close this bug I think.

**Comment by masc4ii** [comment]
Feel free to reopen, if you know more about! ;)
