### ISSUE TITLE
QtApp: Add DarkStyle

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#19]
Some weeks ago @ilia3101 and me, we were talking about adding a kind of DarkStyle as Qt style sheet. Now I found a good looking style sheet. It is not so nice as Ilias Cocoa App, but a lot closer as the Qt standard. I would make it choseable - Darkstyle or System Standard. It would also work on Linux and Windows and on OSX it would look like that (quick test):
![Picture](https://image.ibb.co/ing3tk/Bildschirmfoto.png)
I found the style sheet [here](https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle). They say MIT license. Is there a way to add it to our GPL3 project? What exacly do I have to do? Just adding the License file to the repos structure, or adding a string to the aboutbox, or... Can please anyone translate me the license to a english I understand? :-D

**Comment by ilia3101** [comment]
I'm no license expert, but I think the MIT license is much more permissive than GPL, so it probably doesn't overlap/disagree with the GPL, so we can just treat it as a GPL part of the project. I'm pretty sure.

Looks very tasty indeed 😋

**Comment by masc4ii** [comment]
Okay. I also added a backlink and copyright information to the source homepage in the aboutbox. Hope that is okay. [Commited here.](https://github.com/ilia3101/MLV-App/commit/0b0e14dc2cc0c71e79656e77b96b70919fcab165 )

**Comment by masc4ii** [comment]
There is still one problem: we need new Media-Player icons. When selecting DarkStyle, we have black icons on black background :-)
So if someone finds some nice and free icons, please post here!

**Comment by masc4ii** [comment]
Okay. Created my own icons with support from some free ones...
