### ISSUE TITLE
What is the chroma smooth algorithm for? And how does it work?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#196]
Never used it before, as it changed moire artifacts (without reducing them) and smeared details in a strange way. But recently I had a quite noisy portrait photo that I'd converted with raw2mlv, I tried out chroma smoothing, and 5x5 had an amazing noise reduction-ish effect (and I didn't notice issues with the detail, but it wasn't a particularly sharp photo).

What is the purpose of the chroma smoothing algorithm?

I am so confused by the source code, the comments are surprisingly unhelpful :)

**Comment by bouncyball-git** [comment]
Some kind of interpolation algo (a1ex's child) I could not comprehend and to be honest never interested in. CS is done for every bayer pixel of the raw image. 2x2-5x5 as you can guess it the area width it operates on.

When applied to some noise or pixel artifacts some (but somewhat blurry) good results can be achieved. However YMMV.

More info can be obtained from alex I think.

**Comment by ilia3101** [comment]
Thank you, I shall ask a1ex if I need any more info.
