### ISSUE TITLE
Can vertical stripes be turned on by defualt for the 5D3?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#198]

**Comment by masc4ii** [comment]
Yes, can be done. Easiest is to enable for all cameras. Defaults can be found in ReceiptSettings.cpp. 
If we want just to enable for 5D3, we have to parse on first open into session for camera type and decide for this option. 
But why should we do that? Not all 5D3 will need it (or will it?) and this feature is at the cost of CPU usage.

**Comment by bouncyball-git** [comment]
The best solution will be the ability to save default config

**Comment by ilia3101** [comment]
>  But why should we do that? Not all 5D3 will need it (or will it?) and this feature is at the cost of CPU usage.

I have been experiencing a significant amount of vertical stripes in all my 5D3 clips. And a couple of days ago I read a post by a1ex that confirmed that all 5D3s have this issue in video mode for some reason. Unfortunately I don't remember where that post is, but it is the reason I decided to open this issue. I don't think it's necessary for other cameras, unless some other models have this exact problem.

I am only suggesting this because I think it will significantly improve user experience for 5D3 people. It will make things "just work" easier.

**Comment by ilia3101** [comment]
> The best solution will be the ability to save default config

Definitely a good idea as well, but enabling stripes by default for 5D3 will reduce first-time user frustration.

**Comment by masc4ii** [comment]
Good to know. I'll see what I can do. 
Creating a user-default sounds easier than it is, because of some automation functions behind some parameters, which are not available from the GUI, after the parameter was set by opening.

**Comment by masc4ii** [comment]
Could you please try? For 5D3 it is enabled by default now.

**Comment by bouncyball-git** [comment]
> Creating a user-default sounds easier than it is, because of some automation functions behind some parameters, which are not available from the GUI, after the parameter was set by opening.

Yup I know. But this is really the best solution IMHO.

My 5D3 sometimes produces stripes in highlights but this rarely become a serious issue. So I use the feature very seldom.

@masc4ii could we save only those parameters which are not affected by any automation and available directly? Stripes feature is not affected. If any important parameters need to be exposed from the backend I'll provide them.

**Comment by masc4ii** [comment]
Yes, that would be possible... but who would understand that some values can be changed, and others can't? I think this is an all or nothing decision. I just don't know atm how to access "auto" for those features.

**Comment by masc4ii** [comment]
I have one idea: how would it be to select a MARXML (receipt) beeing the default setting? This would be really easy. We just need a menu somewhere, and can select a receipt or "none" (which is the apps default).

**Comment by bouncyball-git** [comment]
Cool!

**Comment by ilia3101** [comment]
> Could you please try? For 5D3 it is enabled by default now.

Thank you so much! It works.

> My 5D3 sometimes produces stripes in highlights but this rarely become a serious issue. So I use the feature very seldom.

Mine always seems to do it, and its even noticable in the midtones sometimes. Most daylight shots are affected, so I use stripe correction most of the time. But it's nowhere near as bad as my old 5D2 was.

**Comment by ilia3101** [comment]
> I have one idea: how would it be to select a MARXML (receipt) beeing the default setting? This would be really easy. We just need a menu somewhere, and can select a receipt or "none" (which is the apps default).

I like the sound of this. I would like to change my defaults a little.

**Comment by masc4ii** [comment]
Please test it... I implemented it for you. 
All "Auto-Set-On-Import" is overridden with a default receipt.

**Comment by ilia3101** [comment]
How do I set the default??

**Comment by ilia3101** [comment]
Ah ok sorted. I was just confused because it showed a tick even though I hadn't selected a default file the first time.

**Comment by ilia3101** [comment]
I think we can close this issue.

**Comment by bouncyball-git** [comment]
Can we revert the vertical stripes setting for 5D3 back ;)

**Comment by masc4ii** [comment]
Let's keep it: if there comes a new 5D3 user, who doesn't know about this, it will feel better for him/her.

**Comment by ilia3101** [comment]
I agree with masc.

An analogy: With Linux, a lot of computers have screen tearing issues in the default configuration. These computers are like the 5D3s of the computer world. And fixing these issues normally requires editing some file to enable double buffering or something like that. Why isn't it fixed by default!!?? I remember having so much frustration from these issues. Now I only use computers with intel graphics for Linux.

Yes, enabling stripes in mlv app is easier then editing an nvidia settings file, but both should be done automatically.

**Comment by bouncyball-git** [comment]
OKey guys 2vs1 so I surrender :grin:

**Comment by bouncyball-git** [comment]
@masc4ii 

Enhancement:
1. when no clips are loaded and one tries to save receipt mlvapp crashes. I think In that case "Export Receipt" have to be grayed out.
2. in Linux, extension .marxml is not appended by default (remember while ago you corrected this behavior for .masxml)
3. would be very handy if "Receipt Mask Setup" dialog would appear when saving default.marxml receipt. To not save setting which messes up color look for all clips. Personally I would save only RAW Correction setting nothing more.

**Comment by masc4ii** [comment]
1. Really? Here on OSX (and how I implemented it), not the receipt of the selected clip, but the receipt of the currently shown clip will be exported. It should not crash - that is bad. See MainWindow::on_actionExportReceipt_triggered()
2. okay... that is also bad. But I could check for the ending and append it in this case.
3. A receipt always includes all parameters. The mask is applied on import/paste. But you could just use the App default, make your changes, export and set this.

**Comment by masc4ii** [comment]
2. should be fixed. 
1. Could you please use the debugger and tell me where it crashes? Have no idea when reviewing the code...

**Comment by bouncyball-git** [comment]
1. Where is "receipt of the currently shown clip"? I mean when mlvapp just started and nothing was imported yet?
2. Thanks!
3. I thought almost all parameters have default value like "-1" (or similar) to recognize that there's nothing to be changed. Am I wrong?

**Comment by masc4ii** [comment]
1. oaaaah... how good can it be to be able to read?! I should learn that. Sorry. Will fix.
3. Only automated parameters are "-1". You can have a look in ReceiptSettings.cpp. You could manually manipulate your receipt in a editor in this way too... ;)

**Comment by ilia3101** [comment]
How is "normal" and "force" different in vertical stripes? Can't tell the difference.

**Comment by bouncyball-git** [comment]
> How is "normal" and "force" different in vertical stripes? Can't tell the difference.

Usually you can't ;)

normal - calculates stripes for 1st frame only (If 1st frame has no strong pronounced stripes then bad calc will propagate to the entire clip)
force - for every frame. (All frames get good treatment, slow!!!)

Someone requested this on forum long time ago for mlv_dump and I implemented it. Then this feature find it'sway to  mlvdump.

**Comment by bouncyball-git** [comment]
@masc4ii 

1. thanks now crash can not be the case.
2. hm... got it. would be great to have -1 (or whatever default mening) for every parameter to skip it when needed.

**Comment by bouncyball-git** [comment]
Small bug report

When "Use default receipt" selected in menu and file dialog opened if you do not select any .marxml and just press cancel "Use default receipt" appears checked anyway which is confusing. Receipt mot loaded and used but menu shows it is used. (checked)

**Comment by masc4ii** [comment]
Thanks. Yes. Correct. I first thought about that, but then forgot to implement it. 😄

**Comment by masc4ii** [comment]
Fixed: https://github.com/ilia3101/MLV-App/commit/aa39d8d9f8630b878bfe75f5afb263cfcda7b5e3
