### ISSUE TITLE
Overwrite hint on export wrong for all sequences

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#199]
When exporting a sequence, the frames will be saved into a folder. If a file with such folders name exist and has the ending of those frames, MVLApp will warn, that the file will be overwritten. That is wrong.
E.g.: 
1. a file test.dng exists.
2. export a test.mlv clip as dng into the same folder, where the test.dng is located
3. MLVApp brings the warning

**Comment by bouncyball-git** [comment]
Is that only for DNG or other image formats (tiff, etc) also affected?

**Comment by masc4ii** [comment]
All: png, jpg, tiff, dng. Have it nearly solved...

**Comment by masc4ii** [comment]
https://github.com/ilia3101/MLV-App/commit/d2c74861d4b1c7d08c71c4616af613123f4d2efb
