### ISSUE TITLE
Why not allow float values of black level?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#201]
2047 is too magenta looking on 5D3, 2048 is too green. Values like 2047.5 should be allowed I think.

**Comment by masc4ii** [comment]
Haha, I've always the same problem, especially with the M. 
If that works from processing side... let's try it!

**Comment by ilia3101** [comment]
Ah yes, will check if processing can handle that.

**Comment by masc4ii** [comment]
There were two different areas, where black level had importance (RAW Corrections and later in processing somewhere). It is absolutely necessary to handle both the same way, or it will lead to problems. Or we get a new idea to make it better.

**Comment by ilia3101** [comment]
What about:

User can input a float value, for example 2047.5

Raw corrections get the black level as an integer (rounded down to 2047)

Processing gets the float value.

This way, raw corrections can work the same way as before.

**Comment by masc4ii** [comment]
We could try what happens ;)

**Comment by bouncyball-git** [comment]
Interesting approach. Worth trying?

**Comment by masc4ii** [comment]
Why not... I am on the GUI! 😉

**Comment by masc4ii** [comment]
The GUI part. https://github.com/ilia3101/MLV-App/commit/54dec986fa614d64e6ae6d56cd8e9234d43ef4e5
For now, x.0 .. x.9 brings the same picture 😄

**Comment by masc4ii** [comment]
Hej Ilia, please try out: https://github.com/ilia3101/MLV-App/commit/7504752082ef08364c25f58c9423a58fea24a859
I think this does the job...
