### ISSUE TITLE
Wrong profile applied on multiple export

### ISSUE THREAD

**Issue by cmhamiche** [ilia3101/MLV-App#205]
Sorry, nvm you can close it. It's a receipt copy and paste problem. I have to individually select clips.

**Comment by masc4ii** [comment]
Could you please explain what was going on? You should be able to copy the current or the selected receipt and paste to all selected clips at once.

**Comment by cmhamiche** [comment]
Okay, if I have multiple clips selected before copying a receipt it doesn't work. Since I had to do a lot recept copy pasting and only realized it after export I though it was export related but it's not.
Since it might not an issue on Mac, let me demo that in a video real quick so we 100% understand each others.

**Comment by cmhamiche** [comment]
https://youtu.be/d11Ab2hw1wM

**Comment by masc4ii** [comment]
That is correct. You see it when pressing "Copy" (or Ctrl+C), that the mask dialog does not show up. Which of multiple receipts should be the one you want to copy? --> Action blocked. This is the same on all OS.

**Comment by masc4ii** [comment]
Message commited.

**Comment by ilia3101** [comment]
I've definitely encountered this issue before

**Comment by ilia3101** [comment]
Maybe it was different to this. But the description sounds similar... Need to replicate it again.

**Comment by masc4ii** [comment]
Please report if you know how to reproduce!

**Comment by ilia3101** [comment]
I can't find this. I think it must be an old issue, I vaguely remember fixing it. Some function call was forgotten somewhere in processing. I think it's safe to close.
