### ISSUE TITLE
Selecting Dual ISO clips only

### ISSUE THREAD

**Issue by Jip-Hop** [ilia3101/MLV-App#209]
I experimented with Dual ISO recording. Some takes with Dual ISO, and then a take without Dual ISO to compare the results later. Now I've got a bunch of clips of which some are non Dual ISO. When loading all clips in MLVApp, Dual ISO is disabled for all clips by default. Turning on Dual ISO for a clip (which was recorded in Dual ISO mode) and then pasting the receipt from that clip on all clips will force Dual ISO on for all clips, including for clips which weren't recorded in Dual ISO mode.

Is there a way to select (filter) the clips which are Dual ISO, so I can apply the setting to only those clips? Or maybe it could just not force apply the Dual ISO to non Dual ISO footage when pasting the receipt?

Adding sortable details (fps, Dual ISO, resolution, anamorphic mode, bit depth etc.) in the Session list could help in this case too, similar to the Media Pool in DaVinci Resolve.

<img width="400" alt="Screenshot 2020-08-12 at 12 05 03" src="https://user-images.githubusercontent.com/2871973/90003309-2f984400-dc94-11ea-9e19-0152e8a68a14.png">

Right now it's rather tedious to manually select each clip and check if Dual ISO should be on or off.

**Comment by Jip-Hop** [comment]
I've commented this line:
https://github.com/ilia3101/MLV-App/blob/1629971dcd914e7eaefedc84b46481852217a4b8/platform/qt/MainWindow.cpp#L4549

When pasting the receipt it will still set Dual ISO to On for all clips, but it won't Force Dual ISO for the non Dual ISO clips.

I think it's exporting properly but still 12 hours remaining before I can properly check xD

**Comment by masc4ii** [comment]
Unfortunaltely there is no way to select DualISO automatically. What I could imagine: go through your clips and mark the clips (green/yellow/red). After this, a selection of clips of the same color is very easy. 
Since a very long time I am dreaming of a kind of session table, which shows all metadata (like in information dialog) in a big table. Unfortunately I still have no good idea yet howto integrate this into the existing GUI. 
I would like to have it in the left sidebar (sidebar becomes larger (wider) for showing the info). But this would not work for the option "session at bottom". 
Another idea would be to exchange the viewer with such a table... but then we have two lists exactly side by side. Would be stupid. 
Or, we could create a new Dialog which shows such a table. A selection could work the same way as with the FCPXML Dialogs.
Another problem: we don't have the info to be shown without loading each clip completely. So filling such a table needs much much time for bigger projects or clips. "Fast import" is no longer available (it could be available only with empty table).

With your commented line: if you have more than one old dual iso clip in your session (which all needs forcing), it will be impossible to copy the dual iso setting from one to another clip.

**Comment by Jip-Hop** [comment]
I'm dreaming about that too :)

But why is it impossible to select all Dual ISO files? MLV App already clearly distinguishes in the GUI between a regular clip and a Dual ISO clip: only the non Dual ISO clips have the "force button". So MLV App identifies Dual ISO files. I think it would already help a lot if there was a menu option to select all Dual ISO files. This doesn't apply to the legacy Dual ISO files, which I understand from your comment always need manual checking and forcing Dual ISO.

Maybe something like: "Select all Dual ISO clips (except legacy Dual ISO)"

Would that be doable?

**Comment by masc4ii** [comment]
Atm MLVApp just has the metadata of the currently active clip. To get the metadata, a clip must be opened. This makes the App slow (at least one time for parsing all this information).

**Comment by Jip-Hop** [comment]
I see. Less trivial than I thought. Each time I load my MLV files in the app, it loads them one by one (rather slowly). So I thought it might already be parsing this information for each clip.

**Comment by masc4ii** [comment]
This what you call "rather slowly" is the fast import, where we don't get most of the metadata. We would need the "real slow" import to get them. However... we also could use the fast import and create a kind of "load all metadata" button, which can be used if needed. After a file was fully loaded, we could somehow hold the information in some data structure, maybe also in the masxml. So for this I have some idea in mind already. The bigger problem is: how to integrate it in a visually nice way?!

**Comment by Jip-Hop** [comment]
Whoops this is already the fast import! Hahah. What are MAPP files used for? Tried a few times but didn't noticed any benefits + it was really time consuming. Do those files hold all the Metadata?

Visually nice way... Yeah I think it should be a table in the left sidebar. I don't see why it wouldn't work for the session at the bottom... In desktop file explorers you often have the option to toggle between "big thumbnail" view and a "detailed list" view. So you'll only be looking at the table when you're actually looking for this info.

Another options would be akin to "Apple Cover Flow" or "DaVinci Resolve Filmstrip" view:

![526FE598-4AB3-4310-8922-50F7230BFA33](https://user-images.githubusercontent.com/2871973/90175938-8000c600-dda8-11ea-9d2c-8ed162d22ba8.png)

Which combine detailed lists with a thumbnail row on top.

I don't think another window would be the best option, but it's another option too. Some kind of "Media pool" tab or window...

**Comment by masc4ii** [comment]
If MAPP is enabled, all indexes in the MLV are saved into the MAPP. Using the MAPP it is way faster to load a file, especially big files, or files from slow HDD devices.

The selection for the session list view brings me to an idea... what about a 5th setting "table". Maybe the bottom view is good, because we have the full width - much space to show all settings.

**Comment by Jip-Hop** [comment]
Thanks for the explanation and great idea, sounds perfect!

By the way I'd prefer this Metadata to be stored in a separate file for each clip, much like the MAPP files, and not just within a session xml save file. I often check out clips in MLV App without actually saving the session afterwards. Maybe the MAPP file could be 'extended' for this usage?

**Comment by masc4ii** [comment]
Far away from working... but maybe what we are searching for?
![Bildschirmfoto 2020-08-13 um 22 16 40](https://user-images.githubusercontent.com/30245296/90182745-bb07f700-ddb2-11ea-8c46-3409017908e6.png)

**Comment by Jip-Hop** [comment]
Exciting! Looks really good! Love it when things move so quickly :) One piece of info that's still missing in my opinion is if it's Dual ISO or not XD And maybe a column to indicate if it's recorded in anamorphic mode? I can see it from the resolution mostly, but still there are anamorphic modes with different resolutions, or perhaps 'false positives' if someone actually record in a resolution that is much taller than wide without it actually being recorded in anamorphic mode.

**Comment by Jip-Hop** [comment]
Super cool progress!

**Comment by masc4ii** [comment]
>One piece of info that's still missing in my opinion is if it's Dual ISO or not...

...but you can see the scrollbar at the bottom... 😄

**Comment by Jip-Hop** [comment]
You can do it 👍

**Comment by masc4ii** [comment]
I'll have to change the complete internal data structure. The current organization is way too limited for this table mode. So it will take some time to work through the 10000 lines of the main class. 😨 
I plan to create a spezialized model concept which holds all clip metadata and additionally all the receipt data. Advantage of this model is: we can have multiple different views (tables, lists, ...) on one single set of data. 
Currently we would have to hold the data as often as we have tables / lists - additionally to this we have to synchronize all the data of these elements.

**Comment by masc4ii** [comment]
It maybe was the biggest change I ever did for MLVApp. But here is a very first alpha: https://github.com/ilia3101/MLV-App/commit/1d92246b3986446431d26d5de128e94aa52fd73d

Please test carefully. You won't need much time to find bugs. Please report them. 

Biggest problem is having 5 different data representations for one session. It is possible to convert between them, but it is tricky. 

There is one single model holding the data (m_pModel). There is a Proxy, which is able to sort the session to any metadata (m_pProxyModel). There is a selection model, which allows to select and which gives information about selection (m_pSelectionModel). There is a list, which shows the list mode, and there is a table, which shows the table. I need a break now. 😄 

![Bildschirmfoto 2020-08-29 um 18 32 53](https://user-images.githubusercontent.com/30245296/91641768-0b27c000-ea27-11ea-9c55-84de8034a656.png)

**Comment by Jip-Hop** [comment]
I like where this is going! :) Having all this info and being able to sort the clips based on it it super useful. With regards to easy Dual ISO selecting I was thinking maybe you could make it say: "Dual ISO, 100/1600". So first "Dual ISO" and then the actual ISO value, instead of the other way around. At least then, when sorting on ISO value, all Dual ISO clips are grouped together. 

Cool there's even a tiny thumbnail in the table!

Would it be possible to make MLV App fully load the clips upon import?

I quickly played with it, unfortunately can't test extensively. Didn't find any obvious bugs yet, but the app crashed on me once, see log attached.

Enjoy the break 😄 

[mlvapp_crash_log.log](https://github.com/ilia3101/MLV-App/files/5147096/mlvapp_crash_log.log)

**Comment by masc4ii** [comment]
Thanks for the log. You did a rightclick on the table, and then some Qt classes were the last log entries... no idea what this could be. Of you get it reproduced, please try with debugger enabled.

Yes, I first also thought to realize it as you say. Then I saw the existing information looks like how it is now, and I was not sure to change it. But I could do this, I think.

Loading on import... on importing the clips: no; on importing a saved session, yes - but with a different MASXML realization. I also thought to build an action for the table right click menu: "load all metadata". And I would like to have another rightclick option for the list: sort by name, aperture,... and so on. Now you can change the sorting by table only, but the list is affected. There is still much to do...

**Comment by masc4ii** [comment]
Update:
![Bildschirmfoto 2020-08-31 um 20 12 43](https://user-images.githubusercontent.com/30245296/91753388-1d8d2f80-ebc8-11ea-9a39-dfe4852ce1bd.png)
