### ISSUE TITLE
Fedora 32 - problem 

### ISSUE THREAD

**Issue by voglovas** [ilia3101/MLV-App#211]
Hello,
I'm linux (Fedora 32) user.
I have downloaded Appimage, and made permission for executing (chmod a+x...) but nothings happened when i tried to start application. 
When I try over terminal i get this - ./MLV.App.v1.11.Linux.x86_64.AppImage: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory
I have installed libnsl, but nothing has changed

Any advise?

**Comment by masc4ii** [comment]
Is Fedora 32 a 32bit system? The AppImage is 64bit. You could install Qt5.x, download sources and compile from source.
