### ISSUE TITLE
Trying to debug/reproduce a problem where mlvapp hangs approx 50% through an export

### ISSUE THREAD

**Issue by simowilso** [ilia3101/MLV-App#213]
I've spent the whole day trying to install qt. Almost got there but I've failed at (I hope) the final hurdle. "Cannot find winrtrunner.exe in "C:\qt\5.15.1\mingw81_64\bin"

Any pointers? Any simpler way to investigate why the export is hanging?

TIA

/Simon

**Comment by masc4ii** [comment]
Thank you for your time and that you want to help find bugs! I really appreciate that. I never had this problem and I tested very hard to get it. Best is always to debug such bugs on a computer which has this problem...

Unfortunatelly I don't know about winrtrunner, and I don't know why this should be needed. You just should need Qt with mingw64 compiler and gdb debugger, if you want to debug. Normally this installs out of the box with some single (3 or 4) checkboxes in the Qt online install menu. The latest Qt version I tried on Windows was 5.13.1.

**Comment by simowilso** [comment]
It looks like winrtrunner was included in earlier releases of qt https://doc.qt.io/qt-5/winrt-support.html but it's not in the latest one. It took forever to install qt, but maybe I should try again. with an older version.

**Comment by masc4ii** [comment]
It looks WinRT is part of MSVC. MLVApp won't compile with MSVC compiler. You need MinGW, and MinGW is not compatible with MSVC. Maybe this was a checkbox too much in the installer?

**Comment by simowilso** [comment]
Hmm. I removed any reference to MSVC in the installer, still same result :(
![image](https://user-images.githubusercontent.com/15340247/95024858-a2fb7800-067d-11eb-9dab-0bc187bb14d4.png)

**Comment by simowilso** [comment]
Yeeees! Managed to get it to run. Waiting to see if it hangs right now...

**Comment by simowilso** [comment]
...and it doesn't reproduce :( Export worked just fine. How strange.

**Comment by masc4ii** [comment]
Okaaaay... so you now know how I feel?! 😄 You just could try to install the same Qt version we used (see the info menu --> about Qt). Maybe it is a Qt bug which is solved already.

**Comment by simowilso** [comment]
Yes I will try that tomorrow, thanks!

**Comment by simowilso** [comment]
Well I'm stumped. I tried multiple times to export the clip I had with mlvapp 1.11 downloaded from here and each time the app froze. I finally got a debug version running in qt, then realised I didn't have ffmpeg installed. (Tip for doing this - when you install qt, only select the MinGW version you need as above and nothing else).  I installed ffmpeg and added its location to the Windows path and ran again. The same clip exported without any issue. Then I went back to the release build and it ran the export without locking up. Very strange.

**Comment by masc4ii** [comment]
Did you test the latest commit from the repos or the sources from official 1.11 release page?

**Comment by simowilso** [comment]
It was the 1.11 release
