### ISSUE TITLE
Website codebase mentioning

### ISSUE THREAD

**Issue by davvore33** [ilia3101/MLV-App#217]
Hi guys,
I'm not sure if you manage also the website [mpv.app](mpv.app) but in case you should mention this codebase in the website as well

I'm not meaning to make a fuss about this but it wasn't so easy for me to get here from the website itself, I'm a developer and I was thinking to make a package for the OS I'm using/supporting right now (Arch-linux) and as me maybe other people would enjoy to get here in an easy way either to browse the code or also to contribute,
thanks for your help

**Comment by ilia3101** [comment]
Yes I created the page [mlv.app](mlv.app)

Clicking the title of the release takes you to GitHub, but I agree that's not really enough. The webpage needs more work. Right now it's just a simple downloads page.

**Comment by ilia3101** [comment]
Fixed: https://github.com/MLVApp/MLVApp.github.io/commit/704370003ca743276dac4f84c4a1c561ce80face
