### ISSUE TITLE
File export codec CinemaDNG Uncompressed does not take into account profile (Alexa Log-C for exemple)

### ISSUE THREAD

**Issue by hamanohashidate** [ilia3101/MLV-App#219]
Hello,

if you chose File export codec CinemaDNG Uncompressed it does not take into account profile (Alexa Log-C for exemple).

It looks like that always the same profile is choosen automaticaly tonemapping function to "Reinhard" and Processing Gamut to "Rec. 709". Despite I changed it ...

I can choose different profile and always the same dng was export /develop.

The dng developed/exported are not "flat". 

also if I change the sharpen it does not affect the export in CinemaDNG

If the answer is that when you choose CinemaDNG the export do not take into account a profile, the result is not logical because the dng developped in this case should be flat like a raw image / not already graded/tuned (my suspicision is that the grading chosen automaticaly by the app is Reinhard / Rec. 709 the default when you open the app) ...

If I choose codec Apple ProRes 4444 the export is good with the correct profile that I choosen before and I can have a "flat" image/picture.

I will prefer to use DNG as I work under resolve ...

If someone can help me to fix that.

Thank you

**Comment by masc4ii** [comment]
Hi,
see wiki: https://github.com/ilia3101/MLV-App/wiki#export-settings
"CinemaDNG export only contains RAW Correction parameters and CutIn&CutOut applied. All other parameters from edit area don't affect the exported file."

DNG is RAW, so none of all the processing features will be applied. It is the task of whatever application you import the DNG files. There is no flat or alexa or whatever - it is RAW data.

**Comment by hamanohashidate** [comment]
Hello,

Ok . I tried to open it before with picassa to compare also and I saw that picture was not flat ... so it's picassa treatment ok...

so you confirm it's raw. 

I will try to have what I want in resolve ok thanks.
