### ISSUE TITLE
We need a new processing

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#220]
I want to create a new processing module in MLV App. I feel like processing code is now too messy to change anything fundamental. I have coded myself in to a corner. Anytime I try to do something, I end up stuck in some dead-end.

Some new things I want to do:
- Instead of  per-channel "tonemapping", it will use a perceptual colour space for highlight desaturation and roll-off.
- New saturation/curve algorithms using perceptual colour spaces, create same effect but without any hue shifts or artifacts.
- All colour artifacts will be gone completely, so changing the white balance slider will no longer cause any cyan artifacts etc..
- Better highlight reconstruction, no green bands

I have written processing code that does all of this, I am going to publish it on here after some cleaning up.

It will be much cleaner and easier to implement new features in this new module.

@masc4ii Would is be possible to implement a switch in the GUI between Old and New processing? As the new module would have slightly different adjustments, and less at the start.

**Comment by masc4ii** [comment]
Cool! Sounds great! You create a branch for that? (Would be good.) Sure - let's try that. When you're ready, I need to know what options can be setup in what processing.

v1.12 is on the way (bouncyball will compile Win64 version soon). 1.12 is already tagged. So we can start whenever you like.

**Comment by masc4ii** [comment]
@ilia3101 how about your progress? The examples you put into ML forum look nice already! :)

**Comment by bouncyball-git** [comment]
@ilia3101 

Please, PLEASE upload your new code to experiment with :D

**Comment by ilia3101** [comment]
> @ilia3101 how about your progress? The examples you put into ML forum look nice already! :)

Thanks, progress has been quite slow :) But I have started Easter break at university, so I have more time for a couple more weeks.

I have added boilerplate processing code: https://github.com/ilia3101/MLV-App/commit/468caa37e98bf6647aeb08daecd9af823649e1c9 https://github.com/ilia3101/MLV-App/commit/00b4ca5bc766f6e9b0b625ecb5e3634832aaefb1 @masc4ii Do you think you could try and link it up with the interface in some way?

I am thinking of using a 3D LUT for some of the processing, so that we can apply the old processing module to the 3D LUT, to keep the effects we already implemented, like hue adjustments and film filters, while the New processing will handle the first part of converting the raw (exposure/whitebalance/contrast/highlights/shadows/saturation).

**Comment by ilia3101** [comment]
Processing pipeline will be

## PRE PROCESSING (nothing to change)
1. raw corrections
2. Debayer
## PROCESSING (new)
1. (Rawtherapee library) highlight reconstruction etc...
2. Convert linear HDR Raw to SDR using new processing (expo/WB/highlight/shadow/saturation/contrast/tonamepping/gamut mapping all in this stage)
3. Apply a 3D LUT to use allow some of the old processing features (hue effects/film filters) - maybe in AlexaRGB or ProPhoto or ACES AP1 space (mainly something large)
4. Final colour space conversion, with some gamut mapping perhaps.

**Comment by DeafEyeJedi** [comment]
Holy shit Ilia... such a inspiration coming from Masc for sure! :)

**Comment by masc4ii** [comment]
@ilia3101 : thank you! So I can start thinking about now! We'll see, how a switch between old and new processing could look like.

@DeafEyeJedi : that all comes from Ilia. ;) And I am very excited about it.

**Comment by masc4ii** [comment]
@ilia3101 : Did you also already built a wrapper for rawtherapee library? If not: we could merge the master into this branch. (No idea if you tried out latest master commit.)

**Comment by ilia3101** [comment]
I haven't used the rawtherapee library yet, I only found out it exists from conversations here. I'm sure wrapping it won't be too hard. Is the API simple enough?

**Comment by masc4ii** [comment]
The API is simple, yes. Have a look into latest master. Most difficult should be to understand the meaning of the parameters clmax and chmax - and the input should be what they expect. Using the debayers was not too hard.

**Comment by ilia3101** [comment]
I'm thining one of those two is white level for the channels, as for the other not sure yet.

**Comment by ilia3101** [comment]
Might be able to insert a switch on the Old processing object, to use new processing internally, and combine it with old processing, also internally. Will be crazy, some parameters will not work, but API will be simpler from GUI side.

**Comment by masc4ii** [comment]
@ilia3101 : sry, I did not yet start any development... not much time these days. 
It sounds good, when thinking from GUI side. On the other way I am not sure if it is good, because after switching the engine, I'll have to send all parameters again. For now, I just do this with openMlv(..). So it could be, that this is even more difficult to realize (--> sending all parametes in the correct order). What about a function, which is able to switch the engine without a overall initialization? Is that possible?

**Comment by ilia3101** [comment]
Actually, I think it will be possible to switch without initialising the
whole processing object again like you want, but it will probably use more
memory that way, as both old and new processing will exist in a full way,
but this should be not difficult to solve. I will try and have a first
version ready by today. Just exposure and not much more will work.

**Comment by masc4ii** [comment]
@ilia3101 Do you have plans to integrate the new processing into something like "getMlvProcessedFrame16" function? Just to get the debayered frame into the new processing pipeline...

**Comment by bouncyball-git** [comment]
Hey guys!

Any updates to this topic?

**Comment by masc4ii** [comment]
Unfortunatelly not on my side. Atm I just have very little free time, so I am/was waiting for Ilia's reply.

**Comment by masc4ii** [comment]
@bouncyball-git If you like we could release all the other new features / updates. I prepared the release description, if you want to have a look.

**Comment by bouncyball-git** [comment]
Sure! I already saw draft 1.13.
