### ISSUE TITLE
Unable to use focus pixel maps on Linux

### ISSUE THREAD

**Issue by Wintch** [ilia3101/MLV-App#225]
Hi! Using MLV.App.v1.12.Linux.x86_64.AppImage on debian 10 i am unable to load any of the .fpm files, that i got from MLV.App.v1.12.Win32.
On windows i don't need any additional steps to fix pink focus points, just to load my videos.

Thanks!

**Comment by masc4ii** [comment]
An appimage is a readonly archive. Saving any data into this can't work. For using pixelmaps on linux, you have to install/unpack MLVApp. All is explained in the manual/wiki: https://github.com/ilia3101/MLV-App/wiki#fix-focus-dots

**Comment by Wintch** [comment]
> All is explained in the manual/wiki: https://github.com/ilia3101/MLV-App/wiki#fix-focus-dots

Thanks! Worked just great! Still, i don't get why windows version has this *.fpm files, and linux version is not.

**Comment by Wintch** [comment]
linux version could have *.fpm files included, but the feature is working after following steps in wiki (no need to copy ffmpeg or raw2mlv executables though)

**Comment by masc4ii** [comment]
Nice to hear it worked. You can delete all fpm or keep it. If you need it, or there is a newer fpm file online, it will be downloaded again automatically.
