### ISSUE TITLE
QtApp: Create color wheels

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#23]
Some time ago @ilia3101  was asking me, if I could create some color wheels (radial hue vs sat). This should be possible using QPainter. Additionally user interaction has to be handled (MouseClick & Drag on picker).

**Comment by bouncyball-git** [comment]
Cool!

@ilia3101 
Do you have some color code to share? BTW at least we need simple white balance picker with mouse.

**Comment by masc4ii** [comment]
White balance picker in that way - clicking on the picture and autosetup would be cool. But this would be another enhancement. Here the topic are the radial hue vs. sat controller. Shall I add another enhancement for that (is it possible to calculate the whitebalance for a pixel (x,y)?

**Comment by ilia3101** [comment]
Ah yes, white balance picker is a good idea that we need, I don't have any colour code to share yet, but that's one of the original ideas for the app, so that's something I've planned on since the start.
I definitely want to have some nice colour effects that can be applied after the main processing.

**Comment by masc4ii** [comment]
Okay. Created another issue (#26) for the topic wb picker. Here we can discuss about the colour wheels.

**Comment by bouncyball-git** [comment]
I this still on schedule?

**Comment by masc4ii** [comment]
In principle - yes. But before PLEASE lets fill whitebalance picker and/or gradient with live! :-D

**Comment by masc4ii** [comment]
If whitebalance picker works one day, I can commit this (at least if you like it):
![colorwheel](https://user-images.githubusercontent.com/30245296/36019083-6bbd6c04-0d7e-11e8-892f-0a682aabd935.png)

**Comment by masc4ii** [comment]
Do you like?!
<img width="579" alt="bildschirmfoto" src="https://user-images.githubusercontent.com/30245296/36044259-5c16f53c-0dd2-11e8-897e-d0f36614650c.png">

**Comment by bouncyball-git** [comment]
Very cool! :)

Love that familiar knob in the center ;)

**Comment by masc4ii** [comment]
Hehe, right. I just need a transformation from R,G,B to X,Y and opposite now. Is that a kind of normalized equation of the vectorscope transformation? (Vectorscope has 6 edges, here it is a circle) Do you know how to calculate?

**Comment by bouncyball-git** [comment]
Nope sorry :), I have not dig into colors yet. If I knew this stuff like I know MLV/DNG internals the WB picker would be working long time ago (I did revive that picker in my test build for RAW color balancing some while ago and it worked, in RGB I have not done anything before).

BTW, the one thing I'm not satisfied in MLV app is the colors it produces, well it is really lot better then I can achieve in 'mlvproducer' but I can not get the vivid colors that ACR of Resolve can deliver.

White balancing should take into consideration the camera matrixes and it will be better. I could do this but have no time ATM, I know how to do the conversion from kelvin/green to multipliers but not vice versa ;), picker indeed needs opposite calculation to set kelvin and tint for our sliders.

**Comment by masc4ii** [comment]
> I'm not satisfied in MLV app is the colors it produces
Really? I am very satisfied with the colors! For me it works better than Resolve or ACR, that's why I only use MLVApp since AMaZE is working the right way. Also demosaic is way better than in Resolve or ACR (I always have very bad artefacts here). Only one thing is better in Resolve and ACR: there is less noise.

**Comment by bouncyball-git** [comment]
Yeah noise is another story. Demosaic is great! after Ilia added doWB/undoWB into amaze code itself. But colors really need work. I think you are satisfied because now mlvapp uses 5D2 specific approach to color (matrixes) by default ;). But I need 5D3 and other camera matrixes to be considered too. Not only for color space conversion but also when WB is calculated. This is really large theme for me ATM of I would dig into OpenColorIO already.

**Comment by masc4ii** [comment]
Ah okay... that may be the reason, when it uses 5D2 color matrixes by default. It is possible to integrate that for other cams too? Does someone know the right values?

**Comment by bouncyball-git** [comment]
Those values already inserted into every DNG header ;)

Look at those 2 files written by me :) [Link](https://github.com/ilia3101/MLV-App/tree/master/src/mlv/camid)

**Comment by masc4ii** [comment]
Ilia wrote this file camera_matrices.c in mlv folder. Is that the same or can it work together somehow?

**Comment by bouncyball-git** [comment]
Yes I know we already discussed this with Ilia once I added camera_id lib
Matrixes can be removed from 'camera_matrices.c' and used from camera_id lib.

**Comment by masc4ii** [comment]
Okay... but now back to the right topic... (lets make another issue for matrices if necessary)

The colorwheels... There is no space in the GUI to make them in a horizontal row. Should we create another groupbox in the right with 3 or 4 of the colorwheels in a vertical row?

**Comment by bouncyball-git** [comment]
Probably :). I never thought about it. The wheels are so big and I think will be very precise.

**Comment by masc4ii** [comment]
If you like to try it out: elements commited. Comment out last line in `initGui()`

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-02-10 um 13 53 42](https://user-images.githubusercontent.com/30245296/36062299-ef35af42-0e69-11e8-9a7f-1c462917aba9.png)

**Comment by bouncyball-git** [comment]
Looks very cool! :-D

**Comment by ilia3101** [comment]
Are HSL controls good enough to forget this for now?

BTW masc those controls you made are beautiful!

**Comment by masc4ii** [comment]
Thx. I would say they are different. But in the end I am happy as it is for now. So we could close here if you like. I have no idea how to realize the processing for this.
