### ISSUE TITLE
Fix focus dots not working when exporting in CinemaDNG

### ISSUE THREAD

**Issue by orfeas-a** [ilia3101/MLV-App#231]
For some reason MLVApp bypasses the fix focus dots option when exporting in cDNG uncompressed/lossless. This can be fixed by enabling 3x3 chroma smooth but i noticed that the focus dots become visible if you lower the highlights and check highlight reconstruction. Is this a known issue?
Camera: Canon 650D
MLVApp version: MLV.App.v1.13.Win64.static
OS: Windows 10 64-bit

**Comment by masc4ii** [comment]
MLVApp doesn't fix focus dots for "cDNG fast pass", and all other RAW corrections as well. That is a speed feature. If 3x3 chroma smooth works, fix focus dots will work, too. If fix focus dots works in the MLVApp viewer, it also will work for the export. You can choose between 3 different methods to fix focus dots - they all look different. Maybe the features you use in your processing software can't handle the information you created with your MLVApp settings...

**Comment by orfeas-a** [comment]
That's the problem, i export in cDNG uncompressed or lossless (not fast pass) and while the focus dots are not present in the viewer or in H264/ProRes exports they are in the DNGs. If i enable chroma smooth or any other raw correction it is applied but not fix focus dots. I have used Photoshop's Camera Raw and Davinci Resolve to view the DNGs and i get the same result.

**Comment by masc4ii** [comment]
The RAW processing engine is always identical - you get always the same RAW base. So the problem will be the processing of ACR or Resolve which isn't really made for this. I just can recommend trying between the other methods in fix focus dots area.

**Comment by orfeas-a** [comment]
Ok, i will try the other methods thanks for the help.

**Comment by masc4ii** [comment]
@bouncyball-git : any idea to fix this?

**Comment by masc4ii** [comment]
I think I found the bug and fixed it e35171bac9a215b323ca0a5cb2fabb3a8c685e7e
Reason is, that the pixel fix only works, when one single frame of the clip was processed first - kind of init. Fix is to render one frame fully in background when exporting cdng clips.

Please test.

**Comment by orfeas-a** [comment]
That's great thanks for looking into it! I will test it later in the day when i have time.

**Comment by orfeas-a** [comment]
Tested, works great. Nice work, bug fixed!

**Comment by masc4ii** [comment]
Thank you!

**Comment by DeafEyeJedi** [comment]
Great catch, @orfeas-a!
