### ISSUE TITLE
Deleting active video from session messes up other video properties

### ISSUE THREAD

**Issue by vastunghia** [ilia3101/MLV-App#233]
To replicate issue:

1. open new session
2. import 3 MLV files
3. double click on 2nd video
4. set "Cut Out" to 2 (or whatever property to whatever value you like)
5. right click on active video (2nd video) and select "Delete Selected File from Session"
6. confirm "Remove"

You will see that the 3rd video, having become the active one, is inheriting 2nd video properties ("Cut Out" = 2).

**What's worse:** even if you skip step 4 (no edit at all for video 2), you will end up having video 3 with "Cut Out" = full length of video 2 (that could be shorter than full length of video 3).

Very annoying. Took me a long time to understand why some of my exported cDNG's were shorter than due.

Thank you!

Sergio

**Comment by masc4ii** [comment]
Thank you for pointing this out. I am able to reproduce the bad behavior. Now "just" someone has to fix it... ;)

**Comment by masc4ii** [comment]
Please test commit https://github.com/ilia3101/MLV-App/commit/ffb12189ff1a79155598b4425b0c968be904275f

**Comment by vastunghia** [comment]
Commit [aec844a](https://github.com/ilia3101/MLV-App/commit/aec844ac22ba8c67b9bce7e4226b40de060dd9f8) tested, confirm bug solved. Thank you!

**Comment by masc4ii** [comment]
Thank you!
