### ISSUE TITLE
Do not leave behined orphaned files when removing MLV file from disk

### ISSUE THREAD

**Issue by vastunghia** [ilia3101/MLV-App#234]
Would be great if all MLV files (that is: .M00, .M01, .M02 etc, along with .MLV and .MAPP) were deleted from disk when "Remove from disk" is selected.

I use card spanning so I always end up with .M00 orphaned files. Removing them manually is a pain in the neck. Also, for long shots the 4 GB limit is reached and I end up having even .M01 or even .M02 files as well.

Thank you!

S

**Comment by masc4ii** [comment]
Thanks for reporting. Please try this: 85a4ff7efd7249d8f379de628ff93962f85d5db4
Does this work for you?

**Comment by vastunghia** [comment]
Tested. Works like a charm. Solved, thank you!
