### ISSUE TITLE
Urgent help please!! ProRes 4444 exports incompatible with M1 Pro

### ISSUE THREAD

**Issue by HOSKINGJ** [ilia3101/MLV-App#237]
Firstly, I've never posted on GitHub before so apologies for any faux pas.

I've successfully used MLV App to export MLV files from my 5D MK II to ProRes 4444, which I then could use without issue in Finder, Premiere etc on my Intel MacBook pro. These files also playback without issue on my iPad and iPhone.

However, on my M1 MacBook Pro:

- Thumbnails don't show a preview in Finder, they just have the QT player icon
- Opening them in QuickTime, they play with sound but the video is just black
- Opening a "Get info" window within Finder, scrubbing through the little preview window works
- The files playback fine in VLC
- They won't load in Premiere which just brings up errors when I load them
- Re-exporting in different versions of MLV App's ProRes 4444 codec hasn't made a difference

I've spent hours with Apple technical support and they refuse to escalate it to their engineers until "the creators of the application clarify if it has been designed to work on M1 processors".

Please help! Thanks so much.

**Comment by masc4ii** [comment]
More information needed:
- what MLVApp version was used? M1 version? Intel version? Version number? Self-compiled?
- What ProRes4444 encoder was used? There are three different in MLVApp.

MLVApp is "designed to work on M1 processors".

**Comment by HOSKINGJ** [comment]
Thanks so much for responding.

- Files were created with intel version 1.12
- Also tried exporting with M1 version 1.13 - no luck
- Downloaded the DMG from here - [https://mlv.app]
- I used the ffmpeg Kostya codec originally, but when re-exporting I've had no luck with any of them

**Comment by masc4ii** [comment]
Using MLVApp v1.13 Intel or ARM version, ProRes4444 Kostya export, 
looks like that in Finder here:
<img width="894" alt="Bildschirmfoto 2021-12-22 um 20 23 45" src="https://user-images.githubusercontent.com/30245296/147144905-83c28a2a-25c1-4f21-ad3c-47c01c276e74.png">
And loads in Quicktime:
<img width="1552" alt="Bildschirmfoto 2021-12-22 um 20 26 14" src="https://user-images.githubusercontent.com/30245296/147145031-fa05565f-6253-4217-ad5e-2b33d75dec5e.png">
I can't test Premiere, because I don't have it. Opening e.g. in Handbrake works fine.
Tested on BigSur 11.6.1, MacBookAir M1, 16GB RAM, 1TB, 8C-GPU.

You could also try my experimental ARM64 version: https://www.dropbox.com/s/ej6ufca61ijeeyf/MLV.App.v1.13.macOS.arm64.zip?dl=0

**Comment by HOSKINGJ** [comment]
Thanks so much for that, good to see. Unfortunately I had the same result with the experimental build.

To help isolate things, would it be possible for me to test with your MLV file? Here is the file I've been testing with - [https://www.dropbox.com/s/tlce3slngehwkfu/M12-1853.MLV?dl=0](url)

**Comment by masc4ii** [comment]
Hm... can't see a problem. Processed with Kostya ProRes4444.
<img width="1032" alt="Bildschirmfoto 2021-12-23 um 18 01 39" src="https://user-images.githubusercontent.com/30245296/147271400-87064ddd-82f8-43b7-bcee-f896ab16d50a.png">
<img width="1552" alt="Bildschirmfoto 2021-12-23 um 18 01 56" src="https://user-images.githubusercontent.com/30245296/147271409-8c5e54de-95ab-4a99-a86b-4c10a48ea5e9.png">

**Comment by masc4ii** [comment]
You could try with this: https://www.dropbox.com/s/p2j112gyph5ywzu/ElgersburgBHF.zip?dl=0

**Comment by HOSKINGJ** [comment]
Thank you so much. Bizarre, same issue even with the file you supplied. I'm on Monterey (12.0.1) rather than Big Sur which I guess is a difference to note.

Struggling to work this one out. Will go back to Apple but if there's anything else anyone thinks of that'd be great. Thanks again.

**Comment by masc4ii** [comment]
Did you install the Apple Pro Codecs? 
https://support.apple.com/kb/DL2050

**Comment by HOSKINGJ** [comment]
I thought I had but re-installed anyway and no joy.

Please could you provide your successfully exported ProRes 4444 file?

**Comment by masc4ii** [comment]
Sorry, I deleted the clip days ago and have very bad internet here... I uploaded 3 secs downscaled 4444 clip (needed 3hours from here). Please try with that: https://www.dropbox.com/s/8n6ehg4jryqdam7/M05-0921a.mov?dl=0

**Comment by HOSKINGJ** [comment]
No worries and thank you so much. Interestingly I have exactly the same problem. So strange...
