### ISSUE TITLE
Issue when export location is short on storage

### ISSUE THREAD

**Issue by fusionwalls** [ilia3101/MLV-App#238]
Hey Guy's, I've run into an issue this morning, When storage space is low MLVAPP export completes but the resulting file is missing some parameters (XMP) and cannot be imported into Premiere pro.
I wonder if it would be possible to add a warning to advise users of this rather than "export complete"
Happy to provide further info just tell me what you need!

Many Thanks
Fusi

**Comment by masc4ii** [comment]
Thanks for your report.
MLVApp doesn't write the files to disk, so this should be hard to approve. ffmpeg writes the data to disk and we don't get its info into MLVApp atm. Maybe some sort of cyclic disk space checking could improve that...

**Comment by masc4ii** [comment]
Please test https://github.com/ilia3101/MLV-App/commit/a3cf725a9d8d6cfab28df80cd4f859b8b577830b
