### ISSUE TITLE
Updated Amaze code solves some issues

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#24]
As you know dualiso part is almost finished. There is a bug in amaze interpolation mode (@masc4ii knows what I'm talking about) I solved this problem with substitution of latest 'amaze_demozaic_RT.c' from a1ex. It took some time but now it works and the bug is disappeared. I had some very old footage from 60D which had artifacts with existing amaze lib and those debayering artifacts also disappeared. Speed is good and I'm almost happy :)

Now, I want to share the source with you to test with mac and windows before we decide to commit these changes to the repo.

@ilia3101, @masc4ii 
Please download [Modified Source](http://nic.caucasus.net/mlvapp/?dir=&download=mlvapp_with_new_amaze.tar.gz) and test thoroughly. Then we decide what to do :)

**Comment by masc4ii** [comment]
There are indeed big differences between the 2 versions. See here:
![Picture](https://image.ibb.co/cNm46G/Bildschirmfoto.png)
Left: the old version, Right: the new version.
The old one has much less problems with moiree (all these cyan and magenta pixels and lines). Is this expected? Is there another possibility to avoid that?

**Comment by bouncyball-git** [comment]
Indeed my 5D3 raw is a bit sharper with newer version. Aliasing is more pronounced on other camera videos i have (5D3 looks good to me though). What do you think @ilia3101?

Regarding another possibility, I think before we start filtering image there is a possibility to tweak this amaze lib itself, sadly there is no very useful comments in it.

**Comment by ilia3101** [comment]
So this solves a bug, but what is the bug? sorry haven't watched this closely enough.

Does this only affect dual ISO or have you put the new amaze in place of the old one?

If this only affects dual ISO, then I don't really mind which way it goes as I don't use it personally.

**Comment by ilia3101** [comment]
Oh has this finally fixed the pink shadow bug!!?!?!?!?

I have an inclination towards the new one now. You guys make the final decision, but I think this might be good. Especially if we are able to edit the AMaZE source (but thats likely an impossible dream).

**Comment by masc4ii** [comment]
Did another test: again - no "real error" - but still ugly artefacts at high contrast edges. Does anybody know, why the old version is better here as the new one? Or is something else missing? Is the same code used in MLVFS? Then I should compare the results...
Look at the boat (the white in front of the motor) and the white areas in the water.
![Picture](https://image.ibb.co/ipZG3w/Bildschirmfoto.png)

**Comment by masc4ii** [comment]
@ilia3101 : it does not only affect dualIso, also the "normal" debayering.

**Comment by masc4ii** [comment]
Dual ISO files are looking MUCH better than before!

**Comment by bouncyball-git** [comment]
Yes it affects all because we can not (and should not) link the same library twice ;). MLVFS uses the same lib modded by a1ex in 2014 for dual iso and debayered preview (b&w gifs). Pink artifacts are gone on some my old footage from 60D and dual iso is good.

**Comment by bouncyball-git** [comment]
@masc4ii yes :( colored aliasing is ugly on this picture.

**Comment by bouncyball-git** [comment]
I was experimenting with both amaze variants and new one has more pronounced cyan artifacts on the contrasty edges for sure, but older one also produces plenty of them. Exported PNGs have less those artifacts though but even older amaze is FAR worse then darktable/rawtherapee produced images (dt/rt settings: all processing off, amaze demosaic). Eather they're using farther modded version of amaze or filtering the image after demosaicing. I'm sad :(

**Comment by bouncyball-git** [comment]
I also changing some parameters in the code of amaze tile size, etc... but never got desired effect except of core dumping because of floating point exception :P

**Comment by ilia3101** [comment]
I think we should switch to the new one, even with all the cyan edges, as that's mostly a colour bug, so it can be filtered out by chroma filtering easily most likely (?)

Does MLVProducer have better debayering then?

I was working on a thing a couple of months ago, trying to train this [basic neural network library](https://github.com/codeplea/genann) on some simulated line skipped vs binned images to possibly create a filter for bayer data(kind of thing that could be packaged in to llrawproc), but the code was lost (hard drive fail). Maybe I should have another shot at that, as it is something I really care about: artifacts on my(and others) camera can be horrendous.

**Comment by masc4ii** [comment]
Yes, I also think for now we should switch to the new one, even if I am a bit sad about the artefacts. But fixing all the bugs is also important.
@bouncyball-git : I had a look and compared our amaze file with the one from darktable. The base was the same a long time ago (the file header comment is nearly identical)... now they have 1000 lines more and the interface is different to ours. But maybe it is not impossible to adapt that. But that is a lot work just for checking if something changes :(
@ilia3101 : chroma smoothing does not change anything for me. The only thing what helps me is using Resolve and creating a kind of chroma blur with some nodes (I don't understand why this looks so different to our chroma smooth). As you also own a 5D2: do you have other tips and tricks?

**Comment by ilia3101** [comment]
`chroma smoothing does not change anything for me`
That works on bayer data so won't always help with what artifacts amaze causes afterwards.
`Resolve and creating a kind of chroma blur with some nodes`
Yep, that's what I meant, a chroma blur filter that happens after the debayering. I used to do this technique in after effects, creating an adjustment layer with blur and setting it to colour blend mode, then masking out where it's not needed.
Maybe we can have our own type of chroma blur/smooth specifically for moire.

**Comment by bouncyball-git** [comment]
> _But that is a lot of work just for checking if something changes :(_

Yes exactly. 

Ilia is right chroma smoothing applied before amaze so there is no effect on amaze produced artifacts. Needed antialias filter after debayer.

@ilia3101 here is the darktabe git: [https://github.com/darktable-org/darktable](https://github.com/darktable-org/darktable)

**Comment by bouncyball-git** [comment]
Anyway I'm also on updating amaze. May I make commit with those changes?

**Comment by ilia3101** [comment]
Of course, commit it!

**Comment by bouncyball-git** [comment]
ok

**Comment by ilia3101** [comment]
Also has there been any changes by you to the MLV library in the last couple of weeks? (excluding llrawproc), if so, when were the last changes?

**Comment by bouncyball-git** [comment]
0c5ed50 this is the commit with latest change of 'video_mlv.c'

**Comment by masc4ii** [comment]
The new code is commited. Can we close?

**Comment by ilia3101** [comment]
I have another question before we end this, what about RawTherapee source: https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/amaze_demosaic_RT.cc

It is **the original** amaze, and looks way more understandable than Darktable source, what do you guys think? maybe we could simply wrap it in C then it will be easy to switch out the `amaze_demosaic_RT.cc` file whenever RawTherapee makes a change.

Or is there more to it than I think?

**Comment by bouncyball-git** [comment]
Absolutly,  we must try this :) - latest modification: Ingo Weyrich, January 25, 2016

**Comment by ilia3101** [comment]
I did an experimental implementation of newest RT amaze, and difference is small, however if fixes a few darkened pixel bugs in highlights, here's a difference image:
![screen shot 2017-10-08 at 17 26 23](https://user-images.githubusercontent.com/23642861/31318671-f8c25bec-ac4d-11e7-9bed-7089523e8823.png)
(normal side by side comparison would look too identical)

**Comment by ilia3101** [comment]
Here's modified src/debayer if y'all want to test:
[debayer.zip](https://github.com/ilia3101/MLV-App/files/1367026/debayer.zip)
yes, it is now .cc extension, as it uses a lot of c++ things and I couldn't be bothered to try and change that all to C.

**Comment by masc4ii** [comment]
Good job @ilia3101 ! I would add the latest Amaze to the repos. But also for me, the difference is ... I don't see a difference! :-)

**Comment by ilia3101** [comment]
Thanks for testing, we'll see if bouncyball says anything different, then we may finally close the issue :)

**Comment by bouncyball-git** [comment]
I don't see any difference in regard of aliasing either :)
Although it does not produce artifacts during amaze-edge interpolation of dual iso I noticed it's a bit slower.

**Comment by ilia3101** [comment]
So we can conclude it's slower and gives the same image?
I honestly expected it to be faster as there were some issues on RT's github with "20% speedups".
Let's keep the old one then, closing the issue.
