### ISSUE TITLE
MLV App gets in to infinite loop of dialogs when encountering empty files.

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#241]
Try opening this file **at the same time as opening other files** (selecting a few in finder, and opening all at once), I don't know why I have files like this but I'm finding them in various places:

[M02-1622.MLV.zip](https://github.com/ilia3101/MLV-App/files/8445025/M02-1622.MLV.zip)

I think this bug also happens when a file gets deleted or moved on disk but is still in the session and you try to click on it again in the session.

Probably the same control flow issue causes all these infinite loops?

**Comment by masc4ii** [comment]
For me there is no infinite loop. 
1. MLVApp tells the file has no frames.
2. MLApp asks to remove the file from session (remove, delete, abort)
3. When removing or deleting the problem is gone. When aborting: MLVApp tells again once "no frames" when trying to load the file. You can remove the file manually.

**Comment by ilia3101** [comment]
Did you try opening it along with another file?

Here, I select two files, one is this one, the other a random other file, and try to open them both at the same time:

https://user-images.githubusercontent.com/23642861/162452365-8deab69f-9e73-42fd-81c3-1c87676282b0.mov

I'm using MLV App 1.13 official release for macos.

**Comment by masc4ii** [comment]
Okay. I see. The problem comes to life with minimum 2 invalid clips. It happens in MainWindow.cpp:

```
int MainWindow::showFileInEditor(int row)
{
    if( SESSION_CLIP_COUNT <= 0 ) return 1;

    //Stop Playback
    ui->actionPlay->setChecked( false );
    //Save slider receipt
    if( !ACTIVE_RECEIPT->wasNeverLoaded() && !m_inClipDeleteProcess ) setReceipt( ACTIVE_RECEIPT );
    //Save new position in session
    int oldActive = SESSION_ACTIVE_CLIP_ROW;
    SET_ACTIVE_CLIP_IDX( row );
    //Open new MLV
    if( openMlv( GET_CLIP( row )->getPath() ) )
    {
        //If one file is selected, reselect the last one, else do nothing (export)
        //And if there is another file we can switch to...
        if( selectedClipsList().count() <= 1
         && SESSION_CLIP_COUNT > 1)
        {
            m_pSelectionModel->setCurrentIndex( m_pProxyModel->mapFromSource( m_pModel->index( oldActive, 0, QModelIndex() ) ), QItemSelectionModel::ClearAndSelect );
            showFileInEditor( oldActive );
        }
        return 1;
    }
```

oldActive should be loaded by showFileInEditor function and becomes recursive, if a 2nd file is also invalid.

**Comment by masc4ii** [comment]
Could you try this please? 5c6a87cb49bb49d83bba1be28851831d7ea7865d

**Comment by ilia3101** [comment]
Thanks for the fix, will try this out. Reporting back soon.

**Comment by ilia3101** [comment]
Can confirm, no more infinte loop. The window appears a couple of times.

**Comment by ilia3101** [comment]
I think this can be closed, as my core issue is fixed.
