### ISSUE TITLE
Very simple processing improvement.

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#245]
I'm working on a very small and simple processing improvement. This is basically going to be like our "fix cyan highlights" or "uncolourscience fix", but on steroids. It will fix most of the ugly skews and clipping. A trick from @Sobotka . Will be commited today.

@masc4ii Will you be able to add a small checkbox somewhere in the profiles section? And _please_ make it be enabled by default. This is going to be such an upgrade for handling things like colourful LEDs and sunsets. It will be a bit less "colourful" by default, but please try to appreciate the upgrade!

Examples (before on the left, after on the right):
![Screenshot 2022-07-01 at 14 57 57](https://user-images.githubusercontent.com/23642861/176909906-5ed74f39-76c2-493d-8697-1696119f6267.jpg)
![Screenshot 2022-07-01 at 14 57 31](https://user-images.githubusercontent.com/23642861/176909899-61545559-dd06-4469-a8a8-21eb3228e7d2.jpg)
![Screenshot 2022-07-01 at 14 59 00](https://user-images.githubusercontent.com/23642861/176909919-9ac71de5-9ed1-427e-91dc-ed836d93fc86.jpg)

So smooth!!!!!

(I also see an opportunity for making the pipeline fully floating point and less clippy, but this will come later)

@sobotka Can we call this "AgX" in the UI?

**Comment by masc4ii** [comment]
Sure. I'll do this. Is there any dependency to other features? Or just a On/Off checkbox, which always works?

**Comment by ilia3101** [comment]
Yeah, just an on off checkbox that always works.

**Comment by masc4ii** [comment]
Good. I'll do this soon. I found a small bug with it: linear gradient looks wrong:
<img width="1552" alt="Bildschirmfoto 2022-07-01 um 18 21 07" src="https://user-images.githubusercontent.com/30245296/176933221-d99b5e70-d2d7-477a-b6e1-963c2ceb7bbf.png">

**Comment by ilia3101** [comment]
Will look in to this.

**Comment by masc4ii** [comment]
It goes away when linear gradient is disabled. For agx I'll have to create the checkbox first.

**Comment by masc4ii** [comment]
When switching camera matrix off, linear gradient works as expected, with AgX.

**Comment by masc4ii** [comment]
Yeah. Fixed. Try out!

**Comment by ilia3101** [comment]
Thank you!!!

You did it before I even looked!

**Comment by ilia3101** [comment]
Are we ready for a 1.14 release yet?

**Comment by masc4ii** [comment]
The update is great. Thank you Ilia. It looks so much better!
Before:
<img width="456" alt="before" src="https://user-images.githubusercontent.com/30245296/176952106-06a40131-29f4-460b-8d08-80805576cc16.png">
After:
<img width="457" alt="after" src="https://user-images.githubusercontent.com/30245296/176952163-68a2ef2a-a777-4e8b-ace3-8bce81b8bf13.png">

**Comment by masc4ii** [comment]
> Are we ready for a 1.14 release yet?

We could release, if you like. How do we describe AgX? Maybe we should add this in new features section for the update.

**Comment by ilia3101** [comment]
That's a great improvement. Nice medical robot too 😉

> We could release, if you like.

I'ts about time, it's been over a year now :)

> How do we describe AgX? Maybe we should add this in new features section for the update.

How about "Improved reproduction of saturated colours, with less clipping and smoother tonality. Especially helpful for shooting under RGB LEDs."

**Comment by masc4ii** [comment]
Ok! :)

**Comment by masc4ii** [comment]
@bouncyball-git : ready for a little comnpile session for Win build?
2x macOS and Linux is ready and uploaded.

**Comment by ilia3101** [comment]
@bouncyball-git

**Comment by 2blackbar** [comment]
This is great , ill recompile again.
Ilia would it be possible to add functionality to raw2mlv that would include sound in MLV file if theres WAV file in folder with dngs ? So recrodings from other cameras like blackmagic , sigma pf or smarpthones RAW could be imported into mlvapp with sound ? Its currently a bit tedious work to merge sound with all clips one by one after export from mlvapp.
Being able to choose multiple folders with dngs at once would help too but i should probably create new topic here for that.

**Comment by bouncyball-git** [comment]
Better later then never :). Static build uploaded.

**Comment by bouncyball-git** [comment]
Very cool impovement! Congrats!

**Comment by bouncyball-git** [comment]
https://mlv.app/ needs update?

**Comment by masc4ii** [comment]
Ah cool... thx! Now we have dynamic & static builds. The webpage should automatically be updated, as soon we release. It is still a draft...

**Comment by ilia3101** [comment]
What else do we need to add?
