### ISSUE TITLE
Export Current Frame PNG Freezes program

### ISSUE THREAD

**Issue by gabriielangel** [ilia3101/MLV-App#247]
MLV App Version:  1.13 and 1.14
OSX 10.13.6

When exporting Current frame from an MLV, it works on the first and sometimes second trial, but any subsequent trial will make the app freeze and it needs to be forced quit and sometimes the computer needs to be restarted for the app to open again.

MLV App Version 1.14

Exporting a PNG or TIFF sequence creates a folder for the export, but no PNG or TIFF are exported, even though the program says that the export was complete

**Comment by masc4ii** [comment]
Already solved. Please try latest commit.

**Comment by gabriielangel** [comment]
Hello, for the 2nd issue, (Exporting a PNG or TIFF sequence creates a folder for the export, but no PNG or TIFF are exported);

Are you sure you updated the OSX Version? I just installed from this link, and the issue remains:  https://github.com/ilia3101/MLV-App/releases/download/QTv1.14/MLV.App.v1.14.macOS-Intel.dmg

Thanks!

**Comment by masc4ii** [comment]
You used the official release, known to have the bug. Compile latest revision and test this please. There the bug is fixed - see history log messages.
