### ISSUE TITLE
Encoder ffmpeg missing in application path.

### ISSUE THREAD

**Issue by Ivanotchsky** [ilia3101/MLV-App#249]
QTv1.14

Everytime I attempt to export selected ml raw clips - whether that be one or multiple at a time - that error messages pops up.

managed to export one clip but haven't managed to do any others no matter the adjustments if none at all and retried to export originally successful clip to no avail.

 (export settings - h.264 at either high or medium ffmpeg .mp4)

**Comment by masc4ii** [comment]
Hi,
- What (exact) version are you using?
- What OS do you use?
- Have you checked, if ffmpeg is located in MLVApp application path (same path as MLVApp executable)?
- Have you checked e.g. your antivirus, blocking the tunnel between MLVApp and ffmpeg?

**Comment by peterslany** [comment]
Hello @masc4ii, I am running into the same issue with v1.14, I have these files (containing ffmpeg in name) in the application path, am I missing something please?
```
$ ls -R | grep ffmpeg

ffmpegWrapper.h
ffmpeg-4.4-amd64-static
ffmpegLinux.tar.xz
ffmpegOSX.zip
ffmpegWin32.zip
ffmpegWin64.zip
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static:
ffmpeg
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static/manpages:
ffmpeg-all.txt
ffmpeg-bitstream-filters.txt
ffmpeg-codecs.txt
ffmpeg-devices.txt
ffmpeg-filters.txt
ffmpeg-formats.txt
ffmpeg-protocols.txt
ffmpeg-resampler.txt
ffmpeg-scaler.txt
ffmpeg-utils.txt
ffmpeg.txt
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static/model:
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static/model/other_models:
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static/model/vmaf_4k_rb_v0.6.2:
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static/model/vmaf_b_v0.6.3:
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static/model/vmaf_rb_v0.6.2:
./platform/qt/FFmpeg/ffmpeg-4.4-amd64-static/model/vmaf_rb_v0.6.3:
```

**Comment by masc4ii** [comment]
Please read this for focus pixels and appimage: https://github.com/ilia3101/MLV-App/wiki#fix-focus-dots

You must not download ffmpeg. It is included in the repo you already downloaded, for x86_64 at least. Just unzip, if Qt does not do this automatically on deployment.

**Comment by peterslany** [comment]
> You must not download ffmpeg. It is included in the repo you already downloaded, for x86_64 at least. Just unzip, if Qt does not do this automatically on deployment.

I tried unzipping it, but it didn't work because I did not know it has to be placed in the `platform/qt` directory. I think the Qt haven't placed it in the correct location after unzipping too.

**Comment by masc4ii** [comment]
Place it into the application path (path where MLVApp.exe is located). platform/qt is not correct - no idea why this shall work for you.

**Comment by peterslany** [comment]
In my case the `mlvapp` executable (no .exe since I'm on linux) is located in the `platform/qt` directory probably because I built and installed it in there - according to the steps in the guide. That's why it works I guess : )

**Comment by masc4ii** [comment]
If you install the executable to this path, then yes, ffmpeg has to be in exactly this path too.
