### ISSUE TITLE
Warn people about FFMPEg anti aliasing.

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#251]
@masc4ii I've seen a few cases of people ruining their footage using the FFMPeg antialiasing, maybe we need some kind of warning dialog? I appreciate the warning icons, but people still make the mistake!

It could pop up either of these two points:
- After selecting the option
- When beginning export, allowing the user to cancel and change the settings, or continue with warning

I don't mind how, whatever is easier to implement I guess. No hurry. Just wanted to open an issue to not forget so we don't forget.

**Comment by masc4ii** [comment]
https://github.com/ilia3101/MLV-App/commit/9250687012cc03e8c79766ec080fdf904c8de4c2
Like this?

**Comment by ilia3101** [comment]
This is perfect thank you!
