### ISSUE TITLE
Width Stretch Transformation

### ISSUE THREAD

**Issue by EpicBigPPgamer69** [ilia3101/MLV-App#254]
My current build of magic lantern allows for an anamorphic desqueeze of 1.25, 1.33, 1.4, 1.5, 1.66 and 1.8x
The version of MLV app i have only allows for a width transformation of 1.33, 1.5, 1.75, 1.8 and 2x
is there any way of creating a custom width stretch in MLV app?

**Comment by masc4ii** [comment]
MLVApp offers the settings for most common anamorphic lenses. What factor has your lens? ML won't stretch recorded footage. So there is no real need to support the values you wrote. ML just needs 1.0x or 3.0x (= 0.33 vertically).

**Comment by EpicBigPPgamer69** [comment]
mine is a x1.66

**Comment by masc4ii** [comment]
Please test:
923ae211efdefb766258e8f9d9be69b79217c660

**Comment by masc4ii** [comment]
You got a test result?
