### ISSUE TITLE
please also for CinemaDNG

### ISSUE THREAD

**Issue by Automatisator100** [ilia3101/MLV-App#255]
What a great app!

Something like this would be perfect for CinemaDNG!  CDNG-App :)
Can you redesign the app to import CinemaDNG video files directly instead of just MLV?

**Comment by masc4ii** [comment]
MLVApp works for MLV only. But you can use "Transcode & Import" feature for getting cDNG files into MLVApp.

**Comment by Automatisator100** [comment]
Thank you very much!
