### ISSUE TITLE
cant export CinemaDNG - "Disk full" but it's not

### ISSUE THREAD

**Issue by tatrapikao** [ilia3101/MLV-App#256]
Hi,
when i try to export a file as CinemaDNG it aborts with the error message "Disk Full". But There is plenty of space. After aborting i find a folder with an empty (completely transparent) DNG File and the corresponding audio file. exporting as Proress works fine. What am i missing? Version is 1.14. I'm on Ubuntu 22.04.

**Comment by masc4ii** [comment]
MLVApp uses a Qt function for checking disk space:
`QStorageInfo disk = QStorageInfo( QFileInfo( path ).path() );`
This function is used in identical way in CDNG and in ProRes export. You get the "Disk full" Messagebox, if the function returns <= 20MB.
If you like, you could try to debug by uncommenting the "qDebug..." line in "void MainWindow::checkDiskFull(QString path)".

**Comment by masc4ii** [comment]
For DNG export the test pointed into AppArchive by error. Fixed:
d1ed3efcabe27853e0f06f0ac741b4d1ccf4bb32

**Comment by omygolly** [comment]
I get the same error on Lubuntu 22 with 1.14 when I try to export CinemaDNG. Works fine in 1.13.

**Comment by masc4ii** [comment]
Please test the fix.
