### ISSUE TITLE
Resize (not responding)

### ISSUE THREAD

**Issue by gpapaioa** [ilia3101/MLV-App#257]
Sometimes when I enable resizing while exporting, the app freezes. Happens randomly and usually when I batch export a few files

Windows 10

**Comment by masc4ii** [comment]
What version do you use? All 3 available? It absolutely never happens when resizing is disabled?

**Comment by gpapaioa** [comment]
Started with 1.13. Then I tried 1.12 with no luck. Just happened with 1.14 too. I never got the freeze when resizing is disabled. I just tick the resize on the export settings (gears icon), before exporting.

**Comment by masc4ii** [comment]
All 3 Win 1.14 versions?

**Comment by gpapaioa** [comment]
I am only using **static**

**Comment by masc4ii** [comment]
Please also try the other versions. The static version is crosscompiled from Linux.

**Comment by masc4ii** [comment]
Btw... what about all other export settings? Could you screenshot your setting please?

**Comment by gpapaioa** [comment]
![2022-08-24 00_26_12-Window](https://user-images.githubusercontent.com/39616815/186270325-ca6ed53e-77b6-4cdd-a076-1a9a7d0350a8.png)

**Comment by gpapaioa** [comment]
I am going to work with the **dynamic** version and let you know

**Comment by gpapaioa** [comment]
Just had another freeze with 1.14 dynamic 64 version.
![2022-08-25 13_43_50-Window](https://user-images.githubusercontent.com/39616815/186645637-3b3eff19-7fd3-4c0c-b921-8ce3b8da3b09.png)

I disabled resizing and exported it normally. Since its happening on random .mlv files, I think it might be a corrupt .mlv issue?

**Comment by masc4ii** [comment]
So risizing seems not to be the problem?

For a corrupt file, it would always happen at the same clip(s) at the same time/percentage. Does it? Where are your .mlv files located? If it is an external drive, which is not 100% stable in your Windows system, it could lead to errors. Best is to use an internal drive, if this is the case.

**Comment by gpapaioa** [comment]
All files are located on internal m2 ssd. I just tried the same file and worked properly, no freeze. I will investigate more, maybe try a different machine.
