### ISSUE TITLE
macOS: "MLV.app is damaged and can’t be opened. You should move it to the Trash"

### ISSUE THREAD

**Issue by Signynt** [ilia3101/MLV-App#258]
When I try to launch the [latest release for Mac ARM](https://github.com/ilia3101/MLV-App/releases/tag/QTv1.14) the app won't start, and I get "MLV.app is damaged and can’t be opened. You should move it to the Trash”.

**Comment by masc4ii** [comment]
What is your computer?

**Comment by Signynt** [comment]
Mac mini M1 (2020) 8 GB
macOS Monterey 12.4

**Comment by masc4ii** [comment]
Have you enabled access in system preferences? macOS automatically blocks all unknown apps.

**Comment by Signynt** [comment]
Yes I have (Under the 'Privacy' tab), but it doesn't even show up in the 'General' tab of 'Security & Privacy' like the Intel app does, asking you if you want to allow it, since the app won't even start.

**Comment by masc4ii** [comment]
Rightclick on app, "Open". Then in the first tab (general, not privacy tab) in security & privacy allow to open it.

**Comment by Signynt** [comment]
Like I said, it doesn't show up there because the issue is not that the app does not have permission, it won't even start.
I've tried several times already, but tried it again following your instructions exactly, with the same result.

**Comment by masc4ii** [comment]
The app won't start without macOS permisson!

**Comment by masc4ii** [comment]
Checked download again. Works on M1 without any problem.

**Comment by Signynt** [comment]
Here's a screen recording of me trying to open it, just so it's clear what is going on:

[screen recording](https://imgur.com/a/VdjkQlA)

**Comment by masc4ii** [comment]
On your Mac the important security setting "Allow apps from everywhere" is missing, so your Mac blocks this app and puts it into quarantine. Delete this entry by writing this into the terminal:

`sudo xattr -d /Applications/MLV\ App.app`

**Comment by Signynt** [comment]
Weird, I've never had this issue before on this mac. Enabling this option let me allow the app to be opened.

I used the command `sudo spctl --master-disable`

Thanks for your help @masc4ii !
