### ISSUE TITLE
Reference Lines in the Waveform Monitor

### ISSUE THREAD

**Issue by gabriielangel** [ilia3101/MLV-App#259]
It would be good to add a few reference level lines, or maybe a single line with a user-set value.
As exporting to Log-C is quite sensitive to exposure level, this would enable us to get a predictable and  consistent image across all clips exported, and allow us to do all of the grading within MLV app.

Right now, it is a little hit and miss. You have to set levels by eyeballing the height of the waveform on the display.
Thanks!

**Comment by masc4ii** [comment]
Hi, thanks for your issue.
But I just can tell you, this enhancement has already been realized on Sep. 16th: 60894f411739ec7be4e202c453bdb768e46e3370
<img width="341" alt="Bildschirmfoto 2022-09-25 um 09 21 12" src="https://user-images.githubusercontent.com/30245296/192132749-8cc94f08-bed7-498a-9d83-724e7e4354d2.png">
<img width="340" alt="Bildschirmfoto 2022-09-25 um 09 21 28" src="https://user-images.githubusercontent.com/30245296/192132751-70260112-ca24-43d9-99bd-8d6fac30bca3.png">
<img width="337" alt="Bildschirmfoto 2022-09-25 um 09 21 36" src="https://user-images.githubusercontent.com/30245296/192132754-63fb07b8-c21f-4c2f-a2ec-66c1671fb057.png">

**Comment by gabriielangel** [comment]
Thank you very much for the info, this is great news! It wasn't in the version I downloaded.
As I am an end user who cannot compile, I will have to wait for the next release.
Cheers!

**Comment by masc4ii** [comment]
Compiling is very easy - just some clicks. But you could also wait for next release, correct.
