### ISSUE TITLE
Fix Focus Dots not working on EOS M 2.8K raw

### ISSUE THREAD

**Issue by JGSphaela** [ilia3101/MLV-App#260]
Fix Focus Dots function works fine on 2.5K footage but it has no effect what so ever on 2.8K.
I tried all 3 methods but none of them working, too. Also tried install the fpm file but no luck.
I'm using the 1.14 MLV-App and the latest ML build(2022Oct06.EOSM202) for EOS M, shooting 2800*1190 at 10bit.
![image](https://user-images.githubusercontent.com/39881472/194699514-c3896537-2cef-419b-b4c4-e5dbf63c5da6.png)
Thanks in advance!

**Comment by masc4ii** [comment]
Thanks for reporting. Could you please upload a very short MLV sample? You could use cutIn and cutOut in MLV and export just some frames as MLV.

**Comment by JGSphaela** [comment]
Hi, masc4ii! Thanks for the fast respond!
I upload a few frames here:https://drive.google.com/file/d/1xY4bWogniEhWezRj9V4H772jYJP-6pWn/view?usp=sharing
Thanks again!

**Comment by masc4ii** [comment]
For me the focus pixel fix works fine with your clip. Did you install the corresponding map? See the "installed map" widget, please.
<img width="1440" alt="Bildschirmfoto 2022-10-08 um 11 29 55" src="https://user-images.githubusercontent.com/30245296/194700669-6d5bb625-24fd-4a4c-8f83-3972800bc15a.png">

**Comment by JGSphaela** [comment]
> For me the focus pixel fix works fine with your clip. Did you install the corresponding map? See the "installed map" widget, please.>

I just check the Installed Focus Pixel Maps and it's empty even though I install the fpm by dragging them into the MLV App... It's quite weird, but I'll try again

**Comment by JGSphaela** [comment]
When I drag the fpm file into MLV App it shows they have been install but the Installed Focus Pixel Maps is still empty.
![image](https://user-images.githubusercontent.com/39881472/194700921-c65d7ec3-6185-4487-ad03-9687e6609dab.png)
![image](https://user-images.githubusercontent.com/39881472/194700879-e9e1c525-8678-47df-8895-b7ed5f359618.png)
Do I have to install all the fpm file for EOS M in order to use it?

**Comment by JGSphaela** [comment]
I installed every fpm for EOS M but it still shows an empty Installed Focus Pixel Maps window.
![image](https://user-images.githubusercontent.com/39881472/194701071-11f7bbaa-c4bf-4ad6-8492-17e8569f9096.png)

**Comment by masc4ii** [comment]
Looks like MLVApp has no writing rights on your PC, or your Antivir deletes all the maps right after installing. The map files (*.fpm) must be in the same path as mlvapp.exe.

**Comment by JGSphaela** [comment]
> Looks like MLVApp has no writing rights on your PC
Spot on! Seems like it's not a good idea to have MLV App in C: drive. Maybe instead of just showing the installation is success, have a prompt to ask for Administrator privilege when MLV App can't write the file is a better option?
And 2.5k works just fine without the fpm file is also quite weird, I was thinking about the privilege thing but since 2.5k works just fine I didn't think much about it and thought it was a bug.
Thank you so much!

**Comment by masc4ii** [comment]
You can install it to C:, no problem. But you need writing permission in the install directory. No idea what's the problem on Windows: we get a "download okay" note, if the file was downloaded.
