### ISSUE TITLE
Possible regression - Cannot export to CinemaDNG

### ISSUE THREAD

**Issue by h1b1k1** [ilia3101/MLV-App#268]
When I try to export MLV file into CinemaDNG it aborts with "Disk full. Export aborted." There's about 100GB of space. Other codecs work.
Same behaviour in Rocky Linux and Debian, using newest MLV App appimage. 
Previous version ( 1.13 ) works.

**Comment by masc4ii** [comment]
Dublicate of #256.

**Comment by h1b1k1** [comment]
Sorry, didn't uccured to me to look into "Closed"

**Comment by masc4ii** [comment]
No problem. Are you able to test the fix by compiling? I have no new apparchive including the fix yet...

**Comment by masc4ii** [comment]
Perfect. Thanks for testing!

**Comment by blogdemoi** [comment]
I have the same behaviour, on Manjaro latest stable, with the latest appimage of MLV-App.

**Comment by masc4ii** [comment]
@blogdemoi Please read above your message and in the linked thread.

**Comment by masc4ii** [comment]
Then you won't find a solution for apparchive. You could try the installation method mentioned in the manual. If that also doesn't help, use v1.13.

**Comment by blogdemoi** [comment]
My issue is solved. I use Manjaro and didn't notice there was an AUR package, so I installed MLV app using the AUR and the export to CinemaDNG is ok now. Thanks for having tried to help me anyway.
