### ISSUE TITLE
Saving current frame as 16bit PNG.

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#27]
@masc4ii: I often need to write the current frame as 16bit png to disk. Is that feature can be added easily?

**Comment by masc4ii** [comment]
Yepp, no problem.

**Comment by masc4ii** [comment]
You can try out...

**Comment by bouncyball-git** [comment]
Thanks man! I wanted this to test the dual iso images. btw dual iso works now very well practically eliminated noise in the shadows :)

**Comment by masc4ii** [comment]
Oh yes, dual iso is very good now!!! I like it. 
PNG export works as expected? If so, you can close the issue.

**Comment by bouncyball-git** [comment]
YES!!! like a dream :)
