### ISSUE TITLE
HDR Blending doesnt export

### ISSUE THREAD

**Issue by amorell1234** [ilia3101/MLV-App#271]
I recorded a 12 bit 1080p clip at 48 fps using the newest crop mode build. I import to MLV APP I don't press any buttons on the right I only turn on HDR Blending in export. I tried Prores, H264 and PNG sequence MLV App freezes every time. What is the workflow for HDR video how do you get it to export?

**Comment by masc4ii** [comment]
No such problem here. Check checkbox, export, wait for export ready. You forget to write some more information about your system, versions, etc. ... no one can help this way.

**Comment by amorell1234** [comment]
Sure thing Windows 11, MLV App v1.14 

Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
16.0 GB RAM 
RTX 2070 8GB graphics card

Any other info that can help fix this issue?

**Comment by masc4ii** [comment]
Do you leave the cmd window open on export? 
Did you try the same in v1.13 just for test? If I remember right, there was a bug in v1.14  for some options, which is solved since a long time (if you compile latest revision).

**Comment by amorell1234** [comment]
Thank you 1.13 exported the HDR video!
With one adjustment I had to unclick export audio, does that happen for you? 
I noticed the clip is a second longer. Do you have and tips on how to get audio perfectly aligned in your video editing software like Premiere?

**Comment by masc4ii** [comment]
If you override framerate, you disable and unsync audio. If audio sync is important, uncheck framerate override, and use the framerate you recorded the video.
