### ISSUE TITLE
HEVC 10/12 bits NVENC on Windows

### ISSUE THREAD

**Issue by AndrewKeYanzhe** [ilia3101/MLV-App#272]
Does MLV-App support HEVC 10/12 bits NVENC encoding on Windows? I am using a GTX 1650 Mobile TU117 and it always uses CPU encoding.

**Comment by masc4ii** [comment]
None of the devs has a computer with NVidia graphics. That is the reason why MLVApp currently has no NVENC support. (Nvidia builds don't run at all on unsupported hardware.) However you could search for a NVENC-capable ffmpeg build and adapt the export command in MLVApps MainWindow.cpp, startExportPipe().

**Comment by AndrewKeYanzhe** [comment]
Would it be possible to add Intel Quicksync 10 bit HEVC encode to the default MLVApp build? Intel CPUs 7th gen and up are able to encode 10 bit HEVC, so this should be quite well supported. 

My system has an i7-9750H but Intel Quicksync doesn't seem to be used.

**Comment by masc4ii** [comment]
Do you know any ffmpeg version for this? Or a easy-to-use encoding library? All I find and see on a first quick search looks very difficult to use...
