### ISSUE TITLE
Request: 10 bit HEVC hardware encode using FFmpeg + VideoToolbox on macOS

### ISSUE THREAD

**Issue by AndrewKeYanzhe** [ilia3101/MLV-App#274]
Is it possible to enable 10 bit HEVC hardware encode for macOS via FFmpeg with VideoToolbox?

It seems to require just a change in the flag:
`-c:v hevc_videotoolbox`

https://trac.ffmpeg.org/wiki/HWAccelIntro

This will help to reduce CPU and memory usage.

**Comment by masc4ii** [comment]
No, it is not possible. It is possible to enable HEVC Videotoolbox export, but it is 8bit only. I don't find a hint for 10bit in the docs. Even if I try to request 10bit (tested via -pix_fmt p010le), I get out a 8bit file, MediaInfo told.

So for this you can also use AVFoundation export, which uses the hardware.
