### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by deboi238** [ilia3101/MLV-App#275]
sometimes when im using multiple footage. the software just crash randomly.
specs
rtx 3060
gtx 1060
48gb ram
amd ryzen 5 5600x

**Comment by masc4ii** [comment]
Not possible to reproduce. More info needed.

**Comment by deboi238** [comment]
@masc4ii sometimes the software crash when i play the video

**Comment by masc4ii** [comment]
This can be anything - maybe a problem especially with your computer.
