### ISSUE TITLE
Profile menu not updating itself on select?

### ISSUE THREAD

**Issue by Randrianasulu** [ilia3101/MLV-App#276]
I tried to compile MLV-App on Slackware 15.0 i586 (but actual cpu is AMD FX 4300, so plenty of SIMD extensions).

Compile was fine (I used src up to 620d7c8e7ddfd2f13d7bc03253e9d0af14a7d7d0).

But after starting resulting App and playing with ElgersburgBHF.zip (5 seconds MLV file I found on forum) I noticed Profile dropdown menu does not change its content on select, so I was a bit confused about its working.

Next one (Processing gamut) works as intended, showing selected mode on itself.

I am not familiar with qt, looking at last git commit message ( "Set msgbox default buttons") may be some updates were missed?

**Comment by masc4ii** [comment]
This combobox is a pre-seletion of presets. It sets up the transfer function and the processing gamut. You should see these options:
<img width="349" alt="Bildschirmfoto 2023-10-08 um 19 44 59" src="https://github.com/ilia3101/MLV-App/assets/30245296/3f70e561-f6a8-4a52-91cc-678ae68b8593">

If you select for example the Davinci option, you should get this:
<img width="347" alt="Bildschirmfoto 2023-10-08 um 19 45 15" src="https://github.com/ilia3101/MLV-App/assets/30245296/417c3e90-d3cb-42be-8d61-d3f0f4996c78">

**Comment by Randrianasulu** [comment]
> This combobox is a pre-seletion of presets. 

Yes, but shouldn't  its text reflect active selected preset?

**Comment by masc4ii** [comment]
No. Because then it would be incorrect in nearly all cases. The preset is a combination of processing gamut and a unique equation. The formula is changeable. There are endless possibilities. A preset is just one of that.

**Comment by Randrianasulu** [comment]
> No. Because then it would be incorrect in nearly all cases. The preset is a combination of processing gamut and a unique equation. The formula is changeable. There are endless possibilities. A preset is just one of that.

hm, may he then ONLY replace 'Select preset' text with 'Custom' or 'Custom,  click to change" IF changes were made?

or at least indicate it in statusbar somewhere?

**Comment by masc4ii** [comment]
Why adding this additional complexity (the profile thing is very complex already now), as everything is custom (apart from those few presets)? You always see what you selected below. And if you're not sure, select it another time again.
