### ISSUE TITLE
official debian package

### ISSUE THREAD

**Issue by alexmyczko** [ilia3101/MLV-App#278]
so the package is basically ready, however there is issues from ftp-master that should be resolved:
E: mlv-app source: source-is-missing [platform/qt/help/help.htm]
is the html generated from something?

and Files in platform/qt/AudioVideoIcons/*, and at least one file in
 platform/qt/RetinaIMG, do not seem to be in their preferred form of
 modification -- they look to have been generated using Adobe
 ImageReady, so the preferred form for modification is probably not
 .png.
are the png files generated from another format? where are these files, and can they be converted to
png on linux?

W: mlv-app source: missing-license-paragraph-in-dep5-copyright cc-3.0-attrib [debian/copyright:20]
i need the full license text of cc-3.0-attrib

W: mlv-app: no-manual-page [usr/bin/mlvapp]
if someone has a man page for this? (it's just a warning, can be without)

packaging can be found at:
http://sid.ethz.ch/debian/mlv-app/mlv-app_1.14-1.dsc

**Comment by masc4ii** [comment]
Thanks for your help and work!

The html is located in the repo - I don't understand the issue:
https://github.com/ilia3101/MLV-App/blob/QTv1.14/platform/qt/help/help.htm
It was generated from the wiki inside the repo using an online markdown to html converter, plus some manual changes for the pictures paths.

For the icons: What else are they, if not png?! How to get that info?

Where and why is a license missing? What shall I do?
https://creativecommons.org/licenses/by/3.0/

And what to do with the manual page?! A manual is included in-app. Is something else needed?

**Comment by masc4ii** [comment]
sry. Currently there is no plan. There is nearly nobody testing the latest commits. And testing alone, I can't say if it works fine on any other than mine computer.

**Comment by alexmyczko** [comment]
knowing that is fine so can just try again with git2deb... need to dig out reject reasons and retry...

**Comment by masc4ii** [comment]
Hi @alexmyczko ,
here your are:
47c44b505679071daab021159ea80aa6558d4974
