### ISSUE TITLE
Not Compiling on Arch Fix

### ISSUE THREAD

**Issue by MahirAbbas** [ilia3101/MLV-App#287]
The app doesn't compile on arch, qt6, wayland.
Simple fix
replace 
-std=c99 with -std=gnu99

**Comment by masc4ii** [comment]
Thank you for that info. Could you please test latest commit? Thank you.

**Comment by MahirAbbas** [comment]
Hi yes, 
It compiles now, thank you

**Comment by MahirAbbas** [comment]
This is kind of a hack, as it doesn't conform exactly to C99 standard, unless you explicitly declare the usleep funcition. Changing to GNU99 changes the standard to include the gnu libraries, which you may or may not want. Up to you. 
If you care about sticking to C99, then rewriting the usleep function into nanosleep is required (I think), and any function that may depend on it to be updated.
Although, I doubt it will be an issue.

**Comment by masc4ii** [comment]
I wonder this is needed at all on Arch. On Ubuntu or Debian it is possible to compile without that. 

With that commit I tried to support both: for GCC compiler, it uses GNU99, otherwise C99, both Unix only.
