### ISSUE TITLE
Crash when importing very big files

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#30]
Report by escho (on Linux):
> Maybe you know, that I have problems, importing files bigger than 4 Gbyte. The app crashes. 

> It crashes in line 61: https://seescho.files.wordpress.com/2017/10/screenshot_20171005_191349.jpg

> I commented out line 461 in MainWindow.cpp. Now the app crashes in line 468 in MainWindow.cpp:  https://seescho.files.wordpress.com/2017/10/2.jpg
>
> I did another test. I cut the 7,6 G-file using "mlv_dump -fxxxx":
>
> 1318frames.MLV run with no problems
> 1319frames.MLV let the app crash.
>
> Here are the filesizes of the two MLVs:
>
> Code: 
> ```
> edgar@localhost:~/test/frames> ls -l
> insgesamt 8440240
> -rw-r--r-- 1 edgar users 4319763492  6. Okt 20:57 1318frames.MLV
> -rw-r--r-- 1 edgar users 4323038516  6. Okt 20:58 1319frames.MLV
> ```
> I cannot locate, where the crash with 1319frames.MLV appears, since QT Creator tells me, it cannot find binary debug informations for this stack frame.

I don't have such big files (and also can't create them with my 5D2), so I can't test & debug it here. But sounds like a 32bit variable is used instead of 64bit somewhere (2^32 = 4294967296, what is not so far away from the numbers above).

**Comment by bouncyball-git** [comment]
I don't think the cache should be that big to fit whole clip (or hog all available memory). It have to be just big enough to accelerate things noticeably.

**Comment by seescho** [comment]
@masc:

Thanks for opening the issue.

Your 5D2 cannot record files bigger than 4G? I´m doing this using the exfat-fs on the memory-card on 6D or 600D. Before I had exfat, the files, bigger than the 4G-limit were splitted into something like this (MLV and M00):

```
edgar@localhost:~/test/00-37> ls -l
insgesamt 13266880
-rwxr-xr-x 1 edgar users  759283764 25. Mai 2014  M25-0037.M00
-rwxr-xr-x 1 edgar users 4294513248 25. Mai 2014  M25-0037.MLV
-rwxr-xr-x 1 edgar users     521280  5. Okt 22:35 mlv_dump
-rw-r--r-- 1 edgar users 4975166216  8. Okt 14:22 output.MLV
-rw-r--r-- 1 edgar users        419  8. Okt 14:23 Textdatei
```

Now you can use mlv_dump to concatenate the splitted files into one big MLV (output.MLV):
 
```
edgar@localhost:~/test/00-37> ./mlv_dump -o output.MLV *.MLV

 MLV Dumper v1.0
-----------------

Mode of operation:
   - Input MLV file: 'M25-0037.MLV'
   - Rewrite MLV
   - Output into 'output.MLV'
File M25-0037.MLV opened
File M25-0037.M00 opened
File M25-0037.M01 not existing.
Processing...
Reached end of chunk 1/2 after 17498 blocks
Reached end of chunk 2/2 after 3094 blocks
Processed 10197 video frames
Done
```

In this case here the resulting MLV has a size of 4,6 GByte.

I´m really don´t know, where the problem is located. Because other MLVs  bigger than 4G let MLV App crash on different places. I will do some more tests.

**Comment by masc4ii** [comment]
Good! I will try that with mlv_dump! As I know the 5D2 can't handle exfat.

**Comment by ilia3101** [comment]
This is strange, I think I remember @DeafEyeJedi said before that he managed to import a 61 or so gigabyte file with no problem (do I remember right?)

**Comment by ilia3101** [comment]
This might be a more recent bug though, idk.
@seescho does ram usage spike suddenly when you try to import the big files?

**Comment by seescho** [comment]
No spike in ram

**Comment by masc4ii** [comment]
I tried recording a large file and fitted the mlv+m01 using mlv_dump. Now I have a 6.92GB mlv. But:
- if I open in MlRawViewer, it tells 2687 frames, same as mlv_dump told
- if I open in MLVApp, it tells 1019 frames... LOL
- if I open the original 4GB mlv, MLVApp tells 1664 frames... LOL
No crash so far (okay, the shown data is <4GB)... Anyway, I think the behaviour is not correct :o)

**Comment by seescho** [comment]
Yes, that´s looks a bit funny (like the audio-stuff).

I tested some more big files some days ago. And the results was really really funny. I will explain later what happened.

**Comment by bouncyball-git** [comment]
And 1019+1664 = 2683 != 2687 but sclose <- this later is happening often because of the bug in mlv_rec. I saw more than 15 frame difference between summed frame count and actual frame count. This is not happening to me if I use mlv_lite.

I'll explain what is happening. All mlv chunks have it's own frame count in the header e.g. if mlv is multichunk there is no chance to get all frame amount until you sum up all values from all mlv chunks of index the mlv and count actual VIDF block <- this later method always gives exact frame amount.

Now when you rebuild MLV with mlv_dump it seems it has a bug and inserts the last chunk frame count into the header of resulted big mlv. Hence MLV App reports 1019. Or there is a bug in MLV App when it indexes (counts VIDFs) MLV.

When you open 1st chunk of the video in MLV App it reports 1664 because it's true. MLRawviewer never relies on the information of the header and always indexes MLV and extracts wav at the same time.

**Comment by masc4ii** [comment]
Both, 1019 and 1664 was starting from first frame. So do not + the two values.

**Comment by ilia3101** [comment]
MLV App reads the frame indexes from frame blocks, as I've heard frames can be out of order, **is that true?**
If not, I will stop relying on it as a source of info about frames, as I see how it can go wrong if frames provide incorrect info.

**Comment by bouncyball-git** [comment]
In your code frame number derived from indexing VIDFs (frame_total++)

```
#define getMlvFrames(video) (video)->frames
...
video->frames = frame_total;
```
And this is the only reliable method! So we are cool :)

**Comment by seescho** [comment]
I tried a change in video_mlv.c, lines 23 ff. With this change all these funny things with big files has gone for me in Linux:

```
**static uint64_t file_set_pos(FILE *stream, uint64_t offset, int whence)**
{
#if defined(__WIN32)
    return fseeko64(stream, offset, whence);
#else
    **return fseek(stream, offset, whence);**
#endif
}

**static uint64_t file_get_pos(FILE *stream)**
{
#if defined(__WIN32)
    return ftello64(stream);
#else
    **return ftell(stream);**
#endif
}
```
No clue what that does mean for MacOs or for Windows. In openSUSE, I can now import the big files without crashing, without showing funny frame numbers and without showing distorted pink frames.

**Comment by masc4ii** [comment]
Thanks! Cool! Same for me on OSX. Funny frame numbers are gone.

**Comment by bouncyball-git** [comment]
Hehe, my bad I put those routines there a long time ago :)

**Comment by masc4ii** [comment]
@seescho : is the problem solved? We could close the issue, if so.

**Comment by seescho** [comment]
Tried it just now. No, it´s not solved.

It would be nice, if lines 28 and 37 could be changed, too, as I showed above:

line 28: change fseeko to fseek
line 37: change ftello to ftell

Without these further changes, importing big MLVs does not work here. Maybe, you could give the changes a try?

**Comment by masc4ii** [comment]
But with that, it works?!
Tried it out: still works on OSX. 
@bouncyball-git : where is the difference? Would that be okay?

**Comment by masc4ii** [comment]
Ok. Got a test linux now. I don't know if I can test all with that, but it starts.

> line 28: change fseeko to fseek
> line 37: change ftello to ftell

Without that, I was not able to import any file. Commited now. Thx to @seescho  for reporting.

**Comment by bouncyball-git** [comment]
What size files you can not import?

**Comment by bouncyball-git** [comment]
fseeko and fseek differ just with parameter type.

int fseek(FILE *stream, **long offset**, int whence);
int fseeko(FILE *stream, **off_t offset**, int whence);
int fseeko64(FILE *stream, **off64_t offset**, int whence);

**Comment by masc4ii** [comment]
I compiled on ubuntu and no matter what file size... before this change I was not able to open any file. It crashed on clicking "Open" in the file dialog. No I can open the files.

**Comment by seescho** [comment]
I forgot to tell you, how I came to fseek and ftell. QT creator told me some build problems (implicit declaration):
https://seescho.files.wordpress.com/2017/10/implicit.jpg
The third implicit declaration problem is with usleep in frame_cashing.c. But i didn´t test, what happens, if usleep is changed to sleep.

**Comment by ilia3101** [comment]
`what happens, if usleep is changed to sleep.`
the 100 nanoseconds(or whatever) become seconds ;)

Also, what is happening with frame order? as far as I can tell, it will now get the correct amount of frames, but is the order fudged up due to it reading the VIDF's index? Or has someone got fixed that?

**Comment by ilia3101** [comment]
`The third implicit declaration problem is with usleep in frame_cashing.c`
Surprising actually, as `unistd.h` is included, shouldn't be 'implicit' 😕

**Comment by ilia3101** [comment]
Ah ok, I see now, we'll have to replace all usleep:
`use nanosleep(2) instead.  POSIX.1-2008 removes the specification of usleep().`
Source: bottom of [this](http://man7.org/linux/man-pages/man3/usleep.3.html) page

**Comment by seescho** [comment]
Found another thing:
If I compile without -std=c99, than ftello, fseeko and usleep isn´t marked as implicit declaration anymore. And I can import files.

**Comment by bouncyball-git** [comment]
@masc4ii: Very strange. I'm using it from the beginning under ubuntu 16.04 and never had any crash. Is that 32bit linux or 64bit?

**Comment by iFloris** [comment]
@ilia3101 @bouncyball-git Would it help if I uploaded a 6,7 gigabyte 3,5k MLV for you guys?

**Comment by masc4ii** [comment]
@bouncyball-git : it is a ubuntu 12.04 LTS in a virtual box (so it is 32bit?!... don't know. Host is Win8.1Pro 64bit). I use a Qt 5.6.3, this was the only one I found so far for this old distro.

**Comment by ilia3101** [comment]
@iFloris If you can, that would be wonderful to test!
I would appreciate it, and would definitely help a lot to fix any large-file bugs.

**Comment by seescho** [comment]
according to linux man pages:

```
fseeko: CONFORMING TO POSIX.1-2001, POSIX.1-2008, SUSv2.
ftello: CONFORMING TO POSIX.1-2001, POSIX.1-2008, SUSv2.
usleep: CONFORMING TO 4.3BSD, POSIX.1-2001.  POSIX.1-2001 declares this function obsolete; use nanosleep(2) instead.  POSIX.1-2008 removes the specification of usleep().

fseek: CONFORMING TO POSIX.1-2001, POSIX.1-2008, C89, C99.
ftell: CONFORMING TO POSIX.1-2001, POSIX.1-2008, C89, C99.
```

MLV App in Linux is compiled with compiler flag -std=c99. See lines 41 and 42 in MLVApp.pro. But, if I understand this right, than fseeko, ftello and usleep isn`t declared for C99. That´s why the compiler warning and for me the crash comes in.

@masc4ii 

Open a console in your Linux-machine and type `getconf LONG_BIT` That should show you, if your Linux is 32 or 64 bit.

**Comment by iFloris** [comment]
@ilia3101 ok, I hope it helps!
[M02-1232.MLV](https://www.dropbox.com/s/lds9wzljtoawob2/M02-1232.MLV?dl=0)
6,7 GB 3.5K MLV RAW, 28 seconds

**Comment by ilia3101** [comment]
Thank you!
Hope I'll be able to iron out any large file bugs now ❤️

**Comment by bouncyball-git** [comment]
@seescho: Thx for info. Warnings are indeed b/c of this. Can be changed to fseek/ftell and long offset as a parameter.

@iFloris: Thx for the MLV.

@masc4ii: Do what @seescho said or just run "uname -a"

**Comment by masc4ii** [comment]
My linux is 32bit. But with fseek/ftell all is fine. So has anybody still problems with big files?

**Comment by bouncyball-git** [comment]
Here all is fine too.

**Comment by masc4ii** [comment]
Then I think... after a very long time... let's close this thread! :-) Thx everybody!
