### ISSUE TITLE
Memory leak (in llrawproc?)

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#32]
Every time I open a mlv the used RAM by MLV App is approx. 10MB higher. If I disable RAW correction the used memory stays approx. the same.

**Comment by masc4ii** [comment]
Additional info: if I set all to OFF but let the checkbox "Enable RAW correction" enabled, it still uses 5..7MB more each time changing the clip. If I disable RAW correction (checkbox) the used RAM stays the same.

**Comment by bouncyball-git** [comment]
Thanks for pointing it out! I'll check it as soon as possible.

**Comment by bouncyball-git** [comment]
Please check the latest commit. The leak now should be fixed.

**Comment by masc4ii** [comment]
Seems to be fixed! Cool! Thx!
