### ISSUE TITLE
Add xyY or Lab mode to processing

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#33]
Currently, sharpening causes pink edges and exaggeration of moire colours on non-5D3 footage, so adding a processing mode where sharpening can be applied only on luminance will reduce many problems.
This would also help avoid getting very bright red or blue noise flakes appearing from the shadows when adding saturation, as it would be kept separate from luminance.

Colour models xyY and Lab are suitable (they separate colour and luma), this will also add loads of new possibilities for processing and colour.
The xyY colour space looks very simple to implement also, will have a demo as soon as possible.

One of the more interesting things I've come up with for the app yet :)

EDIT: As well as causing less false colour, this would also make removing it easy (possibility to blur chroma separately)

**Comment by DeafEyeJedi** [comment]
That's definitely great news to hear!

**Comment by masc4ii** [comment]
Sounds very interesting! Would it also be possible then to blur colour? This could help against moiree...

**Comment by ilia3101** [comment]
@masc4ii Yess!!!! forgot to mention that in the issue, it would definitely give an easy way to blur colour - in fact that was even the original reason why I came up with the idea 😉

Though it will slow down processing by a factor of 3 I'd imagine :/
... until open**C**L

**Comment by masc4ii** [comment]
Sure... it won't get faster if we do more. But if it looks nice, I have a lot of time :-)

**Comment by ilia3101** [comment]
Issue update:
[xyY was implemented](https://github.com/ilia3101/MLV-App/commit/3818f36ba1ec18739de0a5d341b52fa7dea3c470), but was slow and had some issues with [highlights clipping to yellow](https://github.com/ilia3101/MLV-App/commit/3818f36ba1ec18739de0a5d341b52fa7dea3c470#commitcomment-25116924) 🤢
[YCbCr replaced it](https://github.com/ilia3101/MLV-App/commit/cb75e0131cc2dca7cd3e96e5ff36eda1abdac9d9), now it is much faster and no bad artifacts,. I have tried adding chroma blur, but it caused colour artifacts, so maybe YCbCr isn't the right model to do such things as colour denoising / removing moire, so: Lab space will have to be implemented.

**Comment by masc4ii** [comment]
The look and speed of YCbCr is much better then xyY! :-) Is there a way I can test chroma blur?

**Comment by ilia3101** [comment]
I am rewriting my chroma blur, previously it was fixed at 3x3, and I think something was wrong, as it's looking a little nicer now. Maybe Lab isn't necessary after all.
I'll upload it once I have a bad bug removed.

**Comment by ilia3101** [comment]
@masc4ii What do you think of putting the chroma blur slider in "Correct" tab? I think it should be there, and maybe call it "moire removal" as it has very similar effect to what "moire removal" does in Adobe Camera Raw. And I'll add a second chroma filter soon (bilateral filter) which won't ruin edges, which we can use for colour denoising. So we can have two sliders in the correct tab, "remove moire" and "remove colour noise".

Or... in the future if we have a "detail" tab like adobe they will go there 😉

**Comment by masc4ii** [comment]
I thought to do a "Sharpen & Blur" (or "Detail") tab/group.

**Comment by bouncyball-git** [comment]
Yes IMHO the processing before and after debayering should not be mixed.
