### ISSUE TITLE
Win 32bit port broken - crash on import

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#35]
Since Caching is merged, the 32bit Windows version is not able to open MLV files and crashes. It happens since the very first commits with the new caching.

**Comment by ilia3101** [comment]
Thanks for letting me know. Is there any chance that we are exceeding the 4GB ram limit on 32bit?

**Comment by ilia3101** [comment]
Also, I think with only 4GB ram, caching might not even be worth it(?), as it wouldn't cover many frames in most cases. Maybe this is a lazy solution, but what do you think of something like:
```
#ifdef _WIN32
    #ifndef _WIN64
        #define NO_CACHING
    #endif
#endif
```
Do you disagree?

**Comment by masc4ii** [comment]
Qt is by standard 32bit on Windows. A 64bit version of the environment you must build yourself. As I know we had no 4GB limit on Windows anymore. So when we want to use the standard delivered libraries, we have 32bit libs on a 64bit system. Is it the cache size which causes the problem?

**Comment by masc4ii** [comment]
The PC has exactly 8GB RAM. `setMlvRawCacheLimitMegaBytes( m_pMlvObject, 100 );` makes no difference. No matter which file size, the App crashes.

**Comment by bouncyball-git** [comment]
[win 32bit crash on mlv import] Debugger always bails out on the line 208 of 'frame_caching.c'
[linux 64bit crashes often] the reason is line 264 of the 'frame_caching.c': fclose(file);

if(file) fclose(file); <- this patch works and no crashes are encountered after it. strange because 'file' only lives in this local scope, however there are more threads working with the same opened file. Something's wrong here. Linux always very sensitive about this king of stuff.

**Comment by masc4ii** [comment]
Thx bouncyball. On Win 32bit I can't debug, because I have no zlibd.dll... or how can you debug?

**Comment by ilia3101** [comment]
`always bails out on the line 208 of 'frame_caching.c'`
makes no sense :(
`[linux 64bit crashes often] the reason is line 264 of the 'frame_caching.c': fclose(file);`
That must mean the file is failing to open in the first place :/ So cache is not even working there sometimes :(

**Comment by bouncyball-git** [comment]
Yus, right, makes no sense at all :)

Debugging is difficult without some lib debug versions. But "run to line" feature sometimes helps a lot.

**Comment by bouncyball-git** [comment]
I patched the code now it works. But I think we are walking on the sharp blade with all those caching threads running in the background and hogging almost 100% of all cores!

Example: when I import several MLVs and activating cache, then starting to change videos quickly (clicking on them randomly) after some clicks app crashes and debugger always bails out on 77th line of AudioPlayback.cpp. Look at this line yourself. Some simultaneous access to some resources!

Well... I don't like this any more :) and why this thread code (function) works if caching is off by default when app been crashing on windows 32bit?

**Comment by masc4ii** [comment]
On OSX it does not crash when I click randomly on the session clips also with Caching active. AudioPlayback again? Oh no... why has Linux so big problems with audio?

**Comment by bouncyball-git** [comment]
Unfortunately it still crashes when audio playback is off in the menu.

**Comment by bouncyball-git** [comment]
When file is big enough caching drives me crazy. Whole PC stalls and unresponsive some annoying time. System monitor shows almost 100% load on all 4 cores 4 threads :)

**Comment by bouncyball-git** [comment]
And also unfortunatelly there i

**Comment by masc4ii** [comment]
Audioplayback is off and you get a crash in AudioPlayback? Very interesting! :-/

**Comment by bouncyball-git** [comment]
Yup, s..t happens :)
