### ISSUE TITLE
QT App: Saturation slider has no effect

### ISSUE THREAD

**Issue by seescho** [ilia3101/MLV-App#37]

**Comment by seescho** [comment]
Tested lates versin with Linux

**Comment by bouncyball-git** [comment]
Saturation is fine here on Ubuntu 16.04

**Comment by bouncyball-git** [comment]
I'm sorry, correct. Saturation is not working when chroma separation is ON.

**Comment by bouncyball-git** [comment]
Hmm... strange. Now it works again?! Can not reproduce any more :-D

**Comment by masc4ii** [comment]
Really? What are you doing exactly? ChromaSeparation = On and then changing saturation? On OSX that works... so you are doing something else?

**Comment by seescho** [comment]
It does not work, when I switch from tonemapped to linear (cannot use tonemapped for my planets)

**Comment by bouncyball-git** [comment]
I guess it is intended so like in LOG modes. However I'll better wait for the answer of our processing master Ilia :)

**Comment by ilia3101** [comment]
`I guess it is intended so like in LOG modes`
Yes true.
@seescho You actually mean the one called `Linear`? Not `Standard`?
I think I did disable saturation in that mode... I can easily remove any of the restrictions I put on that mode if it works better for you, I personally have no opinions on what is right there, as I don't use it and didn't think anyone did 😃.
Maybe calling it `Linear` isn't the right term, the values will be linear, but on screen the values will be almost squared. Could rename it to `No Gamma Correction` (Necessary?)

**Comment by seescho** [comment]
Yes ilia, I mean linear. A short explanations,why...
Recording the moon, I prefer the standard mode, playing with the dark and light sliders. Recording planets like Saturn (recorded with a focal length of  6.000mm), I get the best results in linear mode. But maybe, the results could be finetuned another bit more with the other sliders, which are disabled in linear mode.
My astronomy stuff is a very special case. But I would like to get all out of the records, what is possible with mlv-app. So I  would like it, if you enable all sliders for linear mode.

**Comment by masc4ii** [comment]
Ilia enabled the parameters for linear now. And I greyed out the parameters if log is enabled. So in future there should be no misunderstanding.

**Comment by seescho** [comment]
ThankYou all :)
