### ISSUE TITLE
CineForm export?!

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#38]
Has anybody experience in using CineForm encoder? 
As written on ml forum, it is open source now. 
https://gopro.github.io/cineform-sdk/
It is better than ffmpeg in terms of using ProRes 422 and 444 (they write 12bit)? 
Have you seen a code example how to use it?

**Comment by ilia3101** [comment]
I like the idea, from what I've heard it's particularly good with metadata, so maybe it can be good for some more advanced colour management than what we have with ffmpeg (nothing?).
If the sdk isn't a massive pain, let's do it.

**Comment by bouncyball-git** [comment]
Haha I already tried to compile it under Linux. I always loved Cineform, it was my companion on my journeys under windows and I never regretted that I did not have access to prores goodie!

**Comment by bouncyball-git** [comment]
However it is real unknown jungle for me at the moment :)

**Comment by masc4ii** [comment]
I would love to add it as option on export. But I don't understand the SDK :-D

**Comment by bouncyball-git** [comment]
Me too ;)

**Comment by bouncyball-git** [comment]
ffmpeg has some sort of cineform decoder already after RE was done on codec. Now I'm sure it's gonna take not so long to be implemented correctly.

**Comment by masc4ii** [comment]
Maybe we wait until it is added to ffmpeg... then it is easier for us to implement ;-)

**Comment by bouncyball-git** [comment]
Yes definitely ;) this would be easiest way.

I'm gonna take a second look at it when have more time :)

**Comment by bouncyball-git** [comment]
I think  we can close this for now.

**Comment by masc4ii** [comment]
https://github.com/ilia3101/MLV-App/commit/29d73d1921a86f9dae0f64931f2e353d5add203b
Finally added.
