### ISSUE TITLE
QtApp on windows does not open MLV files with audio

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#4]
I tried to compile the v0.7 alpha on Windows with MinGW 32bit. Application opens normal. But when trying to open a MLV with audio, the App crashes. It does not crash, if there is no audio in the MLV. 

Switching off STDOUT_SILENT, the last output is depending on the file:
Block #...
or
AUDF/audio block...

This does not happen on OSX.

**Comment by masc4ii** [comment]
Did some more tests... now I also found files without audio crashing the App on Windows. @bouncyball-git : if you compile this revision (or newest revision), does it have the same behaviour? Or is just my new installed Qt buggy?

**Comment by masc4ii** [comment]
Tried with different PC to build the app for Win32. Opening (nearly any) MLV file crashes the app, not only files with audio.

**Comment by masc4ii** [comment]
First revision with this error is [this one](https://github.com/ilia3101/MLV-App/commit/cb9d313b737599e3fca9becd143843c8c462a369).

**Comment by masc4ii** [comment]
The error comes with this change: video_mlv.c
before:
`void setMlvProcessing(mlvObject_t * video, processingObject_t * processing)
{
    // double camera_matrix[9];
    // double xyz_to_rgb_matrix[9];

    /* Easy bit */
    video->processing = processing;

    /* MATRIX stuff (not working, so commented out - 
     * processing object defaults to 1,0,0,0,1,0,0,0,1) */

    /* Get camera matrix for MLV clip and set it in the processing object */
    // getMlvXyzToCameraMatrix(video, camera_matrix);
    /* Set Camera to XYZ */
    // processingSetXyzToCamMatrix(processing, camera_matrix);

    /* Get and set some XYZ to RGB matrix(a funky one) */
    // getMlvNiceXyzToRgbMatrix(video, xyz_to_rgb_matrix);
    // processingSetXyzToRgbMatrix(processing, xyz_to_rgb_matrix);

    /* BLACK / WHITE level */
    processingSetBlackAndWhiteLevel( processing, 
                                     getMlvBlackLevel(video) * 4,
                                     getMlvWhiteLevel(video) * 4 );

    /* DONE? */
}`
after:
`void setMlvProcessing(mlvObject_t * video, processingObject_t * processing)
{
    double camera_matrix[9];

    /* Easy bit */
    video->processing = processing;

    /* MATRIX stuff (not working, so commented out - 
     * processing object defaults to 1,0,0,0,1,0,0,0,1) */

    /* Get camera matrix for MLV clip and set it in the processing object */
    getMlvCameraTosRGBMatrix(video, camera_matrix);
    /* Set Camera to RGB */
    processingCamTosRGBMatrix(processing, camera_matrix); /* Still not used in processing cos not working right */

    /* BLACK / WHITE level */
    processingSetBlackAndWhiteLevel( processing, 
                                     getMlvBlackLevel(video) * 4,
                                     getMlvWhiteLevel(video) * 4 );

    /* DONE? */
}`

**Comment by masc4ii** [comment]
Okay... I think I have it! Crash at camera_matrices.c line 158 on Windows. Commenting in `original_matrix = matrix_5d2;` fixes the problem for me. @ilia3101 : Could you please check?

**Comment by ilia3101** [comment]
ah right, my matrix stuff causing problems again :(
You can coment out this bit completely for now, and there will be no problems as it is not used at all if i recall correctly
```
getMlvCameraTosRGBMatrix(video, camera_matrix);
    /* Set Camera to RGB */
    processingCamTosRGBMatrix(processing, camera_matrix); /* Still not used in processing cos not working right */
```

**Comment by masc4ii** [comment]
Both functions? Okay, I'll do. :-)

**Comment by masc4ii** [comment]
Bug fixed with [this commit](https://github.com/ilia3101/MLV-App/commit/6c9f4276d815bba3ea85477d04b7be70c724af36).
