### ISSUE TITLE
MLVApp: copy receips to a file

### ISSUE THREAD

**Issue by seescho** [ilia3101/MLV-App#45]
I think, it could be useful, to copy receips to files and load them from there, if needed. So I can create different receips for my different needs and start my work with them in a very easy way.

**Comment by masc4ii** [comment]
That is a good idea. Should not be too hard to implement. The same function is offered by EOS Digital Professional by Canon. I was using it a lot.

**Comment by masc4ii** [comment]
Hej, I implemented it for you. Would you please try it out? Thanks! ;-)

**Comment by seescho** [comment]
Thanks for implementing. Great! That´s what I needed :) Works fine here. 

But when I try to import receipe without a MLV loaded, MLV App crashes with SIGABRT in qvector.h line 422.

**Comment by masc4ii** [comment]
You're right. That was not clean. I fixed it.

**Comment by seescho** [comment]
Thanks
