### ISSUE TITLE
AMaZE not working right??

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#47]
Compare MLV App with amaze and bilinear:

|AMaZE|bilinear|
|-------------|-------------|
|![mlvappamaze](https://user-images.githubusercontent.com/23642861/32986032-d8144b20-ccbf-11e7-8822-403753663799.png)|![mlvappbilinear](https://user-images.githubusercontent.com/23642861/32986036-eb62ed94-ccbf-11e7-9e43-924316374221.png)|

You can see amount of colour artifacts increases!!! ...or at least doesn't decrease

Now look at MLRawViewer amaze vs bilinear:

|AMaZE|bilinear|
|-------------|-------------|
|![mlrvamaze](https://user-images.githubusercontent.com/23642861/32986037-fe7a300e-ccbf-11e7-81de-573ab25d22c9.png)|![mlrvbilinear](https://user-images.githubusercontent.com/23642861/32986040-01d85c6c-ccc0-11e7-860e-6d8ec4c4fe02.png)|

Artifacts of colour are reduced.

What might be wrong?
I have had this suspicion for such a long time, but MLRawViewer really pointed it out to me today.

**Comment by bouncyball-git** [comment]
You mean AMaZE artifacts are less in mlrawviewer and it's opposite in mlvapp right?

**Comment by bouncyball-git** [comment]
I've been also thinking about it all the time from the beginning. I have no any idea why it's wrong though :(

**Comment by masc4ii** [comment]
Same for my clip:
MLV App:
![pic](https://image.ibb.co/jJGdaw/Bildschirmfoto_2017_11_12_um_22_15_30.png)

MlRawViewer:
![pic](https://image.ibb.co/embXA6/Bildschirmfoto_2017_11_19_um_11_34_26.png)

**Comment by masc4ii** [comment]
One more thing: with saturation full right, these stripes are a very light cyan. With saturation full left (b&w), this are dark lines:
![pic](https://image.ibb.co/c1dvV6/Bildschirmfoto_2017_11_19_um_11_45_57.png)
![pic](https://image.ibb.co/eXxdiR/Bildschirmfoto_2017_11_19_um_11_46_03.png)

**Comment by bouncyball-git** [comment]
In mlrawviewer use srgb or re709 for comparison with mlv app.

btw exactly what color space we observing in the player of mlv app?

**Comment by masc4ii** [comment]
I uploaded a short version of the clip for you to test: 
[Download1](https://www.dropbox.com/s/pa3zu0vxux7jz98/M23-1205short.MLV?dl=0)
And another one with so nice moiree...:
[Download2](https://www.dropbox.com/s/nlzxvdo4gqe852j/M24-1153short.MLV?dl=0)

**Comment by ilia3101** [comment]
thanks for the clips :)

@bouncyball-git I found the 'HDR' mode in MLRawViewer was almost the same as MLV App's default tonemapped profile, soI did a direct comparison, tried to match them
![screen shot 2017-11-19 at 13 59 49](https://user-images.githubusercontent.com/23642861/32991370-10476a64-cd32-11e7-9279-8e9bba6d7c94.png)
Still clearly shows a difference.
As for what colour space MLV App uses or is, well that's still a mystery, though it is being treated as rec709 by ffmpeg, so we could probably think of it as rec709 for now, until we get it figured out a little better.

**Comment by bouncyball-git** [comment]
I always dreamed to use [OpenColorIO](https://github.com/imageworks/OpenColorIO) for color management of my future application ;) now I can say "for our cutest MLV App".

**Comment by bouncyball-git** [comment]
As for the images above: YES ugly artifacts are there and we have to understand why.

**Comment by masc4ii** [comment]
It comes not from the processing. I disabled processing, exported a PNG and tried to process with another image tool. The artefacts are the same.

**Comment by ilia3101** [comment]
OpenColourIO is worth looking at. Maybe will come to MLV App 😉

Who might know about how to fix this issue? Is there someone on the magic lantern forum who knows about this kind of thing? I really wish this could just get fixed already.

**Comment by bouncyball-git** [comment]
We should ask there :)

**Comment by DeafEyeJedi** [comment]
OpenColorIO would indeed be amazing to have it built in within the app. Seems like a long shot and shouldn’t be a priority while in this stage.

Though I can totally see/feel this one coming...

**Comment by bouncyball-git** [comment]
Yeah, we need to sort out the quality of the AMaZE debayerer first.

**Comment by ilia3101** [comment]
http://www.magiclantern.fm/forum/index.php?topic=20995.msg193416#msg193416
Asked a1ex, suggestion is to try white balancing the image before AMaZE. If it works well, I'll add some kind of channel equalizing during the demosaic (and of course reset after to not ruin processing).

**Comment by bouncyball-git** [comment]
Hmm.. iunteresting how to apply WB (matrix?) to the bayered data. Is it done during normalization?

**Comment by masc4ii** [comment]
Hm... don't know if that is the reason. If I comment out WB, I would then expect a picture with wrong colors, but without artefacts. 
I commented the WB+exposure part out: The colors are wrong (okay), but the artefacts are still there.
Or was it wrong what I thought?

**Comment by bouncyball-git** [comment]
I dug into darktable's related code today, it's pure C and source is huge, OpenCL is used all over there for image processing and matrix applying. AMaZE is CPU based thought and works fantastic. If I switch WB off in the interface then greenesh familiar debayered unprocessed look appears on the screen and small aliasing artifacts can be seen on the edges (almos exactly like on our mlv app with processing object wholly disabled). After turning WB on in darktabe aliasing is almost gone even when sharpening is applied.

**Comment by ilia3101** [comment]
No, it shouldn't be a matrix, as there's no way to blend the channels, meaning just increase the value of red/blue pixels or decrease the green to get them equalised. I'll show what the results are soon.

**Comment by ilia3101** [comment]
I'll try and put it right in to the AMaZE `demosaic()` function.

**Comment by ilia3101** [comment]
Comment inside AMaZE seems to confirm the theory:
![screen shot 2017-11-21 at 16 19 57](https://user-images.githubusercontent.com/23642861/33083659-e488a666-ced7-11e7-8238-5cb5a418658c.png)

**Comment by ilia3101** [comment]
Apologies for the **years** of bad AMaZE.
![screen shot 2017-11-21 at 17 31 04](https://user-images.githubusercontent.com/23642861/33087338-28379d18-cee2-11e7-9703-1a08cd82b4c4.png)
https://github.com/ilia3101/MLV-App/commit/6ed7e00ed9c8223cee4697491f547533667611df seems to have improved it.
Up next: automatic multiplier generation within AMaZE for even better channel balance.

**Comment by masc4ii** [comment]
WOW! I am impressed! Congratulations! This is so much better, also with my other clips!

**Comment by ilia3101** [comment]
maybe I'll leave this issue open for a little bit until I get the multipliers automated, as currently its most optimal for daytime white balance.

**Comment by masc4ii** [comment]
I am still impressed and AMaZEd!!! This difference is unbelievable!
Before:
![pic](https://image.ibb.co/eEDynm/Bildschirmfoto_2017_11_21_um_19_54_02.png)
After:
![pic](https://image.ibb.co/gSYynm/Bildschirmfoto_2017_11_21_um_19_54_08.png)
You made me really happy today! :-) Now the results with my files are better than with Resolve.

**Comment by bouncyball-git** [comment]
Hey! I IS A REAL AMAZE!!! Hahaha I feel so better now too! :-D

**Comment by bouncyball-git** [comment]
Before
![amaze_no_wb](https://user-images.githubusercontent.com/17232233/33116244-7f04c364-cf7d-11e7-8a7b-cdef278b8dbd.jpg)

After
![amaze_fixed_wb](https://user-images.githubusercontent.com/17232233/33116243-7eea36e8-cf7d-11e7-9651-659b68b53971.jpg)

**Comment by bouncyball-git** [comment]
GREAT!

Uhm... Can it be tuned little bit more? :P

**Comment by masc4ii** [comment]
I had to play around with the new version... sry for that :-)
[![youtube](https://img.youtube.com/vi/gq7qTegjgBg/0.jpg)](https://www.youtube.com/watch?v=gq7qTegjgBg)
Uploaded in 4K, but youtube knows even then how to crush the quality, hehe.

**Comment by bouncyball-git** [comment]
@ilia3101 

Ни как не нарадуюсь как хорошо работает подлеченный AMaZE :-D. Спасибо!
