### ISSUE TITLE
Audio data in the beginning lost

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#48]
https://github.com/ilia3101/MLV-App/commit/8a454f120dcef74daa2cac4b72932abf14c02393
here we discussed that audio and video is not correctly in sync. When shifting the audio one frame later, it fits.

When comparing a clip exported from MLV App to the the same clip exported from MlRawViewer, the video data is identical, but the audio is exactly one frame different, plus there is audio for the first video frame (which would be 0, when shifting the MLV output).
![pic](https://image.ibb.co/emQLDR/Bildschirmfoto_2017_11_19_um_12_51_07.png)

**Comment by bouncyball-git** [comment]
Hm... very interesting. I'm all finishing or at least making usable dng export, can not dig through the audio extracting code of mlv app now.

**Comment by masc4ii** [comment]
Hm... tried with another clip. No problem there, and MLRV and MLVAPP bring the same result. Maybe only my clip was wrong... who knows :-/

**Comment by bouncyball-git** [comment]
I guess so because, I repeat, I never had this issue with any software out there.

**Comment by masc4ii** [comment]
Okay. So I close here. If someone finds this again: reopen!
