### ISSUE TITLE
Wrong audio info for files without audio

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#5]
Opening a file without audio (e.g. the file EOS100D.MLV which we got from the forum), the file information tells:
doesMlvHaveAudio( m_pMlvObject ) = true
getMlvAudioChannels( m_pMlvObject ) = 0
getMlvSampleRate( m_pMlvObject ) = 0

That does not fit...
The App behaviour may be wrong using this information, for example ffmpeg export with audio export  activated can't work because of the empty WAV file.

**Comment by masc4ii** [comment]
This little change helps in video_mlv.h:
`#define doesMlvHaveAudio(video) (((video)->MLVI.audioClass) && ((video)->WAVI.channels > 0))`
But why `(video)->MLVI.audioClass` has wrong information?

**Comment by ilia3101** [comment]
This may even be a bug in magic lantern? I will have to see. I could add a double check for audio(check for AUDF blocks) and make a has_audio property in the mlvObject itself.

EDIT: Actually see that you fixed it, is this bug worth "closing"?

**Comment by masc4ii** [comment]
No, I did not fix it. I could do with that line above... it works, but is that good? Your idea would be better, but makes more work.

**Comment by ilia3101** [comment]
Ah ok, I'll keep that in mind, on my list/
I'll make all these little changes once bouncyball's work is merged to avoid conflicts.

**Comment by DeafEyeJedi** [comment]
Agreed. Good idea!

**Comment by masc4ii** [comment]
Did the temporary fix mentioned above in [this commit](https://github.com/ilia3101/MLV-App/commit/da2bffe45e2b1faa6facb269c9979bc2d48af1b2)

**Comment by masc4ii** [comment]
@ilia3101 : you fixed this by 8a2af3b? Or do you wanted to do more?
