### ISSUE TITLE
Make displayed settings values more consistent (QtApp)

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#53]
A few weeks ago I was thinking about this, and I made the change in Cocoa app so that darkStrength, lightStrength appear as if they are in range 0.0-1.0, and made the lighten slider look as if it goes up to 1.0 instead of 0.6, as I think 0-1 makes more sense to a user than 0-22 or some random looking range. 
I think the Qt App should also do this to make the user experience a little bit less strange.
I also made the tint range appear like -1.0 to 1.0 instead of -10 to 10, and sharpen 0.0-1.0, but that is not as important.

What do you think @masc4ii?

**Comment by masc4ii** [comment]
We can it make as you like. That should be no problem. But is 0.0-1.0 really better? Why not 0..100 for example? 
In Lightroom sharpen is 0..150, Tint is -150..150. Whatever the unit of the values is here... ;-)

For me it was never a problem with the values we have now, because Light-/DarkStrength is a parameter, I only know from our little app. So I did never care about the amount.

I think I now save the internal slider value, which is often something 0..200 or something like that. Maybe we calculate then 2 values... one for the library and one for the user. :-D But this also should be no problem.

**Comment by ilia3101** [comment]
`But is 0.0-1.0 really better?`
Well, it's definitely better than 0-22.5 or whatever else we have, but 0-100 is also fine I think.

My main argument for using 0.0-1.0 for the darkStrenngth and lightStrength values is that it looks more consistent with the darkRange and lightRange, which are also 0.0-1.0, and then make others 0.0-1.0 so that it all looks very consistent. But I don't have anything against 0-100 either.

Does @bouncyball-git have any preference on `0.0-1.0` vs `0-100`?

**Comment by ilia3101** [comment]
`I think I now save the internal slider value, which is often something 0..200 or something like that.`
Gooood!

What do you think of this:
- All parameters will be given as a slider range input to the processing object (double, 0.0-1.0)
- And there will be processings method that return the displayable value... such as: `getSaturationDisplayValue(procesingObject_t * processing)`

**Comment by masc4ii** [comment]
Hmmm. Double sliders don't exist in Qt. But I could do 0..1000 and devide by 1000. The bigger problem is, that the user also can type the desired value as number and I calculte the slider position. The more we calculate there (no matter if you or I do), the more we could have precision problems (we already have it on the saturation slider, you remember...).

**Comment by masc4ii** [comment]
uuuhhh... I again looked into the code: the input where the user types the value has completely to be changed when changing the range. With that all sliders (ranges), all labels and so on... :-S All these elements are working hand in hand now and use their settings. But they should be independant :-S

**Comment by masc4ii** [comment]
I see one possiblity, where the work is not too hard: adapt the library interface to the range you like to have (all the set...()) and I only change the ranges for all elements. This is also not compatible to old versions, but I don't have to implement a new concept for a few values.

**Comment by masc4ii** [comment]
Wait... you mustn't adapt the interface... I can just add factors at the call. I never read it back, so that is no problem as well. :-)

**Comment by ilia3101** [comment]
Ah I forgot there's a typing in value feature to deal with :/
Here's one solution for that:
have a couple of definitions like...
```
#define maxActualSaturationValue 4.0
#define minActualSaturationValue 0.0
```
...and use those as the limit for what user can type in, and processing will have a function like `actualSaturationValueToSliderPosition(typedValue)` to convert what the user types in to a slider position.

Or maybe this whole thing is too much work and just keep it the way it is? I just thought this way I could make changes in the processing unit without needing any change to the GUI.

**Comment by masc4ii** [comment]
ATM the slider limits multiplied with some factors (=the factors to get to the libraries range) and a defined precision per parameter (steps between two possible values) limit for what the user can type.
Defines are not bad... but the GUI is painted in an editor. There I can't handle defines. I can handle them in the code. But then the GUI I paint is different to the GUI I get when the App runs. Anyway... it is never bad to know the exact range needed by the lib! ;-)

**Comment by ilia3101** [comment]
Alright, let's leave the whole range thing as it is for now then, it seems to work. Though let's still change the displayed values to 0.0-1.0

So you also do saturation something like:
```
double saturationValue = pow( [self doubleValue] * 2.0, log(3.6)/log(2.0) );
```
right? (with integer slider of course)

For the user typing input you could just do `pow( userInput, log(2.0)/log(3.6) ) / 2.0;` to get position, or is that what you tried and it was innacurate? I don't exactly remember what the precision problems were like.

**Comment by masc4ii** [comment]
That is exactly what I am doing. Yes. 
Is it okay, when precision is only the half after that change? Now these sliders are 0..225 (0.0..22.5) and then they will be 0..100 (or 0.00..1.00). 3 decimals is overkill I think.
The precision for Lighten will be a bit better. It is now 0..60 (0.00..0.60) and then it will be 0..100 (or 0.00 to 1.00).

**Comment by masc4ii** [comment]
I tried that out now for the DarkStrength, LightStrength and Lighten slider. They are in the range from 0.00 to 1.00 now in my working copy. For compatiblity to old versions I calculate on open and save masxml. That seems to work. BUT: when saving and reopening the same file, there may be slightly different values :-P :-D ... so... drop that old version support?

**Comment by masc4ii** [comment]
@ilia3101 : I commited a version now. DarkStrength, LightStrength and Lighten is now 0.00..1.00. To have backwards compatibility I added a version attribute to the masxml and marxml. If there is no "version=2", that will tell the app to transform the values from old range to new range. When saving such xmls, the app will only save the new range and this "version=2" attribute.

**Comment by ilia3101** [comment]
`If you try to open a version=2 xml in the old MLV App`
Well, let's hope no one uses old versions in combination with new versions. I don't think that should be a big problem.

`I commited a version now. DarkStrength, LightStrength and Lighten is now 0.00..1.00.`
That's good, definitely better than 0-22.5 and friends 🤣

I also noticed that MLV App Qt gets confused if I put decimal numbers in the XML :)

**Comment by ilia3101** [comment]
Actually maybe we should do 0-100 display values (except dark/light range), Adobe after all ;) And also let's make saturation be -100 to 100 instead of showing the whole power thing.

**Comment by masc4ii** [comment]
So which slider(s) you want to change now 0..100? 
Saturation: 0 is now -100, 1 is now 0, and 3.6 is now 100? So I change the slider range to -100..100 and calc the pow-thing only once - when calling your saturation function?!

**Comment by ilia3101** [comment]
Yes, you said exactly what I meant. Do that for saturation.

I think we should also do this for sharpen (0-100), tint (-100to100) and dark/light strength (0-100).
...Maybe even make dark/light range be 0-100%? What do you think?

**Comment by masc4ii** [comment]
With the latest commit, we have:
Tint & Saturation: -100..100
All Dark/Light/Lighten sliders: 0..100
Sharpen: 0..100
Saturation works now really good without this pow functions. 

> I also noticed that MLV App Qt gets confused if I put decimal numbers in the XML :)

Sure. I told the program that there are integers only. So if there is a float/double value, it won't read it. ;-) It should set the slider to 0 I think.

**Comment by ilia3101** [comment]
Good :)
Your sliders (values) look like this now? ...
![sliders](https://user-images.githubusercontent.com/23642861/33291008-65e4e2b8-d3bc-11e7-831d-7ec577b69451.png)

**Comment by masc4ii** [comment]
No, the Range sliders are diggerent:
![bildschirmfoto 2017-11-28 um 08 06 17](https://user-images.githubusercontent.com/30245296/33306718-f4890dda-d413-11e7-8b2d-2eadf4bbed40.png)

**Comment by bouncyball-git** [comment]
When new file imported, saturation by default jumps to 50. Don't you think it is too much?

**Comment by masc4ii** [comment]
Check out new version. I corrected this yesterday evening.

**Comment by ilia3101** [comment]
Alright let's close this issue. We have this sorted, and I've matched it to yours now.

BTW... another idea: make default dark strength 25 instead of 23, and range 75 instead of 73, sounds more rounded ;)

Old version screenshot just for fun 😉 
![screen shot 2017-11-28 at 20 44 57](https://user-images.githubusercontent.com/23642861/33445561-207b979a-d5f5-11e7-9015-0a19d61c9525.png)
Made me remember why I did the long numbers.. . consistent length

**Comment by masc4ii** [comment]
Hehe :-)
25 and 75 looks very dark for my clips. 25 and 50 would be better, what do you think?
