### ISSUE TITLE
disabling Amaze for export

### ISSUE THREAD

**Issue by seescho** [ilia3101/MLV-App#54]
My astronomical rawvideos often are very noisy because of high ISO and very small aperture (on 6000 mm focal distance). Amaze gives very good and sharp debayering results on normal pics. But on noisy pics this noise gets amplified, too.

I made a test and forced MLVApp, not to use Amaze for export.

If I compare the results (after stacking with autostakkert and heavy waveletsharping with darktable), the non-amaze-version gives much better results (less noise) than the version with amaze.

So I would be happy to have an option in MLVApp for disabling Amaze for export

**Comment by ilia3101** [comment]
This could definitely be done, probably without internal changes even. Simply by having no caching and not enabling alwaysuseamaze for export this would work. Let's wait for masc to add this as an official option ;)

**Comment by masc4ii** [comment]
Yes, that is not difficult to implement in the GUI - no change to the lib needed. I will implement a open field in the preferences dialog for that.

**Comment by bouncyball-git** [comment]
It is somewhat out of topic here, but guys, don't you think that export options dialog should be separated from system wide preferences dialog?

**Comment by masc4ii** [comment]
The option is added and commited. Please try it out.
@bouncyball-git : what about making "dark style" to the default and disabling the option "system" (is anybody using this?) ? The preview option can be added to the context menu of the session list. In the end would be the preferences dialog a clean export settings dialog.

**Comment by bouncyball-git** [comment]
I think yes maintaining two look styles on three operating systems is a real PITA ;).

Regarding preview - can be moved to menu as you suggest.

And we can name this dialog "Export settings"! :-D

**Comment by masc4ii** [comment]
I did that. Please have a try!

**Comment by bouncyball-git** [comment]
Great! :-D
Session list preview mode switching possible from two places. Right click on session or menu view. Good as well :)

**Comment by seescho** [comment]
Disabling amaze works fine. Great!
Could you make this working for cdng export, too?

**Comment by masc4ii** [comment]
Good, cool!
cdng is raw, so it is not debayered at all (no AMaZE and no bilinear).

**Comment by seescho** [comment]
Yes, I thought so, that cdng is not debayered. But than I found this in mainWindow.cpp (lines 1012 ff):

```
//CDNG output
void MainWindow::startExportCdng(QString fileName)
{
    //Disable GUI drawing
    m_dontDraw = true;

    // we always get amaze frames for exporting
    setMlvAlwaysUseAmaze( m_pMlvObject );
    llrpResetFpmStatus(m_pMlvObject);
    llrpResetBpmStatus(m_pMlvObject);
    llrpComputeStripesOn(m_pMlvObject);
    m_pMlvObject->current_cached_frame_active = 0;
    //enable low level raw fixes (if wanted)
    if( ui->checkBoxRawFixEnable->isChecked() ) m_pMlvObject->llrawproc->fix_raw = 1;
```

What is this amaze stuff in here for?

**Comment by bouncyball-git** [comment]
I guess it can be removed from there, I missed that one. @masc4ii: what do you think?

**Comment by masc4ii** [comment]
Yes, this line can be removed. That is a copy-paste error. We need it just in the ffmpeg output.

**Comment by bouncyball-git** [comment]
ok I'll remove it tomorrow.

**Comment by masc4ii** [comment]
done.

**Comment by bouncyball-git** [comment]
:)

**Comment by seescho** [comment]
:)
