### ISSUE TITLE
Explain and tune current caching mechanism

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#55]
I need some clarification on caching part of the proggie. Honestly, I dug to this several times and every time I'm looking at it something's bothering me.

Finally I understood what's bothering me: It is the fact that despite of cache is turned off or on from the gui menu, actually it _IS_ always active with all it;s threads and tries to open/read files.

Am I wrong? Can we completely turn it OFF optionally?! It always causes lot of issues...

**Comment by masc4ii** [comment]
It is always active? Really? For me it is OFF by standard and I can activate it from the menu. When changing the file I disable caching, load new mlv, enable caching (if activated in menu). This is how it should be atm. At least on OSX this works for me. And when I tried on Win, I thought the same.

**Comment by bouncyball-git** [comment]
I mean threads are active all the time...

**Comment by ilia3101** [comment]
Should I add a `#define caching` switch in video_mlv.h so you can completely disable it for debugging?
I'm pretty sure the threads shouldn't be active if caching is 'disabled' as they should not be created in the first place, and if they happen to be, should die instantly. If they are active however, that is strange and I'll have to look in to it on Linux (or whatever your using)

**Comment by bouncyball-git** [comment]
That is why I called this thread "help me" :). I need to fully understand how caching  works. I tried to understand several times but I'm not satisfied with the result.

Calls to 'add_mlv_cache_thread()' function:
1. In video_mlv.c (after mapping mlv) from line 603-609 there is thread starting code.
2. in frame_caching.c (set raw cache limit) from line 79-85 same thread starting code.

**Comment by bouncyball-git** [comment]
I would be very nice to have an option to entirely disable caching.

**Comment by ilia3101** [comment]
`Calls to 'add_mlv_cache_thread()' function:

    In video_mlv.c (after mapping mlv) from line 603-609 there is thread starting code.
    in frame_caching.c (set raw cache limit) from line 79-85 same thread starting code.
`

Just took a look, and i'm surprised, there's no check if caching is disabled!
Maybe I was remembering how old cache system worked (which was crap), maybe that checked.

So you are right, it will start the threads, but they should stop before a single frame is cached due to the presence of this in the cache loop... `if (video->stop_caching) break;`

Strange that it crashes though. I will commit a little change with check if caching is disabled so threads are never created for no reason. Sorry about that.

**Comment by bouncyball-git** [comment]
Cool! Thank you :) You're gonna correct the stuff bothering me since the beginning!
This could potentially fix some strange behavior under windows, we'll see.

**Comment by ilia3101** [comment]
fixed btw https://github.com/ilia3101/MLV-App/commit/64fe7d6ef16aee15b51b9c198d85678914a5148a

**Comment by bouncyball-git** [comment]
Thank you for this fix.

On the other hand I would implement the caching in other way: 

No backgroung caching, just put to the cache frames we already read during playback or scrabbing, hence there not gonna be complicated background thread(s) of function with its hungry manner to hog all CPU and disk IO with it's own file reading mechanism.

In this case caching also be using the existing spanned file reading mechanism and if there is no low level raw correcting settings or debayer method changed, no need to recache anything.

Well.. that are just my thoughts :)

**Comment by masc4ii** [comment]
For me the caching works very well in concept atm: 
- for standard I have it off. So I can have a quick preview without much CPU load
- if I want to go deeper into processing, I use "always AMaZE"
- if I still like, I activate caching for a nice preview, after that I deactivate it
That works pretty well!
Maybe I only would like to have a kind of three-state-button in the toolbar...

**Comment by masc4ii** [comment]
With this latest version, caching is completely dead for me now. I can activate as often I like, it is always idle.

**Comment by masc4ii** [comment]
With that change, it works again:
```
void enableMlvCaching(mlvObject_t * video)
{
    /* This will reset the memory and start cache thread */
    video->stop_caching = 0;
    setMlvRawCacheLimitMegaBytes(video, video->cache_limit_mb);
}
```
Would that be okay?

**Comment by bouncyball-git** [comment]
Yes some changes from ilia broke the qt version cache activation, nice you if you fixed it :)

Will try this out and also will commit very, VERY important fix against very bad crashing and memory corruption I discovered by Valgrind today.

**Comment by ilia3101** [comment]
That's fine if it works  @masc4ii

**Comment by masc4ii** [comment]
Commited. Thx!

**Comment by bouncyball-git** [comment]
We have issues with latest version :(

**Comment by bouncyball-git** [comment]
Hm, after my last commits caching works under Linux without a hiccup! Even with @masc4ii's corrupted MLV. I can't believe this but the facts are stubborn ;)

Please test it further and if all is right I'll close this issue.

**Comment by masc4ii** [comment]
For me that works now! Nice! 
The only problem I have is still under Win32: when activating the app crashes... but we have another issue for that.

**Comment by masc4ii** [comment]
I get crashes, if I enable caching and switch between the clips:
![bildschirmfoto 2017-12-05 um 22 41 07](https://user-images.githubusercontent.com/30245296/33632413-d86b843e-da0d-11e7-8c65-2280331af39f.png)
But for the last 10 tests, I get it only when jumping to one special clip... I will upload it for you.

**Comment by masc4ii** [comment]
@bouncyball-git : here is that MLV: https://www.dropbox.com/s/e5u87rt8t127a9a/M29-1225.MLV?dl=0

**Comment by bouncyball-git** [comment]
Thanx for the clip I'll take a look.

> The only problem I have is still under Win32: when activating the app crashes... but we have another issue for that.

Did you understand what is the exact issue?

**Comment by masc4ii** [comment]
The problem with the clip: load it plus another one. Activate the other one. Enable caching. Select this clip. BAM (in average every 2nd time).
The problem with Win32 caching: no idea. Must ask the debugger...

**Comment by bouncyball-git** [comment]
I committed [some changes](https://github.com/ilia3101/MLV-App/commit/d9065cf8813eab7e24ee48ffc50c0d1b5b470975) for testing.

Whole llrawproc and actually getMlvRawFrameFloat(), which calls it, is barely thread safe. Mutexing whole call did the trick and now crashes are gone. Even responsiveness of the gui is better. No memory corruption during focus/bad pixel map ceration etc.

Windows 64 also works. 32bit is crashing when caching is enabled as @masc4ii mentioned earlier.

Now about NULL pointer initialization: we call free( mlvObject )  before any openMlvClip() anyway and fragmenting the memory with 1-2 byte allocations seems unnecessary to me.

Please test this and if something is wrong I''ll roll back this commit.

**Comment by bouncyball-git** [comment]
@masc4ii: About the MLV you sent me. This is 100D 10bit raw clip which needs focus pixel correction that is why it crashed on realloc-ing the map from several threads. 

Now this part really works as expected but unfortunately, taming of caching thread is very tricky because it makes a call to a huge part of 'thread unsafe' code :) and there is no guarantee that it's not gonna crash again.

**Comment by masc4ii** [comment]
One try, one crash.

**Comment by bouncyball-git** [comment]
Yes 100D has largest amount of focus pixels.

Line 767 for this time is the reading focus pixel maps not writing but anyway seems the buffer already corrupted.

**Comment by bouncyball-git** [comment]
If there is better (correct) use of pthread mutex to mask the whole , please someone help me :)

One hint: maybe main thread is interfering with this moment? During refreshing the screen to the current frame?

**Comment by masc4ii** [comment]
Tried to mutex getMlvRawFrameFloat(), but the problem persists. When caching is en-/disabled, the frame in the screen is not refreshed. 
```
...
pthread_mutex_lock( &mutexLL );
applyLLRawProcObject(video, unpacked_frame, unpacked_frame_size);
pthread_mutex_unlock( &mutexLL );
...
```

**Comment by bouncyball-git** [comment]
Hmm... please check with the latest commit if it helps.

**Comment by masc4ii** [comment]
Unfortunately it does not help :-(

**Comment by masc4ii** [comment]
Tried to make caching single threaded: crashes are not so often then, but after some trys I got crashes again in the same line or pixelproc.c line 767. I don't know where to search... really...

**Comment by ilia3101** [comment]
`getMlvRawFrameFloat()` should not need any extra mutexes, at least the code I'm familiar with (not sure about LLRawProc). I'm pretty certain of this, could be wrong though because I have been a couple times recently... but I think I'm right 😐

**Comment by ilia3101** [comment]
Not sure what's going on here. Beyond my brain's capacity to absorb whole thread sorry. But let me know if I can be any help on anything specific.

**Comment by bouncyball-git** [comment]
Yes I understand quite long time ago that realloc is the issue here but why I can not understand really ;)

Phew.... have to experiment with it more... If you say memory grows and grows it means there is a leak for some reason here.

@ilia3101: unfortunately whole llrawproc is very thread unfriendly with lots of different buffer allocations and reallocations and these buffers are needed to process all consequenced frames in the file. They deallocating on demand by calling dedicated functions.

**Comment by ilia3101** [comment]
```
unfortunately whole llrawproc is very thread unfriendly
```
Ah ok, mutex is a good idea then :) But maybe the mutex should be inside applyLLRawProcObject?

```
memory grows and grows
```
```
Yes I allways knew that realloc is the issue here but why I can not understand really ;)
```
Is this realloc issue inside of MLV code or LLRawProc?

**Comment by bouncyball-git** [comment]
@ilia3101:

Well, yes this realloc reallocates mem for focus or bad pixel maps, but it is working very good when caching thread(s) are inactive and calls made only from the main thread. I've added memory allocating error handling to 'pixelproc.c' today. If error happens during mem alloc the pixel map is not allocated and pixel correction is deactivated. But unfortunately this is not the issue I guess... 

The most bad part is, that I can not reproduce those crashes under Linux because enabled caching now magically works here :(.

As you know raw correction ( llrawproc as I called it then and now regretting it because of strange name ;) ) is not simple and consists of a large part of code with lots of files and functions, buffers, structs. I could try to add the mutexes there but if mutexed whole aplyllrawProcObject() call is not helping to address the issue using mutexes under it will not help either.

I also eliminated all mem leaks which valgrind found in the old MLVFS derived 'dualiso.c' code mostly.
but as @masc4ii confirmed crashes are not gone.

**Comment by bouncyball-git** [comment]
Did some tweaks on this part and it looks like the issue is gone, @masc4ii reported no crashes on mac so far. Under Linux so far so good :), hope this affects windows too, need to check this out.
