### ISSUE TITLE
Add relative path to MASXML

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#56]
I have another idea to improve MASXML:

Imagine a folder with MLV files and a MASXML with edits for all of those files (this is how I organise my edits).

If that folder gets moved to a different drive or location, the MASXML no longer gives the correct path to those files, as it specifies absolute file path.

Solution: MASXML should specify absolute *and* relative file path, that way it's more resilient to changes and moving files around.

**Comment by masc4ii** [comment]
I also thought about that, but my idea was a bit different:
if MLVApp does not find the files, it askes to search using a file dialog. The next files will be searched in both: the saved folder and the new selected one.

**Comment by ilia3101** [comment]
`if MLVApp does not find the files, it askes to search using a file dialog. The next files will be searched in both: the saved folder and the new selected folder.`
I thought that too, the user finds one of the files and it can find the rest automatically. I think both ideas can be integrated.
I think the one in my post is a bit easier to do first though. Maybe we could have an element inside `<clip>` soemthing like `<altPath>`

**Comment by masc4ii** [comment]
Yeah, not bad! :-) I'll try that next ;-)

**Comment by masc4ii** [comment]
Writing works:
```
<?xml version="1.0" encoding="UTF-8"?>
<mlv_files version="2">
    <clip file="/Users/masc/Desktop/Testclips/M15-1953.MLV" relative="Testclips/M15-1953.MLV">
        <exposure>0</exposure>
        <temperature>5077</temperature>
...
```

**Comment by masc4ii** [comment]
Works also with loading! Commited.

**Comment by masc4ii** [comment]
@ilia3101 : can we close?
