### ISSUE TITLE
Getting rid of libpng with its zlib dependency

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#57]
I will get rid of the ugly libpng+zlib dependency with pleasure if it's not used anywhere except of one PNG frame export. Besides I added [TIFF sequence](https://github.com/ilia3101/MLV-App/commit/f549ce64263a2df8295a4694c423ef70fe6233a4) export and with cool cut in cut out feature exporting of actual PNG frame looses it's importance. I even wanted to ask you @masc4ii to implement the export current DNG but it is also pointless now :)

What do you think guys?

**Comment by bouncyball-git** [comment]
It's so pity ffmpeg has no EXR output :)

**Comment by masc4ii** [comment]
Oh, ffmpeg can export 3x16bit tiff? Haha... not bad! We can also have this export single png feature, but use the 8bit Qt output. I used it sometimes, but first action was to make it 8bit...

**Comment by bouncyball-git** [comment]
It can export 16 bit PNG too ;), but I prefer more pro TIFF format.

Well it is not very useful to export 8 bit file. The whole purpose to export one frame is to pixel peep on it, or send to someone also to pixel peep on it :P

However, let's do what you said. Actual frame export will export 8 bit png with QTImage.

Do you both agree to get rid of this annoying dependency? @ilia3101, @masc4ii ? What about cocoa app? Is it depend on this lib?

**Comment by masc4ii** [comment]
Give me 5min... I nearly have it done ;-)

**Comment by masc4ii** [comment]
Ready.

**Comment by bouncyball-git** [comment]
Audio is not exporting you are right.

**Comment by masc4ii** [comment]
The good thing: the png is also stretched now! :-)

**Comment by ilia3101** [comment]
```
What about cocoa app? Is it depend on this lib?
```
no

BTW I'm really happy this dependency is gone, gonna be so much easier to compile!
Tried to do it on my linux laptop before and gave up because of this.

**Comment by masc4ii** [comment]
Yes, now you only need Qt 5.6+ :-)

**Comment by seescho** [comment]
Great

**Comment by bouncyball-git** [comment]
Well our dream finally came true :) Can I close this issue?
