### ISSUE TITLE
Error handling needs more attention.

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#58]
MLV import error handling implemented. Now QT App is not crashing when MLVs are invalid or even 0 byte in size instead message box gives us a clue about file state. Please review the code.

[Here](http://nic.caucasus.net/mlvapp/?dir=&download=invalid_mlv_files.tar.gz) 3 files for testing which causes crash of master branch version before [this commit](https://github.com/ilia3101/MLV-App/commit/2a231643ef52d3d8fd8f578af38863c191697851).

**Comment by masc4ii** [comment]
There are many test cases to verify, but all I try just works. Nice!

**Comment by bouncyball-git** [comment]
Yes there are main errors (which caused crash!) like:
1. file can not be opened for some reason
2. file length is zero bytes
3. file is shorter then the basic header block (16 bytes)
4. file does not begin with MLVI (52 bytes) header

**Comment by bouncyball-git** [comment]
Those 3 example files I've posted above caused immediate crash on import.

**Comment by masc4ii** [comment]
Yes, with these files I tested and your error hndling works good.

**Comment by bouncyball-git** [comment]
Huston! We've got a (strange) problem ;) (before my commit there is no issue)

After adding files to the list (one by one or in a batch) if last file frame number is less then previous file frame number cut out of the previous file is set to the last file frame number?!

example.
1. added video with 25 frames <- cut out = 25
2. added video with 65 frames <- cut out = 12 ????
3. added viedo with 12 frames <- cut out = 12

Phew....... been solving this 2 hours... can not understand why, I'm lost....

**Comment by masc4ii** [comment]
Haha... and here it is again. It was already really difficult to implement cutIn / out exactly because of this. And I wanted never to change anything here after I got it to work. Now we have the fun ;-)

**Comment by masc4ii** [comment]
I know why: you first load the file and add it to the session after that. That does not work with the actual concept, because you set the frameCount to the "actualFile". And this one, is the still the last.

**Comment by masc4ii** [comment]
Try out latest commit.

**Comment by bouncyball-git** [comment]
Yes now it should work. I thought about deleting file from session after adding it and is seemed not so pretty solution to me, If there is no other way around we can do nothing about it. Maybe if we rework whole thing from scratch as you say for fast loading then we could make prettier this code too.

I also thought about rewriting the whole C thing into C++ libs, what will play along with QT nicely. It will be very time consuming thought ;)

**Comment by masc4ii** [comment]
Okay... so, now it works for you? Then this is v0.12 now?!
I would not rewrite C modules to C++. I think that is not neccessary. Qt loads a lot of overhead, what is not needed in the processing & debayering libs.

**Comment by bouncyball-git** [comment]
Yup it works :) thank you, we can now release v0.12.

Well yes plain C++ (not qt style) adds some overhead but not that big. Anyway rewriting will be the whole another project so I'm not gonna do this any soon :)

You meant MLV functionality (written in C) wrapper QT (C++) libs in separate .cpp/.h files right?

**Comment by masc4ii** [comment]
Ah... you mean "Qt-less" C++... okay... that maybe good here and there ;-)
But for now it works good enough... I am still happy with the actual release...

**Comment by bouncyball-git** [comment]
Me too :)

**Comment by ilia3101** [comment]
If I began to write this again, I would use c++, but I only knew c then :)

Any way, works for now.

**Comment by bouncyball-git** [comment]
Now you even know Objective C. But all is working as is an we are happy with it :). Besides I always loved pure C.

**Comment by bouncyball-git** [comment]
Will close it for now.
