### ISSUE TITLE
100D file + caching enabled = crash

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#60]
There are many parts of the discussion in many commits... it is hard to find. So from now on, please let us discuss here about the problem.
For everybody who don't know the problem:
- loading a mlv from a 100D
- enable the right focus pixel fix (on/crop)
- enable caching
- load any other file
- doubleclick (load) the first file again
- by 95% (at least on OSX) the app crashes now
- it does not happen on Linux
- nobody knows if it happens on Windows... caching is not working there, so the app crashes before being able to test this bug

**Comment by masc4ii** [comment]
What we already tried wihtout success:
- caching = single threaded
- mutex around getRawFrameFloat()
What we tried with "half" success:
- make malloc for focus pixels way to big, so realloc is never needed -> no crash

**Comment by ilia3101** [comment]
Mutex around LLRawProc didn't help?

So is realloc too often the problem?

**Comment by masc4ii** [comment]
So my understanding. But I may be wrong.

**Comment by bouncyball-git** [comment]
Yeah, very strange. However I kinda thought caching thread interferes with the "QT rendering thread" they are not using same mutexes.

**Comment by masc4ii** [comment]
I switched off the Qt rendering thread and it still happens.

**Comment by bouncyball-git** [comment]
S..T !

**Comment by masc4ii** [comment]
For me this seems to be fixed with [this](https://github.com/ilia3101/MLV-App/commit/12960febdcd2b7b48c176ce256018fc68c5cbbbf) commit.
