### ISSUE TITLE
debayer for preview amaze_cached: no more raw-corrections

### ISSUE THREAD

**Issue by seescho** [ilia3101/MLV-App#63]
some raw-corrections dont´t show any effect on playback screen, if I switch to amaze_cached for playback (bilinear and amaze show no problems).
Tested with chroma smooth and bad pixel fix.

**Comment by bouncyball-git** [comment]
Which one is not working? Maybe all processing is off?

**Comment by seescho** [comment]
I can see this behavior here:

Pattern noise
Fix bad pixels
Chroma smooth

I cannot test:

Fix focus dots (no cam with focus dots here)
Vertical Stripes (cannot see vertical stripes in my astro videos)
dual ISO (no such clips)
deflicker taget (don´t know what that is and what it shall do)

Raw correction is "ON"

Example "chroma smooth":

Preview mode bilinear and amaze:
--- works like expected. all is fine.
Preview mode amaze_cached:
--- I can switch between off, 2x2, 3x3, 5x5
--- The buttons, I press, change their background from black to gray
--- But no effect can be seen in the preview picture

**Comment by masc4ii** [comment]
Right. I see the same with Focus Pixels on OSX.

It would be right, if you do not see the result immediately - that is right as it is, because the picture is not updated. But normaly it should change as soon as another frame is selected (via position slider or next/prev frame). But this does not happen.

**Comment by bouncyball-git** [comment]
Can you be more specific how to reproduce this? For me it is working as expected for bad pixels and for focus pixels. ( ah again this caching code ;), I definitely have to implement my caching proposal I've talked about in issue I created a wile ago. )

**Comment by masc4ii** [comment]
1. Open 100D file
2. activate caching
3. try to change focus pixels, it won't work

**Comment by masc4ii** [comment]
How to solve it the easiest way: deactivate caching, activate caching. But that is not so nice...

**Comment by bouncyball-git** [comment]
Ah, now I understand what you mean :)

I think it is expected. All cached images will be llraw processed with initial settings. To make focus pixels off setting work you must recache all frames again what was never been implemented.

**Comment by masc4ii** [comment]
Would be sufficient, if we bring a MessageBox (including a "Hide always" checkbox) when activating caching, which tells something like: "To see changes to RAW correction parameters in viewer, deactivate caching." ?!

**Comment by bouncyball-git** [comment]
Or... when correction parameters changed along with resetting the BPM and FPM status set caching status to recache all.

**Comment by masc4ii** [comment]
This would be the best solution, indeed!

**Comment by bouncyball-git** [comment]
If we leave the caching part as it is now ( almost separate "program" ;) ) it always will stick into rolling wheel :)

**Comment by bouncyball-git** [comment]
> ut if you are not at frame 1, it will need some time to actualize the frame (and when it is ready for showing up?)

If I remember correctly there is some helper array for caching status of every frame and according to this status proggie gets frame from the cache or renders it from scratch if it's not cached yet. 

Well at least I hoped it works like this :), but you say that actualization of amaze rendered frame will be very late if current frame is for example 5th frame from the end of the clip. It's odd!

**Comment by ilia3101** [comment]
When LLRawProc is changed and caching enabled, call clearMlvCache after any LLRawProc changes. It's what I put in the cocoa app since a long time ago and maybe forgot to tell you to add it.

**Comment by ilia3101** [comment]
You can call reserMlvCache even if caching is off and is won't do anything, just call it every time when setting LLRawProc settings.

**Comment by bouncyball-git** [comment]
Hmm... have to try that huh? @masc4ii

**Comment by masc4ii** [comment]
That does the job I think! Thx!

**Comment by seescho** [comment]
Works fine now. Thx all!
