### ISSUE TITLE
When exporting DNG set proper 'DefaultScale' tag for anamorphic or vertical stretched clips

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#66]
1. I think taking into consideration horizontal and vertical stretch combo box values when exporting DNGs is a good point. Needs passing values of those combos to the 'dng.c'. (anamorphic can not be detected and should be set manually)

2. Also auto detecting and setting vertical stretch combobox is not working at the moment.

**Comment by masc4ii** [comment]
No problem. I can pass a float value to dng.c for x and y stretch. Just give me a function... ;-)

**Comment by bouncyball-git** [comment]
I did it already, will show to you shortly, just one problem:

I wanted to use 'on_comboBoxHStretch_currentIndexChanged()' to make sure that value is changed at least once. But it is changed already when we set the value not just by mouse, but with ui->comboBoxHStretch->setCurrentIndex(true), and this is ruins my whole idea :)

**Comment by masc4ii** [comment]
Don't use the index. In the receipt there is saved the float factors.

**Comment by bouncyball-git** [comment]
What is saved to the receipt does not matter for this action, matters only currentIndex()

**Comment by masc4ii** [comment]
You have no current index on export. You only have access to the receipt.

**Comment by masc4ii** [comment]
m_exportQueue.first()->stretchFactorX() and m_exportQueue.first()->stretchFactorY()

**Comment by bouncyball-git** [comment]
It works, because I'm parsing the index and build array with 4 ints needed for verical and horizontal stretchin.

example array[4] = { 4, 3, 5, 3 } it means horizontal stretch is 1.333333 and vertical is 1.6666667 :)

**Comment by bouncyball-git** [comment]
I even suggest to use this format for receipt and for session

**Comment by bouncyball-git** [comment]
you can see yourself, just export the DNG with unusual v/h stretching and look at the exif with exiftool.

**Comment by bouncyball-git** [comment]
Could you help me with this?

I need additional two values: STRETCH_H_DEFAULT = 0 and STRETCH_V_DEFAULT = 0

Can we initialize stretchFactorX and stretchFactorY with those values if combo boxes have not been touched at all?

**Comment by masc4ii** [comment]
For now I initialize with 1.0, what means output = input. What is the benefit with a factor of 0?

**Comment by bouncyball-git** [comment]
0 factor got no benefit as a factor. I just need to distinguish case when stretch factor is changed manually and when it have not been touched at all and 0 stretch value would be ideal indicator for this. Could you suggest something for this matter.

**Comment by masc4ii** [comment]
I thought 1.0 is the same as untouched. Do you want to make anything different between untouched and 1.0?

**Comment by bouncyball-git** [comment]
Yup, now it works exactly like this except of auto detection instead of right after importing is done before exporting :).

**Comment by masc4ii** [comment]
Exactly. And the user would see the right aspect ratio from the beginning (import). Would be nice if we get that to work! :-)

**Comment by bouncyball-git** [comment]
Hey man I have to appologize to you again ;).

It's turned out that [HERE](http://nic.caucasus.net/mlvapp/) when I gave you links for vertically squashed MLVs with RAWC and without RAWC block. I put shortenet MLV with mlv_dump and it did not include the RAWC into output MLV :P.

Now I've updated mlv_dump and it is working correctly. g3gg0 forgot to implement exporting RAWC into saved MLV.

Please redownload '5x3_aspect_ratio_RAWC.MLV' file and you're gonna have real thing to experiment with stretch detection.

**Comment by masc4ii** [comment]
Okay, donwloaded. Should the autodetection work already? If yes, it seems I make something wrong with it...

**Comment by bouncyball-git** [comment]
Yes I saw the changes in setSliders() but is does not work now, does not set the combo box.

**Comment by bouncyball-git** [comment]
I'll check the return value tomorrow.

**Comment by masc4ii** [comment]
Yes, please check. If I turn the if to the opposite the checkbox is set and the frame is stretched. I get getMlvAspectRatio( m_pMlvObject ) = 0 for 5D2 files (that should be fine) and = 1 for most others.

**Comment by masc4ii** [comment]
Got it. Works with [this commit](https://github.com/ilia3101/MLV-App/commit/2596b1136fa48f302b14b6a15362f9246ba2bb6a).

**Comment by bouncyball-git** [comment]
Now this fully works! Closing.
