### ISSUE TITLE
CutIn/CutOut and deleting clip from session issue

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#68]
Here is the [mp4](http://nic.caucasus.net/mlvapp/?dir=&download=cutin_cutout_problem.mp4) explaining the problem.

**Comment by masc4ii** [comment]
Ups... I will have a look.

**Comment by masc4ii** [comment]
Could you try out? I hope I got it fixed.

**Comment by bouncyball-git** [comment]
Fantastic! :)
