### ISSUE TITLE
Win32: console windows on startup

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#69]
When starting the latest revisions on windows, there are shown 5 console windows for some seconds. They close automatically. But this is not nice... 
Is it possible to not open these windows? 
I think they came with the filters function - 5 consoles - it might be for the 5 availlable filters. But I don't know atm which function opens the console windows.

**Comment by bouncyball-git** [comment]
Hmm... why the filter init code should use console? Is there a call to external executable?

**Comment by masc4ii** [comment]
The configs are are written to disk in temp files and loaded again to the program...

**Comment by bouncyball-git** [comment]
I guess it does writing temp files in a strange way, otherwise I can not understand why it should use console.

**Comment by masc4ii** [comment]
Yes, to me that looks strange too. I think Ilia got this from the original author. I am sure there is a better way to do the same... but I did not found out, where exactly this console is called. The problem is: the console opens on Windows only.

**Comment by bouncyball-git** [comment]
> The problem is: the console opens on Windows only

As always ;)

**Comment by bouncyball-git** [comment]
I've also looked trough genann.c and filter.c and can not find any direct console writing hint... for linux temp data is written to mem, for other 2 oses to the temp files.. that's all.

**Comment by ilia3101** [comment]
This is so strange!!!

**Comment by ilia3101** [comment]
the temp files are deleted with a console command ("rm tempfile" or something). Is there a windows C api to delete a file by name?

**Comment by bouncyball-git** [comment]
Hehe can you please point the exact line and file where this is done?

**Comment by bouncyball-git** [comment]
I can confirm that no console windows are showing up on latest Win64 version.

**Comment by masc4ii** [comment]
That's good @bouncyball-git . 
@Ilia: I think it is "del" on windows. The Qt Console was not showing an error when I tried with del... but I did not commit until now.

**Comment by masc4ii** [comment]
Checked it. Console is away. :-) Good job!
