### ISSUE TITLE
Black/Highlights clipping indication on histogram.

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#70]
Could this be added to the histo?

**Comment by masc4ii** [comment]
I think yes :-)

**Comment by masc4ii** [comment]
Is it okay to have that only when zebras is activated? If not this feature makes everything veeeery slow (slow as when zebras is active). I get a max of 2fps with that.

**Comment by bouncyball-git** [comment]
Yes sure :)

**Comment by masc4ii** [comment]
Does it work as expected?

**Comment by bouncyball-git** [comment]
Yes pressed Z and it is working :)

**Comment by bouncyball-git** [comment]
We can close this thread.
