### ISSUE TITLE
cDNG export: different timecode video & audio

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#72]
When exporting cdng, and importing it in Resolve:
Timecode audio: starts always at 0
Timecode video: starts not at 0
So video and audio does not fit, even when it is linked.

See timecode differences here:
<img width="718" alt="bildschirmfoto 2018-02-05 um 12 42 29" src="https://user-images.githubusercontent.com/30245296/35802891-228ff150-0a72-11e8-900d-f369441b6f30.png">

Upper audio is the linked one, below the original wav (audio only).
<img width="1425" alt="bildschirmfoto 2018-02-05 um 12 43 00" src="https://user-images.githubusercontent.com/30245296/35802898-29a92dda-0a72-11e8-814b-c3bfeac02b84.png">

**Comment by bouncyball-git** [comment]
I'll take a look

I'm so lazy to reboot to windows and check this in resolve :-D
There is resolve 14 free version for Linux but regrettably audio is not working if you got no BM audio card :-P and I removed it long time ago.

**Comment by bouncyball-git** [comment]
Very strange duration is the same but time code is so off?!

**Comment by masc4ii** [comment]
Exactly. Should it start always at 0?

**Comment by bouncyball-git** [comment]
Hehe you found the bug (btw my mlv_dump is not affected with this bug, this code automatically inherited from mlv_dump's dng.c, but unfortunately this should be treated in MLV App differently). 

Now time code for all frames is the max time e.g. the time of the last frame. This is very easily correctable but...

There is a caveat: if cutin is set to > 0 then things getting complicated. We should decide start the timecode from zero for cut clip or leave it as is (dng numbering remains unchanged, if cut in is 4 dng starts from 3) and somehow put timecode to cut WAV header! I vote for second approach, what do you think?

**Comment by bouncyball-git** [comment]
Or! I came up with universal solution:

Always start time code from 0 but change the recoding start time = old time plus start frame time, so no hassle with WAV header and if FPS was overriden the time will be correct. Also this can be implemented to cut MLV export. Set the RTCI block time = old time plus start frame time.

What do you think?

**Comment by masc4ii** [comment]
If fps is overriden, there is no audio. But if I read, you think last idea is the best?! If it is easy and universal, than do it ;-)

**Comment by bouncyball-git** [comment]
Yes I know :) my bad.

**Comment by bouncyball-git** [comment]
commit 6b747380128c93078250db9d0d3a754b7dfc5e5b for now. Try please.

**Comment by masc4ii** [comment]
You wrote in the commit "will not work with cut audio"?

**Comment by bouncyball-git** [comment]
please try with resolve, whole clip then cut clip.

**Comment by bouncyball-git** [comment]
Every frame before this fix had same time code which was clip duration, now every frame has correct incremental time code.

**Comment by bouncyball-git** [comment]
For cut clip:video timecode will be 00:00:00:something and for audio 00:00:00:00. I guess.

**Comment by bouncyball-git** [comment]
The universal approach I've been talking about need more time. I'm tired today ;) seya tomorrow.

**Comment by masc4ii** [comment]
Okay, no problem. Cya!
For uncut clip it works, for cut clip it doesn't - as expected:
![bildschirmfoto 2018-02-05 um 19 11 45](https://user-images.githubusercontent.com/30245296/35821251-a8bbeb4a-0aa8-11e8-8bee-80f09ffe039b.png)

**Comment by bouncyball-git** [comment]
Thanks :), I wish we could get the WAV time code information.

**Comment by bouncyball-git** [comment]
I guess I got it all is in this struct:

typedef struct {
    char description[256];
    char originator[32];
    char originator_reference[32];
    **_char origination_date[10];      //yyyy:mm:dd
    char origination_time[8];       //hh:mm:ss
    uint64_t time_reference;_**
    uint16_t version;
    uint8_t umid[64];
    int16_t loudness_value;
    int16_t loudness_range;
    int16_t max_true_peak_level;
    int16_t max_momentary_loudness;
    int16_t max_short_term_loudness;
    uint8_t reserved[180];
    char coding_history[4];
} wave_bext_t;

**Comment by bouncyball-git** [comment]
uint64_t time_reference; is what we need for time shift. OKOkOk I'm gone ;)

**Comment by bouncyball-git** [comment]
Committed [f69d7d4dc828745523bb805681c36c816e9af0d6](https://github.com/ilia3101/MLV-App/commit/f69d7d4dc828745523bb805681c36c816e9af0d6) changes. Please try in resolve.

Changes:
1. Wav header updated and very interesting how resolve will interpret the metadata
2. Changed timecode inserting ideology to DNGs, it is done according actual MLV frame number.
3. Changed the way DNGs file numbering, now it always matches actual MLV frame number, even when it is cut and exported as an separate MLV, the numbering is not changed, now we always know exactly what frame it was from the start of recording (date/time in RTCI)

Predicted resolve behavior:
1. For full clip A/V time code will match 0 to 0
2. For cut MLV A/V time code also should match nonzero to nonzero
3. For exported MLV A/V should match zero to zero
4. For cut and exported MLV A/V should match nonzero to nonzero

**Comment by bouncyball-git** [comment]
I think sample calculation is wrong... wait.

**Comment by masc4ii** [comment]
Tested 1. and 2., does not fit for both:
<img width="1159" alt="bildschirmfoto 2018-02-06 um 12 45 01" src="https://user-images.githubusercontent.com/30245296/35858124-a734bbe2-0b3b-11e8-8b44-1ae66808a100.png">
<img width="1077" alt="bildschirmfoto 2018-02-06 um 12 44 49" src="https://user-images.githubusercontent.com/30245296/35858131-aa55ad18-0b3b-11e8-94e5-20e7befe9d25.png">
1. Audio is too long
2. Offset does not fit

**Comment by bouncyball-git** [comment]
I know there was veeery ugly bug in calculations. Try now. I even installed 14.3 resolve to test it out ;)

please try the following cases:
1. export DNGs with uncut clip (tc should be vid 0/aud 0)
2. export DNGs for cut clip (tc should be vid Xval / aud Xval)
3. export cut MLV and then export DNGs from this cut MLV (tc should be vid Xval / vid Xval)

**Comment by masc4ii** [comment]
A quick coffee break test: 1.-3. OK! Great!
