### ISSUE TITLE
Export audio track (wav, cut wav) of the current clip

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#73]
Sometimes I need to export audio only of the current clip. What about adding:

`Export Audio Track`

In the File menu under the 'Export Actual Frame' with hot key 'Shift-Ctrl-A', 
CutIn & CutOut should be taken in consideration.

What do you think?

**Comment by masc4ii** [comment]
Yes, good idea. I also thought about that. Shouldn't be too complicated.

**Comment by masc4ii** [comment]
Done. But a bit different: I added it as codec "WAV (Audio Only)". So batch is done as well and realization was really easy.

**Comment by bouncyball-git** [comment]
Hehe cool! Thank you. I guess time code also works because it is there already :)

**Comment by masc4ii** [comment]
Japp. When I thought about, I saw that all was nearly there already... ;-)

**Comment by bouncyball-git** [comment]
Yes me too :)

One problem: after exporting is finished progress window not disappearing.

**Comment by bouncyball-git** [comment]
Like this :)

![screenshot from 2018-02-10 13-40-10](https://user-images.githubusercontent.com/17232233/36060701-16797cac-0e68-11e8-9c72-a3f3be89dc12.png)

**Comment by masc4ii** [comment]
Höööö... what's that?! Very strange.

**Comment by masc4ii** [comment]
`m_pStatusDialog->hide();` is only a few lines in front of the messagebox... And what is inside your statusdialog?!

**Comment by masc4ii** [comment]
Could you try? I made a commit.

**Comment by bouncyball-git** [comment]
The same. I had this problem if during MLV exporting there was an error and error dialog appeared. m_pStatusDialog->hide(); is also there but works like you see on the picture above. Clears progress bar in the window but leaves window itself with garbage inside. That is why I left it not hidden and when error dialog is shown it always under the progress bar window. However hiding somehow working in DNG export and I can not understand why ;)

**Comment by masc4ii** [comment]
Another try... don't understand it... and it does not happen on OSX.

**Comment by bouncyball-git** [comment]
The same, well I knew this is the problem under Linux (I have tried lot of things while ago to solve this, but alas, I hoped you could help me), but I can not understand why it works for DNG export ;)

**Comment by masc4ii** [comment]
And one more try. In cdng export it does not return after the messagebox and could call some more statusdialog messages... tried the same here now.

**Comment by masc4ii** [comment]
OR: could you try to delete the return after `abortExport()` please?

**Comment by bouncyball-git** [comment]
:( nope did not help. Maybe I'm using some buggy QT version? 5.9.1 Linux.
What puzzles me most is why hiding is working for DNG export then...

**Comment by bouncyball-git** [comment]
the chek   -  if( !doesMlvHaveAudio( m_pMlvObject ) ) is for error message box, but I'm talking about successful exporting. And even doing hiding outside this check is not woking. As it was for MLV export.

**Comment by bouncyball-git** [comment]
Very strange

**Comment by bouncyball-git** [comment]
Can you compare the hiding with DNG export? Why it is working there?

**Comment by masc4ii** [comment]
There are differences... yes. But I need a Linux with Qt to try all that out. I don't see a "real reason" right now... :-(

```
            //Set Status
            m_pStatusDialog->ui->progressBar->setValue( i - ( m_exportQueue.first()->cutIn() - 1 ) + 1 );
            m_pStatusDialog->ui->progressBar->repaint();
            m_pStatusDialog->drawTimeFromToDoFrames( totalFrames - i + ( m_exportQueue.first()->cutIn() - 1 ) - 1 );
            qApp->processEvents();
```
e.g. this is never called in WAV export.

**Comment by bouncyball-git** [comment]
This do not make sense for me too. The hide() or close() should work anyway, but... they don't :)

**Comment by bouncyball-git** [comment]
Commit fc056dc64a1cebd3e58af059a19a6158d1e37c85. Please check

**Comment by bouncyball-git** [comment]
I guess this can be closed.
