### ISSUE TITLE
Dark Frame Gui

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#75]
@masc4ii 

When MLV has internal darkframe as you know Int button is activated when deleting the MLV from session list Int remains being active and selected. It is not the case for Ext button which on deletion of the clip gets disabled and deselected (Off is selected). Can you help quickly correct this?

**Comment by masc4ii** [comment]
I need more info. Was it the only clip in session before or are there other clips? Is it shown wrong for "no clip" or for the next automatically selected clip?

**Comment by masc4ii** [comment]
Maybe have a look here in `setSliders()`:
`ui->toolButtonDarkFrameSubtractionInt->setEnabled( llrpGetDarkFrameIntStatus( m_pMlvObject ) );`
If `llrpGetDarkFrameIntStatus` can be more than just 0 and 1, this could bring a problem like this.

**Comment by bouncyball-git** [comment]
OK thanks I'll try.

**Comment by masc4ii** [comment]
Changed your commit slightly with https://github.com/ilia3101/MLV-App/commit/1254ac65819273845822393fdcef59165ca0ebea

It is done with that? You want that also in v0.14? Then I compile again and upload...

**Comment by bouncyball-git** [comment]
I did want to change deletesession() func :) Now it is lot more better! Thanx!

And yes why not include it into 0.14?

**Comment by masc4ii** [comment]
Okay. Update loads...
