### ISSUE TITLE
Audio sync according to first video frame time stamp

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#77]
This is the continuation of this thread: [LINK](https://github.com/ilia3101/MLV-App/commit/0ae7f8883dba8c8cf5fd1801be5c2c21825cd814)

Look how precise this sync is:

BookSync.MLV. It is synced to 1milisecond + 12samples = 60 samples all. This long zeros been added in the beginning of the audio data.
![booksync](https://user-images.githubusercontent.com/17232233/36642402-58b5bf08-1a58-11e8-98df-3d1a8b46ae96.jpg)

BikeSync.MLV. There have been cut 558miliseconds at the beginning
![bikesync](https://user-images.githubusercontent.com/17232233/36642432-c5103a7a-1a58-11e8-9358-baeb0a83c8be.jpg)

BUT, there is very ugly mistake made in this example! If you will look at the left and right channel waveforms of original and synced wav very carefully you will see that they are swapped ;)

I'm doing rounding to even number of bytes, but I had to do 4byte rounding to account both channels correctly, one stereo sample = 4bytes not 2... ehh... have to do my math again :)

Edit: This also concerns to cut-in alignment. It have to be 4 bytes instead of 2.

**Comment by masc4ii** [comment]
Maybe another export option for h264 / h265?

**Comment by bouncyball-git** [comment]
Yes why not.

**Comment by masc4ii** [comment]
For you it was working? I only get crashes without any error message. Maybe may graphics card is not able to do that :-(

**Comment by masc4ii** [comment]
Ah... -loglevel 0... hehehe. `Unknown encoder 'h264_nvenc'` Is there a newer ffmpeg version necessary?

**Comment by masc4ii** [comment]
It seems that needs CUDA >= 2.0, I have 1.0. :-(

**Comment by bouncyball-git** [comment]
I was lucky to use the ffmpeg version with nvenenc on windows. On Linux I got the same error you have. We have to compile for macos and Linux. ffmpeg included In Win64 version of MLV App has all these features compiled.

**Comment by bouncyball-git** [comment]
This issue should be fixed now after commit 3255c70d411b04d1f291a4b08bae7b181cae92c5.

**Comment by bouncyball-git** [comment]
I hope I ironed out last bug causing crash on some long delayed audio MLVs, so I'm gonna close this issue for now.
