### ISSUE TITLE
Resize setting enhancement.

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#79]
@masc4ii 

What do you think if in export settings dialog beside of resolution would be added aspect ratio lock check box?

Behavior:
If this check box checked vertical resolution will gray out and only horizontal resolution is activated. During batch export every clips horizontal resolution will be upscaled/downscaled to specified value and the vertical resolution of the clip will be accordingly scaled maintaining calculated clips aspect ratio. This will eliminate need of any resolution presets.

**Comment by masc4ii** [comment]
Done. 
![bildschirmfoto 2018-03-03 um 20 35 53](https://user-images.githubusercontent.com/30245296/36938492-8002b664-1f22-11e8-91bc-e37cf29330e9.png)

**Comment by bouncyball-git** [comment]
Hey! COOL! :)
