### ISSUE TITLE
How to use the camid getting matrix functions?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#80]

**Comment by bouncyball-git** [comment]
Sorry about late answer. It is very simple.

These are funcs from cam_id.h:

This one is for getting the index of array for the given camera model ID:
const char* camidGetCameraName(uint32_t cameraModel, int camname_type);

There funcs are using func above to get info by camera model ID:
int32_t* camidGetColorMatrix1(uint32_t cameraModel);
int32_t* camidGetColorMatrix2(uint32_t cameraModel);
int32_t* camidGetForwardMatrix1(uint32_t cameraModel);
int32_t* camidGetForwardMatrix2(uint32_t cameraModel);
int32_t* camidGetHFocalResolution(uint32_t cameraModel);
int32_t* camidGetVFocalResolution(uint32_t cameraModel);
int32_t camidGetFocalUnit(uint32_t cameraModel);

To get matrix 1 or 2 use first 2 functions. How ever the matric you need it the matrix2.

Example:
int32_t * 5d2_camera_matrix2 = camidGetColorMatrix2(0x80000218);

all camera model IDs are in the cam_id.c file
Thats all :)

**Comment by bouncyball-git** [comment]
it returns vanilla matrix with dividers ( hated byt you ;) ). I could write some funcs which will return float matrix without divider to eliminate more work for you . Need it?

**Comment by ilia3101** [comment]
Thanks for the explanation, it was really helpful. Sorry didn't reply at the time

The dividers are alright :)

**Comment by bouncyball-git** [comment]
[Some info](https://forums.adobe.com/thread/398450)
