### ISSUE TITLE
How to use anamorphic preview in QtApp?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#81]
Can't find it anywhere :(

**Comment by masc4ii** [comment]
Right menu, go as much as possible to the bottom. There you find "Aspect Ratio". Expand if it is collapsed. Set what you want there...

**Comment by masc4ii** [comment]
![bildschirmfoto 2018-03-13 um 20 22 38](https://user-images.githubusercontent.com/30245296/37364975-4da24b9e-26fc-11e8-8053-f11438c0417b.png)

**Comment by ilia3101** [comment]
Ahh thanks!
