### ISSUE TITLE
v0.15

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#85]
Hi @ilia3101  & @bouncyball-git ,
I wanted to ask you, if you have still plans for the next version v0.15? Are you still working on features? Do we want to release a new version? Last version was released 43days ago and has 1142 downloads now.
- White balance in general: later
- wbPicker: also later
- what about a faster blur algorithm?
- audio in AVFoundation: I think no one is working on it, right? -> later
- other topics?

What do you think? Do you see this different? etc. ...

**Comment by bouncyball-git** [comment]
I'm cool. Not gonna update anything.

**Comment by masc4ii** [comment]
Cool! Have fun! 😄 So we could release in a week?

**Comment by bouncyball-git** [comment]
If Ilia has no objections we can release it right away :)

**Comment by ilia3101** [comment]
Ah sorry didn't see. Yea, no `WhiteBalance` yet for this release, as I haven't finished sorting out highlight reconstruction (and correct multipliers). I see no problem with releasing it now, if none of you find any serious problems.

**Comment by masc4ii** [comment]
Good! Thank you! I released v0.15 - at least for OSX. I have no Windows PC here now, maybe in one or two days I can compile the 32bit Win version.
