### ISSUE TITLE
DualIso -> black image

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#89]
From @dannephoto  (in ML Forum):
I tried enabling dualiso on this file but it turns completely black(eosm)?
https://bitbucket.org/Dannephoto/magic-lantern/downloads/M24-0848_10frames.MLV

I can reproduce here, but have no idea. @bouncyball-git , could you please have a look?

**Comment by bouncyball-git** [comment]
I'l take a look

**Comment by bouncyball-git** [comment]
I've rewritten the code but not quite satisfied with the result (pink highlights). I guess I have to set processing object white an d black levels accordingly. Theoretically this could help to fix the dual iso preview picture too. Need more time.

To be continued...

**Comment by dannephoto** [comment]
Dualiso neverending code story :)

**Comment by bouncyball-git** [comment]
Yup ;)

**Comment by bouncyball-git** [comment]
Hey guys try las commit and share your findings :)

I tried to trace the bug but unfortunately Dual ISO preview is still half broken (pink shades, etc). I think it is no big deal. This is the low quality preview after all and it work in all other modes.

**Comment by masc4ii** [comment]
A lot of discussion was here:
https://github.com/ilia3101/MLV-App/commit/5e31f96baca5a8f54657c7365a6c167c7a44c8ba#commitcomment-29235754

**Comment by masc4ii** [comment]
The pink highlight problem comes from here:
raw_processing.c, line 341 `if (tmp1b == processing->highest_green)` (make it `...<= highest_green/2` and the pink highlights + some more areas are gone), and the place where highest_green is calculated (that seems not be correct for dualIso, just for non-dualIso). We should think about, how to get this value for dualIso... :)

**Comment by dannephoto** [comment]
Great progress!

**Comment by bouncyball-git** [comment]
I'll take a look but please provide me with the sample to reproduce. On all clips I have there are no pinks at all.

**Comment by bouncyball-git** [comment]
You are right, if tone mapping is turned off pinks are clearly showing up on low exposure values.

**Comment by masc4ii** [comment]
Take the clips from Danne you gave me yesterday, set exposure to -2, and then the sky is pink ;)

**Comment by bouncyball-git** [comment]
if (tmp1b <= processing->highest_green/2) does not help here. Does not matter highligts reconstruction turned on or off.

**Comment by masc4ii** [comment]
<img width="1347" alt="bildschirmfoto" src="https://user-images.githubusercontent.com/30245296/40963879-e7283208-68a9-11e8-8ad6-ebc88e6d768a.png">

Turned on only. But you're right... hm... what else did I change yesterday?! Strange :(

**Comment by masc4ii** [comment]
It was >= not <=. 
<img width="1347" alt="bildschirmfoto 2018-06-05 um 10 14 11" src="https://user-images.githubusercontent.com/30245296/40963977-358e8b72-68aa-11e8-8e3b-275c4509ef23.png">
But look the tree is brown now ;)

**Comment by dannephoto** [comment]
Haha, brown

**Comment by masc4ii** [comment]
Played around... `>= highest_green * 0.95` does still work, at `>= highest_green * 0.97` it stopps working.

**Comment by bouncyball-git** [comment]
Eh... those pinks of course are overexposed clipped areas. Normally exposed part were also pink before I made my changes. Now we need to go deeper into highligh reconstruction ;). I wonder when these is gonna end :D

**Comment by masc4ii** [comment]
Ah okay... never had different pink areas than those. 😄

**Comment by bouncyball-git** [comment]
It is working for me for max *0.93.

**Comment by bouncyball-git** [comment]
could we just put *0.9 and test other non dual iso footage if it works?

**Comment by masc4ii** [comment]
The right way should be to scan the picture/clip for the highest (possible?) green. It is calculated in another function (you'll find with project search).

**Comment by bouncyball-git** [comment]
However there is a strange behavior. If you lower the exposure gradually with slow pace you will see that on some values pinks are not present then lowering more they showing up and then after some more lowering they disappearing again ;) F..k! I don't like this...

**Comment by bouncyball-git** [comment]
What I really can not understand why present code is not working. All processing operations are done on 16bit data which already debayered no matter it was dual iso corrected or not. All present calculations should be valid for any source data.

**Comment by masc4ii** [comment]
Yes we always highlight-correct the processed picture and not the raw. This may happen (with correct highest_green it was nearly never visible, and with this factor 0.9x it is worse now. If you switch to Linear it is worst. But it works for non-dualIso.

**Comment by bouncyball-git** [comment]
So what we're gonna do now? Find highest green separately? Hasn't it (code I mean) always tried to do so for every fed in footage?

**Comment by masc4ii** [comment]
I try to understand what @ilia3101 implemented. For me it looks like he precalculates a matrix for all possible input values, calculates with these matrix the highest possible green, and this one gets corrected later. (max green was overexposed and cut at maximal input value)
But maybe the highest possible matrix green (maximal input value) is higher than the real green, because the real one is moved down darker in the dualIso function (so maximal input value is never reached). Could that be? The behaviour between possbile dualIso green values and possbile normal green values should be different.

**Comment by masc4ii** [comment]
I got a solution, but it is slow. I search through all the actual picture for the highest green (raw_processing.c, line 308, add this):

```
    /* find highest green in actual picture */
    uint16_t highestGreen = 0;
    for (uint16_t * pix = img; pix < img_end; pix += 3)
    {
        uint16_t pix1 = processing->pre_calc_gamma[ LIMIT16(pm[3][pix[0]] + pm[4][pix[1]] + pm[5][pix[2]]) ];
        if( highestGreen < pix1 ) highestGreen = pix1;
    }
```

And now change these line (a bit below, same file):

```
        /* Now highlilght reconstruction */
        if (/*processing->exposure_stops < 1.0 && highestGreen < 65535 &&*/ processing->highlight_reconstruction)
        {
            /* Check if its the highest green value possible */
            if (tmp1b == highestGreen)
            {
                pix[1] = (pix[0] + pix[2]) / 2;
            }
        }
```

For me that always seems to work. For you as well?

**Comment by bouncyball-git** [comment]
Hehe thanx for this investigation. I'll take a look later.

**Comment by bouncyball-git** [comment]
When MLV is loading and processing  object is initialized default mode is dualiso off. So calculation as you said should be done on original striped dualiso debayered (not processed as dual iso) image and green is different for sure.

**Comment by masc4ii** [comment]
Ilia does it in processing.c; processing_update_highest_green(). But I think this is a theoretical method, because it is calculated without the clip, just using the slider settings (which are precalculated in a matrix which will be applied on the clip). It calculates the value of the clipped green.

**Comment by bouncyball-git** [comment]
I think your actual green value calculator will give different result for every frame and every clip in case of non dualiso too.

**Comment by bouncyball-git** [comment]
What alex's dual iso processing actually does is: upsample data to 20bits then combine even and odd lines according to alex's algorithm and downsample again the data to true 16bit raw values.

Then we debayer this 16bit raw to 16bit per channel RGB and after that processing begins. In any case (14 bit or dual iso 16bit) the data max is the 65535 per channel.

That is why I can not understand why there is the difference between dualiso RGB and non dual iso RGB data?!

**Comment by masc4ii** [comment]
> I think your actual green value calculator will give different result for every frame and every clip in case of non dualiso too.

Yes, that is why I was asking about how to get if dualIso is on in processing module, to drive Ilias algorithm for non-dualIso. 

I think our problem is in alex's algorithm: I think he will search somehow the area where the lightness curves are overlapping (or however he combines low and high Iso). What I saw in my tests: in every frame the highest green is different, +-5 for the frames I tested. That is not much, but enough to let not work a algorithm which works with a static highest green. I took one of the highest green values I found and implemented it as static for a quick test: the corresponding frame was good, all other frames had the pink area (as expected). But these different highest green values bring me to the result, that alex is doing something dynamic in his algorithm, otherwise it would always be the same. 

14bit -> 16bit must have another contrast than 14bit+14bit (with some overlapping) to 20bit to 16bit. The second one must have less contrast (more dynamic), otherwise you can't bring all color values to 16bit. So I think the second one won't reach practically the 65535 - it should be less.

**Comment by bouncyball-git** [comment]
> But these different highest green values bring me to the result, that alex is doing something dynamic in his algorithm, otherwise it would always be the same highest green (because of clipping).

You are right. It seems to be so.

**Comment by bouncyball-git** [comment]
The dualiso footage sometimes flickers from frame to frame... that is the simple proof of your hypothesis.

**Comment by masc4ii** [comment]
> How exactly can I help you?

I need a pipeline from `llrawprocObject_t->dual_iso` into processing module, function `apply_processing_object`, maybe via `processingObject_t` (this solution is not really good, information is doubled, or we create a pointer here, which points to llrawprocObject_t->dual_iso variable) or maybe you have a better idea... it would be nice to have all seperated and clean, so this is not easy here.

**Comment by masc4ii** [comment]
I think I got it... will commit.

**Comment by bouncyball-git** [comment]
> Flicker is due to white balance figures right?

I guess so.

**Comment by masc4ii** [comment]
Please try https://github.com/ilia3101/MLV-App/commit/45ee8c49743aba778a0fe530dfc4b9f50b06ff19

**Comment by bouncyball-git** [comment]
Fantastic job man!!!

**Comment by bouncyball-git** [comment]
@dannephoto : I guess I was wrong in the prev message to you.

White balance is not varying troughout the frames in the same clip. The flickering should be caused with the dynamic processing nature of dualiso @masc4ii mentioned above.

**Comment by masc4ii** [comment]
F***, it does not work if AMaZE debayer was selected... it works only for bilinear. WHY?????

**Comment by bouncyball-git** [comment]
Right :(

**Comment by bouncyball-git** [comment]
SHould we ask for help Ilia?

**Comment by masc4ii** [comment]
Yeah... why not... 
Is it possible that the low ISO somehow affects the clipped high ISO values?! With our old good cheat factor 0.96 it works for me 😝

**Comment by dannephoto** [comment]
"The shitty broen leave effect" 😁

**Comment by bouncyball-git** [comment]
dualiso interpolation happens before debayer anyway and we feed the same raw data to both debayers.

**Comment by masc4ii** [comment]
Crazy: find the highest green using bilinear, saving that value and use it with AMaZE kills only the pink. Is there some noise or something else above?!

**Comment by bouncyball-git** [comment]
Wow cool finding, I'm lost. No ideas at all.

For amaze there are of course more frequencies (details) obtained from the same raw source but what relation it has with the bilinear highest green if you still search the green val in amaze RGB output???

**Comment by masc4ii** [comment]
I wanted to check if Resolve can reconstruct the highlights... the clip looks very strange in Resolve, looks as if the high iso is clipped completely. I can only export it uncompressed? Lossless aborts...

**Comment by bouncyball-git** [comment]
I do not remember why I did that will take a look.

**Comment by bouncyball-git** [comment]
Hm strange... compression work for my tiger MLV. Dual DNGs exported as lossless.

**Comment by bouncyball-git** [comment]
On all Danne's dualiso MLVs "dng_get_frame()" function returns "LJ92_ERROR_ENCODER". Encoder does not like something there. That is why compression aborting. Uncompressed export as you said is fine.

**Comment by masc4ii** [comment]
As long as there is some area pink in the picture, a solution could be to search for the first highest green peak. There should be one value be very often in the picture! The highest green my algorithm found so far was 4 pixels 😄 ... but it won't get faster doing such things!

**Comment by bouncyball-git** [comment]
I'm not sure I'm exactly following your thoughts. What means first highest green peak?

**Comment by masc4ii** [comment]
Okay... HQ (green channel histogram) diagram comes... 😄 

![bildschirmfoto 2018-06-06 um 18 51 25](https://user-images.githubusercontent.com/30245296/41053227-419ab44c-69bb-11e8-8edb-5d310dc7d32e.png)

**left**: (non dual iso), or dual iso bilinear. The green is clipped, we search for the highest green, voilà.

**right**: dual iso amaze. The green is clipped, but some green is behind (more right). Algorithm from above gets le lower red arrow value, but we like to have the upper red arrow (green peak). But I don't know an easier approach as building a whole green channel histogram, which has to be analysed...

**Comment by masc4ii** [comment]
Another idea: building the dual iso picture in the other way. From what I saw, I think the lower part is fix and the higher part is adapted to it -> clipped value is not 65535. 
If we could build it the other way (higher part stays where it is and lower part is adapted) we wouldn't have the problem, therefor black is darkgray or something...
(without knowing what the dual iso algorithm really does)

**Comment by masc4ii** [comment]
Also funny: I found another dual iso clip from a 5D3, 1920x960, 14bit lossless. Ilias highlight reconstruction algorithm works here perfectly for amaze!

**Comment by masc4ii** [comment]
Okay friends... please try out https://github.com/ilia3101/MLV-App/commit/ed358900c8290b568251f3d76f717f0f34e1dad6 
It is not really fast, but the pink highlights are gone in amaze. I implemented the algorithm "drawn" above.

**Comment by bouncyball-git** [comment]
I think now, after some thinking, I understand your point. High ISO lines which clipped in the original raw are not mapped to highest 16bit values after interpolation. Am I correct?

But why the highest green value searched in the whole image by your previous code is not the really highest?  

it was so simple:

if(highval < current_green_pix) highval = current_green_pix;

**Comment by bouncyball-git** [comment]
Otherwise, it is working very nicely!!! :)

**Comment by masc4ii** [comment]
It was not only this - before I had to create the histogram. 
Yes, I think your understanding is correct. I think the peak was not the highest green value, because of some noise/artefacts created by AMaZE. If the clipped value is the highest 16bit value, the noise above is also clipped (=not there -> no problem). But here the peak is below -> problem.

**Comment by masc4ii** [comment]
Do you have an idea why the dualiso cdng export was looking so clipped, and why the lossless error occured at cdng export?

**Comment by bouncyball-git** [comment]
They mostly look not clipped for me (shotwell under Linux, Lightroom under Windows) and latitude is good enough for tweaking because it is 16bit raw. However all is gets down to the alex's code again...

Regarding encoder error:

This is the part of the writeBody() function in lj92.c

        // Write the ssss
        while (huffbits>0) {
            int usebits = huffbits>nextbits?nextbits:huffbits;
            // Add top usebits from huffval to next usebits of nextbits
            int tophuff = huffenc >> (huffbits - usebits);
            next |= (tophuff << (nextbits-usebits));
            nextbits -= usebits;
            huffbits -= usebits;
            huffenc &= (1<<huffbits)-1;
            if (nextbits==0) {
                if(w >= self->encodedLength - 1)
                {
                    free(rowcache);
                    **return LJ92_ERROR_ENCODER;**
                }
                out[w++] = next;
                if (next==0xff) out[w++] = 0x0;
                next = 0;
                nextbits = 8;
            }
        }

I saw this happening time to time: 

if(w >= self->encodedLength - 1), when huffman encoder does not like something the encoded data length is bigger than original data that causes error. I never dug deeper than that into this algo. It's quite mind twisting stuff ;)

**Comment by bouncyball-git** [comment]
BTW I added that 5th ERROR code to lj92.c because I had this problem with some footage and wanted to handle it more gracefully.

**Comment by masc4ii** [comment]
Dannes file was very clipped in Resolve (see some posts above) and in LR it looks the same:
![bildschirmfoto 2018-06-07 um 17 45 42](https://user-images.githubusercontent.com/30245296/41110985-08c8da84-6a7b-11e8-92a3-a9dd7e951e5f.png)

So it is not easy to change something with that error... okay.

**Comment by bouncyball-git** [comment]
This [commit](https://github.com/ilia3101/MLV-App/commit/7bb4a12d75948c3d8034b23abe2fe8b8e7ad9da3) fixes lossless dualiso DNG export :)

> So it is not easy to change something with that error... okay.

Yeah... will take tons of time and still can be ended unresolved :)

**Comment by dannephoto** [comment]
10bit file. Maybe focus on 12bit footage? And 14bit of course. Sorry, I havn't been able to test anything yet.

**Comment by masc4ii** [comment]
Cool! Thx, I'll check it out!

**Comment by dannephoto** [comment]
Deifinitely improved. native cr2hdr can´t come close to handling lossless files. However, getting some mixed results. Ths file is having a flicker party:
https://bitbucket.org/Dannephoto/magic-lantern/downloads/M10-1030.mov
I get one file with less flicker and two files with perfect results. Hmm...
Gota run but will provide MLV files if you want them.

**Comment by masc4ii** [comment]
The flicker in this clip looks bad - there are real artefacts inside! Do you get these artefacts also in the app for the same frames? MLV could be interesting - especially a part with such a frame!

**Comment by bouncyball-git** [comment]
We can ask a1ex to help with that flickering. I'm out of this shit. Sorry ;)

**Comment by dannephoto** [comment]
Haha, bouncyball. This is probably only with lossless? Or maybe some conflicting issue with pixel maps or who knows what ;).
Too much stuff to test and so many loose ends :). I try to get some mlv cut and dissectable for you guys and A1ex.

**Comment by dannephoto** [comment]
Check this 3K 100D footage. Works great in Mlv App:
https://bitbucket.org/Dannephoto/magic-lantern/downloads/M12-1643cut.MLV

Putting it here since I exceeded my message quota at the ML forum :)

**Comment by masc4ii** [comment]
Hey Danne, thanks! There are 2 little problems I see:
![bildschirmfoto 2018-06-12 um 19 13 47](https://user-images.githubusercontent.com/30245296/41305997-02ba66dc-6e75-11e8-8efa-82d78f8c39f6.png)
1.: Focus Pixels doesn't work
2.: There is a strip down in the picture -black with green points. You can make it visible when playing a bit around...

**Comment by dannephoto** [comment]
Stop playing around finding stuff ;).
Kidding. For now it,s not very usable. 1 sec 24fps only 14bit lossless isn't exactly the recipe for a masterpiece :).

**Comment by masc4ii** [comment]
Are there still issues with this bug? For pink highlights I made new issue #90 . Can we close? Dual ISO seems to work so far?! (okay, preview mode does not... but... 😝)

**Comment by dannephoto** [comment]
Sure, close away. No black frames so far :)

**Comment by bouncyball-git** [comment]
Yay! :)
