### ISSUE TITLE
QT Creator emits "[mlvapp] error 2" at the end of compilation.

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#91]
@masc: If you remember I mentioned this some while ago. I really fed of this error ;)

I discovered when this section is commented out error is gone:

#for using the compiled version
linux-g++ {
    target.path = $$(HOME)/bin
    desktop.path = $$(HOME)/.local/share/applications
    desktop.files += mlvapp.desktop
    icon512.path = $$(HOME)/.local/share/icons/hicolor/512x512/apps
    icon512.files += RetinaIMG/MLVAPP.png
    INSTALLS += target desktop icon512
    QMAKE_POST_LINK += tar -C $$(HOME)/bin -xvJf FFmpeg/ffmpegLinux.tar.xz --strip=1 ffmpeg-4.0-64bit-static/ffmpeg
}

IDK what to do :)

**Comment by masc4ii** [comment]
Yes, wasn't it these lines I asked you to comment out? 😄 
I think these lines are working for openSuse. Maybe something is different on your linux. Try to comment in line for line. Maybe we can find what exactly is the problem.

**Comment by bouncyball-git** [comment]
> Yes, wasn't it these lines I asked you to comment out?

:rofl: yeah now I remember that!

Thanx for advice :smile:

**Comment by masc4ii** [comment]
The commands shall build a clickable icon and untar+install ffmpeg to a location MLVApp can work with it.

**Comment by bouncyball-git** [comment]
I'm always creating /home/bin. In reality last line causes this error.

QMAKE_POST_LINK += tar -C $$(HOME)/bin -xvJf FFmpeg/ffmpegLinux.tar.xz --strip=1 ffmpeg-4.0-64bit-static/ffmpeg

**Comment by bouncyball-git** [comment]
running following command in the shell:

tar -C $HOME/bin -xvJf FFmpeg/ffmpegLinux.tar.xz --strip=1 ffmpeg-4.0-64bit-static/ffmpeg

works fine but QT can not execute it correctly post linking :(

**Comment by bouncyball-git** [comment]
tar -C /home/nic/bin -xvJf FFmpeg/ffmpegLinux.tar.xz --strip=1 ffmpeg-4.0-64bit-static/ffmpeg
tar (child): FFmpeg/ffmpegLinux.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
Makefile:496: recipe for target 'mlvapp' failed
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make: *** [mlvapp] Error 2
18:35:56: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project MLVApp (kit: Desktop Qt 5.9.1 GCC 64bit)
When executing step "Make"
18:35:56: Elapsed time: 00:06.

**Comment by seescho** [comment]
Disable shadow build in QT-Creator project settings. Than it should run.

**Comment by bouncyball-git** [comment]
I found the solution and think it will work in any Linux distro:

`QMAKE_POST_LINK += tar -C $$(HOME)/bin -xvJf $$_PRO_FILE_PWD_/FFmpeg/ffmpegLinux.tar.xz --strip=1 ffmpeg-4.0-64bit-static/ffmpeg
`

**Comment by bouncyball-git** [comment]
Commited

**Comment by bouncyball-git** [comment]
@seescho: please try on suse :)

**Comment by seescho** [comment]
compiles fine on Tumbleweed :)

**Comment by bouncyball-git** [comment]
Thanks everyone. Closing...
