### ISSUE TITLE
Changing Black/White level will work better with double range slider

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#92]
Something like [this](https://stackoverflow.com/questions/25155908/qt5-double-range-slider).

It is lot more better to set bound restriction from the slider than in the C back end.

**Comment by bouncyball-git** [comment]
[https://doc.qt.io/qt-5/qml-qtquick-controls2-rangeslider.html](https://doc.qt.io/qt-5/qml-qtquick-controls2-rangeslider.html)

**Comment by bouncyball-git** [comment]
OK then. Can we just restrict overlapping of existing sliders?

**Comment by bouncyball-git** [comment]
btw is that also bad slider? [http://doc.qt.io/qt-5.9/qml-qtquick-controls2-rangeslider.html](http://doc.qt.io/qt-5.9/qml-qtquick-controls2-rangeslider.html)

**Comment by bouncyball-git** [comment]
You know what. Slider on change event should be emitted only when mouse button released. E.g. you are dragging knob with mouse button down to where ever you want then when mouse button released slider gives the last position value.

**Comment by bouncyball-git** [comment]
We should do this only for those 2 sliders not for others. Then user has to understand this ;)

Feeling with value over the slider not changing as long as you drag is worse hehe... this could be dealt with 2 slots?

**Comment by masc4ii** [comment]
Overlapping is limited now. 

For the slider release event: is this really worth it: if we release the slider before render thread is ready, we still have the same problem. No no, not all sliders, only these two. For my buffer idea... I don't know how easily and nicely implementing this... I would get that to work, but the style would be really ugly... so I am still searching for a good idea!

**Comment by masc4ii** [comment]
HA! I have commited a quick fix. Sliders are working now - they feel ugly @ dual iso clips but they do their job!

**Comment by bouncyball-git** [comment]
Fantastic! That ugly feeling is expected :)

As I understand, now _all_ sliders are working correctly?

**Comment by bouncyball-git** [comment]
Overlapping restriction fixed all problems :) (as I expected)

**Comment by bouncyball-git** [comment]
Changed B/W levels are correctly written into exported DNGs :) (for dual iso an non dual iso)

**Comment by masc4ii** [comment]
Something else to fix / more wishes for v0.17?

**Comment by bouncyball-git** [comment]
Let's release it and postpone more features for v0.18 ;)

**Comment by masc4ii** [comment]
OSX version is uploaded... could you please upload win versions? Linux I will upload tomorrow. When you're done, you can press release button ;) (now it is draft)

**Comment by bouncyball-git** [comment]
Phew,,, published :)

**Comment by bouncyball-git** [comment]
Love your Seychelles vews :)

**Comment by masc4ii** [comment]
<img width="676" alt="bildschirmfoto 2018-07-06 um 12 39 17" src="https://user-images.githubusercontent.com/30245296/42374807-a4cf6c2c-8119-11e8-89e9-c79c7babee47.png">

😄

**Comment by bouncyball-git** [comment]
[Here](https://www.youtube.com/watch?v=mWjcaEZ5-pM) is very cool Seychelles 4K drone footage :)

**Comment by masc4ii** [comment]
La Diague... exactly where I was... and it was sooo perfect! I can absolutely recommend this island!

**Comment by bouncyball-git** [comment]
I'd love to see your edited video :)
