### ISSUE TITLE
wow wow is this real!??

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#93]
Clearly, all the stats that say Linux has 2% makret share are lying, its 52% 😆

![Mad linux downloads](https://user-images.githubusercontent.com/23642861/42395568-3b6287be-8156-11e8-9960-dcd7a3ea18af.png)

This proves over half of ALL computer users use Linux!

Is it a glitch? If not, I'm amazed...

**Comment by masc4ii** [comment]
Last saturday we had around 100 downloads there. Sunday you could watch the number climbing. For me it looked like a robot downloading the app.

**Comment by ilia3101** [comment]
Yeah thought it could be something like that.
But that's strange... what can a robot even gain from doing that? Not even profitable.
At least it's funny.

**Comment by ilia3101** [comment]
Small google search and I found 3 random Linux blogs mentioning MLV App:
http://www.ubuntubuzz.com/2018/07/10-gnulinux-video-editing-apps-in-appimage.html
https://linuxespanol.net/2018/07/31/10-editores-de-video-libres-en-formato-appimage/
https://ubunlog.com/editores-de-video-formato-appimage/

Maybe just maybe we do actually have this many Linux downloads?

**Comment by masc4ii** [comment]
That would be crazy... but most Linux downloads came within 2..3 days...

**Comment by bouncyball-git** [comment]
Yup, so strange.

**Comment by masc4ii** [comment]
Congrats!
![bildschirmfoto 2018-08-15 um 13 09 38](https://user-images.githubusercontent.com/30245296/44145605-84a1f694-a08c-11e8-9cc0-5e14ba8331ff.png)

**Comment by bouncyball-git** [comment]
However, it's still strange when looking at Linux appimage downloads ;)
