### ISSUE TITLE
video not going above 1405 frames

### ISSUE THREAD

**Issue by CanonDestroyer69** [ilia3101/MLV-App#94]
so 
my problem is
i have long videos like 5 mins and in mlvapp when i import mlvs it shows only 1405 frames and thats 1/5 of a video
while when i open mlvs in mlrawviewer it shows full lenght video and i can export it with no prob
is this a normal thing? a limit? or is it a bug or problem :(

**Comment by masc4ii** [comment]
Thanks for reporting. What version and OS are you using? We got opened files with 2500 frames and more without problems... There should be no limit.

**Comment by CanonDestroyer69** [comment]
![image](https://user-images.githubusercontent.com/40923402/42414577-52716a7a-8240-11e8-8830-10df874c5f76.png)
im using win10 x64 and mlvapp latest 
i thought it was problem in build so i downloaded newest update today
still same problem
maybe its because my mlvs are separated in chunks and program wont read them? because theyre labeled as .m00 and not .mlv

**Comment by masc4ii** [comment]
Recorded a file with 4 chunks (mlv, ..., m03) and no problem on OSX. Can't test Win here today.
![bildschirmfoto 2018-07-07 um 23 13 06](https://user-images.githubusercontent.com/30245296/42414712-7a7cd9b4-823b-11e8-971c-4021469e2669.png)

**Comment by masc4ii** [comment]
Could test Win32 version on OSX via Wine - also no problem.
![bildschirmfoto 2018-07-07 um 23 20 13](https://user-images.githubusercontent.com/30245296/42414743-6e19274e-823c-11e8-996c-2fd85b8fa106.png)

**Comment by ilia3101** [comment]
it sounds like something in the file must be wrong/unusual

**Comment by bouncyball-git** [comment]
I need full clip with all chunks. It's interesting to investigate what is happening.

**Comment by masc4ii** [comment]
>I need full clip with all chunks. It's interesting to investigate what is happening.

@CanonDestroyer69 : Yapp... so if you always have this problem, the smallest chunk-set should be a little more than 4GB. The problem should still be there. If you could upload a complete clip this would be fine... (I know, uploading so much data is ugly...).

**Comment by CanonDestroyer69** [comment]
i recorder another mlv just for this 
its a bit smaller (8gb~2min) because its simpler adding it my google drive
and yes i still have the same problem only 1405 frames
in one hour i will attach a link to it for download

**Comment by CanonDestroyer69** [comment]
https://drive.google.com/open?id=1ceKKgaO6qMbTpgwRr46ZZlGsrgT2jXWS
here is the link
i hope this will be figured out 
because i dont want to get to mlrawviewer after all the neat features mlvapp offers :(

**Comment by masc4ii** [comment]
Wonderful, thank you. I can reproduce the error with your clip. @bouncyball-git  & @ilia3101 : maybe also download this clip for debugging. 😏

**Comment by masc4ii** [comment]
Okay... found the first problem: @CanonDestroyer69 : where is .M00 chunk? Debug print says "M08-1718.M00 not existing". If I rename M01 to M00 and M02 to M01, we get another problem what tells: "Unknown blockType 'VKDF' or corrupted file". Is this some experimental build which produced this clip?

**Comment by CanonDestroyer69** [comment]
I dont have m00 either
My build is nightly.2017aug18.5d3113
Video system was PAL 
At 24p alli
I can send a pic of ml settings after i get home 
Because i cant upload them here from a phone

**Comment by masc4ii** [comment]
That is strange. Maybe you should try another build. Without m00 chunk no software should be able to load that completely. The clips ends with the end of mlv chunk - this one has 1405 frames. MLVProducer does the same. I have no idea how MLRawViewer can work for you ... does it jump after 1405 frames? I can't load it in MLRawViewer at all (app crashes after some pink noise).

**Comment by CanonDestroyer69** [comment]
and yet im finishing exporting video from mlrawviewer 
![image](https://user-images.githubusercontent.com/40923402/42448132-dc836836-8384-11e8-89e0-1d972f8b09ee.png)
i will try another built. but a bit later because my laptop charger died and new one is still in the way
so i will update in a day or two

**Comment by CanonDestroyer69** [comment]
![image](https://user-images.githubusercontent.com/40923402/42448413-b525c012-8385-11e8-9b4c-d13837627118.png)

aaand here it is working just fine

**Comment by masc4ii** [comment]
Could you try what happens in MLVApp if you rename the chunks to their correct names? M02=M01 and M01=M00.

**Comment by CanonDestroyer69** [comment]
![image](https://user-images.githubusercontent.com/40923402/42449009-cdc17d3a-8387-11e8-8145-1368cbde6460.png)
well.. i guess we just solve a problem 
but why is it working for me but not you

**Comment by CanonDestroyer69** [comment]
maybe problem was in uploading?
because if i remember correctly my internet went bad for a moment one time
if you need i can upload them again when i get my charger

**Comment by masc4ii** [comment]
I think some bytes are broken in my download or your upload. 
@bouncyball-git : what exactly tells the MLV spec? Is only MLV,M00,M01,... allowed, or is also MLV, M01,M02 okay? I am wondering about that...

**Comment by bouncyball-git** [comment]
1st file has all needed blocks and all sequential ones only VIDF, AUDF and some repeatable blocks. Renaming should work.

**Comment by bouncyball-git** [comment]
I can play all 2821 frames after renaming. What is interesting that there is no gap between 1st and second chunk they overlap flawlessly without any dropped frames ;). That means the video is not corrupted it's just chunk file names are messed somehow.

**Comment by bouncyball-git** [comment]
I'm ok.
