### ISSUE TITLE
v1.0 (kinda anniversary) release discussion

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#95]
We can be a maybe a couple days late with this release??

This will be place to discuss this release for now.

Maybe we can come up with some other ideas for it...

**Comment by masc4ii** [comment]
Until now I only did some bugfixes. 
Yesterday I started in analysing and trying out making dual iso faster. But until now I had not to much success: I multithreaded amaze interpolation and tried to comment out other parts of the algorithm to see if something gets faster... in a 3min export it was not a single second faster 😢

**Comment by masc4ii** [comment]
Not to difficult should be to add the gradient filter. But render speed would be a bit less than half: we process the picture twice (1x original, 1x with gradient settings). Then a alpha mask should be calculated and the pictures must be blended together. But I am not sure yet where to add which parameter structure into Ilias code to have it nice... 
This feature should be discussed here https://github.com/ilia3101/MLV-App/issues/49

**Comment by masc4ii** [comment]
If we could add BMD Film profile this could also be great, because of some EOS Luts. But I haven't found any function therefor yet. Even trying out with the Resolve LUT linear->BMD looks not correct using our linear profile (looks very different to what Resolve shows).

**Comment by bakersdozen** [comment]
I see MLVProducer has BMDFilm curve, could be a starting point or reference?

**Comment by masc4ii** [comment]
>I see MLVProducer has BMDFilm curve, could be a starting point or reference?

Two problems: MLVProducer is not open source and also seems not to be correct here (for me this looks very different (bith BMD color space + EOSHD LUT)):
![bildschirmfoto 2018-07-11 um 11 48 47](https://user-images.githubusercontent.com/30245296/42564295-af7ac550-8500-11e8-8665-a20a7a55f760.png)
<img width="1764" alt="bildschirmfoto 2018-07-11 um 11 48 22" src="https://user-images.githubusercontent.com/30245296/42564302-b4247eca-8500-11e8-8d74-1d4aeccd2cd5.png">

>This could help eliminate Resolve from some people's workflow if they wanted to. Shoot > MlvApp > NLE

Hehe... this is what I do nearly all the time 😏

**Comment by bakersdozen** [comment]
Good point, thanks for doing the comparison too, I thought maybe it was a not 100% version of the curve. It would just be awesome to be able to not rely on resolve and have MlvApp all the way! You get it.

**Comment by ilia3101** [comment]
Actually, there seems to be much of the MLVProducer's processing source code on sourceforge where it's hosted, there is both c and basic files, though some of it looks obfuscated (weird variable names with `$` in them).

**Comment by masc4ii** [comment]
Really? I was searching and always found executables and no code. Could you provide a link?

**Comment by ilia3101** [comment]
I only noticed this yesterday, I looked as I'd seen reddeercity say it is open source. Anyway I have no clue about the license so it might not be much use and it's really confusing to read

**Comment by ilia3101** [comment]
Ok I'll send a link 1 sec

**Comment by masc4ii** [comment]
Found it:
https://sourceforge.net/projects/mlvproducer/files/src/
But all curves are in a binary format... :(

**Comment by ilia3101** [comment]
https://sourceforge.net/projects/mlvproducer/files/src/

Code inside folders with . DLL extension

**Comment by masc4ii** [comment]
All the magic happens in the basic files. But there are no comments - so very hard to understand. BMD color space is realized using a .cslut ... a kind of LUT, but it seems it is a format by awpstar. I have no idea what he is doing there.

**Comment by bakersdozen** [comment]
Don't know if these will help. Unable install the Mac file and don't have access to PC right now.
[BMDFilm for ACR.zip](https://github.com/ilia3101/MLV-App/files/2184500/BMDFilm.for.ACR.zip)

**Comment by masc4ii** [comment]
Thanks, but this seems also to be a kind of binary format. What we need in the end is an equation like in the end of this post: http://www.magiclantern.fm/forum/index.php?topic=15801.msg158145#msg158145

**Comment by bouncyball-git** [comment]
I don't think we get equation ever. We could try to mathematically approximate to the curve but we even do not have reliable real curve ;)

**Comment by masc4ii** [comment]
Right, I think so too. Resolve comes with a LUT Linear->BMD, but applying this one don't looks right as well - so why doing the approximation here?!

**Comment by bouncyball-git** [comment]
[Here](http://www.bmcuser.com/showthread.php?15819-BMD-film-log-specs&p=189019&viewfull=1#post189019) are 2 curved BMD Film and BMD Film 4K, but who knows are they right ones or not :)

**Comment by bakersdozen** [comment]
I decomplied the VisionColor BMDFilm for ACR .dcp from the files above for Canon. Using dcpTool.
Here is the xml output, i'm not sure if this will help or not. See the <tone curve> section.

    <Element HueDiv="86" SatDiv="4" ValDiv="0" HueShift="0.000000" SatScale="1.0
70312" ValScale="0.951996"/>
    <Element HueDiv="86" SatDiv="5" ValDiv="0" HueShift="0.000000" SatScale="1.1
03463" ValScale="0.932002"/>
    <Element HueDiv="86" SatDiv="6" ValDiv="0" HueShift="0.000000" SatScale="1.1
31715" ValScale="0.916383"/>
    <Element HueDiv="86" SatDiv="7" ValDiv="0" HueShift="0.000000" SatScale="1.1
50643" ValScale="0.906876"/>
    <Element HueDiv="86" SatDiv="8" ValDiv="0" HueShift="0.000000" SatScale="1.1
58849" ValScale="0.903046"/>
    <Element HueDiv="86" SatDiv="9" ValDiv="0" HueShift="0.000000" SatScale="1.1
57380" ValScale="0.903272"/>
    <Element HueDiv="86" SatDiv="10" ValDiv="0" HueShift="0.000000" SatScale="1.
148837" ValScale="0.905679"/>
    <Element HueDiv="86" SatDiv="11" ValDiv="0" HueShift="0.000000" SatScale="1.
136398" ValScale="0.908767"/>
    <Element HueDiv="86" SatDiv="12" ValDiv="0" HueShift="0.000000" SatScale="1.
122893" ValScale="0.911663"/>
    <Element HueDiv="86" SatDiv="13" ValDiv="0" HueShift="0.000000" SatScale="1.
110244" ValScale="0.914076"/>
    <Element HueDiv="86" SatDiv="14" ValDiv="0" HueShift="0.000000" SatScale="1.
099394" ValScale="0.916060"/>
    <Element HueDiv="86" SatDiv="15" ValDiv="0" HueShift="0.000000" SatScale="1.
090561" ValScale="0.917799"/>
    <Element HueDiv="86" SatDiv="16" ValDiv="0" HueShift="0.000000" SatScale="1.
083564" ValScale="0.919461"/>
    <Element HueDiv="86" SatDiv="17" ValDiv="0" HueShift="0.000000" SatScale="1.
078073" ValScale="0.921154"/>
    <Element HueDiv="86" SatDiv="18" ValDiv="0" HueShift="0.000000" SatScale="1.
073749" ValScale="0.922921"/>
    <Element HueDiv="86" SatDiv="19" ValDiv="0" HueShift="0.000000" SatScale="1.
070306" ValScale="0.924764"/>
    <Element HueDiv="86" SatDiv="20" ValDiv="0" HueShift="0.000000" SatScale="1.
067519" ValScale="0.926657"/>
    <Element HueDiv="86" SatDiv="21" ValDiv="0" HueShift="0.000000" SatScale="1.
065224" ValScale="0.928569"/>
    <Element HueDiv="86" SatDiv="22" ValDiv="0" HueShift="0.000000" SatScale="1.
063304" ValScale="0.930467"/>
    <Element HueDiv="86" SatDiv="23" ValDiv="0" HueShift="0.000000" SatScale="1.
061673" ValScale="0.932321"/>
    <Element HueDiv="86" SatDiv="24" ValDiv="0" HueShift="0.000000" SatScale="1.
060270" ValScale="0.934111"/>
    <Element HueDiv="87" SatDiv="0" ValDiv="0" HueShift="0.000000" SatScale="1.0
00000" ValScale="1.000000"/>
    <Element HueDiv="87" SatDiv="1" ValDiv="0" HueShift="0.000000" SatScale="1.0
03451" ValScale="0.997414"/>
    <Element HueDiv="87" SatDiv="2" ValDiv="0" HueShift="0.000000" SatScale="1.0
16202" ValScale="0.988232"/>
    <Element HueDiv="87" SatDiv="3" ValDiv="0" HueShift="0.000000" SatScale="1.0
40142" ValScale="0.971832"/>
    <Element HueDiv="87" SatDiv="4" ValDiv="0" HueShift="0.000000" SatScale="1.0
72836" ValScale="0.950749"/>
    <Element HueDiv="87" SatDiv="5" ValDiv="0" HueShift="0.000000" SatScale="1.1
07720" ValScale="0.929872"/>
    <Element HueDiv="87" SatDiv="6" ValDiv="0" HueShift="0.000000" SatScale="1.1
37570" ValScale="0.913594"/>
    <Element HueDiv="87" SatDiv="7" ValDiv="0" HueShift="0.000000" SatScale="1.1
57580" ValScale="0.903857"/>
    <Element HueDiv="87" SatDiv="8" ValDiv="0" HueShift="0.000000" SatScale="1.1
66001" ValScale="0.900253"/>
    <Element HueDiv="87" SatDiv="9" ValDiv="0" HueShift="0.000000" SatScale="1.1
63606" ValScale="0.901036"/>
    <Element HueDiv="87" SatDiv="10" ValDiv="0" HueShift="0.000000" SatScale="1.
153061" ValScale="0.904079"/>
    <Element HueDiv="87" SatDiv="11" ValDiv="0" HueShift="0.000000" SatScale="1.
138068" ValScale="0.907625"/>
    <Element HueDiv="87" SatDiv="12" ValDiv="0" HueShift="0.000000" SatScale="1.
122168" ValScale="0.910692"/>
    <Element HueDiv="87" SatDiv="13" ValDiv="0" HueShift="0.000000" SatScale="1.
107771" ValScale="0.913053"/>
    <Element HueDiv="87" SatDiv="14" ValDiv="0" HueShift="0.000000" SatScale="1.
095936" ValScale="0.914909"/>
    <Element HueDiv="87" SatDiv="15" ValDiv="0" HueShift="0.000000" SatScale="1.
086734" ValScale="0.916563"/>
    <Element HueDiv="87" SatDiv="16" ValDiv="0" HueShift="0.000000" SatScale="1.
079762" ValScale="0.918240"/>
    <Element HueDiv="87" SatDiv="17" ValDiv="0" HueShift="0.000000" SatScale="1.
074496" ValScale="0.920049"/>
    <Element HueDiv="87" SatDiv="18" ValDiv="0" HueShift="0.000000" SatScale="1.
070472" ValScale="0.922010"/>
    <Element HueDiv="87" SatDiv="19" ValDiv="0" HueShift="0.000000" SatScale="1.
067332" ValScale="0.924091"/>
    <Element HueDiv="87" SatDiv="20" ValDiv="0" HueShift="0.000000" SatScale="1.
064820" ValScale="0.926238"/>
    <Element HueDiv="87" SatDiv="21" ValDiv="0" HueShift="0.000000" SatScale="1.
062763" ValScale="0.928398"/>
    <Element HueDiv="87" SatDiv="22" ValDiv="0" HueShift="0.000000" SatScale="1.
061043" ValScale="0.930525"/>
    <Element HueDiv="87" SatDiv="23" ValDiv="0" HueShift="0.000000" SatScale="1.
059579" ValScale="0.932582"/>
    <Element HueDiv="87" SatDiv="24" ValDiv="0" HueShift="0.000000" SatScale="1.
058316" ValScale="0.934546"/>
    <Element HueDiv="88" SatDiv="0" ValDiv="0" HueShift="0.000000" SatScale="1.0
00000" ValScale="1.000000"/>
    <Element HueDiv="88" SatDiv="1" ValDiv="0" HueShift="0.000000" SatScale="1.0
03376" ValScale="0.997486"/>
    <Element HueDiv="88" SatDiv="2" ValDiv="0" HueShift="0.000000" SatScale="1.0
15855" ValScale="0.988517"/>
    <Element HueDiv="88" SatDiv="3" ValDiv="0" HueShift="0.000000" SatScale="1.0
39268" ValScale="0.972430"/>
    <Element HueDiv="88" SatDiv="4" ValDiv="0" HueShift="0.000000" SatScale="1.0
71185" ValScale="0.951688"/>
    <Element HueDiv="88" SatDiv="5" ValDiv="0" HueShift="0.000000" SatScale="1.1
05230" ValScale="0.931079"/>
    <Element HueDiv="88" SatDiv="6" ValDiv="0" HueShift="0.000000" SatScale="1.1
34532" ValScale="0.914897"/>
    <Element HueDiv="88" SatDiv="7" ValDiv="0" HueShift="0.000000" SatScale="1.1
54504" ValScale="0.905066"/>
    <Element HueDiv="88" SatDiv="8" ValDiv="0" HueShift="0.000000" SatScale="1.1
63188" ValScale="0.901278"/>
    <Element HueDiv="88" SatDiv="9" ValDiv="0" HueShift="0.000000" SatScale="1.1
60775" ValScale="0.901879"/>
    <Element HueDiv="88" SatDiv="10" ValDiv="0" HueShift="0.000000" SatScale="1.
149485" ValScale="0.904708"/>
    <Element HueDiv="88" SatDiv="11" ValDiv="0" HueShift="0.000000" SatScale="1.
133182" ValScale="0.907887"/>
    <Element HueDiv="88" SatDiv="12" ValDiv="0" HueShift="0.000000" SatScale="1.
116040" ValScale="0.910407"/>
    <Element HueDiv="88" SatDiv="13" ValDiv="0" HueShift="0.000000" SatScale="1.
100990" ValScale="0.912173"/>
    <Element HueDiv="88" SatDiv="14" ValDiv="0" HueShift="0.000000" SatScale="1.
089181" ValScale="0.913562"/>
    <Element HueDiv="88" SatDiv="15" ValDiv="0" HueShift="0.000000" SatScale="1.
080477" ValScale="0.914979"/>
    <Element HueDiv="88" SatDiv="16" ValDiv="0" HueShift="0.000000" SatScale="1.
074212" ValScale="0.916651"/>
    <Element HueDiv="88" SatDiv="17" ValDiv="0" HueShift="0.000000" SatScale="1.
069675" ValScale="0.918633"/>
    <Element HueDiv="88" SatDiv="18" ValDiv="0" HueShift="0.000000" SatScale="1.
066304" ValScale="0.920874"/>
    <Element HueDiv="88" SatDiv="19" ValDiv="0" HueShift="0.000000" SatScale="1.
063710" ValScale="0.923282"/>
    <Element HueDiv="88" SatDiv="20" ValDiv="0" HueShift="0.000000" SatScale="1.
061638" ValScale="0.925762"/>
    <Element HueDiv="88" SatDiv="21" ValDiv="0" HueShift="0.000000" SatScale="1.
059930" ValScale="0.928235"/>
    <Element HueDiv="88" SatDiv="22" ValDiv="0" HueShift="0.000000" SatScale="1.
058486" ValScale="0.930640"/>
    <Element HueDiv="88" SatDiv="23" ValDiv="0" HueShift="0.000000" SatScale="1.
057242" ValScale="0.932935"/>
    <Element HueDiv="88" SatDiv="24" ValDiv="0" HueShift="0.000000" SatScale="1.
056159" ValScale="0.935096"/>
    <Element HueDiv="89" SatDiv="0" ValDiv="0" HueShift="0.000000" SatScale="1.0
00000" ValScale="1.000000"/>
    <Element HueDiv="89" SatDiv="1" ValDiv="0" HueShift="0.000000" SatScale="1.0
03197" ValScale="0.997618"/>
    <Element HueDiv="89" SatDiv="2" ValDiv="0" HueShift="0.000000" SatScale="1.0
14898" ValScale="0.989152"/>
    <Element HueDiv="89" SatDiv="3" ValDiv="0" HueShift="0.000000" SatScale="1.0
36558" ValScale="0.974054"/>
    <Element HueDiv="89" SatDiv="4" ValDiv="0" HueShift="0.000000" SatScale="1.0
65699" ValScale="0.954670"/>
    <Element HueDiv="89" SatDiv="5" ValDiv="0" HueShift="0.000000" SatScale="1.0
96508" ValScale="0.935378"/>
    <Element HueDiv="89" SatDiv="6" ValDiv="0" HueShift="0.000000" SatScale="1.1
23028" ValScale="0.920012"/>
    <Element HueDiv="89" SatDiv="7" ValDiv="0" HueShift="0.000000" SatScale="1.1
41353" ValScale="0.910286"/>
    <Element HueDiv="89" SatDiv="8" ValDiv="0" HueShift="0.000000" SatScale="1.1
49619" ValScale="0.905974"/>
    <Element HueDiv="89" SatDiv="9" ValDiv="0" HueShift="0.000000" SatScale="1.1
47529" ValScale="0.905630"/>
    <Element HueDiv="89" SatDiv="10" ValDiv="0" HueShift="0.000000" SatScale="1.
136625" ValScale="0.907257"/>
    <Element HueDiv="89" SatDiv="11" ValDiv="0" HueShift="0.000000" SatScale="1.
120533" ValScale="0.909067"/>
    <Element HueDiv="89" SatDiv="12" ValDiv="0" HueShift="0.000000" SatScale="1.
103761" ValScale="0.910206"/>
    <Element HueDiv="89" SatDiv="13" ValDiv="0" HueShift="0.000000" SatScale="1.
089596" ValScale="0.910829"/>
    <Element HueDiv="89" SatDiv="14" ValDiv="0" HueShift="0.000000" SatScale="1.
079144" ValScale="0.911510"/>
    <Element HueDiv="89" SatDiv="15" ValDiv="0" HueShift="0.000000" SatScale="1.
071979" ValScale="0.912680"/>
    <Element HueDiv="89" SatDiv="16" ValDiv="0" HueShift="0.000000" SatScale="1.
067163" ValScale="0.914465"/>
    <Element HueDiv="89" SatDiv="17" ValDiv="0" HueShift="0.000000" SatScale="1.
063851" ValScale="0.916785"/>
    <Element HueDiv="89" SatDiv="18" ValDiv="0" HueShift="0.000000" SatScale="1.
061453" ValScale="0.919468"/>
    <Element HueDiv="89" SatDiv="19" ValDiv="0" HueShift="0.000000" SatScale="1.
059603" ValScale="0.922343"/>
    <Element HueDiv="89" SatDiv="20" ValDiv="0" HueShift="0.000000" SatScale="1.
058096" ValScale="0.925264"/>
    <Element HueDiv="89" SatDiv="21" ValDiv="0" HueShift="0.000000" SatScale="1.
056815" ValScale="0.928127"/>
    <Element HueDiv="89" SatDiv="22" ValDiv="0" HueShift="0.000000" SatScale="1.
055699" ValScale="0.930862"/>
    <Element HueDiv="89" SatDiv="23" ValDiv="0" HueShift="0.000000" SatScale="1.
054712" ValScale="0.933428"/>
    <Element HueDiv="89" SatDiv="24" ValDiv="0" HueShift="0.000000" SatScale="1.
053835" ValScale="0.935805"/>
  </HueSatDeltas1>
  <ToneCurve Size="96">
    <Element N="0" h="0.000000" v="0.002750"/>
    <Element N="1" h="0.010526" v="0.009230"/>
    <Element N="2" h="0.021053" v="0.018493"/>
    <Element N="3" h="0.031579" v="0.024885"/>
    <Element N="4" h="0.042105" v="0.033218"/>
    <Element N="5" h="0.052632" v="0.041246"/>
    <Element N="6" h="0.063158" v="0.048790"/>
    <Element N="7" h="0.073684" v="0.055119"/>
    <Element N="8" h="0.084211" v="0.063678"/>
    <Element N="9" h="0.094737" v="0.070144"/>
    <Element N="10" h="0.105263" v="0.078114"/>
    <Element N="11" h="0.115789" v="0.084235"/>
    <Element N="12" h="0.126316" v="0.092570"/>
    <Element N="13" h="0.136842" v="0.099788"/>
    <Element N="14" h="0.147368" v="0.105836"/>
    <Element N="15" h="0.157895" v="0.111758"/>
    <Element N="16" h="0.168421" v="0.118725"/>
    <Element N="17" h="0.178947" v="0.124412"/>
    <Element N="18" h="0.189474" v="0.130219"/>
    <Element N="19" h="0.200000" v="0.136064"/>
    <Element N="20" h="0.210526" v="0.142361"/>
    <Element N="21" h="0.221053" v="0.148218"/>
    <Element N="22" h="0.231579" v="0.153846"/>
    <Element N="23" h="0.242105" v="0.159585"/>
    <Element N="24" h="0.252632" v="0.165290"/>
    <Element N="25" h="0.263158" v="0.170763"/>
    <Element N="26" h="0.273684" v="0.176379"/>
    <Element N="27" h="0.284211" v="0.181407"/>
    <Element N="28" h="0.294737" v="0.187046"/>
    <Element N="29" h="0.305263" v="0.192969"/>
    <Element N="30" h="0.315789" v="0.198332"/>
    <Element N="31" h="0.326316" v="0.203760"/>
    <Element N="32" h="0.336842" v="0.208511"/>
    <Element N="33" h="0.347368" v="0.213620"/>
    <Element N="34" h="0.357895" v="0.219364"/>
    <Element N="35" h="0.368421" v="0.226534"/>
    <Element N="36" h="0.378947" v="0.232338"/>
    <Element N="37" h="0.389474" v="0.237032"/>
    <Element N="38" h="0.400000" v="0.242099"/>
    <Element N="39" h="0.410526" v="0.247495"/>
    <Element N="40" h="0.421053" v="0.252672"/>
    <Element N="41" h="0.431579" v="0.257483"/>
    <Element N="42" h="0.442105" v="0.262034"/>
    <Element N="43" h="0.452632" v="0.267474"/>
    <Element N="44" h="0.463158" v="0.272686"/>
    <Element N="45" h="0.473684" v="0.277561"/>
    <Element N="46" h="0.484211" v="0.282742"/>
    <Element N="47" h="0.494737" v="0.287740"/>
    <Element N="48" h="0.505263" v="0.292101"/>
    <Element N="49" h="0.515789" v="0.297479"/>
    <Element N="50" h="0.526316" v="0.302769"/>
    <Element N="51" h="0.536842" v="0.308345"/>
    <Element N="52" h="0.547368" v="0.313428"/>
    <Element N="53" h="0.557895" v="0.318497"/>
    <Element N="54" h="0.568421" v="0.324055"/>
    <Element N="55" h="0.578947" v="0.328562"/>
    <Element N="56" h="0.589474" v="0.334349"/>
    <Element N="57" h="0.600000" v="0.340174"/>
    <Element N="58" h="0.610526" v="0.345865"/>
    <Element N="59" h="0.621053" v="0.351960"/>
    <Element N="60" h="0.631579" v="0.357580"/>
    <Element N="61" h="0.642105" v="0.363632"/>
    <Element N="62" h="0.652632" v="0.369271"/>
    <Element N="63" h="0.663158" v="0.375627"/>
    <Element N="64" h="0.673684" v="0.381907"/>
    <Element N="65" h="0.684211" v="0.388445"/>
    <Element N="66" h="0.694737" v="0.396199"/>
    <Element N="67" h="0.705263" v="0.403111"/>
    <Element N="68" h="0.715789" v="0.410449"/>
    <Element N="69" h="0.726316" v="0.417734"/>
    <Element N="70" h="0.736842" v="0.425094"/>
    <Element N="71" h="0.747368" v="0.432749"/>
    <Element N="72" h="0.757895" v="0.440145"/>
    <Element N="73" h="0.768421" v="0.447784"/>
    <Element N="74" h="0.778947" v="0.455474"/>
    <Element N="75" h="0.789474" v="0.463346"/>
    <Element N="76" h="0.800000" v="0.471803"/>
    <Element N="77" h="0.810526" v="0.481653"/>
    <Element N="78" h="0.821053" v="0.490578"/>
    <Element N="79" h="0.831579" v="0.500443"/>
    <Element N="80" h="0.842105" v="0.510993"/>
    <Element N="81" h="0.852632" v="0.522832"/>
    <Element N="82" h="0.863158" v="0.535119"/>
    <Element N="83" h="0.873684" v="0.548137"/>
    <Element N="84" h="0.884211" v="0.561236"/>
    <Element N="85" h="0.894737" v="0.577007"/>
    <Element N="86" h="0.905263" v="0.594495"/>
    <Element N="87" h="0.915789" v="0.612728"/>
    <Element N="88" h="0.926316" v="0.632372"/>
    <Element N="89" h="0.936842" v="0.655548"/>
    <Element N="90" h="0.947368" v="0.681910"/>
    <Element N="91" h="0.957895" v="0.712413"/>
    <Element N="92" h="0.968421" v="0.746553"/>
    <Element N="93" h="0.978947" v="0.787925"/>
    <Element N="94" h="0.989474" v="0.855779"/>
    <Element N="95" h="1.000000" v="0.950000"/>
  </ToneCurve>
  <ProfileCalibrationSignature>com.adobe</ProfileCalibrationSignature>
  <UniqueCameraModelRestriction>Canon EOS 5D Mark III</UniqueCameraModelRestrict
ion>
  <ProfileLookTableEncoding>0</ProfileLookTableEncoding>
  <BaselineExposureOffset>0.000000</BaselineExposureOffset>
  <DefaultBlackRender>0</DefaultBlackRender>
</dcpData>

**Comment by masc4ii** [comment]
Looks like a tone curve... thanks. But the variables are different from what I've seen until now. Let's see if that helps ;)

**Comment by masc4ii** [comment]
Goooood... I added 3 new debayers to the app and made some bugfixes... I would please you to test it a bit - when you have no findings and no other little projects for MLVApp this could be v1.0 ?! 😄 And could someone film a cake with a "1" candle for a new screenshot?! 😆 I could only fake a picture...

**Comment by masc4ii** [comment]
![k_2261_l1a](https://user-images.githubusercontent.com/30245296/42738260-1afe6f60-8881-11e8-8fd2-3d681205e296.jpg)

**Comment by bouncyball-git** [comment]
Great photo we can "photoshop" it to the MLV App main screen :)
I've tested debayer methods and they are working great.
Simple is a bit faster than bilinear
LMMSE is 2x slower than threaded Amaze

Some quirks with OpenOMP optimized dual iso (to be debugged).
Sorry about not being helpful. Your effort is huge!

**Comment by ilia3101** [comment]
OMG really amazing stuff going on!!! I now have a lot more free time as it is summer. What I've been trying to do for this anniversary release is basically the white-balance branch, but to actually succeed this time. Working on it right now. But this is truly amazing what's going on here.

I've gone through a few ways of doing it - the most difficult thing is keeping highlight reconstruction working while avoiding clipping everything. If the processing was floating point, these problems wouldn't exist :laughing:, but that not worth doing considering how slow it is already. @masc I remember I mentioned trying out integer multiplication + shift for matrices - I did it and didn't notice a difference though I may try again, and use it in more places in processing. I didn't do any actual timing tests.

Also apologies for all the difficulty you guys may be having maintaining the code, I'm having a hard time too. There's some things about it that I did a year ago that would be good to change, but there is not enough time in the universe to do that.

**Comment by ilia3101** [comment]
I could try and make a cake in blender, not promising it will be realistic but it would be amusing.

**Comment by masc4ii** [comment]
BMDFilm profile is there... yeah... I realized it different to the other profiles. But it seems to work and looks correct in my test (please try it out too!):
MLVProducer:
![bildschirmfoto 2018-07-11 um 11 55 48](https://user-images.githubusercontent.com/30245296/42564580-6a11c1d4-8501-11e8-92f8-fead8e004594.png)
Davinci Resolve:
<img width="1792" alt="bildschirmfoto 2018-07-11 um 11 55 57" src="https://user-images.githubusercontent.com/30245296/42564586-6d8c8830-8501-11e8-99e8-66f78798d206.png">
MLVApp:
<img width="656" alt="bildschirmfoto" src="https://user-images.githubusercontent.com/30245296/43182558-21b1db68-8fe2-11e8-97dd-488d53d99e1d.png">
All three with only set WB, BMDFilm profile and EOSHD LUT.

**Comment by bouncyball-git** [comment]
Fantastic man! MLV App image is a bit cooler (on the bluish side) I guess it is WB.

**Comment by bouncyball-git** [comment]
Is "bmd_film.h" linear to bmdfil lut? is it 4K lut or older one?

**Comment by bakersdozen** [comment]
Awesomeness MASC. Will compile when I can and test bmdfilm. Great work, would also like to know if 4k version or not...

**Comment by masc4ii** [comment]
Japp, bmd_film.h is the converted linear-to-BMDFilm.cube :-D (I know I won't get the nobel price therefor, but hey... working). It is not the 4K version... there color is again different, so I thought the non 4K should be better for most non 4K footage (whyever color must depend on resolution, maybe you could explain).

**Comment by bouncyball-git** [comment]
It only depends on Black Magic sensors (for older cameras and for newer with 4K raw output cameras)
I think non 4K BMD Film lut is more appropriate for canon sensors, however I can be wrong :)

**Comment by masc4ii** [comment]
Description (under releases) and picture is ready... now only the last bugs have to be fixed 😄 

![pic](https://user-images.githubusercontent.com/30245296/43606298-3a5e4f7e-969b-11e8-88f4-32a54a44fc3c.png)

**Comment by bouncyball-git** [comment]
Love waveform ;)

**Comment by bouncyball-git** [comment]
Bayer pattern cream is nice ;)
I like both, so you decide.

**Comment by masc4ii** [comment]
Haha, very good Ilia! Very cool! I also like both. You're still the boss... so I also think you decide 😄

**Comment by ilia3101** [comment]
Okay let's use this everywhere until next replacement comes along
![mlvappgirthday](https://user-images.githubusercontent.com/23642861/43786055-a8edb62e-9a5f-11e8-9154-8d0209068331.png)

**Comment by masc4ii** [comment]
I love it!

**Comment by ilia3101** [comment]
wow cool label

**Comment by masc4ii** [comment]
What do you think about releasing v1.0 this weekend? I don't think we solve the windows malloc problems in the next days. For dual iso I would revert the openmp lines again, but after the release we put it in again and try to debug it in the future. What do you think?!

**Comment by ilia3101** [comment]
Sorry I have been absent, currently on holiday. Sorry didnt manage to contribute much to 1.0 (Doing another project too, potentially helpful to MLV app, though I don't want to talk about it too much because when people tell me they like an idea I lose motivation to actually do it). Was going to say let's release it but just noticed it's released, yay!

**Comment by masc4ii** [comment]
Sounds great... hrrrrhrrrmmm... not great at all... (hope that helps your motivation). 😆
