### ISSUE TITLE
Vibrance slider

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#97]
Hej @ilia3101 ,
I have a question: could you somehow create an inverted precalculated vector of `processing->pre_calc_gamma[...]` -> "`processing->pre_calc_ungamma[...]`"? You calculate it in `processingSetGamma(...)`, and I think what I need could be calculated there as well. 

If we had this, we could try to implement a vibrance slider (which I use quiet often in LR). I found this code and would like to give it a try:
https://stackoverflow.com/questions/33966121/what-is-the-algorithm-for-vibrance-filters
I think we could add this after saturation calculation in `apply_processing_object(...)`. All is there we need, only ungamma is missing. The function toGray I would try with (r+g+b)/3.

Edit: seems to be difficult to invert all the tonemap vector as well...
Edit2: and there is another line which can't work: `scale2 = 1 + scale2 * (1 - a)` ... the question is if that is worth all the work 😢

**Comment by masc4ii** [comment]
Found another solution (from darktable) - but do you know in which color room this is done? It can't be RGB, YCbCr, or HSV... But the function looks easy.

https://github.com/darktable-org/darktable/blob/master/src/iop/vibrance.c

**Comment by masc4ii** [comment]
Nothing existing works... meh. So I tried now to implement it myself from how I understood what vibrance shall do. In principle I do nearly the same as Ilia did with saturation. The difference is, that I calculate the saturation value (from HSV color space), and if the higher the saturation is, the less it will be saturated by the slider. In the end that looks like this:

Saturation all the way up:
![m23-1205_frame_1sat](https://user-images.githubusercontent.com/30245296/43280022-01e97d16-9110-11e8-963c-699ad9bfe991.png)

Vibrance all the way up:
![m23-1205_frame_1vibr](https://user-images.githubusercontent.com/30245296/43280062-1f3766f8-9110-11e8-9ae5-9b3ba591618a.png)

**Comment by ilia3101** [comment]
oooooohhhh

**Comment by bouncyball-git** [comment]
COOL!!!

**Comment by tigerdhl** [comment]
> Found another solution (from darktable) - but do you know in which color model this is done? It can't be RGB, YCbCr, or HSV... But the function looks easy.
> 
> https://github.com/darktable-org/darktable/blob/master/src/iop/vibrance.c

@masc4ii  hi  I found the same question in darktable，I can't found which color space the author used in vibrance，did you have the answer？

**Comment by masc4ii** [comment]
@tigerdhl : Sorry, I can't answer this question. I played around with this function in past, but I had no luck in getting it to life. That's why I implemented my own solution.
