### ISSUE TITLE
DUAL ISO export to Cinema DNG doesn't work

### ISSUE THREAD

**Issue by erikeah** [ilia3101/MLV-App#99]
I was recording MLV Dual ISO and processing it to jump to DaVinci but when I open it, just display totally black.

SETUP:

- Canon 100D
- MLV App windows 32bit / 64bit (I test both)
- MLV Receipt:  [100D_Dual_ISO.zip](https://github.com/ilia3101/MLV-App/files/2235684/100D_Dual_ISO.zip)
- Export Settings: 
![dng export and audio](https://user-images.githubusercontent.com/11900869/43320478-8043b33a-91a0-11e8-8864-7189c936329b.JPG)

**Comment by masc4ii** [comment]
Thanks for reporting. Which version do you use?

**Comment by bouncyball-git** [comment]
And upload shortened original MLV somewhere to test.

**Comment by masc4ii** [comment]
Okay... very strange. If I export any dual iso file it is working fine in Resolve. If I apply the posted receipt on the same clips, export and import in Resolve, the clip is just black. But it is black in Resolve only. All other apps show the same dngs the right way.

**Comment by masc4ii** [comment]
It seems to be the Deflicker Target. Set the value to 0 solves the problem also with the posted script. @bouncyball-git : what does deflicker target to dual iso on cdng export?

**Comment by erikeah** [comment]
@masc4ii @bouncyball-git DeFlicker to 0 solve the problem. Thanks a lot!

**Comment by masc4ii** [comment]
@erikeah : nice to hear. But @bouncyball-git : could we analyze what was the problem? If that parameter combination doesn't (or can't) work we should disable it.

**Comment by erikeah** [comment]
Yes, of course we can. Just tell me what do you want and i'll provide you.

**Comment by bouncyball-git** [comment]
Phew... strange it only changes one tag in dng header that is all :(

**Comment by masc4ii** [comment]
One single tag? Then I think that is a Resolve bug. All other software is working fine with these dngs!

**Comment by bouncyball-git** [comment]
Yes it's called tcBaselineExposureOffset

**Comment by bouncyball-git** [comment]
We could remove deflicker feature entirely b/c it seems no one even understands what it does, how to use it so it has no future (I doubt it ever been used in MLVFS).

Also without respecting BaselineExposureOffset tag NLEs can not take the advantage of this feature at all and, I guess, this is only adobe...

**Comment by masc4ii** [comment]
By default it is 0. How about just hiding it in the GUI?! If someone needs it, it is possible to show it by some simple changes to the code and recompiling... or just hacking the receipt file :-D

**Comment by bouncyball-git** [comment]
Good suggestion :)
